### ISSUE TITLE
Years in Figure 5 need updating

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1000]
The U.S. at-sea sector standardized catch rate figure needs to show 2018 to 2022 rather than currently showing 2016 to 2020 (and so doesn't match text in 1.4.1.

**Comment by kellijohnson-NOAA** [comment]
- potentially still need to delete the .eps file
- update the code in hakedataUSA to save this figure in the correct place.
