### ISSUE TITLE
Fix headers on at-age tables

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1001]
Now they look like this for some reason. I don't know why, nothing was changed by me:

![image](https://user-images.githubusercontent.com/4551051/214392269-03c59d8c-02d4-4b2e-abf2-aa083a0478d8.png)

**Comment by andrew-edwards** [comment]
I had that the other day. Got corrected automatically when building (maybe a fresh build).

**Comment by cgrandin** [comment]
This fixed itself... weird but I'll take it
