### ISSUE TITLE
US Fishery report (from industry) needed for appendix

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1004]

**Comment by aaronmberger-nwfsc** [comment]
I was told they will have it by 1/25. If I don't see it by midday tomorrow, I'll email about it.

**Comment by aaronmberger-nwfsc** [comment]
Done with 1cb706449f15c7d350e473dfac906f67b7859b96

Will need to check to ensure no lingering syntax issues, but will do upon next build, closing...
