### ISSUE TITLE
Change "Unfished\nEquilibrium" to SB_0

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1010]
https://github.com/pacific-hake/hake-assessment/blob/68ce8e0a642da263565e363415f538756d4d7910/R/plot-biomass.R#L101-L103

What do you think about changing "Unfished\nEquilibrium" to $B_0$ using `expression(B[0])` and then adding the definition of $B_0$ to the caption. I think that Unfished Equilibrium takes up too much room and it also was slightly difficult for me to know what it was actually referring to because it is not on the same line as the years. We already use the expression in the definition of Relative Spawning Biomass in the panel below. $B_0$ and Unfished Equilibrium are the same thing right?

**Comment by aaronmberger-nwfsc** [comment]
I think this is fine, though I suppose you can unfished equilibrium anything (SSB, B0; Recruitment, R0; shoot even wt-at-age).  As long as we are consistent throughout that we when we say unfished equilibrium (or unfished equilibrium biomass) we mean B0, which is indeed unfished equilibrium spawning biomass.

**Comment by andrew-edwards** [comment]
In Fig. 16 (Bridging models) yes? Sounds good, we use it everywhere. Definitely $B_0$ (not SB_0).

**Comment by cgrandin** [comment]
Sure, can I change it though? I already have changes in that file I haven’t pushed and we can avoid a conflict

**Comment by kellijohnson-NOAA** [comment]
No problem. I also think that line 148 should be changed because the relative age-1 index is in numbers of fish not biomass so it doesn't make sense that there are more mt in the age-1 index than in the age-2+ survey.

**Comment by cgrandin** [comment]
Right, thanks, I keep forgetting that, you’re talking about plot_survey_index() function right

**Comment by kellijohnson-NOAA** [comment]
`plot_biomass()`

**Comment by cgrandin** [comment]
This was completed in 409fcd025ede470f177ae453a779512c10e42e26
