### ISSUE TITLE
Overlapping footer, page 153

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1013]
MCMC estimates of stock status (relative spawning biomass) for the base model and alternative sensitivity runs representing changing the mean of the prior for steepness

Uglyness at the bottom of page 153

![image](https://user-images.githubusercontent.com/4551051/214719835-0df5fada-3a03-488a-b2ac-f7ea313aba32.png)

**Comment by andrew-edwards** [comment]
It's because of the new subsection heading. Same for Fig 1 and 42 and maybe others. Presumably also what's causing the blank pages #1011 . There might be some commented notes regarding blank page before Fig 1 from past fixes.

**Comment by cgrandin** [comment]
Any idea how to fix? My next step would be googling and hoping I find something

**Comment by kellijohnson-NOAA** [comment]
Should I just take the headers back out, seems like that would be the fastest fix for all of this and would close two issues and give us time to work on stuff that we need rather than want?

**Comment by cgrandin** [comment]
Sure, we can do it properly when we have more time.

**Comment by cgrandin** [comment]
I'm pretty sure it means monkeying around in the style file and trial and error with that

**Comment by kellijohnson-NOAA** [comment]
I tried a few things like `openany` and `\let\cleardoublepage\clearpage` listed here https://stackoverflow.com/questions/491904/how-do-i-remove-blank-pages-coming-between-two-chapters-in-appendix but things seem to be more difficult when certain packages are loaded. It doesn't seem worth it right now.

**Comment by cgrandin** [comment]
Ok, maybe make it all one commit to take it out and make note of it, then we can revert that commit later and continue on, maybe keep an issue open with the commit # in it ?

**Comment by cgrandin** [comment]
I do want to see it done, one day!
