### ISSUE TITLE
Missing references to figures in ES

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1014]
I don't know if it matters but
We don't reference in the text Figure d (Biomass) or Figure e (Rel. Biomass) in the Executive summary, or the 2024 and 2025 forecast plots, Figure l and Figure m

Also, Table h is not referenced. I checked all the others

**Comment by kellijohnson-NOAA** [comment]
Nope ... they are Figures d and e and Tables g and h

**Comment by cgrandin** [comment]
and here I was feeling all smart 😂
