### ISSUE TITLE
2022 catch was roughly 320,000, not 325,000

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1015]
The decision table and all the risk tables are assuming 2022 catch level was 325,000 (row f in Table g). It was actually 320,224.

Should we re-run this at 320,000? It is not that difficult to do. I know it isn't much difference but someone will mention it.

**Comment by aaronmberger-nwfsc** [comment]
I'm not too worried about that difference, but also happy to have the server keep your house warm :)

**Comment by andrew-edwards** [comment]
I'm fine with it - we define it as 'similar to 2022 catch'. Could update it if someone complains. The probs are all close for 320,000 and 350,000 anyway.

@cgrandin  - Fig j legend says '2021 catch' though, not '2022 catch':

![image](https://user-images.githubusercontent.com/6977190/214918450-931bd353-7997-4329-942d-08791e3b7add.png)

**Comment by cgrandin** [comment]
Thanks Andy, I updated that catch year in 8c0899c4ddffd74be2892eff41be4ab5b1059402
