### ISSUE TITLE
Allan wants baseline selectivity defined

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1017]
https://github.com/pacific-hake/hake-assessment/blob/1a62b9a85159656bb3aab4f85aa75ad3839ed255/doc/executive-summary/executive-summary.rnw#L797

I am not entirely sure if "baseline" means average selectivity without the deviations or average selectivity across all years after applying yearly deviations to those years that have them?

**Comment by aaronmberger-nwfsc** [comment]
In table 26 and table f, we say ...."baseline selectivity (1966–1990; prior to time-varying deviations", so I just added similar text to the executive summary and to similar text in Model Projections sections. Closed with 04e186bf4e59bde2b402ae1b1fb20855698f11dd
