### ISSUE TITLE
Fix MCMC selectivity plot with individual draws from posterior

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1019]
This plot needs to be updated so that the whole range of ages is covered in the survey (top panel) plots.

**Comment by cgrandin** [comment]
Did you mean  this one:
![image](https://user-images.githubusercontent.com/4551051/214904820-8b913bd7-5469-4191-9d52-b99e35765ed2.png)

If so, we had this discussion last year and decided on this (we actually changed it, I remember doing it) because I believe only for those ages is selectivity estimated, which is what the caption says

**Comment by aaronmberger-nwfsc** [comment]
I still think it needs to be improved (next year!).  I think last year we were in a similar situation (near the deadline) and thought it was fine given the caption.  However, that is not how I have ever seen a selectivity curve and it makes people wonder about what it means (e.g., is selectivity at age-1 = 0; is selectivity at age-6 = 1.0?).  I think we can come up with some options (again, next year).

**Comment by kellijohnson-NOAA** [comment]
Both fishery and survey selectivity are estimated for age 6 so the figures should match on the right-hand side where the initial age at which selectivity does not equal zero is different so the left side is correct. Though, we might want to include a point for age zero that is fixed at 0 for both top and bottom panel.

**Comment by cgrandin** [comment]
It doesn't seem like it. Check this:

`grep("Selex_", names(base_model$mcmc), value = T)`

There's only age 2-5, so what would we do for the rest of the plot?

**Comment by kellijohnson-NOAA** [comment]
that is because we are not reporting it
```
2 2 -1 4 # selex_fleet, 1=len/2=age/3=both, year, N selex bins
```
from the control file line 219

...
but how are you getting the survey ones because we don't specify those in the extra stddev reporting, oh duh because those are not time-varying so you just look at the parameter.

**Comment by cgrandin** [comment]
So what can we do?

**Comment by kellijohnson-NOAA** [comment]
Sorry I was a bit backwards the fishery is the bottom figure and it is fine. The survey, the top panel needs one more age, which would be AgeSel_P7_Fishery(1) so how come we are not plotting P3 through P7 for the survey?

**Comment by cgrandin** [comment]
As above, I was grepping this:
`grep("Selex_", names(base_model$mcmc), value = T)`

And it only gives:
"AgeSelex_std_2_Fem_A_2"
"AgeSelex_std_2_Fem_A_3"
"AgeSelex_std_2_Fem_A_4"
"AgeSelex_std_2_Fem_A_5"

So not sure what parameter to look for

**Comment by cgrandin** [comment]
Doing this:
`grep("AgeSel_.*Acou", names(base_model$mcmc), value = T)`

Gives this:
"AgeSel_P4_Acoustic_Survey(2)"
"AgeSel_P5_Acoustic_Survey(2)"
"AgeSel_P6_Acoustic_Survey(2)"
"AgeSel_P7_Acoustic_Survey(2)"

**Comment by cgrandin** [comment]
So
 2, 3, 4, 5
 or

 4, 5, 6, 7

**Comment by kellijohnson-NOAA** [comment]
P[1-7] is parameter 1-7 not age 1-7. They link to ages starting with age 0; so, P4 is age 3.

**Comment by cgrandin** [comment]
So the plot should be using only those and go from age 3-6? Or do these two sets of parameters get linked up somehow? I'm baffled now

**Comment by aaronmberger-nwfsc** [comment]
Fishery selectivity goes from ages 1-6 (age-1 is a fixed parameter and age-2 through age-6 are active parameters). The fixed parameter is because for selectivity everything is scaled to 1 so you need one less parameter for selectivity ages.

Survey is the same thing but goes from ages 2-6 (age-2 is a fixed parameter and age-3 through age-6 are active parameters).

Does that help?

**Comment by aaronmberger-nwfsc** [comment]
The Survey selectivity plot looks fantastic, but the fishery one now also starts at age-2.  The fishery plot should start at age-1.

**Comment by aaronmberger-nwfsc** [comment]
re-closing with dbea467ed1c2b9636bf813734361203ae743a61a, given user-friendly figure function call options
