### ISSUE TITLE
Figure 16 (pesky bridging model results) has some messed up axes in pdf version

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1020]
Might get mostly solved with some smaller font sizes?

**Comment by cgrandin** [comment]
What's wrong with it?

![image](https://user-images.githubusercontent.com/4551051/214968476-e12079b4-8c5a-409b-a37d-3d8aa1bf6f12.png)

**Comment by cgrandin** [comment]
I mean we can make the y axis titles smaller easily

**Comment by kellijohnson-NOAA** [comment]
Can you just not label as many of the tick points?
