### ISSUE TITLE
Figure j (biomass projection plot) - worth just omitting the grey rectangle?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1021]
It's really hard to see the projections as it's so dark (60 shades of grey?). 

Could keep the vertical line at 2023, (or remove as it's somewhat obvious because the trajectories diverge). I removed 'grey region' from the caption, though the main figures version said 'grey rectangle'.

**Comment by cgrandin** [comment]
Can just make it lighter as well
