### ISSUE TITLE
2023 exploratory run: increase survey input sample size

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1022]
Increase the input sample size for the survey to see if the D-M parameters change such that the survey multiplier is not so close to 1.0. Suggested by Allan.

**Comment by aaronmberger-nwfsc** [comment]
This one can be post assessment draft submission, right Kelli?

**Comment by aaronmberger-nwfsc** [comment]
We may want to just pin this for 2024 assessment milestone now that we are past the SRG.

**Comment by kellijohnson-NOAA** [comment]
They never really asked for it this year like we thought they were going to and now Allan wants bootstrapped input sample sizes so I think we can just close it.
