### ISSUE TITLE
SRG presentations

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1025]
Edit this message to add you name by a presentation, and then check the box once it is ready for others to review.

- [x] Data - Kelli
- [x] Assessment - Aaron (draft available for comment on google drive [here](https://drive.google.com/drive/folders/14Rl-_PJ0Eo4BQAdk3A7Izjosk-YZQx2W))
- [x] Sensitivity/retrospectives - Andy (draft also available on above Google drive link)
- [x] Management - Chris

**Comment by andrew-edwards** [comment]
By the way, I added an option to `plot_biomass()` and a couple of other functions to not have the dotted lines at the edge of the uncertainty ribbons. I found it just made the plots a bit less busy. You can just add
```             ribbon_line_type = 0)```
in the function call. The default is still the dotted lines.

**Comment by cgrandin** [comment]
I think you can/should use "none" instead of 0 which is easier to understand if reading the code (like "dotted", "dashed", "none" etc)

**Comment by andrew-edwards** [comment]
"none" doesn't work. I looked up something and it said to use 0, which I agree isn't ideal.

**Comment by cgrandin** [comment]
Ahh, its "blank"
