### ISSUE TITLE
Bridging text question on new SS version

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1028]
In the paragraph about bridging to new SS version, it the highlighted text supposed to be '2023'?  Or did this fix happen for last year's assessment as well (i.e., the '2022' is correct)?
![image](https://user-images.githubusercontent.com/7946234/215276506-3d444bd4-852e-4c4b-9356-0a2f22b8ac94.png)

**Comment by cgrandin** [comment]
Yes, 2022 is correct. It is just part of the code now so used this year as well

**Comment by aaronmberger-nwfsc** [comment]
Ok, but this is the bridging text which talks about changes specific to this year, or rather things that are new relative to last year.  So this really should be in here?   I not to worried about it in the draft document now, but I won't put it in the presentation if it really isn't part of the bridging.  @kellijohnson-NOAA - I thought you mentioned this was new for SS this year, no?

**Comment by cgrandin** [comment]
I didn’t realize this may be a new SS feature, I thought it was referring to how we changed the weight at age inputs into the forecasting which was last year, so I leave it to Kelli..

**Comment by kellijohnson-NOAA** [comment]
It was available for us last year but we technically didn't use it in the base model. We ran the base model, noticed the forecasts were wrong and then used a different executable for the forecasts. So it is a bit of a mess. I think it is fine to leave where it is at in the document but I was the one who put it there so I might not have the best judgement, and I am open to moving it to wherever people think it goes best. This is just one of those things that is hard when you are not using pre-compiled versions of SS3 and you use multiple executables in a given year.

**Comment by aaronmberger-nwfsc** [comment]
Okay, no worries, I understand the nuisances here.  I'll still mention this in bridging presentations so nobody other than us knows the timing details. Closing....
