### ISSUE TITLE
Trevor's comments 2023 assessment

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1031]
- [x] Figure g: is relative fishing intensity = 1 a management  target or a management limit? Do you want it below 1 or equal to 1? 
- [x] Figure j: once understood, this is a well thought out figure, but initially I thought this was the result of applying the rules to three biomass levels, those at the 95th percentile, 50th percentile, and 5th percentile. 
- [x] Figure k-l-m: labels on the x-axis are not in line with tickmarks on axis. Also, the legend is right justified and should be left justified (indeed this is true of many other plots in the report).
- [x] p. 60 “due to remaining unknowns about the size of the 2020 cohort (e.g., not yet sampled by the acoustic survey)”   given the age-1 index this needs rewording, for example “ … 2020 cohort (acoustic survey only provided one year of age-1 information, which is more uncertain than the 2+ estimate).”
- [x] p. 64 Delete the [] and move the phrase “[in last year’s assessment the equivalent calculation was P(B2022 > B40%) = 90.5%]”, so that it is a separate sentence at the end of this sentence: “This probability higher than in last year’s assessment, where the …. 90.5%.”
- [x] p. 64 ‘0%‘  should be ‘0%’  
- [x] p. 68 “Both sensitivities resulted standard deviations of the estimates of recruitment deviations from the period with the most informative data that were higher than the input” needs reworking. 
- [x] p. 70 “Since 2008, catchability has been freely estimated by the model.” This would be a good place to insert the model estimate of survey catchability to gauge how different it is from absolute biomass (q = 1). 
- ~~p. 72 Research and data needs. Each of these items is really a large number of items, better broken out as separate items or subheadings under a main header like ‘Survey needs’. For example, is ROMS as high a priority as ecosystem variables? Similarly, documenting the survey methods seems separate from ecosystem based surveys and separate from using MSE to examine changes in survey methods.~~
- [x] p. 78 Hamel and Cope ref repeats doi. 
- [x] p. 81 “Osney mead” -> “Osney Mead”
- [x] Table 17 Columns 2-4 should be left aligned not right aligned. 
- [x] Table 19 & 22 Specify that this is total biomass (both sexes combined) and not female spawning biomass. 
- ~~Table 23 It does seem like another column of “Added biomass due to growth” would ensure that everything balanced for the next year.~~ 
- ~~Table 24 Adding total catch would ensure the table contained all the key relevant information.~~
- [x] #1032
- [x] Figure 3: only plots age-1 index for 2003-21, but Figure 8 & 11 include 1995 & 1998 (but not 2001) as data used in the assessment. 
- [x] Figure 21: needs more bars (thinner bin width) for the two panels with the Dirichlet-multinomial value. 
- [x] Figure 58 caption ‘correctly‘  -> ‘correctly’

More that were in the original email have already been dealt with in a47f3f42

**Comment by cgrandin** [comment]
The third item, figures k, l, m axis ticks and labels was fixed in 39c6a and 65d36

**Comment by cgrandin** [comment]
> Figure 3: only plots age-1 index for 2003-21, but Figure 8 & 11 include 1995 & 1998 (but not 2001) as data used in the assessment. 

See #1034, will check here as it is an open issue

**Comment by andrew-edwards** [comment]
Thanks for doing most of this. I'm fine with the remaining two not being done. Techincally the bars in the histograms should indeed be narrower, but it's making the point when comparing with the prior.

**Comment by kellijohnson-NOAA** [comment]
I just finished with changing the figure but I have been talking with @cgrandin and @aaronmberger-nwfsc about what is best to actually show. I think we need both a full prior figure and a truncated prior but full posterior figure. So, if we all agree I will add the lower figure and change the one that is already there to have the full distribution from of the prior for all parameters.
Full prior
![testa](https://user-images.githubusercontent.com/4108564/218615758-2d7115df-c9e5-4578-931e-a52cdcd65f15.png)
Truncated prior
![testb](https://user-images.githubusercontent.com/4108564/218615757-e92e6b69-689d-40ea-a12f-39c37c61899c.png)

**Comment by cgrandin** [comment]
Looks good Kelli, thanks for tackling this one
