### ISSUE TITLE
Add text about the spatial age-1 plot that comes from the survey team

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1034]
The figure shows from 2003-present and is missing 1995, 1998, 2001. This is due to the lack of spatial data for those years, the indices for those years are correct and are included in the model. It is simply a mapping issue.

The caption should be changed, and possibly the main text.

**Comment by aaronmberger-nwfsc** [comment]
And include in caption that only pure age-1 aggregations are shown and not aggregations where age-1 are intermixed with age-2+ and the degree of age-mixing in aggregations changes from survey year to year.  (i.e., be very careful interpreting spatial patterns using this figure alone)

**Comment by aaronmberger-nwfsc** [comment]
This is closed with 7d453049ff63abdaba10b8120258e8b130008da8 and acf273964605715d728b1f4d6327255e15648629
