### ISSUE TITLE
Move Figure 55 (Historical assessments) to somewhere NOT next to retrospectives

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1039]
Jaclyn noted that it is difficult to know that the historical analysis of previous assessments is not a retrospective yet when placed next to the retrospectives it is slightly difficult to interpret.

**Comment by aaronmberger-nwfsc** [comment]
I think if we end up shortening an moving the Performance of Past Projections section to an appendix, we could then have section 3.10 by something like "Historical Performance" and just move the pertinent paragraphs from the Retrospective section to the new 3.10 section.

**Comment by andrew-edwards** [comment]
Figure 55 was (in the draft last year) this one
![image](https://github.com/pacific-hake/hake-assessment/assets/6977190/7dd57545-1e7f-4a5b-9605-f9316e889dca)

Jaclyn's correct that the text falls under the 'retrospective analyses' section, which is indeed confusing. So we should simply just add in a new section heading "Comparison with past assessments". 

Regarding 'Performance of past projections', I can shorten the text, and remove Figures 60-63, which help the understanding of Figure 64 (but we can just refer to previous assessment for the more detailed explanation). I find them really interesting but not sure other readers do! Kind of think there's not really enough to move it back into an Appendix, once it's just four figures and some text (Trevor and Shannon appreciate them).

**Comment by aaronmberger-nwfsc** [comment]
It's still a retrospective analysis in a sense, though perhaps not what most assessment scientists think of when they hear retrospective analysis.  Changing to a new section is fine too.
