### ISSUE TITLE
Use steepness h = 0.99 rather than 1.0

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1040]
John - because of theory potentially limit h explorations to 0.99 rather than 1.0. Need to change the sensitivity code if we want to change this. I am honestly uncertain though if we want to do this or if we should just leave it. I don't like doing a sensitivity with a parameter on the bound.

**Comment by aaronmberger-nwfsc** [comment]
I agree. I think we intentionally forget about this until someone brings it up again (or if it finds its way into the SRG report). If we did 0.99 based on theory then we would probably fix it, which doesn't do anything compared to 1.0.

**Comment by aaronmberger-nwfsc** [comment]
We did not do this (for good reason) this year so I'm going to close this issue as we decided against it.

**Comment by kellijohnson-NOAA** [comment]
@aaronmberger-nwfsc the run exists it just is not used in the document.
