### ISSUE TITLE
SRG Appendix entries list

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1041]
Running list of SRG requests to add to our document appendix:
- [x] age-1 index residual plots
- [x] update max age selectivity sensitivity runs and add figures
- [x] Updated relative fishing intensity decision table (will also be in the E.S. and the main tables) {Do we need it in here?} - no, I think we just fix it in the document and not put it in here

**Comment by andrew-edwards** [comment]
@aaronmberger-nwfsc  - didn't see you assigned this. I've done it (as mentioned in Slack). Hope you haven't started....
