### ISSUE TITLE
Make a switch to turn off tagging when building

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1044]
I got it working locally (installed TexLive plus dependencies) but it takes a while to build, and makes a 180Mb pdf on Windows. (The preSRG local version was 7Mb, without any tagging). So be ideal to have tagging turned off while we're working. Chris said to make an issue and it can be looked into at some point.

**Comment by cgrandin** [comment]
Done. See commit 7e3d56f798390f51c5a914ff07a2225ce8e6c0ad
It is a switch in the YAML headers of the `doc/000-launcher.rmd` file
