### ISSUE TITLE
Alt-text algorithm breaks those plots where layout() is used

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1046]
Only the upper of the two plots is shown.
For example the age comp fits plot (Fig 19) and the traceplots for the MCMCs in the MCMC appendix. This looks like its not too hard to fix, my task for Wed Feb 15.

There are two `includegraphics[width=\maxwidth]{path/to/file}` calls in a row in the input tex file in these cases. The alt-text algorithm just ignores the second on while injecting tagging structure.

Need to check for two or more.
We will never use layout again once converted totally to ggplot, so maybe only worry about two for now.

**Comment by cgrandin** [comment]
This is a lot more work than first seems. The age fit plots cannot be placed into a cowplot grid, so they have to be rewritten so they do otherwise the alt text algorithm will fail. This will take longer than today

**Comment by aaronmberger-nwfsc** [comment]
should these be changes earmarked for 2024 given the time it will take?

**Comment by cgrandin** [comment]
No I'm almost done. It has to be done to make the alt-text tagging work.
