### ISSUE TITLE
Write script to automatically copy all model input/output files to Google Drive

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1047]
Write a script to sync or once a day or anytime something changes (ideally). They are backed up already but I would have to run a restore on the server etc, which takes a long time. Also if server is dead, what would we be restoring to?

If they were on Google Drive we could start working locally right away in the event of catastrophic failure.

**Comment by andrew-edwards** [comment]
That would be awesome. Sounds tricky, but a challenge that you'd like to tackle!

**Comment by cgrandin** [comment]
Done. Currently only copies SS inputs files and the RDS files for each model in the correct structure so it can be downloaded and the document built on another machine.

The model output is huge and not worth saving because we have the SS version (commit information) and the SS input files with that infomation we can remake them exactly anytime.

However, it is really easy to add files to save to this script so if there is anything pertinent we can add it.
