### ISSUE TITLE
Create JMC presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1049]
I think this can largely be similar to what we've given in the past.  I think there is going to be interest in the 'ecosystem' presentation that I gave so I was thinking of keeping that separate from our normal presentation and basically shortening the one we gave at the SRG (and probably including some of the stuff that others presented on).

So presentations to create include:
- [ ] standard JMC assessment presentation
- [ ] auxiliary 'ecosystem' info and research (mainly discussing productivity, hake migration (or lack thereof), and assessment results of high biomass but poor northern fishing)

**Comment by aaronmberger-nwfsc** [comment]
There was some discussion about JMC not understanding dynamic reference points, but I spoke to Frank and we thought the summer JMC meeting was a better place for that, so at this point we don't plan to mention it much (ourselves bringing it up anyway) at the March JMC meeting. Agree?

**Comment by cgrandin** [comment]
I already updated the JMC presentation with all the new stuff so it builds and just needs content updates
