### ISSUE TITLE
Can we change 'thousand tonnes', 'thousand t', '000' t, '1,000 t' etc to kilotonnes (`kt`)

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1052]
We should use metric and it would unify all the text, plots, and tables. The values wouldn't have to change, only labels etc.

It would also shorten axis labels making special code for when they are plotted smaller unnecessary.

**Comment by kellijohnson-NOAA** [comment]
Thanks Chris for the suggestion, I think this would be great. In addition, there are the following abbreviations that we could use, not just `kt`

<html>
<body>


Name | The Number | Prefix | Symbol
-- | -- | -- | --
trillion | 1,000,000,000,000 | tera | T
billion | 1,000,000,000 | giga | G
million | 1,000,000 | mega | M
thousand | 1,000 | kilo | k
hundred | 100 | hecto | h
ten | 10 | deka | da
unit | 1 |   |  
tenth | 0.1 | deci | d
hundredth | 0.01 | centi | c
thousandth | 0.001 | milli | m
millionth | 0.000 001 | micro | µ
billionth | 0.000 000 001 | nano | n
trillionth | 0.000 000 000 001 | pico | p


</body>
</html>

**Comment by cgrandin** [comment]
Everything in the document has been changed to metric. See 7e3d56f798390f51c5a914ff07a2225ce8e6c0ad

**Comment by andrew-edwards** [comment]
We should go with `gigahake`.
