### ISSUE TITLE
Make all legend text left justified for all plots

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1053]
For all ggplot plots, eg. `plot_biomass()`, `plot_rel_biomass()`, `plot_recruitment()` etc need this done.

See `plot_fore_compare()` for how to do it.
I think Trevor mentioned it in 2023 SRG meeting.

**Comment by kellijohnson-NOAA** [comment]
Maybe we can just make a common `theme_hake()` to use in the {ggplot2} figures.

**Comment by cgrandin** [comment]
We already have that, but yes great idea. We can just add to that!

**Comment by cgrandin** [comment]
Pretty sure they are all done in commit 7e3d5. If not, this is how it's done (`legend.text.align = 0`)
https://github.com/pacific-hake/hake-assessment/blob/659c342d03591919313521abdf46ed3f4cb2364a/R/plot-fore-compare.R#L132
