### ISSUE TITLE
SRG Request sensitivities

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1061]
2023 SRG Request
2. The SRG also __recommends continuing sensitivities for steepness, natural mortality, σR, excluding the age-1 index, alternative standard deviations for time-varying selectivity, and using the McAllister-Ianelli method to weight fishery age composition data.__

We need to double check that they are all coded to run and reported.

**Comment by aaronmberger-nwfsc** [comment]
Completed this year.
