### ISSUE TITLE
SRG Request for dynamic unfished spawning biomass

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1062]
2023 SRG Request
3. The SRG recommends that the JTC __include dynamic unfished spawning biomass in the 2024 assessment as a comparator with the equilibrium unfished spawning biomass used to provide management advice.__ The SRG also encourages the continued outreach regarding the use of dynamic reference points to stakeholders and managers, including identifying pros and cons of using dynamic unfished spawning biomass.

**Comment by andrew-edwards** [comment]
Closely linked to:
1. **Pacific Hake dynamics are highly variable even without fishing mortality. The SRG
applauds the efforts of the JTC and the MSE Working Group to add capabilities for
estimating dynamic reference points within the assessment and MSE, and encourage
those groups to jointly develop alternative reference points, including dynamic
reference points, for future SRG consideration.**

**Comment by aaronmberger-nwfsc** [comment]
I think we have adequately responded to this request, such that it can be closed.
