### ISSUE TITLE
SRG Request natural mortality

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1063]
2023 SRG Request
4. The SRG recommends that the JTC __explore alternative ways of estimating natural mortality to update the current approach in the model, which is based on methods from more than a decade ago, since newer methods are available. Information presented during the SRG meeting implies that natural mortality on age-2 Pacific Hake is higher than currently assumed in the assessment model and should be explored more fully.__
I am assuming that they are talking about the cannibalism work that Sophia presented.

**Comment by aaronmberger-nwfsc** [comment]
@kellijohnson-NOAA did some explorations and while further work could always be done we have responded to this request.  We can open a new issue if the SRG continues a version of this request.
