### ISSUE TITLE
SRG Request Age-1 index distribution modelling zero value

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1066]
2023 SRG Request
7. The SRG noted that the age-1 index did not include a value for 2001 because it was zero. Although this decision had negligible influence on the results because the estimate for 2000 recruitment was close to zero, the SRG noted that Stock Synthesis uses a lognormal likelihood which does not handle zero values. Given that future zero values are expected to have a bigger influence on the results in the short-term, the SRG recommends that the JTC __explore likelihood forms that can fit to very low index values from the age-1 survey (e.g., robust likelihood).__ The SRG acknowledges that implementing new likelihoods will require changes to the Stock Synthesis platform.
Was not developed in SS3. Rick did suggest using the T-distribution.

**Comment by aaronmberger-nwfsc** [comment]
The t-distribution was added and our current platform (SS) doesn't allow us to directly do this currently.  I'm going to close this issue rather than switch it to a 2025 milestone.  Feel free to reopen if you feel otherwise.
