### ISSUE TITLE
SRG Request Canadian sampling of more tows but fewer fish

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1068]
2023 SRG Request
9. A new at-sea sampling program in the Canadian freezer-trawler fleet was implemented in 2022 involving vessel crews sampling 50 fish per tow from two tows per trip. The SRG recommends that __Canada consider sampling fewer fish from more tows to spread the sampling out and provide a more representative sample of fishery catches.__

**Comment by cgrandin** [comment]
I forgot to set this up for the 2023 fishing season so will do for 2024 season

**Comment by cgrandin** [comment]
Done in a0b1c2c7d15fb509172458c3ab378c17737c6e5f
