### ISSUE TITLE
"Observed" CPUE may not be the full time series in model 1

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1074]
https://github.com/pacific-hake/hake-assessment/blob/dd81068b3b34980e6b48c307a322a513ace2f29a/R/create-group-df-index.R#L19

I am trying to plot the fits to the age-1 index for the bridging models. When I pass the list of models read in using readRDS() over multiple directories, the first model in the list is from early in the bridging thus it does not have the 2023 index point in the data file. I can think of a lot of ways to code this differently but I am not sure what is best. So, I figured capturing it in an issue to brainstorm a fix was the best option. At the extreme end we could pull out the observed values for each model, at the opposite end we could pull out the observed values from the time series that is the longest. All options have potential problems.

**Comment by cgrandin** [comment]
Let me know which models and I can fix it pretty quick

**Comment by kellijohnson-NOAA** [comment]
This is okay in the document so I am closing.
