### ISSUE TITLE
Cannot have \usepackage....[hyperref] and \hypersetup

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1077]
I had to comment out the lines in `preamble.tex` - see commit referenced below (once I push it).

https://tex.stackexchange.com/questions/203045/latex-error-option-clash-for-package-hyperref
says "A package can be given several times in LaTeX, however, the options of the calls after the first \usepackage must be a subset of the options present in the first \usepackage call, because LaTeX does not actually input the .sty file more than one. (Otherwise each \newcommand, ... would cause errors, if called more than once.)"
which is why I just commented the call to get it working.
Also later on that page is says (for beamer at least) that hyperref gets loaded automatically.

I think the solution is to have all the options set in one place maybe? Personally I like having the links to Figures and citations etc not underlined or highlighted, as it's a bit distracting when reading. But it's useful having them in there. This should be doable, but just wanting it working for now.

**Comment by cgrandin** [comment]
I find it much nicer to have the figures, tables and refs underlined, as I'm always searching the text for the related figure/table to click, it becomes easy when they're all so obvious. I don't know what to do, vote on it ?

**Comment by andrew-edwards** [comment]
There's still currently a slight inconsistency between how references are written:

![image](https://github.com/pacific-hake/hake-assessment/assets/6977190/3b4e689b-87b1-4e8a-a579-04bde596451f)

so leaving issue open. Fixed original problem in above commit.

**Comment by kellijohnson-NOAA** [comment]
I think that we should just leave the links as is, if they are not highlighted then most people will not even know that they can click on them. I also do not think that there is an inconsistency in how the references are linked because it always links to the text in the brackets rather than Phillips et al. that is outside of the brackets. I think that we can close this until someone from the SRG complains.

**Comment by cgrandin** [comment]
I agree, I think it looks good as it is now

**Comment by andrew-edwards** [comment]
I meant to say the other day that I can live with the links as they are :)
