### ISSUE TITLE
Remove `hake::` when not needed, as it will use library version not the local version; need to keep some though.

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1079]

**Comment by cgrandin** [comment]
Keep the ones in vignettes and documentation/comments

**Comment by andrew-edwards** [comment]
Presumably good to remove them in the YAML?
```
output:
 hake::hake_pdf:
```
Else will use the `library` version of `hake_pdf()`.

**Comment by andrew-edwards** [comment]
Also see 759aec7e and 3fa8e733. Kept `hake::` in output that was a message from the user, and kept it in all vignettes and other comments. doc builds okay, haven't tested the talks.

**Comment by cgrandin** [comment]
> Presumably good to remove them in the YAML?

> output:
>  hake::hake_pdf:

Leave that one in for now, as the render() function requires it to be there

**Comment by andrew-edwards** [comment]
`render()` works fine, and never had `hake::` in it. Think you edited your comment as I was thinking about it!

**Comment by cgrandin** [comment]
Did you restart R, then `clean()`, then `render()`

Also try the beamer presentations

**Comment by andrew-edwards** [comment]
Yes to first. Haven't tried any beamer ones at all yet this year.
