### ISSUE TITLE
Keeping track of who has carefully read each section

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1081]
We want to ensure at least one person has *carefully* checked that each section makes sense (once we have the new results). Tick a box when done. We should all do the Executive Summary if possible. This seems better than flagging the text as in the past, and will cut down on discussions about who's checked what. 

Suggest we still say on Slack when we're working through and editing a section.

**Under development! Just testing some Issue formatting for now**

- [ ] test - [ ] nonsense
- [ ]
- [ ]

Looking at the source html produced by the above, doesn't help 
<html>
<body>

<ul class="contains-task-list">
 <li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox"> test - [ ] nonsense</li>

</body>
</html>

| Section | Kelli | Aaron | Chris | Andy |
|--------|-------|-------|-------|------|
| One-page summary | test - [ ] a | - [ ] | - [ ] | <input type="checkbox"/> |
| Stock | - [ ] | - [ ] | - [ ] | - [ ] |

html trick, but doesn't produce a checkbox:
<input type="checkbox" id="checkbox1">
<label for="checkbox1">Click me</label>

**Comment by cgrandin** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

**Comment by andrew-edwards** [comment]
I saw that one. The problem is that task lists have to be the at the start of a line, like a list of bullet points. Can't easily get them into cells in a table.

**Comment by andrew-edwards** [comment]
People have created other fudges, but not clickable boxes within a cell of a markdown table in a GitHub issue. Thought it would be fairly straightforward.

**Comment by cgrandin** [comment]
GitHub is really strict in what they allow, you probably can't hack something together if the functionality isn't built in. They have their own Markdown interpreter

**Comment by andrew-edwards** [comment]
Yes, not getting anywhere. So solution is to just have one long list of sections (which I've got from hake.toc!) and just one checkbox at the start for each, rather than the table idea.

**Comment by andrew-edwards** [comment]
i.e.
- [ ] One-page summary
- [ ] Stock
- [ ] Catches

**Comment by andrew-edwards** [comment]
I'll do it a new clean issue and close this 'experimental' one.
