### ISSUE TITLE
Update Canadian economic information

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1085]
https://github.com/pacific-hake/hake-assessment/blob/e221c15b63d5b032cf5a3482a5ab83ea465e5f71/doc/007-introduction.rmd#L244-L250 needs to be updated.

**Comment by andrew-edwards** [comment]
Will do, though I think I looked last year and the stats hadn't been updated. Might not be "Canada's largest commercial wild fishery" any more.
