### ISSUE TITLE
Databases for Canadian data might need updated in text

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1088]
https://github.com/pacific-hake/hake-assessment/blob/4d3bbbd7d58390c8bec563709ce41ca91ef68e11/doc/008-data.rmd#L74-L78

@cgrandin can you double check that the information available is correct?

**Comment by cgrandin** [comment]
Same databases and years, but there is now software that merges the data together instead of an undocumented manual procedure to do that. So leaving text as-is.

**Comment by kellijohnson-NOAA** [comment]
Great, thanks for checking @cgrandin!
