### ISSUE TITLE
El Ni\~no is not rendering

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1091]
https://github.com/pacific-hake/hake-assessment/blob/3d31648663ebbf12f026208efa63468f494e62e6/doc/008-data.rmd#L227 and others within the document are not rendering. I checked a build that @cgrandin put on slack and they were not rendered there either. So, this is not just a me problem. I tried `El Ni\{~}no` and `El Ni{\~}no` and neither of those worked either. But, `El Niño` does. I honestly do not like putting the actual character into the document so I haven't changed anything. @cgrandin feel free to fix this however you see fit.

**Comment by cgrandin** [comment]
We need to use the real symbols now because it is a UTF-8 compliant project... I did the degree symbols previously, if you see any more, go ahead and change the the proper symbols
