### ISSUE TITLE
Bridge model plots are becoming illegible. How do we deal with it?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1092]
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/a271f318-8607-48cc-8333-5891b065ab2a)
What should we do about this? It is starting to get illegible and legend contains too much to fit. There will be another one as well, for group 2. We could just split them up into more groups or something to make nicer plots.

Here's my idea so far.
We could break this up into two plots:

plot 1: 2 panels, one is the biomass plot and the other is a legend
plot 2: five panels, with the four on top and one wide one on the bottom containing the legend so it looks the same as the legend panel in the first plot

So with this there will by four plots, two for each bridge group.

**Comment by aaronmberger-nwfsc** [comment]
I think Kelli already has a plan to split the bridging steps into perhaps 3 steps (3 plot bridge groups).  @kellijohnson-NOAA is this correct?  I think the 5 panel plot configuration is still okay, we just can't have more than like 4 models in the legend as it get too busy.

**Comment by kellijohnson-NOAA** [comment]
Close with 2f9552d10ede643abf35161cc82d39330f1eb599 and 76041c3a64c69ba86e3390fc07ff876a4879e843
