### ISSUE TITLE
base_model$mcmcparams is `NULL`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1093]
https://github.com/pacific-hake/hake-assessment/blob/45c40301274b7a3a52841a60b3ff1d888c5f8e38/doc/004-load-project-variables.rmd#L781-L785

Not sure where `mcmcparams` should be defined but all places where these objects are used in the document are blank because `base_model$mcmcparams` is `NULL`.

**Comment by cgrandin** [comment]
I fixed the code and also updated the base model on the server, so by morning the Google drive should be updated as well.
