### ISSUE TITLE
2.5.2 Steepness Chantel Wetzel

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1094]
https://github.com/pacific-hake/hake-assessment/blob/94c3fe351c2982af3a8af26865f6cb2dbdfa3ebf/doc/008-data.rmd#L587-L590

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa do you have time by Friday January 19th, 2024 to edit this piece of text regarding the prior on steepness for the Pacific Hake assessment. I have checked that all the values are correct, I am just not certain if the information regarding the history of the prior is correct. Can we have this statement about being used since 2007. Didn't you change/update the prior? Do we need to update our prior in the future as well 🤷? Any thoughts here are welcome. Thanks a bunch.

**Comment by chantelwetzel-noaa** [comment]
This looks roughly correct for Pacific hake.  Looking back at the older assessments I find references to using two Myers papers for a median of 0.75 in 2006 and 2007, then 2008 being the first assessment where they appear to move to the Myers 1999 paper using the median of 0.79 similar to the current approach.  The updated steepness prior I have worked on is for rockfish alone.

**Comment by kellijohnson-NOAA** [comment]
Thank you for looking and for the details! Much appreciated.
