### ISSUE TITLE
Resolution - should use 300 dpi but can stick with 100 dpi for now

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1095]
300 dpi looks great on screen and prints fine. 100 dpi not so good but is quicker to build.

So nearer submission we should switch to 300, can stick with 100 for now. 

Quick test, with Andy's local build (just main text and main figs), deleting `knitr-figs/` cache first:
100 dpi - 2.6 Mb file - took 231 secs
300 dpi - 7.7 Mb file - took 615 sec, so 3x larger file and nearing 3x longer in time.

I think the extra file size is fine. A lot of the build time seems to be figures like the selectivity one with all the MCMC's - could shorten by subsampling the MCMC's. I can look at that if time.

**Comment by andrew-edwards** [comment]
I'll do the subsampling - Chris has already done it in `plot_survey_fits_mcmc()`.

**Comment by andrew-edwards** [comment]
Have done the subsampling for the figure, which has cut the build time in half :o 
So let's just keep the dpi at 300 going forward, doing in the commit below.

**Comment by cgrandin** [comment]
If you really want to see the difference, compare the stock recruitment plot, for the embedded text "Median recruitment" and "Mean recruitment"
