### ISSUE TITLE
Remove keyposteriors.csv and nuisanceposteriors.csv from the project

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1097]
They aren't used anywhere and just seem to pop up in bugs all the time. Please speak up if you have a reason to keep these!!

**Comment by aaronmberger-nwfsc** [comment]
I use those all the time when I need to 'hand calculate' a posterior median for a metric that we don't automatically do it.  I'm fine to get rid of them as csv's as long as the information is stored somewhere.

**Comment by cgrandin** [comment]
What if we put them as data frames attached to the RDS file? Then you would access like this:

base_model <- readRDS("/path/to/01-base.rds")
base_model$keyposteriors
base_model$nuisanceposteriors

If you had built the doc you wouldn't even need to run the loading part, they would just be there.
