### ISSUE TITLE
Could sample MCMC samples for the plotting parts of the pairs plots in MCMC diagnostics appendix

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1098]
The pairs plots take a long while to build. 
Might just involve adding a `subsample` option to `lower_triangle()` in  `plot_pairs()`. So the correlation coefficients and diagonal plots would stay the same.
So it will then plot 1000 (say) points in each panel, instead of 8000.

First check if `plot_pairs()` used elsewhere though.

**Comment by kellijohnson-NOAA** [comment]
I don't think that the "long" build time should make us change to subsampling for this figure given we are not talking about hours. One can always comment the figure out while you are building if you want to do things more quickly. I am closing this issue but @andrew-edwards if you feel that we should prioritise this, then feel free to reopen.
