### ISSUE TITLE
Update plot-biomass figure function to include plot unfished SSB option

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1099]
Add a function option to additionally plot the unfished time series so that it looks something like the below inserted figure except that it follows the plot-biomass layout.

In the below example I did this for reference.
```
rds_2024 <- readRDS("C:\\Users\\Aaron.Berger\\Documents\\AMB\\Hake\\2023_2024\\Models\\BaseModel_rds\\01-base.rds")   #load rds
iter1 <- which(dimnames(rds_2024$mcmc)[[2]]==paste0("Dyn_Bzero_",rds_2024$startyr))   #pull out start year value
iter2 <- which(dimnames(rds_2024$mcmc)[[2]]==paste0("Dyn_Bzero_",rds_2024$endyr+1))   #pull out end year value
plot(time,(rds_2024$mcmccalcs$smed[1:(rds_2024$endyr-rds_2024$startyr+2)]),type='l',ylab="SSB (million t)",xlab="Year",lty=1,col='black',ylim=c(0,5),lwd=2,las=T)   #SSB time series
lines(time,(apply(rds_2024$mcmc[iter1:iter2],2,median)/1000000),col="darkgreen",lwd=2,lty=2)   #unfished time series
polygon(c(rds_2024$startyr:(rds_2024$endyr+1),(rds_2024$endyr+1):rds_2024$startyr),
        c((rds_2024$mcmccalcs$slower[1:(rds_2024$endyr-rds_2024$startyr+2)]),
          rev((rds_2024$mcmccalcs$supper[1:(rds_2024$endyr-rds_2024$startyr+2)]))),col=adjustcolor("black",alpha.f=0.2),border=NA)  #SSB time series
polygon(c(rds_2024$startyr:(rds_2024$endyr+1),(rds_2024$endyr+1):rds_2024$startyr),
        c(apply(rds_2024$mcmc[iter1:iter2],2,quantile, probs=c(0.025))/1000000,
          rev(apply(rds_2024$mcmc[iter1:iter2],2,quantile, probs=c(0.975))/1000000)),col=adjustcolor("darkgreen",alpha.f=0.2),border=NA)  #unfished time series
```

Where only the unfished time series rows would need to be added to plot-biomass function.

<img width="547" alt="image" src="https://github.com/pacific-hake/hake-assessment/assets/7946234/0b8f9199-f79f-4893-abb5-bd309f3651b2">

Chris - I figured it would be useful to have you quickly add this so that it remains consistent with your code structure :)

A legend would be something like:
```
legend("topright",legend=c("Fished Population","Unfished Population"),lty=c(1,2),lwd=c(2,2),bty="n",col=c("black","darkgreen"))
```

**Comment by aaronmberger-nwfsc** [comment]
Let's also add the below figure, possibly as a two panel single page set, for our response to SRG request 3.

<img width="551" alt="image" src="https://github.com/pacific-hake/hake-assessment/assets/7946234/81caf5cf-8d51-4507-b747-669370acf9de">

Draft code to make above plot:
#plot static and dynamic B0
iter1 <- which(dimnames(rds_2024$mcmc)[[2]]==paste0("Dyn_Bzero_",rds_2024$startyr))
iter2 <- which(dimnames(rds_2024$mcmc)[[2]]==paste0("Dyn_Bzero_",rds_2024$endyr+1))
iter3 <- which(dimnames(rds_2024$mcmc)[[2]]==paste0("SSB_",rds_2024$startyr))
iter4 <- which(dimnames(rds_2024$mcmc)[[2]]==paste0("SSB_",rds_2024$endyr+1))
dyB0 <- (rds_2024$mcmc[iter3:iter4]) / (rds_2024$mcmc[iter1:iter2])
dyB0_med <- apply(dyB0,2,median)
dyB0_low <- apply(dyB0,2,quantile, probs=c(0.025))
dyB0_high <- apply(dyB0,2,quantile, probs=c(0.975))
plot(time,(rds_2024$mcmccalcs$dmed[1:(rds_2024$endyr-rds_2024$startyr+2)]),type='l',ylab="Relative Spawning Biomass",xlab="Year",lty=1,col='black',ylim=c(0,1.6),lwd=2,las=T)
lines(time,dyB0_med,col="darkgreen",lwd=2,lty=2)
polygon(c(rds_2024$startyr:(rds_2024$endyr+1),(rds_2024$endyr+1):rds_2024$startyr),
        c((rds_2024$mcmccalcs$dlower[1:(rds_2024$endyr-rds_2024$startyr+2)]),
          rev((rds_2024$mcmccalcs$dupper[1:(rds_2024$endyr-rds_2024$startyr+2)]))),col=adjustcolor("black",alpha.f=0.2),border=NA)
polygon(c(rds_2024$startyr:(rds_2024$endyr+1),(rds_2024$endyr+1):rds_2024$startyr),
        c(dyB0_low,rev(dyB0_high)),col=adjustcolor("darkgreen",alpha.f=0.2),border=NA)
legend("topright",legend=c("Static B0","Dynamic B0"),lty=c(1,2),lwd=c(2,2),bty="n",col=c("black","darkgreen"))

Thanks Chris, and feel free to make it more attractive via our ggplot scheme.

**Comment by cgrandin** [comment]
Thanks @aaronmberger-nwfsc - For future reference, you can put triple backticks around the code so it shown up nice on here!

I can edit your post and already did it here, but you can go and edit to see how I did that
thanks

**Comment by cgrandin** [comment]
Finished in 0198d609f0bc2b31c495b1e4c4f67bbf099b9ca0

**Comment by cgrandin** [comment]
All the colors, etc can be set when the calls to make the plots get done.

**Comment by cgrandin** [comment]
Plots embedded in doc here 7ddea65175607cffb7f43e03367022b4e570dd0d

**Comment by aaronmberger-nwfsc** [comment]
I get an error with the:

```
plot_biomass_fished_unfished(base_model,
                             model_nms = c("Base model - Fished",
                                           "Base model - Unfished"),
                             rel = TRUE)
```

**Comment by andrew-edwards** [comment]
Think I can see the problem. Just running  a fresh build.

**Comment by andrew-edwards** [comment]
Have traced the problem, just not sure how to fix it.
Error is 
```
Error in `mutate()`:
ℹ In argument: `model = model_names`.
Caused by error:
! `model` must be size 1, not 2.
Run `rlang::last_trace()` to see where the error occurred.
```
which I've traced to here: https://github.com/pacific-hake/hake-assessment/blob/f078a717e4d73580acc9adc46512633161c94209/R/utils-extract-mcmc-quant.R#L39 

Tried changing the `mutate` to `bind_cols` which gave no error, but also didn't plot both lines. Will comment out the figure for now so the build works.

**Comment by andrew-edwards** [comment]
It's only the `rel=TRUE` figure that doesn't work.

**Comment by cgrandin** [comment]
I’ve already fixed this but haven’t pushed it because I’m not done yet, so don’t try to fix the relative biomass plot issues or we will end up with conflicts. Probably best to just comment it out if it breaks for you for now

**Comment by cgrandin** [comment]
Make sure you run clean() and start a new R session, It does plot fine
