### ISSUE TITLE
Priors in Figures 21 and 22 (prior and post plots) are a bit Etch-a-Sketch-y (and thus misleading)

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1101]
I looked into it and it seems they come from applying `geom_density()` on `base_model$parameter_priors`, which has `prior_random` for each parameter, which I think is a sample of 1000 from the prior. This then gets smoothed by `geom_density()`. 
Are we able to just plot the actual distributions? This may be a bit hard to fully automate (the defining of distributions), but the parameters are available to this can be mostly automated. 

Alternative quick fix is to make `prior_random` have 10,000 values, if it makes the distributions look smooth enough. But I'm not sure where that's made (and want to carry on with editing text right now).

**Comment by aaronmberger-nwfsc** [comment]
Agree. The priors should be smooth distributions.

**Comment by cgrandin** [comment]
Done in b594df529974076618390ed6cb2aa20d547c7a0e
