### ISSUE TITLE
Bridging model final relative biomass plot does not agree with base model plot

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1105]
Figure 16 we have
![image](https://github.com/pacific-hake/hake-assessment/assets/6977190/4691763f-ac94-4953-9495-0887f8d82eeb)

for which green is final bridging step (use modeled spatio-temporal maturity). But Figure 27 for base model we have 
![image](https://github.com/pacific-hake/hake-assessment/assets/6977190/f249e22e-0216-4899-adb9-b4c62e508279)

showing the stock being healthier all the way through (mostly way above B40). 
The bridging plot closely matches last year's plot (none of the bridging steps show a large change in relative biomass trajectory).

Am I missing something obvious?

**Comment by andrew-edwards** [comment]
Maybe someone first check a build on the server, though I downloaded all model results yesterday after Chris re-uploaded them, and we checked they were the same. So I don't think it's that.

**Comment by aaronmberger-nwfsc** [comment]
There is clearly an error in the rel spawning biomass figure with scale.  This may have arisen with recent edits to that plot when trying to add the dynamic B0 stuff (???).

**Comment by andrew-edwards** [comment]
Yes, that's it. I have Kelli's version she saved the other day and the relative figure looks correct. Phew.

**Comment by andrew-edwards** [comment]
Was comparing with last year's figure and wondered why it looked so different! Thanks. Chris can presumably easily fix it - I want to do some writing (and I'd get bogged down in debugging if I start digging into it!).

**Comment by andrew-edwards** [comment]
Think it's actually a bit more than that, as `curr_depl_median` has the value `143%`. The other day it was `80%`. So likely not the figure change.

**Comment by cgrandin** [comment]
Looks to be fixed not. Figure 27 was wrong, they now both match and `curr_depl_median` is 76% which makes sense given that the model changed a bit
