### ISSUE TITLE
Previous year's biomass not correct

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1106]
`prev_bio_median_last_assess` is 1.904 million t, but One-page summary from last year's assessment says 1,909,550 t (so not a rounding error).

Similarly, `prev_bio_lower_last_assess` to `prev_bio_upper_last_assess` is  0.760 to 5.429, but last year's one-page says 757,006 to 5,609,831.

The numbers I just quoted are the same as Chris's build from 12th Jan (that I kept for reference).

Not major differences but should be fixed. Not sure if related to #1105 or to do with that problem we had with exactly which model runs were used last year.

**Comment by cgrandin** [comment]
We have to put the rds file we used last year on the server. It currently has output from new code

**Comment by andrew-edwards** [comment]
I have the .rds. I'll test it now locally.

**Comment by andrew-edwards** [comment]
But I thought the structure had changed, which is why I originally got the new .rds from you. I'm leaving shortly and this will take a while to reload models, so won't get to it now, sorry. So I have `01-base.rds` dated 16/2/23 from last year.

**Comment by cgrandin** [comment]
@andrew-edwards If the structure has changed enough that we can't load it, let me know and I will strip the parts off the old one and place those into the new structure so that it works and the values are correct.

**Comment by andrew-edwards** [comment]
Just noting that the numbers in Table 27 (showing last year's results) are slightly wrong also - which makes sense if it's not the same .rds file. In case anyone was looking at them.

**Comment by andrew-edwards** [comment]
Also `med_est_2021_rec`, see first comment added in 2e6d3ad. Can remove that when this issue is resolved.

**Comment by andrew-edwards** [comment]
Okay, so using the base-01.rds (dated 2023-02-16) I have from last year's assessment (I'll upload it somewhere and post in Slack). 
`004-load-project-variables.rmd` fails, and I traced it down to L1088 (since `d_obj_bridge_recdev` from the bit before exists). Trying to run L1088 alone:
```
 iter <- 0
 d_obj_bridge_age1_index <- map2(bridge_models, bridge_models_names, ~{
    iter <<- iter + 1
   create_group_df_index(.x, .y,
                         survey_type = "age1")
 })
```
gives
``` 
Error in `map2()`:
ℹ In index: 1.
Caused by error in `map2()` at hake-assessment-2024/R/utils-extract-survey-index-fits.R:29:3:
ℹ In index: 1.
Caused by error in `UseMethod()`:
! no applicable method for 'filter' applied to an object of class "NULL"
Run `rlang::last_trace()` to see where the error occurred.
>
```
Am guessing it might be something to do with having no age-1 index value last year, but that's pure speculation. So over to Chris I think.

**Comment by cgrandin** [comment]
Thanks, that helps. If that’s all it is then it’s an easy fix. Until the next error crops up :) 
There is no end to debugging

**Comment by cgrandin** [comment]
I got this working fine but the values are still what they were. i.e.

```
prev_bio_median_last_assess is 1.904 million t, but One-page summary from last year's assessment says 1,909,550 t (so not a rounding error).

Similarly, prev_bio_lower_last_assess to prev_bio_upper_last_assess is 0.760 to 5.429, but last year's one-page says 757,006 to 5,609,831.
```

Are still the same, not what it in last year's one-page summary. So I think the only explanation for that is that the RDS file you posted is not the one we built the final document with
 
Also, we can't use the HTML comments to comment-out r objects, knitr still parses them on the first pass. I don't think we need those variables about probability that a given cohort is greater than the 2010 cohort (https://github.com/pacific-hake/hake-assessment/blob/34f6d547a2a0659cfe19a5c24064b90d6eae8480/doc/004-load-project-variables.rmd#L756) anyway so we should just remove this commented section.

**Comment by cgrandin** [comment]
@kellijohnson-NOAA , that's perfect. Can you put it in `/srv/hake/models/2023/01-version/01-base-models/01-base` - last year's base folder

Thanks!

**Comment by andrew-edwards** [comment]
I also have one from last year that I saved as `01-base-2023-02-09.rds` on 13th Feb 2023. Sounds like it's the same as Kelli's. I just took the later saved one from my directory yesterday (but must have sent Aaron the earlier one).
So let's try Kelli's first, which sounds like it should work.

**Comment by cgrandin** [comment]
This is done. Old RDS on server and has been fixed in structure to work with this year's document. Also reduced the size by 25 times. The Google drive will have the updated RDS at 

```
/srv/hake/models/2023/01-version/01-base-models/01-base/01-base,rds
```
