### ISSUE TITLE
citreproc ref not found

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1107]
At the end of the build:

**Citeproc: citation LindgrenEtAl2011 not found**

@kellijohnson-NOAA Looks like it is referenced in a section you edited 3 days ago in `008-data.rmd`

**Comment by kellijohnson-NOAA** [comment]
I added it in the main text because @andrew-edwards will be adding that reference to the .bib file when he integrates the citations from Eric's maturity analysis into an appendix.

**Comment by andrew-edwards** [comment]
Yes, this will get done when I do the appendix, so closing
