### ISSUE TITLE
Suggest we don't break tables over two pages when not necessary

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1110]
E.g. Tables 26 and 27 are short but get broken, and doesn't save a page by doing so.
Chris - I see \clearpage is still used elsewhere, so is that what can be done? 
I won't do anything, just wanted to note it.

**Comment by cgrandin** [comment]
Yes that’s what I figured we’d end up doing but I didn’t put any in because I knew we would have to redo it again anyway after adding things

**Comment by andrew-edwards** [comment]
Just mentioned it in case it ends up being a bigger issue than I thought. Extra `\clearpage`s may actually help with #1109. Perhaps.

**Comment by andrew-edwards** [comment]
Also I just clicked on a Table 24 link and it went to the page before Table 24. No big deal but may be related also (Table 23 goes over two pages).

**Comment by cgrandin** [comment]
Going to close this, as we will figure it out as we finish up the cosmetics
