### ISSUE TITLE
Figure j in exec summary and Figure 39 need forecast time series

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1111]
These two identical figures (one in the main document and one in the executive summary) need the forecast catch scenarios added to the plot.

**Comment by cgrandin** [comment]
The new objects in the model object created are:

```
base_model$forecasts$<forecast year>$<catch stream>$depl
```

Example - for projected 2025 assessment forecast for 2023 catch we get:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/31891ffe-e6af-442a-9192-c118500113ef)

The Executive Summary builds fine, I didn't build the rest yet

**Comment by aaronmberger-nwfsc** [comment]
Thanks for adding these @cgrandin.

I notice that the pre-forecast relative spawning biomass time series in these plots don't match our relative spawning biomass time series without forecasts (i.e., figures e and 27) - maybe it is only for the 2024 point.  Last year, the end year (2023) lined up correctly.

**Comment by cgrandin** [comment]
It's for the 2024 point, because 2024 is replaced with the forecast value for that plot. It is the only way to make the series line up, and it is "more" correct isn't it?

In previous years it was the same, the end year in the two plots is not the same.

**Comment by aaronmberger-nwfsc** [comment]
I don't think it is correct.  Biomass (and relative biomass) at the start of 2024 is not a forecast.  Our executive summary says rel biomass at the start of 2024 is 76.4%, but then these forecast figures say it is ~43%.  I think that's wrong.

This figure in last years document lines up with what is in the executive summary (i.e., both show 2023 rel biomass just above B0), so there must have been a change.

**Comment by cgrandin** [comment]
Ok, I can put it back to use the 2024 value from the model output. It will look really weird though as there'll be a huge bump up and then down in one year.

**Comment by cgrandin** [comment]
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/7a464107-54bb-421a-8266-19e1335e0068)

**Comment by cgrandin** [comment]
See how the forecasts don't line up...

**Comment by cgrandin** [comment]
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/a66e2cb3-a742-41e1-bf81-db1d16cb466b)

**Comment by cgrandin** [comment]
Updated the 2024 depletion in b4313bc05cba55987df4594ad8cfad0a83f2cc7b

**Comment by aaronmberger-nwfsc** [comment]
Hmm, I'm still not fully following.  While the connection to 2024 now looks good, I can't understand why No Fishing scenario would bring it right back down so drastically.  I would have thought it would have been something similar to last year where the no fishing scenarios doesn't have a huge effect (figure from last years assessment):
<img width="692" alt="image" src="https://github.com/pacific-hake/hake-assessment/assets/7946234/ac1f4138-2145-417a-891e-a850d2283f16">

Am I missing something?

**Comment by cgrandin** [comment]
The values appear to be correct...

This is the chunk of code where the calculations take place: 
https://github.com/pacific-hake/hake-assessment/blob/b4313bc05cba55987df4594ad8cfad0a83f2cc7b/R/load-forecasts.R#L83C6-L104C29


The depl value is Bratio_* / SSB_Initial from the forecasts mcmc values (posteriors.sso). Is that correct? See this line:

https://github.com/pacific-hake/hake-assessment/blob/b4313bc05cba55987df4594ad8cfad0a83f2cc7b/R/load-forecasts.R#L100

**Comment by cgrandin** [comment]
Nevermind... I shouldn't be dividing BRatio by SSB_Initial, it should just be BRatio itself. Stand by

**Comment by aaronmberger-nwfsc** [comment]
The purple line should follow our decision tables for the No Fishing (a) scenario, so the points in 2025, 2026, and 2027 should be 1.00, 1.02, and 0.98, respectively.  The other catch scenario lines (green, red, blue, black) should also match the decision table median rel spawning biomass output values.  The decision table looks correct.

<img width="566" alt="image" src="https://github.com/pacific-hake/hake-assessment/assets/7946234/eaf90b1a-9b9a-449d-af34-78530701fa95">

**Comment by cgrandin** [comment]
I was dividing by B0 twice. I blame myself for calling it biomass in the previous code even though it was depletion. I was too lazy to change it all apparently. 

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/0f6b88e3-6483-47f7-a3f2-a898017cde60)

**Comment by aaronmberger-nwfsc** [comment]
ohh - that looks good!  I don't blame you at all.  I blame myself for asking you to make the static and dynamic B0 plots and the fished and unfished biomass trajectories plots because then you start dividing by all sorts of non-usual stuff that gets confusing.  So I'm guessing you were still thinking on that level.....

Close this sucker up Chris.

**Comment by cgrandin** [comment]
Done in 5031a68303bd64a623784b050a9daa8a47ebd1ec

@aaronmberger-nwfsc close this please if satisfied
