### ISSUE TITLE
Fig 39, depletion with forecasting has the CI's out of bounds (top)

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1114]
Reminder to myself - I need to modify CI data as I have done on other plots like this

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/91c454f8-33d2-4a4a-8ead-ba2c8fcd926a)

**Comment by andrew-edwards** [comment]
Can't just change the `ylim`? I did notice this just now and thought that would be the fix.
