### ISSUE TITLE
Comments on the new Cohort table?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1116]
I replaced the old one which was a wide table with few rows to a long table with many rows and cohort groups. If someone doesn't want to use this I need to know right away so I can revert everything back to the old way.

Reasons for changing it:
- make it simpler for us to add/remove cohorts to the table
- it is easier to implement the accessibility on a simpler table like this (hopefully)
- allow for an arbitrary number of cohorts to be in the table as the table can break across pages
- much simpler to code and maintain
- no vertical lines, which follows research paper standards (we have removed tham all from the tables in this doc)

The old way:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/663815b2-0118-4589-8e3d-6c2acf8293ad)

The new way (only part of it shown here):
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/43c57470-eaa2-4939-856d-461a1dbef788)

**Comment by cgrandin** [comment]
I hope I haven't already asked this..

**Comment by aaronmberger-nwfsc** [comment]
I don't have any issues with the new format.

**Comment by kellijohnson-NOAA** [comment]
I am okay with the change.

**Comment by cgrandin** [comment]
Great, closing it up then as it was just a question
