### ISSUE TITLE
Cannot place two (or more) short  landscape tables on one landscape page

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1118]
This can possibly be ignored until after the SRG meeting, but the age proportion data tables have few rows and they are consecutive. They should be placed on one page but cannot be currently.

This will take a lot of programming time

**Comment by andrew-edwards** [comment]
I wouldn't bother - having them each on a new page makes it easy to flip between them to see differences. A bit of white space is fine also, a bit easier on the eye.

**Comment by cgrandin** [comment]
OK, I will close this and try to remember that it can't be done currently.
