### ISSUE TITLE
Figure 60 and 61 captions are not correct

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1122]
I've done the rest but the captions for those two don't make sense to me - these were the plots you came up with so I am assigning you @andrew-edwards 

I added checkboxes in #1082 for these.

**Comment by andrew-edwards** [comment]
What doesn't make sense? I've just updated the highlighted years in the first caption (not pushed yet), but the rest hasn't changed from previous years. Is that it?

**Comment by cgrandin** [comment]
You have Blue squares - I guess you meant triangles?

> For the 2024 assessment the probabilities are shown for all catch
> alternatives for 2024, as described in Table ??, with 0 t shown in pink.

There's no pink, but maybe that is supposed to be red, not sure becuase I don't see lines for each catch alternative from the decision table, only one red line.

**Comment by andrew-edwards** [comment]
Triangles, squares - they're topologically equivalent! Thanks - good spot. 

Pink should be from the forecasts - I'm still building and was expecting that to show up. Aha - it should now, as I had set `add.projs = FALSE` last week to get building. I'll check, hopefully changing to `TRUE` will fix it.
