### ISSUE TITLE
Shorten verbose text in 1-page summary about new data

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1123]
https://github.com/pacific-hake/hake-assessment/blob/940416319630608f97ef2f54b3b69886ceb877f5/doc/005-one-page-summary.rmd#L13-L18

Could be shortened to say `Data for `r end_yr-1` were included for each data set and minor changes to pre-`r end_yr-1` data were made as necessary.` And we could have a different blanket statement for non-survey years. I think this would give us a bit more flexibility to make an additional statement or provide more about the model. Also, I wouldn't be suggesting this if we did not list every data source in the previous bullet. I am happy to cut that bullet instead if people want to keep this one as is.

**Comment by aaronmberger-nwfsc** [comment]
Makes sense to me @kellijohnson-NOAA
