### ISSUE TITLE
DM parameters hard to interpret

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1124]
A comment from internal review mentioned that the Dirichlet Multinomial parameters in our Figures 20 and 21 as well as in the parameter Table 26 are hard to interpret.  We could consider showing these as back transformed values:   [exp(theta) / ((1+exp(theta))] 
I think we already do that calculation in load-project-variables as we use it in the text. 

I'm not convinced this is needed as what we do show is indeed the parameter theta, and we do have in the text what that value means in terms of traditional data-weighting values.

Thoughts?

**Comment by cgrandin** [comment]
This is what that look like
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/3d890042-b94e-4ce7-994b-337587f57692)

But then it cannot be compared to previous assessments...

**Comment by cgrandin** [comment]
When set to the posterior limits:

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/5a352953-072c-4587-8bda-8cdf8ce87396)

**Comment by andrew-edwards** [comment]
From memory, I thought we generally talk about theta everywhere, but also give the calculations as Aaron said. We do show log theta in some tables, so much easier to stick with what we have, though the reviewer has a point. Kind of think this got discussed a while ago and we went with theta and log theta.

**Comment by aaronmberger-nwfsc** [comment]
I think we are fine showing log(theta) here; in response to the internal reviewer I added log(theta) in our text in places where we should have had it.  I think that resolves the basic confusion when we were calling it theta but it was negative (impossible).  So I'm closing this.  Thanks @cgrandin for showing the figures.
