### ISSUE TITLE
Do we "estimate" catch or "calculate" catch?

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1127]
https://github.com/pacific-hake/hake-assessment/blob/80bf192c9e81759ce9589509407430df4b13ad50/doc/006-executive-summary.rmd#L86-L89

The ES has the term "estimated" catches but we really do not estimate catch within the assessment as a parameter or a derived quantity because we do not have discard rates. So, I think it is somewhat misleading to say estimated here even though they are estimated in the field. We can leave this as is if others want to.

**Comment by aaronmberger-nwfsc** [comment]
agree; maybe just change to 'that cohort being approximately...'
