### ISSUE TITLE
2023 TAC is incorrect

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1131]
Looks like the TAC values were not updated from last year just the catches were. I can fix them but I just wanted to make an issue so we can discuss how we want to handle this with respect to the draft document. Also, @cgrandin can you verify that the Canadian value below is correct? I got the U.S. values from the [2023 Federal Register](https://www.federalregister.gov/documents/2023/04/06/2023-07097/magnuson-stevens-act-provisions-fisheries-off-west-coast-states-pacific-coast-groundfish-fishery). And, here is a link to the [U.S. Federal Register for 2022](https://www.federalregister.gov/documents/2022/06/02/2022-11728/magnuson-stevens-act-provisions-fisheries-off-west-coast-states-pacific-coast-groundfish-fishery) where it lists 545,000 t as the 2022 coastwide TAC.

https://github.com/pacific-hake/hake-assessment/blob/9cdc66d78cfdcdbd2adf01571fac70ef699c48c6/data-tables/landings-tac-history.csv#L59

I opened a branch `fix-2023-TAC` that has the above values, we can merge it in when I know that they are correct.

U.S. TAC = 461,750
CAN TAC = 163,250
Total TAC = 635,000

**Comment by cgrandin** [comment]
I updated this file and left it because the 545,000 was set two years in a row. It was set at the JMC meeting last year and the year before at 545,000 both times was it not? Have I forgotten something?
If so, then the previous year is probably wrong too

**Comment by aaronmberger-nwfsc** [comment]
The US federal register says the US portion of the TAC was 461,750, so dividing that by the allocation of 0.7388 equals a coastwide TAC of 625,000 last year.

**Comment by aaronmberger-nwfsc** [comment]
I'll confirm with Colin today that the coastwide TAC was 545,000 in 2022 and 625,000 in 2023.  If correct, we can easily update that value.  We *may* also have to redo that forecast run.  Doing so would be consistent with what we normally do (i.e., include a run with constant catch at y-1 coastwide TAC).  However, a constant catch at 625,000 isn't really that helpful and then leaves a gap between 430,000 constant catch scenario and other scenarios in the 600,000 range. We could just change the label from "2023 TAC" to "2022 TAC".  Thoughts?  I'll post here what Colin says.

**Comment by kellijohnson-NOAA** [comment]
I feel like we should also send an email to John, Owen, and the SRG members that will be present.

**Comment by cgrandin** [comment]
I think for the final draft we should be consistent and replace the 545 with the 625 forecast. It shouldn't affect much as they are catching less than half that but can fix this ahead of time and show the new decision table in the meeting

**Comment by kellijohnson-NOAA** [comment]
Should I merge the branch into main then?
