### ISSUE TITLE
Bug in forecasting

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1133]
I just noticed that the FI 100% forecasts are based off the DHCR.
Unless a total coincidence, I don't think the 2024 value should be the same for both FI=100% and DHCR.
Here is last year:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/61ad663c-5989-4d62-a210-258a3d59cf6b)
Here is this year:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/1be70889-33d8-49a2-b985-5ffd14510413)

**Comment by cgrandin** [comment]
Does not appear to be a bug, it looks like I just had the tolerance for the FSPR case set to 10%, and the FSPR value at the TAC of 545,000 was 91.5% so it passed on the first pass, and never updated the initial value. I am setting the tolerance to 1% and re-running the forecasting (we needed to anyway to update the 2023 TAC to 625,000).

Mt fault on this one, I forgot that I had set all the tolerances so that the forecasting ran more quickly during the draft process so we could "get working" and forgot to re-run them at a lower tolerance. I think we will have to hand out new decision tables.

This should be all done by later tonight or tomorrow. I don't know for sure how long because of the iterative nature of the "zoning in on catch" algorithms.

**Comment by cgrandin** [comment]
There were two issues here. In addition to the tolerances being set too high I discovered another bug. The FSPR=100% and Default HR cases were swapped. So in the decision table in the draft, rows 'm' and 'n' were swapped. That doesn't really matter and we could just not even mention it because they are almost identical anyway in the draft due to the tolerance issue.

All this has been fixed and the new decision table looks ok. Here it is for Rel. biomass:

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/88f76ff7-9a48-4cfd-ad96-96812e8173ff)

Also, the last bullet in the One-page Summary has changed a lot due to the 625,000 TAC instead of 545,000:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/e42b9f76-2f8f-4f34-b645-b043c727f1a3)

**Comment by andrew-edwards** [comment]
Nicely done. If I remember correctly we had a similar problem in a previous year, or maybe the numbers came out the same (by coincidence) and it was a bit confusing. 
So the numbers in the draft are correct, they just don't correspond to last year's TAC. I would say the percentages have not changed too much, and such catches are way above realistic catches anyway, so not a huge deal (no need to alert anyone before the meeting I think).
And so bullet 3 (and other text) will automatically get updated with the 2023 corrected TAC. All sounds good. Thanks Chris.

**Comment by andrew-edwards** [comment]
Though I guess stating last year's TAC incorrectly is a bit of a big deal, so maybe we could send an email beforehand.

**Comment by cgrandin** [comment]
This is fully done now.
