### ISSUE TITLE
Survey posterior fits figure not working 

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1137]
This figure doesn't build for me anymore (in assessment presentation but also in general).  Any changes recently that would have affected that?

```
plot_selex_posteriors(base_model,
                      type = "survey",
                      age_range = c(1, 8),
                      n_posts = 1000,
                      post_med_line_color = "red3",
                      unc_line_color = "red3",
                      glow = TRUE)
```

**Comment by andrew-edwards** [comment]
No longer working for me either; I just hadn't noticed in the build.

**Comment by cgrandin** [comment]
It's caused by my fix for the fishery one from last week. They use the same code and the  end yr is different, so when I fixed the end yr for the fishery, it broke the survey one. I am now running `load_extra_mcmc()` with the fix.

**Comment by cgrandin** [comment]
Need the new base model RDS
