### ISSUE TITLE
Add ticks to maturity ogive plot

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1142]
Noticed during SRG meeting that non-numbers on x-axis don't have ticks

**Comment by andrew-edwards** [comment]
Suggest maybe adding some faint vertical grey lines also, to make it easier to compare years for age-2 and age-3 in particular.

**Comment by kellijohnson-NOAA** [comment]
Do we need to keep this figure now that they have asked us for a heat map with the values per year. I am inclined to remove it.

**Comment by aaronmberger-nwfsc** [comment]
We've had a maturity figure every assessment so I'm thinking given that we switched to a 'new approach' that it would be weird to now not have one.  I'd like to keep it I guess.  Though if you wanted to remove the inset, I think that would be fine.

**Comment by kellijohnson-NOAA** [comment]
I really don't care either way, just trying to decrease the "creep" of more stuff/longer documents when the information is now in the heat map. But, I guess we do show weight-at-age by year in a figure as well as the heat map. So, ignore that I said anything.

**Comment by aaronmberger-nwfsc** [comment]
Given the changes this year, I think it makes sense.  However, I can easily see next year we remove one or the other (figure/table) for weight-at-age and maturity-at-age and fecundity-at-age.  Or keep all three tables and have only one figure that includes them all.  Just thoughts...
