### ISSUE TITLE
Figure 8 (age comps) has 2021 cohort highlighted in top panel and 2020 in bottom. 

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1148]
Be good to have consistent (or remove them both because they're so uncertain still?). I thought Chris had an issue somewhere about which cohorts were 'large'. 

Though looks a bit fiddly to change, so can just leave it. Thought I'd mention it (spotted while checking the alt text).

**Comment by andrew-edwards** [comment]
Fig 24 (residuals) is also slightly different to Figure 8. Not a huge deal, and fine with leaving it (or fixing next year).

**Comment by cgrandin** [comment]
Completing #1150 will complete this
