### ISSUE TITLE
git rm .rmd presentation files that are not used

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1153]
It was confusing why the text in some of the JMC presentation did not match the actual rendered pdf. Finally, I got my act together and looked at the bookdown file to see that we are referencing text from the SRG presentation, which is great. I was just being dumb. Anyways, it would be good to remove the files that we are no longer using.

**Comment by cgrandin** [comment]
I was going to do this but haven’t found time yet to make sure that we aren’t deleting something we might want, in particular for the JMC presentation this year. I know it’s in the repo in previous commits but I figured I might forget to look there !!
You can delete them all though if you want, I’ll remember now

**Comment by cgrandin** [comment]
Also did you know you can just delete the files in file explorer ? And then commit
