### ISSUE TITLE
capitalize Pacific whiting

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#122]
If we are following the 'new' guidlines (by some anyway; AFS) of capitalizing the common name as in Pacific Hake, should we not also to the same for Pacific Whiting.  I'll make changes (only a few spots) unless I hear otherwise.

**Comment by allan-hicks** [comment]
I've been waiting for this question. Ian Taylor and I have discused this a
lot in the past few years, and we determined that AFS says to capitalize
the accepted common name of the species (Pacific Hake) and not other names.
Like you would capitilaze Widow Rockfish, but not brown bombers.  So, we
figured to capitalize Pacific Hake, but not Pacific whiting.  However, I've
been trying to use \fishname\ in case you want to move away from
capitalization.

**Comment by cgrandin** [comment]
It should only need to be done in hake-assessment.rnw on this line:
`\newcommand{\commonname}{Pacific whiting}`
If you see anymore in the text, we should change those to \commonname\

**Comment by aaronmberger** [comment]
Well, it sounds like you guys have made an informed decision so I'm happy to leave as is.

**Comment by andrew-edwards** [comment]
Agree with Allan. Think we discussed this a few weeks back.
