### ISSUE TITLE
various things related to bubble plots

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#423]
**Diagonal lines**
In commit 516eb06420ffd890b22de0ab013cb87026fcde63 I added an option to add diagonal lines for the large cohorts to Figure 8 as discussed https://github.com/cgrandin/hake-assessment/issues/298#issuecomment-363271354 and elsewhere. I didn't add them by default but if we want them present, we would need to supply a `cohortlines` argument to `make.age.comp.bubble.plot()` in main-figures.rnw. There's no control over the color or line type but those are easy to change.

**Minor bug in Pearson plot**
In the process of adding the lines I noticed a minor bug in figures-age-comps.r whereby the plot uses `model$extra.mcmc` when it should use `model`. The change made a very small difference in the size of the residuals, making me think it previously showed the residuals for one of the mcmc samples not the MLE. This is also fixed in 516eb06420ffd890b22de0ab013cb87026fcde63.

**Diversity of methods for bubble plots**
We use many ways of making bubble plots for age comps or residuals in the document and presentations:
1. A custom function `make.age.comp.bubble.plot()` is used to make the bubble plot showing the age comp data in Figure 8 of the document
2. The r4ss function `SSplotComps()` is used to make the Pearson residual plots in Figure 25 of the document (both fleets) and also in the assessment presentation
3. The PBSmodelling function `plotBubbles()` is used to make bubble plots for the data presentation

In some future year, we might consider reducing this diversity of approaches, so that at least figures 8 and 25 are consistent in appearance.

**Comment by cgrandin** [comment]
This is finished! Finally!

**Comment by andrew-edwards** [comment]
Figure 8 (age compositions for survey and fishery) looks quite different to last year, so I don't think that "area of the bubbles are proportional to the proportion" is correct. I think it's now the radius, but we should stick with area. I think it involves changing
```
 g <- ggplot(d, aes(x = Year, y = Age, size = sqrt(Proportion))) +
 ```
in `plot_bubbles` to 
```
g <- ggplot(d, aes(x = Year, y = Age, size = Proportion)) +
```
And maybe elsewhere [though `?ggplot` doesn't instantly explain what `size` is, radius or area]. Chris - we can chat tomorrow, especially given you've just worked on all these. 
Also suggest lightening the grey, and maybe not adding the red lines to highlight cohorts? In last year's version they show up clearly. I kind of think the data should speak for themselves - the lines kind of obscure things a bit.

**Comment by andrew-edwards** [comment]
I'm a bit confused about the new plot now (if it's using the radius, shouldn't the differences be more pronounced?). 1984 age-4 proportion is 62% of that year, age-7 is 17% (so about 3.6 times). Measuring the bubbles on last year's plot that sounds right (assuming they were areas), but on this year's, I get (blowing the figure up): age-4 is 10mm diameter, age-7 is 8mm diameter. Ratio of radii is therefore 1.25, ratio of areas is.... 5^2/4^2 = 25/16 = 1.56. So I'm not too sure what's being plotted in the new figure.....

**Comment by kellijohnson-NOAA** [comment]
[This ggplot2 post](https://ggplot2.tidyverse.org/reference/scale_size.html) might be helpful, if you use a scale to set the scale to start at zero and thus have an area of zero to the max value then the sizes will be by area.

**Comment by cgrandin** [comment]
In the plot_bubbles() function I made uses ggplot.. See this bit: 

```
g <- ggplot(d, aes(x = Year, y = Age, size = sqrt(Proportion))) +
```

The square root makes it area that's proportiononal

**Comment by cgrandin** [comment]
Square root was used in the previous code as well.

**Comment by cgrandin** [comment]
I hate to cite wikipedia but : https://en.wikipedia.org/wiki/Bubble_chart

The section "Choosing bubble sizes correctly" explains it pretty well I think

**Comment by cgrandin** [comment]
I've repaired all these in 2bcaf965d783bbde5e1ea19ed6e5815b801ced9c, 43215594f868cf82ff7a62731a553dde4e202176 and d9bed7e278bd5558808dfe920e17c831cd68c067
