### ISSUE TITLE
Alternative squid plots

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#454]
**Downweighted age comps from fishery or survey**
Squid plots for models with downweighted fishery or survey ages were discussed in issue #410 as a way to explore the influence of each data set on the estimation of deviations. These were not included in the 2018 assessment but they might be worth considering for future documents. Even without the squid plots, the models with one or the other data set downweighted could be considered as additional sensitivities.

**Squid plot based on historical assessments**
Separately, at the 2018 JMC meeting, Paul Ryall asked if it would be possible to make a squid plot showing the retrospective estimates over the true history of assessments applied in each year, rather than the current assessment with data peeled back one year at a time. This required an edit to the SSsummarize function in r4ss (commit cbced3b6f0acf461db52f15893e48fa9f75555cb) but is now possible using commands below, which produced the figure pasted below. Over the period 2011 to 2018, things have been pretty stable, although the low survey biomass estimated in 2011 first included in the 2012 assessment cause a drop for the in between the first 2 points for the '05, '06, and '08 cohorts. 

I'm not convinced that this plot is that useful, but perhaps a side-by-side comparison with the base model squid plot would be informative.

```
# read base model MLE assessments from each year starting in 2011
# (model files are archived on NWFSC network but available upon request to anyone)
h2011 <- SS_output('PWhiting2011/SS_2011_base_case_model_files', covar=FALSE, forecast=FALSE)
h2012 <- SS_output('PWhiting2012/2012 MLE model files (not base model)')
h2013 <- SS_output('PWhiting2013/2013hake_mle_notBase')
h2014 <- SS_output('PWhiting2014/2014hake_21_TVselex1991start_MLE')
h2015 <- SS_output('PWhiting2015/base_model_MLE')
h2016 <- SS_output('PWhiting2016/base_model_MLE', forecast=FALSE)
h2017 <- SS_output('PWhiting2017/MLE model files', covar=FALSE, forecast=FALSE)
h2018 <- base.model

# summarize output across assessments
h.sum <- SSsummarize(list(h2011, h2012, h2013, h2014, h2015, h2016, h2017, h2018))
# make squid plot
SSplotRetroRecruits(h.sum, endyrvec=2011:2018, cohorts=1999:2016)
```
![image](https://user-images.githubusercontent.com/4992918/37539058-db0b4476-290f-11e8-9501-250e7a3df8f8.png)

**Comment by andrew-edwards** [comment]
You're still working on hake! ;)

Yes, not sure how useful that new plot is - impressed you got it working though. Bit of a dismembered squid though....

**Comment by taylori** [comment]
Just trying to write down anything lingering in my mind before it completely gets taken over by other stuff. 

It was good to realize that the SSsummarize step wasn't working right for comparing models from different years because the parameter labeled "Main_RecrDev_2016" in the 2018 base model was labeled "Late_RecrDev_2016" or "ForeRecr_2016" in earlier models with different ending year and different range of "main" recdevs. I don't think that issue impacted anything we've done in the past, but is good to have fixed in general (they now show up in the same row of the $recdev table output from SSsummarize, rather than different rows).

**Comment by taylori** [comment]
Temporarily closing "2020 assessment" milestone issue
