### ISSUE TITLE
SRG requested table of changes in model structure

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#461]
The SRG recommends that the JTC produce a table showing changes in model structure and parameterization that have been implemented since 2011 as a standard table to be included in the assessment document. 
how much detail here?  Probably most of the information needed is in one-page exec summaries or relevant section (3.2 in 2018); Ian/Andy to work on this

**Comment by taylori** [comment]
Postponing this to 2020 assessment due to U.S. government shutdown.

**Comment by taylori** [comment]
Temporarily closing "2020 assessment" milestone issue

**Comment by cgrandin** [comment]
I decided not to add to this table, although I stashed some changes locally in case we want to include some information on data changes and survey analysis decisions over time

**Comment by andrew-edwards** [comment]
This is Table 18, yes? Was done last year, and updated by someone already this year. (Just confused by your comment....).

**Comment by cgrandin** [comment]
Yes it is and it’s done for this year unless I add more columns. I was spending too much time trying to make the table work so I set it aside
