### ISSUE TITLE
SRG request: Canadian samples for maturity analysis

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#465]
Final sentence of text below from 2018 SRG report is related to Canadian samples in maturity analysis (the rest about genetics is described in #464):
> 4. The new histological analysis of ovaries for maturity, like previous analyses, showed a distinct difference in the percent of hake that are mature at age 2 and age 3 between areas, with a greater proportion mature south of Point Conception (34.47°N). These data suggest that there may be two populations of hake, north and south of this boundary. The SRG also notes that ovaries collected in Canada were not used to update the maturity ogive. The hake found in Canada are generally older age fish and including samples of these fish in the maturity analysis should improve the robustness of the maturity ogive. **The SRG strongly supports the planned genetic analyses to determine whether there are also genetic differences between these two southern regions and other regions as well. In addition, the SRG notes that Canadian samples should be included in the maturity analysis.** 

@cgrandin to work on figuring out what it would take to get ovary samples from Canada to Seattle or have DFO staff trained by Melissa Head on the histological methods she uses for maturity analysis. Presumably the 2019 survey or fishery would be the earliest time to actually get samples, but the response to SRG request could include a note about progress toward that goal even though

**Comment by aaronmberger** [comment]
Chris/Andy:

The following response to SRG request regarding adding Canadian ovary samples into new maturity analysis okay, anything additional to add at this point?

[Regarding including the Canadian samples in the maturity analysis, DFO is
  continuing to assess workload logistics, including the possibility of getting trained by Melissa
  Head (NWFSC) on the histological methods she used in the recent maturity analysis or
  alternatively getting samples sent from Canada to Seattle, if appropriate.
  Presumably, the 2019 survey or fishery would be the earliest time to get any additional
  Canadian samples.]

**Comment by cgrandin** [comment]
There isn't anything new to add here. We had a rotten time with the contractor this year, they could barely get us the samples and data let alone ask them to do more. I think the survey is the best bet for 2020.

**Comment by aaronmberger** [comment]
Seems we can close this now with updated text in doc

**Comment by kellijohnson-NOAA** [comment]
# 2022 Assessment

SRG Request # 5

> The SRG encourages work to develop a picture of the Pacific Hake reproductive cycle both seasonally and at the life-time scale based on histological and physiological measurements. In addition, the SRG notes that Canadian samples and those from the winter research cruises should be included in the maturity analysis. The SRG encourages continued sampling and analysis to improve understanding of the Pacific Hake reproductive cycle.

**Comment by aaronmberger-nwfsc** [comment]
Just a simple two sentence response to SRG this year given no real progress:
\fishname ovary samples continue to be collected (see Table~\ref{tab:main-ovaries}) for future
  analyses. While laboratory work has been limited over the past year due to facility closures, plans remain
  to include any available Canadian samples in subsequent maturity analyses.

I'm closing this for this year as not much else to do at this point.
