### ISSUE TITLE
SRG request: review of how time-varying selectivity is parameterized and estimated in other assessments

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#466]
2018 SRG request:
> The SRG notes that when setting values for other parameters that cannot be estimated directly with confidence, the choice of values should be made using methods that are objective, repeatable, and depend on fits to the observed data rather than on the model’s subsequent estimates of biomass or recruitment. One clear example is setting the parameter controlling time-varying fishery selectivity (ɸ), with a goal of establishing repeatable steps for setting ɸ each year. **The SRG recommends that the JTC provide a review of how time-varying selectivity is parameterized and estimated in other assessments.**

@taylori is working on testing the semi-parametric approach which shows some promise at being able to estimate the variance parameter and also trying to compile some info on approaches to time-varying selectivity used in other assessments.

**Comment by taylori** [comment]
I propose postponing this to 2020 assessment due to U.S. government shutdown.

**Comment by taylori** [comment]
Temporarily closing "2020 assessment" milestone issue

**Comment by andrew-edwards** [comment]
Andy to look for any Canadian assessments examples of time-varying selectivity
