### ISSUE TITLE
SRG request related to sigmaR

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#468]
From 2018 SRG report (item 1, second sub-bullet): 
> The SRG encourages the JTC to explore methods for parameterizing recruitment and/or estimating sigmaR that would reduce model sensitivity to the value of this constraint.

**Comment by taylori** [comment]
Temporarily closing "2020 assessment" milestone issue

**Comment by andrew-edwards** [comment]
Ian on a closing frenzy... All that Marie Kondo stuff ...

I'm copying the SRG requests into the document shortly, and will add a sentence regarding the ones we couldn't do.

**Comment by aaronmberger-nwfsc** [comment]
Just looking again at sigmaR and t.v. selectivity parameter phi and did the following:
1. Conducted a bi-variate likelihood profile of these two fixed parameters to see how much 'action' there is - plot just below shows differences in the negative LL between the base model (box) and alternative fixed values.
![image](https://user-images.githubusercontent.com/7946234/72647470-81aafe00-392d-11ea-9e0b-43fd43dd28cf.png)

The below figure is the same for 2020 Depletion:
![image](https://user-images.githubusercontent.com/7946234/72647512-97b8be80-392d-11ea-8f95-01357204c57a.png)

I note that the survey extra SD parameters and the Dirichlet Multinomial parameters for fishery and survey do not change much:
SD parameters: range is 0.24563 - 0.250434
DM fishery: range on transformed theta to actual weight is 0.4192 - 0.4832
DM survey: range on transformed theta to actual weight is 0.8972 - 0.9101

2. tried estimating sigmaR in MLE model (likelihood profile below):
![prof_sigmaR](https://user-images.githubusercontent.com/7946234/72647814-43620e80-392e-11ea-82cc-5440fbc06ec4.png)

Estimate is 1.67 with comp data pulling it towards larger values:
![prof_sigmaR_Acomps](https://user-images.githubusercontent.com/7946234/72647915-8ae89a80-392e-11ea-844d-b058b062b3ce.png)

**Comment by aaronmberger-nwfsc** [comment]
I think our general recommendation that more research needs to be done on concurrently estimating variances associated with Dirichlet Mult, t.v. selectivity, sigmaR, and extra SD parameters.  Estimating sigma R had little influence on DM and SD parameters, but I didn't delve into additionally estimating phi (variance associated with t.v. selectivity).  The affect on stock status is a shift slightly down, given upward shift in eq biomass. 
![compare2_spawnbio_uncertainty](https://user-images.githubusercontent.com/7946234/72648284-88d30b80-392f-11ea-963c-f3408b7fcef0.png)

**Comment by aaronmberger-nwfsc** [comment]
I added a response to this SRG request in commit f28aa38, though I would appreciate it if you have a look to make sure it makes sense.  I did not cite any of the figures above - as they were more for back pocket stuff at SRG.  I'll close for now.

**Comment by kellijohnson-NOAA** [comment]
# 2017 Assessment

Issue #180

**Comment by kellijohnson-NOAA** [comment]
# 2022 Assessment

Text from the 2021 SRG Report 
1. The SRG notes that σ_{R} is an influential parameter and that determining the choice of σ_{R} remains a challenge and encourages the JTC to continue to work on the issue.

**Comment by kellijohnson-NOAA** [comment]
- [ ] Run the model using WHAM (KFJ)
