### ISSUE TITLE
catch levels for decision tables

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#574]
Get catch level recommendations from the JMC for 2020. At the 2019 Feb. SRG meeting it was brought up that equally spaced increments could be helpful.

**Comment by cgrandin** [comment]
To run forecasting with the new catch level of 500,000, make a copy of the base model folder and call it `2019.03.00_base_srg500000`, then delete the folder `mcmc/forecasts`

Run the following:
`source("R/all.R");build(TRUE, FALSE, FALSE, "2019.03.00_base_srg500000")`

**Comment by andrew-edwards** [comment]
Also have to update the captions (in Exec Summary and main tables) , and check the actual text.....

**Comment by andrew-edwards** [comment]
Hmmm.... I get an error:
```
...
If you see 999, we got to the end of the control file successfully! 999
Making a copy of an unallocated dvector
Making a copy of an unallocated dvector
 end of parameter section 
Error: param_init_bounded_number_vector was not allocated.
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In shell(shell.command) :
  'cd c:/andy18/github/hake-assessment/models/2019.03.53_fecundity/mcmc/catch-levels/default-hr & ss3 -mceval' execution failed with error code 1033
2: In file(file, "rt") :
  cannot open file 'c:/andy18/github/hake-assessment/models/2019.03.53_fecundity/mcmc/catch-levels/default-hr/derived_posteriors.sso': No such file or directory
```
Same for base case. I'll try again in the morning (when more alert!), just mentioning in case anyone else gets it....

**Comment by aaronmberger** [comment]
I got an error too, but restarting my R workspace seems to have solved it.

**Comment by andrew-edwards** [comment]
Ah, that old chestnut. But I started a new R session each time.

**Comment by cgrandin** [comment]
Just so you know, I'm most of the way there but having some issues with the risk plot. I'll push everything once I get that right. It's been a lot of poking around and debugging to get this right.

**Comment by cgrandin** [comment]
I got it working at 1AM. I have the new doc built for the morning

**Comment by andrew-edwards** [comment]
All done and Chris automated the captions.
My error was not due to any changes - I just can't run SS any more...

**Comment by cgrandin** [comment]
I'm guessing this was opened again so that we could ask JMC in July about whether or not to keep the levels we have or use new ones? The technical aspects of code are all done and working.

**Comment by andrew-edwards** [comment]
Yes. They should be able to specify then what they want, so we don't have to re-run in the meeting (which then caused me further problems). Though I think now we have an idea of what people will want - just make sure there's not a big gap of, say, 200,000 t between the useful values.

**Comment by andrew-edwards** [comment]
So last year we originally (submitted version) had a big gap between 410,000 and 587,000 for 2019 catch. So in the meeting we added the intermediate 500,000. This year the coverage is fine.
