### ISSUE TITLE
Separate out tribal catch in our US catch tables

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#584]
Consider separating out tribal catch in US catch table (2019 assessment table 1) just so we can be explicit what has been used and not buried in other sector totals.

**Comment by aaronmberger-nwfsc** [comment]
Thanks to Kelli, I believe this is done.  Though I will the satisfaction of closing this issue to her....

**Comment by kellijohnson-NOAA** [comment]
YES! And, the number was dynamically added to the document in a2681c3154a042723903dce0716d5edc8b8e949d
