### ISSUE TITLE
retrospective analysis of age comp forecasting

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#585]
Request in March JMC meeting by AP - we should consider this as a maybe a standalone analysis to be presented at the 2020 JMC meeting.

Request:
To the extent Figure 45 is intended to be used as a tool in forecasting age compositions in the Fishery catch in future years, the AP requests further information about the selectivity and other assumptions used in the model and a comparison over time of the forecasted and the actual harvest.

**Comment by cgrandin** [comment]
They said they feel this was very informative to them and would like to use it in the future for their TAC deliberations. So, yes we need to do more on this for 2020.

**Comment by cgrandin** [comment]
Include retrospective analysis - i.e. compare past forecast age comps with actual comps. I'm writing this during the JMC meeting.

**Comment by cgrandin** [comment]
See issue #454 which is about empirical squid plots

**Comment by andrew-edwards** [comment]
Agreed to leave until it's clearer what is requested, or an oceanographic model that might be more informative.
