### ISSUE TITLE
Use 3.30.13.00 SS

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#586]
Parameter deviations are modelled differently in this version of SS, which will be influential in selectivity estimates. Though, this version is not officially released yet. More info to come.

**Comment by andrew-edwards** [comment]
JTC call - Kelli suggested 3.30.14 . Tick a box when you have it:

- [ ] Kelli
- [ ] Aaron
- [ ] Chris
- [ ] Andy

**Comment by kellijohnson-NOAA** [comment]
3.30.14.08 is available in the google drive, though I changed the extension or [here](https://vlab.ncep.noaa.gov/web/stock-synthesis/document-library/-/document_library/0LmuycloZeIt/view_file/7170426?_com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_0LmuycloZeIt_redirect=https%3A%2F%2Fvlab.ncep.noaa.gov%3A443%2Fweb%2Fstock-synthesis%2Fdocument-library%2F-%2Fdocument_library%2F0LmuycloZeIt%2Fview%2F6427430%3F_com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_0LmuycloZeIt_redirect%3Dhttps%253A%252F%252Fvlab.ncep.noaa.gov%253A443%252Fweb%252Fstock-synthesis%252Fdocument-library%252F-%252Fdocument_library%252F0LmuycloZeIt%252Fview%252F5042555%253F_com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_0LmuycloZeIt_redirect%253Dhttps%25253A%25252F%25252Fvlab.ncep.noaa.gov%25253A443%25252Fweb%25252Fstock-synthesis%25252Fdocument-library%25253Fp_p_id%25253Dcom_liferay_document_library_web_portlet_DLPortlet_INSTANCE_0LmuycloZeIt%252526p_p_lifecycle%25253D0%252526p_p_state%25253Dnormal%252526p_p_mode%25253Dview). Currently, there is only a build for Windows. Let me know if you need a different version.

**Comment by aaronmberger-nwfsc** [comment]
I did a test earlier today comparing the SS version we did last year and this version and got the same results for SSB and stock status.  I have yet to look at all the results.  At any rate, this conversion will be part of the bridging analysis.  There was one minor change I had to make in the control file (new version wanted one less line, that being the second to last line, so I commented it out).  I.e., 

# -1 # vector with growth std bin picks (-1 in first bin to self-generate)

**Comment by andrew-edwards** [comment]
`ss.version` in R correctly says that we're using 3.30.14.08 for the base model. Since it gets copied into the other model directories, we're good and so I'm closing.
