### ISSUE TITLE
I got everything working for last year's models.

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#593]
Read the README, I made a few changes for this year.

I had to run the forecasts again to get it to work, I presume we were doing something fancy at the end last year and I forgot what so I just ran forecasts for everything again like this:

```
delete.rdata.files()
build(fore = TRUE)
```

I suppose this is as good a place as any to discuss problems we might have getting it going

**Comment by andrew-edwards** [comment]
Closing this - I never tried running last year's again. Onto 2020!
