### ISSUE TITLE
Why were the Canadian catch values off in last year's assessement for 2007-2011?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#594]
:sob:

It appears that last year I changed the format of the data files for catch and inadvertently forgot to include one for the JV fishery, presumably because there hasn't been one for awhile. I'm talking about the files *data/can-ft-catch-by-month.csv* and *data/can-ss-catch-by-month.csv*.

Thanks @kellijohnson-NOAA for noticing this.

I'll close this once fixed.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin can you upload the new files today?

**Comment by cgrandin** [comment]
Yes, I will. I'll let you know when I commit them to the repo

**Comment by cgrandin** [comment]
I added all the Canadian catch in commit aefbab232139239a72cdeb8b0204578bcdb723e3. There is no 2019 JV catch so it doesn't appear in the file. The file format is better also

**Comment by kellijohnson-NOAA** [comment]
does anyone mind if i remove the landings file from the repo and commit that change?

**Comment by aaronmberger-nwfsc** [comment]
landings-tac-history one?

**Comment by kellijohnson-NOAA** [comment]
No, 'Landings_by_year_Canada.csv'

**Comment by aaronmberger-nwfsc** [comment]
seems like we are covered without it - ok
