### ISSUE TITLE
Compare cohort calculations to last year's due to bug fixed in c4b9efe51

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#597]
Write some text in document if necessary.

**Comment by andrew-edwards** [comment]
Numbers (just before Data and Assessment) are a bit higher than last year, which makes sense with extra year of catch and increase biomass estimate. The cohort table (I finalised caption) didn't use the calcs from c4b9efe51 anyway, so all good. 
But I do get a warning still:
```
Warning message:
In waa[[i]] * naa[[i]] :
  longer object length is not a multiple of shorter object length
```
which I think may come from the table function, so will look into that.

**Comment by andrew-edwards** [comment]
That function is nasty (very long) - will leave it for now. I expect it's all good, though a bit worried by the warning, since that's what I got a few weeks ago leading to the fix mentioned in the issue title.

**Comment by cgrandin** [comment]
I'll take a look

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards you can do 
```options(error=recover, warn=2)```
and it give you a selection of places you want to enter your code regarding the error. I often do that when I want to investigate something.

**Comment by andrew-edwards** [comment]
Thanks Kelli - didn't know about that. Useful for investigating warnings, and it may have arisen when I deleted my full knitr-cache. Luckily Chris said he'd take a look ;)

**Comment by cgrandin** [comment]
The table numbers were correct, I removed the warnings.
