### ISSUE TITLE
All need to install rnaturalearthhires package

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#598]
```
devtools::install_github("ropensci/rnaturalearthhires")
```
Tick when done:
- [x] Chris
- [x] Kelli
- [x] Aaron
- [x] Andy

It's for the new map in Figure 1.

**Comment by kellijohnson-NOAA** [comment]
I added a DESCRIPTION file to the repo (af556d537535085a92fb91a5ea484f041e8fbdf7) so we can keep track of what packages are necessary. The list is far from complete, but I did add this new package.
