### ISSUE TITLE
Need to re-run adnuts with forecasting turned on

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#599]
I get the following when I try to run forecasting on the adnuts run:

 Error in SS_output(dir = model_path, verbose = FALSE, printstats = printstats,  : 
  Forecast-report.sso file is empty.
Change input to 'forecast=FALSE' or rerun model with forecast turned on. 

I'm not exactly sure why but I think it means that forecasting must be turned on when the MCMC was run.

**Comment by cgrandin** [comment]
I got a similar issue with 2019.03.92_simpledevs.
It has an MCMC folder which breaks the code because I don't think it was run the same way. Any ideas?

**Comment by aaronmberger-nwfsc** [comment]
We don't need to worry about the adnuts run or the simpledevs mcmc folder I don't think.  I don't think we are going to be 'reporting' mcmc from the simpledevs run in the document so I just would not include that folder in the document build.  For adnuts, I was thinking of just making some figures and adding them into this years assessment document via eps (or similar) images.  There are a host of things that would need to change to make the adnuts workflow 'work' with existing ss stuff, such as r4ss, etc.
