### ISSUE TITLE
Next immediate steps (today/tomorrow)

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#601]
- [x] finish fixing table (Andy, #460 ) 
- [x] check document still builds with no errors (for 2020_00_08 base model, Andy)
- [x] Chris - check document builds with 2020.01.09_DMprior_base base model
- [x] Andy - check document builds with 2020.01.09_DMprior_base base model
- [x] Kelli - check document builds with 2020.01.09_DMprior_base base model
- [x] Aaron - check document builds with 2020.01.09_DMprior_base base model
- [x] flag text to be changed (Andy)
please edit and add any more - these are steps to get us all building, Aaron and Kelli are looking at other stuff until we can all build

**Comment by aaronmberger-nwfsc** [comment]
I can get the document to build using the within R studio CompilePDF button.  However, things are a bit funky that attribute to not latex several times (like we have had to in the past; e.g., table of contents not formatted correctly or non-existent).  All other option fail for me currently so trying to figure out why.

**Comment by cgrandin** [comment]
What about the buildtex.bat way?

**Comment by aaronmberger-nwfsc** [comment]
I'll try again, but in the past I've had issues because I can't put stuff on my path (no admin rights).

**Comment by cgrandin** [comment]
If you have tinytex installed, you can supposedly do this:
```
build_pdf <- function(){
  knitr::knit("hake-assessment.Rnw")
  tinytex::latexmk("hake-assessment.tex")
}
build_pdf()
```

**Comment by aaronmberger-nwfsc** [comment]
For whatever reason, I stepped through each individual step (no batch files) and it worked.  Now shortcut batch files work too.  Not exactly sure what happened but I think I'm good.  Doing one last double check test on document build, but checking my 'build' box above for now.

**Comment by andrew-edwards** [comment]
One curious quirk I had the other day was that
```
library(knitr)
knit("hake-assessment.Rnw")
```
worked fine, but just trying
```
knitr::knit("hake-assessment.Rnw")
```
doesn't (it ignored some option and tried to build a .pdf in one go I think). I made a note on the README. Just mentioning it in case it helps.

**Comment by cgrandin** [comment]
That makes no sense.. they are the same!

**Comment by cgrandin** [comment]
@kellijohnson-NOAA Can we close this? You have the model running right

**Comment by kellijohnson-NOAA** [comment]
yep! Just ticked the box.
