### ISSUE TITLE
Finishing fixing NA's in Tables i,j (and revert the figure-related commit)

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#603]
Document builds okay, I just need to fix a couple of things with these. Haven't checked all figures (see that the survey one is missing anything useful, will look into it).

**Comment by andrew-edwards** [comment]
I'm just doing
```
> build(.run_forecasts = TRUE,
            .model_list = "2020.01.09_DMprior_base")
```
which I think will be enough for me (as I previously did the full `build(T, T, ...)` before Chris did the fix). 
This can then be closed if
- [ ] Kelli
- [ ] Aaron
don't have the NA's in Table j (i.e. the did the full build after this commit).

**Comment by aaronmberger-nwfsc** [comment]
looks good - closing
