### ISSUE TITLE
Need missing number of survey hauls with samples

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#611]
Table 13, I added the dates of the survey and biomass estimate but we need the number of hauls with samples. Right now it is a dash -

**Comment by aaronmberger-nwfsc** [comment]
I added the values and updated CV values that were slightly off from previous years (according to survey team and double verified this year) - apparently the very small change in CVs were due to a reanalysis that never got communicated or was lost in communication.
