### ISSUE TITLE
Remove blank page between tables 24 and 25

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#612]

**Comment by andrew-edwards** [comment]
Yes, there's a few here and there. Can be fixed once everything is in there. (Also some fiddling of the exec summary, but has to wait until the text is finalised).

**Comment by andrew-edwards** [comment]
"I'll just knock this one off before leaving for the night....". Sounded so easy, turns out to not be. Will come back to it at some point if I don't succeed.

**Comment by andrew-edwards** [comment]
The exec-summary ones will get done once we finalise the text (since tables/figures can move around in that).
