### ISSUE TITLE
MCMC sensitivity appendices template

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#618]
Use `appendices-fecundity/appendix-fecundity-53.rnw` as a template for doing MCMC appendix. It's currently commented out in `hake-assessment.rnw`.

**Comment by andrew-edwards** [comment]
I presume we're doing these two as full MCMC sensitivities in two separate appendices (like last year)
- [ ] 2020.01.23_age1Survey
- [ ] 2020.01.33_eqFecund_early10

If so can set them up.

**Comment by aaronmberger-nwfsc** [comment]
Yes, thanks Andy!

**Comment by andrew-edwards** [comment]
Done them both (by commit `d26a1b8`). If you don't have the full MCMC .RData files yet, but still want to build the document, then
```
git checkout 77acffd
```
will get you to the commit before I made the appendices.
I haven't done any text in main document for these yet, but the figures and tables all build.
