### ISSUE TITLE
Everyone to download updated survey maps from Google Drive

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#623]
The maps are referenced as of commit 9593f67 (so commits after that won't work until you download them).

In Google Drive, go to Hake JTC2020/document/eps images/  and download the four files I put there this morning:
`age1hake_03_19.....` , both `.eps` and `.pdf`
`hake_survey_03-19....` both `.eps` and `.pdf` 

Julia made the .pdf files, and I converted them to .eps for the document (the .pdf don't get used in our document, but you may want them anyway).
Click when done:
- [x] Andy
- [x] Kelli
- [x] Chris
- [x] Aaron

**Comment by andrew-edwards** [comment]
GitHub being too clever - thought I'd resolved it based on my commit message!

**Comment by cgrandin** [comment]
I think you closed this by accident...

**Comment by cgrandin** [comment]
Interesting, the word "resolve #XXX" closes issues automatically.

**Comment by andrew-edwards** [comment]
Yep. I know "closes" and "fixes" do (very handy, saves manually closing it), I was just using "resolve" in a different context.

**Comment by aaronmberger-nwfsc** [comment]
presumably Andy has these as he created them.  If so, this can be closed now.

**Comment by andrew-edwards** [comment]
Julia just sent me an updated map (closer to the old color scheme). But not the age-1 map. Just reopening this to try the new one at some point - if I have to mess around with the formatting again (margins etc.) I may not bother.

**Comment by andrew-edwards** [comment]
Okay, you need to update the two new .eps files from the Google Drive, that I just uploaded:
`hake_survey_1995-19_NASCTimeSeries_BiomassAtAgeHistograms_grayblue.eps`
`age1hake_03-19_sA_squareroot_bin_narrow-panel_bluergray.eps`
I'll commit the knitr change, tick box when you have it:
- [ ] Chris
- [ ] Kelli
- [ ] Aaron

Sorry. Be easier in the future if we can just build the figures - they sound really fiddly in ArcGIS.
