### ISSUE TITLE
Fill in Fisheries by country sections in the Introduction

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#624]
- [x] Canada (Chris)
- [x] US (Kelli)

Last person to complete close issue

**Comment by cgrandin** [comment]
We may have to wait to receive the AP reports to complete these sections

**Comment by kellijohnson-NOAA** [comment]
@cgrandin should we close this without the CAN AP fishery report? I did the US with 4eb168e8c7cb945813

**Comment by cgrandin** [comment]
I got the Canadian fishery report in there in 418c3b2f so I'm closing it up.
