### ISSUE TITLE
Make Table a just go back 10 years?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#625]
The text says "Over the last 10 years, ... (Table a), ..."
but Table a goes back to 2006. In 2016 assessment (first year of knitr approach) we had 2006-2015.

Presumably best to always make it just the last 10 years, yes? Seems like that was the intention in 2016, but the 2006 start year got hardwired and so now the table is getting a bit long.

Easy to fix, just give a thumbs up or down ....

Tables 6-10 are for last 10 years. Maybe I should have just changed it rather than make an issue! Only downside may be it might move some text around, but I always fix that at the end.

**Comment by andrew-edwards** [comment]
Decided to just do it - seems sensible and not controversial.

**Comment by cgrandin** [comment]
Agree that makes sense
