### ISSUE TITLE
ADNUTS appendix

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#626]
I will begin to set this up. It will replace the Fecundity appendix we had from last year.
See #588

**Comment by andrew-edwards** [comment]
Should be easy to get some results shown - just use the one I left in as a template. We'd need more stuff but that will be a start....

**Comment by cgrandin** [comment]
Some good news here.. It looks like the forecasting code works for this. So we will have decision tables, etc in the appendix. I'm still working on it but looks like not much work

**Comment by cgrandin** [comment]
This is all working so I’ll close it.
