### ISSUE TITLE
Address SRG requests in text

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#627]
Andy to create this section initially, we can go over it together later

**Comment by kellijohnson-NOAA** [comment]
- [ ] 1. R_0
- [ ] 2. tv selectivity (KFJ)
- [ ] 3. maturity
- [x] 4. sample size (KFJ)
- [ ] 5. adnuts (AB)
- [ ] 6. PacFIN

**Comment by cgrandin** [comment]
@kellijohnson-NOAA I added more to the sample size text in 72bb69b9da47ac05b929b8a1c054d811024271d5. Just a heads-up to you as you've been working on the sample size stuff.

**Comment by aaronmberger-nwfsc** [comment]
Update on genetics/maturity coming tomorrow so almost done here...

**Comment by aaronmberger-nwfsc** [comment]
I think we are done here, barring any minor edits, but closing now.
