### ISSUE TITLE
Need a reference for parameter correlations in the Selectivity Sensitivity

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#632]
I left some text in there with double stars about where the numbers come from. I'd like to know how this was determined and possibly make a table outlining this

**Comment by andrew-edwards** [comment]
Check for repetition from earlier section. Take out anything no longer needed (just reference earlier assessment).

**Comment by aaronmberger-nwfsc** [comment]
I updated text referring  to these correlations.  We could eventually auto populate this using the ss.cor file for models of concern, but I don't think this is something we need to continually produce.  We probably will not to continue reporting this as it is a straightforward fact of that approach.

I'll let Andy close this as he was going to check on some remaining things.

**Comment by andrew-edwards** [comment]
I'm sure it's fine....
