### ISSUE TITLE
Add appendix for fecundity mcmc run

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#633]
Following the appendix structure for the age-1 survey, I would like to add one for model run 2020.01.33_eqFecund_early10.  I am adding some text in the model uncertainty assessment section (3.6) regarding these alternative structural models (age-1 survey and eqFecund) and will also reference the adnuts stuff.

I also need to add in one or two comparison plots for the adnuts stuff.

**Comment by cgrandin** [comment]
I thought we agreed to remove the fecundity appendix and the two fecundity sensitivities from the document on the phone yesterday? I spent a couple of hours going through and doing that. I won't push the changes until I hear back.

**Comment by andrew-edwards** [comment]
It was assigned to me #496. So check there (feel free to carry on - all I did so far I think was comment out the appendix to make it build a little quicker, though it still has to load in those results so only a quick fix).

**Comment by andrew-edwards** [comment]
So work off #496. I think we didn't close this current issue on the phone call this as Aaron wanted to think about something? If not then Aaron should close it.

**Comment by cgrandin** [comment]
OK,  thanks. We did agree that I would do this yesterday on the phone so we need to be more vigilant in issue assignments while on the phone perhaps.. Thanks Andy

**Comment by andrew-edwards** [comment]
Re-assigned!
