### ISSUE TITLE
Add DM plot to prior/posterior plots (Figure 21)

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#639]

**Comment by cgrandin** [comment]
On commit 4eb8e4e74595a1ace11cc4c83c030a885d5e7fff I added these. I don't like how the fishery DM parameter looks. The histogram has 50 breaks and 1833 samples are in one bin and 167 in the one beside it. If I increase the breaks to 500 there are only 14 bins with values. Is this acceptable? I'll leave open until you all have a look.

**Comment by andrew-edwards** [comment]
So the x-axis is determined by the prior presumably. Looks like Uniform (-5, 20), but that's what we used last year. Is the new one close enough to that (I wrote related text a few commits ago)? It just looks uniform to me in the new figure.

**Comment by cgrandin** [comment]
The prior is now Normal but there is still an ugly 2-bin histogram. I will close this as "it is what it is"

**Comment by andrew-edwards** [comment]
Yes, looks good now. Can make more bins if anyone wants them in the meeting...
