### ISSUE TITLE
Comparison of pdf's - maybe fix spacing issue

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#641]
Comparing uploaded .pdf's from commit dbf1b73a45ea . 
Compared to Andy's, all Chris's figures, numbers and tables are identical. Some minor differences, Chris's:
1. has less whitespace after one-page summary and other headings. It does mean:
  a.  that some text in Exec Summary ends up in different places (because some tables and figures have to be manually fixed in place for readability)
  b. Table of Contents differs because sections end up on different pages (no big deal, but explains why we were two pages off for some sections in the phone call)
  c. some long tables get split differently - no big deal
2. % symbol comes out differently, kind of cursive-like (!) - no big deal
3.  Table I.5 ADNUTS catch alternative i has slightly different catch values (+12, -3, -3 t, compared to Andy's), percentages are all the same. No big deal - think he just had a different tolerance when running it.

1a is the only important one. Mine matches last year's format (I haven't changed latex installation or anything), so may be best to use for final submission. I'll look into trying to fix it, but may be a rabbit hole. 

Kelli's matches Chris's (regarding the spacing). Her I.5 numbers (point 3 above) are identical to Andy's. Some figures have some strange extra spacing between numbers - e.g. numbers in heatmaps (Fig 13), Fig 22, 23 years axis, Fig C.1 has weird 0.4 and 0.1 twice?! Just some font issue but no big deal.

So, good news is that we have the same identical results. Amazing (though shouldn't be) that the document builds like that on the separate computers.

Just waiting Aaron's upload ;)

**Comment by aaronmberger-nwfsc** [comment]
Okay, I uploaded mine, but there will be a few minor differences as I had to do some things while waiting for my adnuts run to fully build again.

**Comment by andrew-edwards** [comment]
Aaron's matches Kelli's, with a few minor expected differences.

So this confirms we are all using the same model runs. Excellent.

I'll try and fix the spacing issue if time (but tricky to test). It might be best to use mine for submission as the formatting is exactly the same as the final version last year (by Aaron), so can easily flick between documents to compare figures and tables in exec-summary.

**Comment by aaronmberger-nwfsc** [comment]
that sounds good to me Andy - I get twitchy anyway when building/running that final submission run anyway (though I know we do a final compare to safeguard)...

**Comment by andrew-edwards** [comment]
Will maybe try this after we submit.

**Comment by andrew-edwards** [comment]
It's to do with hake.sty. Check csasdown to see if Chris and I have differences there also.

**Comment by aaronmberger-nwfsc** [comment]
Why do we have this still open?

**Comment by aaronmberger-nwfsc** [comment]
closing because reference in this years pdf check issue

**Comment by andrew-edwards** [comment]
I'll look at fixing the spacing issue. May be due to: https://stackoverflow.com/questions/27592837/r-knitr-chunk-options-for-figure-height-width-are-not-working

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards this would be a great thing to tackle right now rather than in January.

**Comment by andrew-edwards** [comment]
Thanks for the nudge Kelli. Yes, too late last year to look into.

Notes mainly for me: So my current build matches what we submitted up to 2020 (think we submitted my version then). But 2021 assessment has less spacing, as described above. I updated Pandoc as one search suggested that might be it, but no luck. Think it's to do with me not using RStudio (though nor does Kelli I think).

Playing around with some `\renewcommand{\section}` etc. settings in hake.sty. Somehow those setting are getting overwritten (since 2019/2020).

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards have you looked at the build from aws to see if this issue still exists?

**Comment by andrew-edwards** [comment]
Will do once it's done. I expect the issue will only exist on my machine, which is okay.

**Comment by andrew-edwards** [comment]
Closing since won't fix it this year. Think it's a tinytex vs miktex thing (tinytex ignoring some settings in our style file - some are a bit of a hangover from the CSAS style file we created for DFO documents because they were picky on spacing between section headings and text, and other such nonsense). Can maybe try again early in next year's cycle.

**Comment by andrew-edwards** [comment]
I'll look into this before we do any model runs. I may just have to reinstall Latex, which I'm a bit wary but it's worth fixing.

**Comment by kellijohnson-NOAA** [comment]
I vote that we close this issue and just worry about the pdf that is coming off of the server. And, we will all need to reinstall LaTeX eventually anyway because of the new tagging features.
