### ISSUE TITLE
need to download 2 updated eps files for adnuts appendix

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#642]
These are:
1. SummaryDiagnostics_nuts
2. MCMC_compares_StockStatus

and can be found on the google drive

https://drive.google.com/open?id=1HyU2u4ayA2F2MQbFsW6H7uBobPnZIkaG

These go in the doc/main-figures folder...

**Comment by andrew-edwards** [comment]
I got them but they're 9Mb and 6Mb. Can't see why so big (since not trace plots or anything). Did you save them just with `postscript()` (I think) in R?

**Comment by aaronmberger-nwfsc** [comment]
Gimp...

**Comment by andrew-edwards** [comment]
I figured that out. I can try a different conversion if necessary (what's the original format?). Remaking in R would prob be better.

**Comment by aaronmberger-nwfsc** [comment]
original came from R (postscript, pdf, whatever - I have them all) - I'm not too worried about the size.  I imported pdf to gimp to make postscript as it was better than straight out of R (but maybe I don't have settings/flags right).

**Comment by andrew-edwards** [comment]
My usual command is:
```
postscript("nSeaFungMLEbinsNew.eps", 
            height = 6, width = 7.5,
            horizontal=FALSE,  paper="special")
```
The `special` makes it .eps I think, which we need. Or were you saving from an R window - that can generate big files. Postscript shouldn't be very big with these types of plots. 
An extra 15Mb is a lot, given whole document is 56Mb (pdf is 14Mb)!

**Comment by aaronmberger-nwfsc** [comment]
oh right, I was thinking Kb, yes that is large - I didn't even notice. I will work to decrease those tomorrow.

**Comment by andrew-edwards** [comment]
Can't we just make them in the document? The autocorrelation etc. one is a simple function to give Figure A.3. Though I seem to remember it might be trickier due to the NUTS??

**Comment by aaronmberger-nwfsc** [comment]
perhaps, but these are one offs for this year only, likely

**Comment by andrew-edwards** [comment]
```
make.mcmc.diag.hists.plot(sens.models.6)
```
works, but the figure looks quite different to yours. (I'm probably just guessing at what your plot shows).

**Comment by cgrandin** [comment]
If we've all done this it can be closed.. I have them

**Comment by aaronmberger-nwfsc** [comment]
I think Andy wanted me to make smaller versions which I can do shortly

**Comment by aaronmberger-nwfsc** [comment]
There are two smaller versions of these files now on the google drive if you wish to have smaller ones.  Files are:
MCMC_compares_StockStatus.eps
SummaryDiagnostics_nuts.eps

I'll leave it up to you to decide if you want to copy them over.  Same thing, just smaller size.

**Comment by andrew-edwards** [comment]
We should all get them - way smaller. I'll reopen to make sure Kelli and Chris download them.

**Comment by cgrandin** [comment]
I have them now

**Comment by andrew-edwards** [comment]
Assuming Kelli's thumbs up meant she has it.... closing
