### ISSUE TITLE
forecast probability plots need small fix

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#646]
executive summary figure k and similarly figure 38 (forecast probability plots for 2021) need what looks like an x-axis (catch level) fix.  It appears as though the same figure for 2020 works so maybe code just needs to be updated for 2021

**Comment by andrew-edwards** [comment]
No - see the text I wrote at the end of "These metrics...." paragraph. Hopefully that explains it.

**Comment by aaronmberger-nwfsc** [comment]
yep, forgot about that - thanks
