### ISSUE TITLE
Working on today? - the Thursday before D-day (D for delivery)

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#650]
Here is my plan:
1. finish first pass through 'remainder' (4+) section of R and D
2. finish remaining response to SRGs
3. Have a look at sensitivity section (I haven't read that section yet)

Hopefully this doesn't take much past noon.  Then I can see where everyone is at and then maybe look more closely at all the figures.

**Comment by cgrandin** [comment]
I am going through and double-checking the assessment section text right now and automating a bunch of hard-coded values. I will also look at data.rnw and close #496 once I've checked that over.

**Comment by andrew-edwards** [comment]
I'm still going through the assessment section, specifically still 3.5.2 Assessment model results (taking a while).

**Comment by kellijohnson-NOAA** [comment]
is there a particular section or something that i should focus on next?

**Comment by andrew-edwards** [comment]
I'm onto 3.5 Model Uncertainty section. Taking a while but am going through quite carefully.

**Comment by andrew-edwards** [comment]
To answer Kelli - #651  ;)

**Comment by andrew-edwards** [comment]
The ADNUTS code comes out pretty - I'm just going to format it a little to make it more readable (a mindless task before leaving, emacs will take care of most of it). I'll be back it some time after 8pm (after yoga!), I'll be going through 3.7 Model Projections.

**Comment by andrew-edwards** [comment]
Just doing #647 also - Chris, we can cite the IFMP yes, just not distribute it? Else can call it 'unpublished'.

**Comment by cgrandin** [comment]
Yes, I think so. By the time we go to the SRG it will be published anyway

**Comment by andrew-edwards** [comment]
Am done for tonight. Tomorrow will do final two paragraphs before 3.8 Sensitivity Analyses (DFO one needs changing for sure as I changed the earlier ref point text).  Yes, that's kind of a note-to-self!

**Comment by cgrandin** [comment]
Would anyone mind if I clean up the adnuts code that's displayed?
