### ISSUE TITLE
weight-at-age figure colours don't match

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#651]
colours in weight-at-age don't match colours in sample size of weight-at-age, it is because the sample size figure was made with hakedataUSA:: and the plot of the actual data was made with code that was created last year and available in hake-assessment. I will get them to match.

**Comment by cgrandin** [comment]
I think the weight-at-age one (not # of samples) has been looked at more and for a longer time period (people are used to seeing it in that coloration) so it may be best to use that one as the basis for the other.

**Comment by cgrandin** [comment]
Thanks @kellijohnson-NOAA. The changes break the build though, here:

```
weight_age_extrapolation_mask <- read.csv(
  file.path(rootd.data, "wtatage_all_samplesize.csv"),
  header = TRUE)

```
in model-setup.R

**Comment by andrew-edwards** [comment]
I think `wtatage_all_samplesize.csv` needs to be in `data\`?

**Comment by andrew-edwards** [comment]
And I'm now getting an error:
```
Error in eval(parse_only(code), envir = envir) : 
  object 'last.year.landings' not found
```
even though it's in my custom-knitr-variables. But I think that's not the problem, it's related to not having the .csv file so something breaks beforehand, I think. I'll use my previous knitr-cache for now....

**Comment by andrew-edwards** [comment]
I was wondering where the 1,0,0,0,... 'masking' matrix went - looking at your helpful commit message to de6c0ec  I think it's in the .csv file. So adding that should be good ;)

**Comment by cgrandin** [comment]
> And I'm now getting an error:
> 
> ```
> Error in eval(parse_only(code), envir = envir) : 
>   object 'last.year.landings' not found
> ```
> 
> even though it's in my custom-knitr-variables. But I think that's not the problem, it's related to not having the .csv file so something breaks beforehand, I think. I'll use my previous knitr-cache for now....

This is due to the error with the missing file.. the code never gets to custom-knitr-variables.R and therefore knows about none of those variables. That just happens to be the first one used in the doc.

**Comment by andrew-edwards** [comment]
Yep, that's what I thought. Got that the other day with an unrelated error......

**Comment by andrew-edwards** [comment]
@kellijohnson-NOAA So I did 
```
git revert de6c0ecf
```
to revert that one commit (thanks for the detailed commit message!). I can build now. 
I'll want to push at some point so others can build (and I think you're offline), so presumably then you should rebase and then revert my revert, which will be
```
git revert c3cccdcf
```
Then do what you need to. I think that should work....

**Comment by kellijohnson-NOAA** [comment]
sorry, i was at my in-laws... I can push the weight at age file with the changes in a few. sorry i broke everything!

**Comment by andrew-edwards** [comment]
No worries. I can do the revert before pushing then. Hopefully that's all you have to do (I think it is - does it contain the masking 1,0,0,1,1,0 stuff also?).

**Comment by kellijohnson-NOAA** [comment]
774fa3b should fix it

**Comment by andrew-edwards** [comment]
I see - that's sounds better. I've reverted my revert, rebased and just rebuilding....

**Comment by cgrandin** [comment]
Love the optimization and happy to see the mask matrix go

**Comment by andrew-edwards** [comment]
Yes - it works. Figures look the same now, which is great. And I like all the 0 sample sizes on the second figure for the early and late years  - kind of emphasises it all. Thanks for doing (and fixing) - I'll push now. Rebase worked fine....

**Comment by kellijohnson-NOAA** [comment]
Thank you for letting me know that it works.
