### ISSUE TITLE
Figure 39 - differences between panels don't seem as great as weight-at-age color plot would imply

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#655]
I just edited some text about projected catch in numbers vs weight (median values):

![image](https://user-images.githubusercontent.com/6977190/74006370-5619a300-4930-11ea-8547-6eb5a7e222fd.png)
 
However, the color heat map says age-10 fish (for projections) is 1.5x as heavy as age-3. So wouldn't you expect these numbers to change more? And the two panels on Figure 39 to look more different. Maybe I'm just missing something (it's late!)?

**Comment by aaronmberger-nwfsc** [comment]
We should add the assumption about wt-at-age in the caption since we call out selectivity assumption, right?  Maybe like:
These estimates are based on the posterior distribution for selectivity averaged across the most recent five years, weight-at-age data averaged across the most recent five years, and the distribution for expected numbers at age at the start of 2020...

**Comment by andrew-edwards** [comment]
Doesn't the caption already say that? (Or am I looking at a newer version). Hmm...... (think I'm just missing something).

**Comment by aaronmberger-nwfsc** [comment]
Mine doesn't have the recent five year data part, i.e.,  '..., weight-at-age data averaged across the most recent five years, ....'
But maybe this has been updated since my last doc build.

**Comment by aaronmberger-nwfsc** [comment]
One thumbs up will signify agree with this addition and then I can quickly add that text in, just wanted to make sure others are okay with it.

**Comment by aaronmberger-nwfsc** [comment]
And Andy I get your point about 'age-10 fish (for projections) is 1.5x as heavy as age-3'.  It might be a bit hard to fully understand just from the figure and that increase in weight b/c these are proportions (sum to 1) so consider relative changes in weight across all ages (if that makes sense?)

**Comment by andrew-edwards** [comment]
We're talking about 'Forecast age compositions in numbers and in weight....' current Figure 39 yes? (Sorry, I should have been more explicit in Issue title as fig numbers can change).

**Comment by andrew-edwards** [comment]
Actually, I think it is fine. Looking at my first comment again properly. Think I was just tired....
The ratio of 2017 to 2010 by numbers is 13/12 =~ 1. Ratio by weight is 11/16 = ~069, which is indeed the ratio of weights in the heat map. Sorry about all that.....
Aaron can close if he's happy with the caption. It's got all the info in there.
