### ISSUE TITLE
Address Owen's comments

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#657]
I can work on these today.

**Comment by andrew-edwards** [comment]
Anything major? Maybe share on Slack (we may have fixed some already through editing).

**Comment by aaronmberger-nwfsc** [comment]
Two major things:
1. addition of D-M prior influences results a lot so need more discussion why?  - this was a misunderstanding b/c our bridging model for D-M prior is right on top of the add 2019 survey comp data and the latter is what causes the difference, not the former. So we are good there. [AMB will still add some text to bridging to ensure this is apparent]
2. addition of non-zero centered rec dev does influence results more and so he wanted more explanation as to why we made that choice.  Fair enough.  Looking at the document we have some placeholders to still add text there, which I will work on next. [AMB will add some text here]
3. He thought the year label for 1999 was incorrect on figure h and 33. We should check 1999 and other.  I do note that he turned this around rather quickly for us so if we have details like in the caption they may have been overlooked, but let's still check. [any takers to check this?]
4. Regarding figure k (and 38) he writes: "Maybe consider using average catch in 2020 and 2021 on this axis, and then put in scenario letters rather than catch amounts as labels on the x-axis. The current plot, while I can figure it out by looking at the scenario tables, is not intuitive (as I am sure you are aware)." [any thoughts on this or takers to try his suggestion - the plot does look weird, but the caption explains it - but I doubt any stakeholder will understand]

Other things include wording edits and small additions I believe [AMB will do]

One question he had regarding DFO provisional reference points: "...at the start of 2021 the stock is expected to be above the cautious zone with a probability...."  is it 'cautious zone' or 'precautionary zone'? 

I'll put his marked up version on slack now.

**Comment by andrew-edwards** [comment]
Thanks. 1 and 2 are good, thanks.
3 - I fixed yesterday.
4 - It is a bit weird, but I think it best to keep the same format as people are used to. And we have some text explaining the drop (it also forces people to really understand it). Plus it'd be a fair bit of coding to make the changes. I'd vote for leave as is for now (he said "Maybe"!), and see what the SRG says.

DFO bit is correct (it's the 'precuationary approach).

**Comment by aaronmberger-nwfsc** [comment]
so for DFO sentence then change 'cautious' to 'precautionary', right?  I'll do that as I'm going through today.  committing with messages that say 'Owen edit - section name'.

**Comment by andrew-edwards** [comment]
His suggestions are generally good - he's a careful reader! I'm good with most of them, except maybe:
p35 - this is about acoustic survey, fishery values are presented later (I think they're there later - just might be confusing to mention them here, though I know what he means)
p41 - I've since expanded on that. Not sure what his question means though, since there isn't really a bound now with the normal priors.
Actually, that's it! Impressed with his comments (we already thank him explicitly in the Acknowledgments)

**Comment by aaronmberger-nwfsc** [comment]
Okay I finished 1 and 2 so closing this as everything else I think is addressed or ignored (for good reason)
