### ISSUE TITLE
Working on today (Friday Feb 7)

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#658]

**Comment by cgrandin** [comment]
I don't think there are any large tasks to do, so at this point I will proofread and do spelling checker on the various files. If anyone needs me for anything, let me know!

**Comment by andrew-edwards** [comment]
I'm going to do last two paragraphs before 3.8 Sensitivity Analyses. Then go over Exec Summary again, then come back to Sensitivity Analyses onwards (haven't looked at that, but I think people have gone over it pretty carefully - give a thumbs up if you have!).

**Comment by andrew-edwards** [comment]
I read through a paper copy of the Exec Summary - will type up some edits. All pretty minor I think.

**Comment by andrew-edwards** [comment]
I've just finished edits to Exec Summary - please say if you disagree with any. I'm now going to:
- [ ] edit one-page summary
- [ ] double-check a few things from others' recent commits
- [ ] add some references that Aaron sent me
Then next steps would be (yes, notes to myself!)
- [ ]  fix any more missing references/citations
- [ ] read SRG response
- [ ] read sensitivity section (haven't looked at yet)
- [ ] finish my other issues

**Comment by cgrandin** [comment]
Closing as this has passed. Andy can still view if he wants if it is closed
