### ISSUE TITLE
t.v. non-parametric selectivity added twice

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#659]
Looks like we have two equivalent models in t.v. sensitivity plot:

## -----------------------------------------------------------------------------
sens.model.dir.names.4 <- c("2020.01.27_tvSelect_phi_extralow",
                            "2020.01.28_tvSelect_phi_low",
                            "2020.01.29_tvSelect_phi_high",
                            "2020.01.26_semiPara_tvSelect_sig0.695",
                            "2020.01.26_semiPara_tvSelect_sig0.695")
sens.model.names.4 <- c("Phi t.v. selectivity (0.21)",
                        "Phi t.v. selectivity (0.70)",
                        "Phi t.v. selectivity (2.10)",
                        "Semi-Parametric t.v selectivity (0.695)",
                        "Semi-Parametric t.v. selectivity (1.0)")

We only compare 0.695.

**Comment by aaronmberger-nwfsc** [comment]
Chris and I made the decision to just quickly run this missing sensitivity (missing relative to last year).  So you will need to:
1.  download model 2020.01.37_semiPara_tvSelect_sig1.0 from the google drive
2.  run build(.model_list = "2020.01.37_semiPara_tvSelect_sig1.0")

I have changed the bit of text that describes this run in the sensitivity section.  I still have the correlation part to do (doing now), but that is another issue.

**Comment by cgrandin** [comment]
I did it. Worked perfectly first time.

**Comment by andrew-edwards** [comment]
Damn, I thought `build()` would just find the one missing the .Rdata file, as everything is FALSE. (This is sooo last week...). And I get an error:
```
Error in fetch_retrospectives(model$retropath, retrospective_yrs) : 
  object 'retros_list' not found
```
Ugh - and I can recover the .Rdata file from my recycle bin.

**Comment by cgrandin** [comment]
Just run build again with both models as a vector:
```
build(.model_list = c("2020.00.23_age1Survey", 2020.01.37_semiPara_tvSelect_sig1.0""))
```

**Comment by andrew-edwards** [comment]
Aha, my retros were only to 10 but now it thinks they're to 20. But we don't need them for appendix. Have deleted the retros folder and rebuilt the .RData file.

**Comment by andrew-edwards** [comment]
Ooh, I get to close. Realised I didn't finish the QAQC on sensitivity input files (did the base model ones a couple of weeks back). Mean to go back and do them once we had the new model. Figured we might spot any glaring issues, like this one!
