### ISSUE TITLE
adnuts results conflict

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#661]
Need to check on what the adnuts sensitivity plots are showing in Fig 54 and 55.  Is this MLE base model versus adnuts MCMC?  That seems odd to show.  If so, we should take these out of the main document and only show MCMC vs. MCMC comparisons in adnuts appendix. The reason I ask is in the adnuts appendix it shows the main difference between admb MCMC and adnuts MCMC is slight difference in stock status (rel spawn bio) trends, due to slight difference in estimated R_0. That in itself tells us that R_0 may not be fully mixed using admb MCMC (simply b/c adnuts has better diagnostics to ensure mixing).  Anyway, the difference shown in the appendix has adnuts trend HIGHER than admb (which is correct, I double checked).  Whereas in fig 54 and 55 it has it LOWER.  

Chris said he was going to look at adnuts results today anyway so I'll assign this to him.  I'm happy to do work on this too, just let me know.

**Comment by cgrandin** [comment]
The appendix says "age-1 survey index
is included as an index of recruitment as described in Sections 2.2.1 and 3.8 and Table 33."

Is this correct?

The sensitivity figures in the main document are indeed mcmc vs mcmc results
