### ISSUE TITLE
DM parameters not in MCMC pairs plots

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#662]
We can add these but the plots may get very hard to read.. We could also remove 2008 recruitment and perhaps one other value from the plot and then they would remain the same size. It's easiest code-wise to remove recruitment years (recr argument below).

So, if we add them, which should we remove, if any?

```
make.mcmc.diag.pairs.plot(base.model,
                          inc.key.params = TRUE,
                          recr = c(2008, 2010, 2014),
                          bratio = end.yr,
                          forecatch = end.yr)
```

**Comment by andrew-edwards** [comment]
Yes, suggest removing 2008 (as 2010 and 2014 are much bigger anyway). And what Kelli said in the other Issue....
