### ISSUE TITLE
Need to run this to update key posteriors for mcmc diagnostic plots

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#664]
**Necessary to build the document**
Run the following to re-make the files ```keyposteriors.csv``` and ```nuisanceposteriors.csv``` in the mcmc folders of the base and adnuts models. They are used by ```r4ss::mcmc.out()``` to make the posterior diagnostic plots and I've added the DM parameters in there.

```
rm(list = ls())
source(file.path(here::here(), "R/all.r"));load.models.into.parent.env();source(file.path(here::here(), "R/custom-knitr-variables.r"))
create.key.nuisance.posteriors.files(base.model, key.posteriors, key.posteriors.file, nuisance.posteriors.file)
create.key.nuisance.posteriors.files(sens.models.6, key.posteriors, key.posteriors.file, nuisance.posteriors.file)
```

**Comment by kellijohnson-NOAA** [comment]
Are we just putting these in for this year bc of the change in the prior? I dont think they are really key for every year.

**Comment by cgrandin** [comment]
Yes, that was the idea. So the SRG can see the traces of them if they want to, then we can remove again. It was the easiest way to add the plots this late in

**Comment by aaronmberger-nwfsc** [comment]
This is good - I had planned on showing them at the SRG via presentations, but good to have in assessment too.  Also plan to show adnuts shinystan app, where you can flip through these easily.  Do you think it worth to add that to adnuts code?  The launch command is already in there so it is just loading the saved file and then launching as in:

library(rstan)
library(shinystan)
setwd("C:\\Users\\Aaron.Berger\\Documents\\AMB\\Hake\\2019.2020\\Models\\2020.01.31_nutsMCMC")
load(file = "C:\\Users\\Aaron.Berger\\Documents\\AMB\\Hake\\2019.2020\\Models\\2020.01.31_nutsMCMC\\hake.RData")
launch_shinyadmb(nuts.updated)

**Comment by cgrandin** [comment]
I think the code in the appendix is good as-is. There is the launch_shinyadmb() command in there already which is enough for the people that are likely to use the code/understand it anyway.

**Comment by andrew-edwards** [comment]
Closing, assuming that Kelli's and Aaron's Thumbs-up at the top mean that they've run the code. (That's indeed a more efficient method than the checkboxes...)

**Comment by aaronmberger-nwfsc** [comment]
I noticed that my DM parameters were not in my keyposteriors file that we re-made per this issue.  I think it is fixed via commit 16815, but you likely will have to redo Chris' suggestion above (at least I had to).

**Comment by kellijohnson-NOAA** [comment]
For some reason, the column names do not match across the base model and the AD-Nuts model. That is, the former has ( and the latter has . which makes the key.posteriors not match the column names for AD-Nuts. I think that we need to change key.posteriors to use more of the functionality within grep, i.e.,
```
key.posteriors[5:6] <- c("ln.+EffN.+1", "ln.+EffN.+2")
```
but I don't know if this will break other things.

**Comment by cgrandin** [comment]
I will take a look at this today

**Comment by cgrandin** [comment]
Looking at the actual files.. If you ran the code above your keyposteriors.csv file will have been regenerated using our code and has the column names with parentheses. Here is what the first few lines of my adnuts keyposteriors.csv file looks like. Does yours look the same? The base model one and the adnuts one should be the same format like this once you've run the code above.

```
"NatM_p_1_Fem_GP_1","SR_LN(R0)","SR_BH_steep","Q_extraSD_Acoustic_Survey(2)","ln(EffN_mult)_1","ln(EffN_mult)_2"
0.238071,14.6843,0.626021,0.323789,-0.554361,1.84774
0.242955,14.8588,0.829455,0.222974,-0.544911,2.6709
0.248358,15.0228,0.792333,0.41464,-0.576372,2.33912
0.23015,14.6616,0.797337,0.389884,-0.568618,3.2155
```

**Comment by cgrandin** [comment]
I will also fix ```make.mcmc.diag.plot()``` today to use the actual ```key.posteriors``` definitions properly.

**Comment by andrew-edwards** [comment]
Chris, I don't have all the columns either:
```"NatM_p_1_Fem_GP_1","SR_LN(R0)","SR_BH_steep","Q_extraSD_Acoustic_Survey(2)"
0.238071,14.6843,0.626021,0.323789
0.242955,14.8588,0.829455,0.222974
0.248358,15.0228,0.792333,0.41464
```

**Comment by cgrandin** [comment]
Did you run the code at the beginning?

**Comment by aaronmberger-nwfsc** [comment]
That's what mine said too Andy until I added via commit 1681501.  Then after redoing Chris' code above it became:

NatM_p_1_Fem_GP_1 | SR_LN(R0) | SR_BH_steep | Q_extraSD_Acoustic_Survey(2) | ln(EffN_mult)_1 | ln(EffN_mult)_2
-- | -- | -- | -- | -- | --
0.238071 | 14.6843 | 0.626021 | 0.323789 | -0.55436 | 1.84774
0.242955 | 14.8588 | 0.829455 | 0.222974 | -0.54491 | 2.6709
0.248358 | 15.0228 | 0.792333 | 0.41464 | -0.57637 | 2.33912

**Comment by andrew-edwards** [comment]
I hadn't re-run after Aaron's commit. All good now, though I have an older version (31 Jan) in extra-mcmc/  . Presume I can delete that one, yes?

**Comment by cgrandin** [comment]
This code overwrites that one

**Comment by andrew-edwards** [comment]
You're fast!

**Comment by andrew-edwards** [comment]
My `extra-mcmc/*.csv` files aren't changing (don't they appear when doing the first `build()`?). Are they still needed (one is 37Mb!).

My `mcmc/*.csv` files are good and get updated each time I run those commands.

**Comment by cgrandin** [comment]
Yes that's right. The extra-mcmc posterior files aren't used.

**Comment by andrew-edwards** [comment]
Thanks. Expect they got built in an earlier iteration.... 
Leave this for Kelli to close when she's re-run those lines (she may have already...).
