### ISSUE TITLE
MCMC diagnostics in the age-1 appendix

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#666]
We could leave them out, but it's mostly a cut-and-paste-and-rename-chunks exercise if we have the time.

**Comment by andrew-edwards** [comment]
I would think probably okay to leave out? Or add a sentence mentioning that they look okay (presuming they do). 
Ooh - Issue #666 !

**Comment by cgrandin** [comment]
Going to leave them out. Closing it up
