### ISSUE TITLE
Remove the no extrapolation points from the survey plot

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#667]
It is Figure 10 now, we don't use these at all so can we remove them? @aaronmberger-nwfsc are you aware of any reason to keep them in?

**Comment by cgrandin** [comment]
Just revert the commit if you want to bring it back

**Comment by aaronmberger-nwfsc** [comment]
I think that if we discuss extrapolation at all, we should then show the affect of it.  But I see we removed it from the caption and legend, and also just say in the text that an extrapolation method was approved. I think we are good to remove it as it is 'standard practice' now.  So I agree with this commit.  Of course, if the survey team refines their extrapolation approach we should then add back in a comparison at that point.
