### ISSUE TITLE
Monday delivery day - who's doing what

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#671]
I have some edits for the SRG section. Is anyone working on that (I thought Kelli was)?

**Comment by aaronmberger-nwfsc** [comment]
I'm going to read data section (haven't done that fully) and look over adnuts appendix (haven't done that since additions)

**Comment by kellijohnson-NOAA** [comment]
I already put in my edits to the SRG section in assessment-section.rnw

**Comment by andrew-edwards** [comment]
Okay, I'll do my SRG ones (expect Kelli's done many of them!).

**Comment by andrew-edwards** [comment]
I'm going to fix the empty whitespace in the Exec Summary. Hopefully there's no more text to add - I think we've all had a good go at it....

**Comment by andrew-edwards** [comment]
Done the whitespace thing (avoids splitting a paragraph strangely), managed to keep things mostly in same place as last year (so easy to compare .pdf's).
Just going to add a couple of things to the 'joint prob' one-page bullet point. Promise to keep it at one page!

**Comment by andrew-edwards** [comment]
Someone please double-check calcs 5d40ab98d5aae8d7eb54d3d8d4cc36a8e7ed6074 and f0eb97396b57e11e861b03e7ec9e3405455dd652 . Especially as one is the one-page summary. (Get nervous doing that sort of thing so late!).

**Comment by andrew-edwards** [comment]
Just doing the **Andy bit still in there (about theta and theta). Then I'm thinking I'm done with editing....

**Comment by aaronmberger-nwfsc** [comment]
I'm jumping all over the place and can't seem to read a large section all at once - get distracted cause read this so many times.  If there are any lingering issues that yet another read through would catch, I'm fine to fix those later.  I guess I'm saying I'm about done.  Should we aim to do a pdf compare at 2PM (or even earlier)?

**Comment by kellijohnson-NOAA** [comment]
I believe everything is correct, but the year is hardwired and will be wrong next year. Where
```paste("Bratio_",endyr)
```
would be better.

**Comment by andrew-edwards** [comment]
Thanks. Yes, I tried 
```
# probs.curr.bforty      <- f(mean(paste0("base.model$mcmc$Bratio_", assess.yr) > 0.40) * 100, 1)
```
the other day but it didn't work, even though
```
base.model$mcmc[[paste0("SPRratio_", end.yr-1)]]
```
worked, so I gave up....  maybe tomorrow ....

**Comment by kellijohnson-NOAA** [comment]
f(mean(base.model$mcmc[paste0("Bratio_", assess.yr)] > 0.40) * 100, 1)

**Comment by andrew-edwards** [comment]
Well, okay, fair enough ;)

**Comment by andrew-edwards** [comment]
Just finishing the theta bit (sorry, it got fiddly). I'm just going to flick through the whole thing checking for any formatting issues. Then time to upload pdf's (maybe just to Slack) and we all compare?

**Comment by aaronmberger-nwfsc** [comment]
awaiting your mark to fetch, rebase, build...

**Comment by andrew-edwards** [comment]
Looks good. No pesky dangling subheadings. Go for it, commit 52c4ed81c7b9703ac1971f8de836d4e8d05040e5  ("Give results of theta...").

**Comment by kellijohnson-NOAA** [comment]
I have to go to a meeting and won't be on my computer until late tonight. Are we good?

**Comment by aaronmberger-nwfsc** [comment]
Yes, I think so.  I'm sure the pdfs compare and then Andy will just send to Stacey.  If they don't (unlikely), Andy and I can fix anything remaining.

**Comment by kellijohnson-NOAA** [comment]
Sounds good. I will have my phone where I can see slack, but no computer :(

**Comment by andrew-edwards** [comment]
Done and done.
