### ISSUE TITLE
Isn't the current model a state-space model?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#672]
We have measurement error (e.g. survey variance) and process error (e.g. sigmaR), so I think that make our model a state-space model? Text in SRG reply 2 (p49) implies it isn't.

No big deal, just wondering.

**Comment by aaronmberger-nwfsc** [comment]
That process error (sigma-R) is fixed and not estimated in our base model.

**Comment by andrew-edwards** [comment]
But we still have process noise in the annual recruitments (i.e. they're not deterministic), and can vary randomly year to year.

**Comment by kellijohnson-NOAA** [comment]
The kicker is that the variability of them is not estimated. So a true state-space model estimates both the process error and observation error levels.
