### ISSUE TITLE
SRG presentations

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#673]
We should start (tomorrow or so) thinking about presentations and who want to do what this year.  

We have presentations for:
- [ ] data  (Kelli)
- [ ] assessment (Chris)
- [ ] sensitivities (Andy)
- [ ] management (Aaron)

then any others, maybe 
- [ ] hake-related research update (depending on SRG agenda - maybe they are inviting people to talk)

**Comment by cgrandin** [comment]
I'm going to get the assessment one started today.

Some function names changed, i.e. have underscores instead of decimals in their names, so watch for 
that first off. Also some functions now have different arguments. These should be the main issues when getting the presentations building.

**Comment by kellijohnson-NOAA** [comment]
I can work on the data one.

**Comment by andrew-edwards** [comment]
I don't mind which. I have to go through some proofs today (and likely tomorrow) for a paper (Marine Ecology Progress Series!). Thankfully no-one reformats our hake assessment - could never proofread it! (I don't mind doing 14 pages for a paper, still takes a while though).

**Comment by aaronmberger-nwfsc** [comment]
Okay, I'll take the management one I guess, or at least start working on the presentation

**Comment by andrew-edwards** [comment]
Great - I'll do sensitivities. Still proof-reading, so may not start until Friday, but we have a week still.

**Comment by kellijohnson-NOAA** [comment]
A draft of the data presentation is available. I still have to add some info on how the historical data changed from last year.

**Comment by aaronmberger-nwfsc** [comment]
draft of management presentation has been pushed

**Comment by aaronmberger-nwfsc** [comment]
I'm going to close this and then we can start individual presentation 'issues' as a spot to add comments for the creator as needed.
