### ISSUE TITLE
Build and send excel spreadsheets 

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#675]
Usual excel spreadsheets of biomass/numbers at age (etc) - send to Shannon and post to google drive.

**Comment by andrew-edwards** [comment]
They're good - Chris had just cleaned them up the other day. I have them and he just needs to rebuild them.

**Comment by cgrandin** [comment]
They are done and posted on the Google drive under 2020 TAC folder
