### ISSUE TITLE
2015 tribal reallocation

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#677]
Column 5, Line 15, of data/further-tac-details.csv is incorrect I think. The [Federal Registry](https://www.federalregister.gov/documents/2016/01/05/2015-33155/magnuson-stevens-act-provisions-fisheries-off-west-coast-states-pacific-coast-groundfish-fishery) specifies that 30000 t was reallocated not 26888 as the spreadsheet indicates. Can someone confirm that this is a mistake and I will fix it.

**Comment by aaronmberger-nwfsc** [comment]
Yes, it looks like 26,888 was what was left over for the tribal TAC after the re-apportionment of 30,0000.  So tribal were allocated 56,888 at the beginning of 2015 and then in September 30,000 was re-allocated to other US sectors, leaving 26,888 left for tribal.  That column refers to the allocation amount, so yes it should be 30,000.  Good spot.

**Comment by kellijohnson-NOAA** [comment]
3bbe5263727678744b0aee8203fc9233033a329b
