### ISSUE TITLE
Management history figure - seems incorrect

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#679]
![image](https://user-images.githubusercontent.com/7946234/74755877-a0e8c400-5228-11ea-9906-3706813767d4.png)

![ManagementResponse](https://user-images.githubusercontent.com/7946234/74755888-a6460e80-5228-11ea-9d76-2374ba86c972.png)

The first image is from last year and the second image is my corrected version (if I interpret the reason for showing this figure in the first place).  Using 2018 as an example, the first image shows the level of 2018 catch on the y-axis (both the realized catch and the TAC implemented by management) and the x-axis shows the default harvest control rule TAC predicted from the assessment for 2019.  The second figure shows the same thing except that the x-axis is the default harvest control rule TAC from 2018.  It seems like matching them, as in the second figure, is what we want to show (not how current catch levels relate to next years default TAC, as in the first figure, given this picture has always been about past management).

I'm changing this in the beamer-hake-management file unless someone has a reason for me not to do so.

**Comment by cgrandin** [comment]
So the circles and squares are referencing the y-axis and the x-axis shows what the assessment came up with as a TAC. What if we changed this plot to show all three of those values along the same vertical line, with the x-axis being years? I think it would be easier to interpret that way. Each line would have three shapes on it and the differences between predicted TAC, actual TAC, and actual catch would be easier to discern between years. I offer to make this..

I just noticed that that figure is hard-wired. Do you have a CSV with those values?

**Comment by andrew-edwards** [comment]
Sounds good - I always assumed the x-axis is what you have in the second figure.
Any reason not to add this to the assessment document?  (Having a caption may have helped spot the issue!).
Is the top figure last year's version, or last year's code on this year's results. Just trying to figure out what's labelled. Aha - Chris has just answered also.

**Comment by cgrandin** [comment]
Nevermind on the csv file. I found the code inside the beamer presentation figures directory.

**Comment by aaronmberger-nwfsc** [comment]
The code is under beamer/SRG/Management/Figures  - although I have updated that on my local to make these adjustments.  What is in the master repo would be what was used last year.  All three values are already on there - it's just that the assessment-based default harvest control rule TAC is shown as the one-to-one line.  I do like how the one-to-one line shows the default policy TAC as one demarcation, from which then you can see how management and fishery have performed relative to the default.

**Comment by cgrandin** [comment]
This is what I was thinking. We don't need to use it but it's another way of looking at this:

![image](https://user-images.githubusercontent.com/4551051/74770727-aacaf100-5241-11ea-96df-2309c88e8ae6.png)

**Comment by aaronmberger-nwfsc** [comment]
Might as well output that figure as well in case we want to use it this year or in the future.  Maybe no connecting lines?

**Comment by cgrandin** [comment]
I have written it into the code base, and can transfer the other figure code into the same file as well. Will make an option to include those lines or not

**Comment by aaronmberger-nwfsc** [comment]
I have much of all beamer-hake-management related files, including the file to create this figure in the figure folder all changed/updated as I'm working through the presentation, so maybe wait to merge your new stuff

**Comment by cgrandin** [comment]
The new stuff is all inside a new R source file so it won't affect your work at this point

**Comment by cgrandin** [comment]
![image](https://user-images.githubusercontent.com/4551051/74776451-6ee95900-524c-11ea-8302-51821e9174bc.png)

**Comment by andrew-edwards** [comment]
I think the connecting lines help. Maybe not dashed - keep them faint. And the vertical black lines could be light grey maybe?

**Comment by cgrandin** [comment]
Something like this? I also added in the ability to show the current year's assessment-estimated TAC, and reversed the legend order

![image](https://user-images.githubusercontent.com/4551051/74778676-e6b98280-5250-11ea-8263-f863f820ddea.png)

**Comment by aaronmberger-nwfsc** [comment]
I think this can be closed as Chris will push his changes for making this figure once I push (maybe Thursday).
