### ISSUE TITLE
Request from David Sampson regarding age-composition sample sizes

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#680]
David Sampson's email dated February 18, 2020 is pasted here (By Chris Grandin)

Aaron and other members of the JTC. 

At the risk of breaching protocol, I have a request for additional information regarding the new assessment, which (as always) is very well written and thorough.  My request is for some additional information that focuses on the issue of the age-composition sample sizes that are input to Stock Synthesis (relating to SRG request #4).  In the attached Excel workbook I compiled information from Tables 5-11 regarding the recent age-composition samples that inform the assessment model.  If it is not too difficult to do, I was hoping you could fill in the information that I've flagged with yellow highlights.  What I hope to explore is the stability of the ratio of the numbers of hauls/sample and fish/sample from the different fisheries.  The current annual age-composition sample sizes are the simple summation of the number of hauls (from at-sea operations) and the number of trips (from shore-side operations).

It is not crucial that I receive this information in advance of the SRG meeting, but I hope we will at least be able to explore this information during the SRG meeting.

Regards

David
[for_JTC-Recent_Age_Composition_Sample_Sizes.xlsx](https://github.com/pacific-hake/hake-assessment/files/4221743/for_JTC-Recent_Age_Composition_Sample_Sizes.xlsx)

**Comment by kellijohnson-NOAA** [comment]
I already cried to @aaronmberger-nwfsc asking if he would respond.

**Comment by aaronmberger-nwfsc** [comment]
Quick Canadian data question: I assume the number of fish could be added for Shoreside and FT, but the number of hauls for Shoreside even recorded.  It is not for US Shore-based.

**Comment by cgrandin** [comment]
It is, but it would take me some time to query that. Should I do that? We already have the number of hauls sampled for age

**Comment by aaronmberger-nwfsc** [comment]
Sounds good, thanks Chris.  Let's give him all that we can with reasonable effort.  I don't want us to spend hours and hours on this as now is not the time for that.  I think he wants to simply create an alternative input sample size starting point metric based on some work that Ian Stewart and Stacey Miller did a while back.  Maybe I'm wrong, we'll see....

**Comment by cgrandin** [comment]
Done and Sent off via email on Feb 19, 2020. I re-opened #462 to finish this year.
