### ISSUE TITLE
Estimated MLEs - Table 19 starts at 1966, but Figure 29 also has 1965.

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#681]
Just noticed this - wondering why that would be. Can look into it later...

**Comment by aaronmberger-nwfsc** [comment]
off the cuff - might be that the 1965 is representing initial age comps, which are obtained from equilibrium conditions as described from early year rec devs (1946-1965) and M

**Comment by kellijohnson-NOAA** [comment]
Yeah, if you go the table from the report file it has a category of "Era" which the first year of the table, the Era is Virgin and the other years are Time.

**Comment by andrew-edwards** [comment]
That's what I wondered. Sounds like we should add 1965 to Table 19, and edit both captions to explain it's the initial conditions.

**Comment by andrew-edwards** [comment]
For reference before I lose it, here's the bubble plot as MLEs:
![image](https://user-images.githubusercontent.com/6977190/106990749-bb61c900-6729-11eb-83a2-202394b3e195.png)

And here it is for median MCMCs. Note the change in scale, and the directional difference in the red line for the last few years:
![image](https://user-images.githubusercontent.com/6977190/106990812-dfbda580-6729-11eb-84f9-a33770e843e2.png)

**Comment by aaronmberger-nwfsc** [comment]
no bias adjustment ramp down in MCMC, but bias adjustment ramp in MLE (i.e. the way recent recruits are handled) might have something to do with it.  The MCMC one looks more logical to me given the 2010 and 2014 year classes are 6+ now.
