### ISSUE TITLE
Scale of figures

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#685]
The scale of the figure here and on the next slide don't match, so when you flip between then the values on the x-axis are in different positions making it difficult to compare them. Also, I would switch to having the base-model results first and then ADNUTS. The titles above the figures are in different spots as well.

https://github.com/pacific-hake/hake-assessment/blob/1164b7e3de6a7a009f8ed8f27bfa542b674ce319/beamer/SRG/Sensitivities/beamer-hake-sensitivity.rnw#L1083

**Comment by andrew-edwards** [comment]
Thanks. Yes, I realised the scales were different. But xlim is not a simple ```...``` option in the function:
```
  matplot(catches, prob.dat,
          xlim=c(0,max(catches,
                       na.rm = TRUE)),
```
and I didn't feel like messing with functions that are used elsewhere. I didn't the difference was too bad, so can still get the point across.
I did the offset titles on purpose to make it a bit easier to spot the difference when flipping between them! 
I haven't finished the talk yet, so still have stuff to fix/check. 
Got a bit distracted yesterday with a paper we had published in MEPS - it has the term 'bin structure' in the title, which I got from Monnahan et al. (2016) that you're an author on....

**Comment by kellijohnson-NOAA** [comment]
As long as you know the scales are different I think it is fine. Just a point to note out when explaining it. Not a big deal. But, maybe we can decrease the implications of the text that says 'Would allow MCMC results for all sensitivities' and say 'Would increase the use of MCMC results for sensitivities'?

**Comment by andrew-edwards** [comment]
Yes, done. While you're looking at it - page 42 'Suggested Sensitivity Runs'. Chris and I kind of came up with the ones we thought worth keeping - definitely suggest any changes to that list.

**Comment by andrew-edwards** [comment]
If you have a minute - the squid plot shows bump in 2010 rec dev with the final year of data. I'd like to know how many fish is that (based on MLEs)? Presumably the stock-recruitment function has the multiplier 
```
exp(\epsilon_t - {\sigma_R^2}/2)
```
yes (with the bias-correction term)?

**Comment by kellijohnson-NOAA** [comment]
I think this might have to do with late vs. main recruitment period b/c the endyear of the model in changing. Looking into it now.

**Comment by cgrandin** [comment]
@andrew-edwards I made the risk plots able to take xlim values in d8f6d2e3e07899e62c6bbc7798b89e443e4d248a. I just pushed all my commits from the last 3 days.

**Comment by kellijohnson-NOAA** [comment]
You can look at the estimates of recdevs vs recruitment using the `SSsummarize` function. 
```
xx <- r4ss::SSsummarize(retro.list)
xx$recruits[xx$recruits$Yr %in% 2010, ]
xx$pars[grepl("RecrDev", xx$pars$Label) & xx$pars$Yr %in% 2010, ]
```

**Comment by andrew-edwards** [comment]
And, yes, I haven't actually been consistent with showing base or age-1 first. Will fix, thanks.

**Comment by andrew-edwards** [comment]
Anyone any quick thought as to why
```
make.comparison.plot(c(list(base.model), list(sens.models.2[[1]])),
                     subplots = 13,
                     model.names = c(base.model.name, sens.model.names.2[1]),
                     end.yr = end.yr,
                     indexfleets = c(2))
```
works (giv es similar to Fig 44 but just age-1 index sensitivity), but the mcmc version does not:
```
make.comparison.plot.mcmc(c(list(base.model), list(sens.models.2[[1]])),
                     subplots = 13,
                     model.names = c(base.model.name, sens.model.names.2[1]),
                     end.yr = end.yr,
                     indexfleets = c(2))
```
it just shows the survey points.
[I used subplots = 13 instead of 14 to not have log scale (not sure why we do that usually), but that's not the issue].
For now I'll stick with the MLE version, which gets the point across about the fit to the survey index.

**Comment by cgrandin** [comment]
I think this is because SSplotComparisons() has no knowledge of the extra mcmc output we have to get the posteriors. I don't think it is trivial to do this at this point. One thing you could add here though is the uncertainty by doing:

```
make.comparison.plot(c(list(base.model), list(sens.models.2[[1]])),
                     subplots = 13,
                     model.names = c(base.model.name, sens.model.names.2[1]),
                     end.yr = end.yr,
                     indexUncertainty = TRUE,
                     indexfleets = c(2))
```
