### ISSUE TITLE
Data presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#687]
This looks good.  Comments I have are:
- I got an error on Age composition by sector slide, but maybe just me (PBSmodelling pkg error)
- New survey and fishery age-composition comparison plot is rad
- [x] Might be worth adding the age-1 survey map of maps figure as the third slide under 'Survey' section (I think a main topic with the age-1 survey estimate (again this year) is how much age-1 biomass was missed on the southern end and this year this map shows that potential).
- [x] First Wt-at-age slide: maybe 'Puget Sound stock' - as we consider it different than the coastal stock
- [x] first maturity slide: maybe 'Data from 2018 and 2019 have yet to be analyzed (expected to occur in 2020)'
- last maturity slide: do we dare say "More winter acoustic surveys or alternative survey approaches may..."?  People will immediately think saildrone though...

**Comment by kellijohnson-NOAA** [comment]
Thanks @aaronmberger-nwfsc I will make these changes today, I wasn't sure how much to present regarding the survey data b/c it is a survey year and I thought they would be showing much of the same information.

**Comment by aaronmberger-nwfsc** [comment]
Yes, good point about survey year - I'll leave it up to you!

**Comment by kellijohnson-NOAA** [comment]
I will add it, it doesn't hurt to beat them over the head with it b/c I think we will end up mentioning it again in the sensitivity presentation, but all mentions will, in theory, be from different perspectives.

**Comment by cgrandin** [comment]
I went through this presentation again and aside from what @aaronmberger-nwfsc has mentioned, I don't see anything to add at this point. Nice work on this one.
