### ISSUE TITLE
Sensitivity presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#689]
Again, this looks really good!
Some minor comments/thoughts from me:
- just a note on the sigma-R sensitivity - last year the upper limit was 1.8 and I reduced it to 1.6 because I don't know of a species that has a 1.8 sigmaR.  1.6 seemed like more of a reasonable upper level to run given the r4ss sigma-r output suggests higher than 1.4 and closer to 1.6 (though I note that r4ss sigma-r output continues to suggest higher and higher values as your increase sigma-r and rerun....);  all this relates to stability of equilibrium conditions!
- if not too hard 'age-1 index' slide 2 could include Trevor's suggestion:  [Figure 11: would it be hard to instead plot the Bayesian estimates and 95% credibility intervals of age-1? Instead of the MLE values.] - though I wouldn't worry too much about this given the late hour.  And now I see you have more age-1 index stuff later so could just say 'more later' here (???).
- just a note: interesting that the alternative weighting methods show using DM results are more similar to Francis when by design it is supposed to be fairly similar to M.I. (though I don't know it that 'heard a long time ago now' logic still stands)
- ADNUTS section: first slide bullet 4 - 'So same base model structure,...';  
- ADNUTS first slide bullet 6 - '..2.5 h diagnostic step...'; 
- ADNUTS: the risk plots are typically shown in the management presentation, but doesn't hurt to speak to them first here; 
- ADNUTS: What point are we trying to make by thinning the already thinned NUTS samples for steepness?; 
- ADNUTS: 'Nuts conclusion slide' first bullet - maybe say 'Worked well, but further considerations will be needed, such as:'  because e.g., we usually only have one person run the mcmc so fixing run length among users isn't a big deal, now if we start running sensitivities we definitely will want the same seeds as the base run and then would be nice (though not necessary in my mind) to have the samples match); 
- ADNUTS: 'Nuts conclusion slide' second main bullet - maybe 'Suggest adnuts be further considered for 2021 assessment' just so we aren't sounding too prescriptive at this point; 
- ADNUTS: 'Nuts conclusion slide' fourth main bullet - ...'would need to reduce....' I don't think there is a way around it, even if MCMC takes 2-3 hours each - that's too much to do ALL our current ones; - ADNUTS: Last ADNUTS slide: I think we need to think carefully and strategically about these so I suggest we just list the current ones and not highlight any in red at this point (or highlight the SRG recommended 'key' sensitivities in red), My idea on this whole thing is that we really should only be doing sensitivities for things that we actually have information about given this is a 'mature' assessment, not a brand new one or one that hasn't been done in decades where you may want to look at a bunch of stuff cause no one ever has, such that our sensitivities be real possibilities (alternative states of nature) with results that should be considered by the JMC.  Now we still may have some runs that we show, even mcmc runs, when developing changes to the assessment (e.g., t.v. selectivity), but I see those types of things coming and going, depending on the assessment year.  This is of course just my opinion, but perhaps this general idea is something we want the SRG to consider and discuss when this slides comes up. 
- 'summary' slide bullet one: make sure you qualify this b/c there is quite a bit of difference depending on what one is looking at (second bullet helps); bullet 4: maybe remove as that is not an explicit sensitivity this time.

**Comment by andrew-edwards** [comment]
Thanks. I didn't work at the weekend - will finish talk on the ferry and look at these. The plaid shirts are packed - we're getting the 3:15 ferry.

**Comment by andrew-edwards** [comment]
"ADNUTS: What point are we trying to make by thinning the already thinned NUTS samples for steepness?;"   - I was seeing if crudely thinning it got rid of the autocorrelation.  It seemed to.

Was a crude calculation. Can take it out if you like - I'm good either way.

**Comment by aaronmberger-nwfsc** [comment]
No worries - I was just wondering if that was going to be a suggestion or if it is an example of the types of things we need to address before using adnuts or maybe something else.

**Comment by andrew-edwards** [comment]
Thanks Aaron. Did most of your suggestions (age-1 MLE slides were coming out anyway, just hadn't got back to them). 
Did leave the suggested sensitivities to keep (in red), just as a starting point. Good point about bringing some back in as necessary. 
Or would you suggest an even shorter recommended 'keep' list? We can just discuss it openly at the meeting - Chris and I just came up with the 'keep' ones fairly quickly...
