### ISSUE TITLE
Fix MLE vs MCMC biomass plot (Fig 34)

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#691]
The MLE was determined to be double for all model runs just before the SRG meeting. This is fixable by re-running the models with ```nsexes = -1``` in the data file but does not explain why the MCMC biomass in the MLE vs. MCMC biomass plot is also double what it should be. The other MCMC biomass plots are correct.

**Comment by andrew-edwards** [comment]
Kelli fixed in #653.
