### ISSUE TITLE
Fishery sector depth distributions

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#692]
SRG informal request 2020-02-25
- check data to ensure they are not fishing at depths of zero
  - [x] USA
  - [x] Canada
- [x] write a more-specific caption providing information on exactly what is being shown
- ~~provide individual data points~~ JTC decided to not do this because the data are confidential

**Comment by andrew-edwards** [comment]
Guessing it's just the default setting in `boxplot` or whatever is used, that does that weird 1.5x interquartile range for the whiskers.

**Comment by kellijohnson-NOAA** [comment]
I checked the US data and the boxplots have a minimum value of > 50 m. 
A more specific caption was provided in 3413cb0

**Comment by cgrandin** [comment]
Canadian data done in 00e7f6e5ab48a0ac8f98479fd61785b15b2958a2

There were a few below 50m. Not anymore.
