### ISSUE TITLE
Trying to understand positive recruitments at age-0 in retrospective plot (Fig 55)

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#694]
My initial theory for why there are positive age-0 deviations is somehow related to the bias adjustment being applied to years with no information about recruitment due to the removal of the final years of data.

That is, the control file inputs
```
2018 # _last_yr_fullbias_adj_in_MPD
2019 # _first_recent_yr_nobias_adj_in_MPD
```
would need to be adjusted back by one year for each year of the retrospective. It might help to look at the "RecDev" group of r4ss plots for one of those retrospective models.

**Comment by kellijohnson-NOAA** [comment]
We adjust the main period, but we don't adjust the bias adjustment ramp inputs. Thanks for the input @iantaylor-NOAA

**Comment by iantaylor-NOAA** [comment]
Using a retro-6 model, I confirmed that shifting the inputs from
```
2018 # _last_yr_fullbias_adj_in_MPD
2019 # _first_recent_yr_nobias_adj_in_MPD
```
to
```
2012 # _last_yr_fullbias_adj_in_MPD
2013 # _first_recent_yr_nobias_adj_in_MPD
```
makes the recdevs in the recent years now match 0. Using MCMC for the retrospectives would also make the issue go away.

Digging deeper into why they were non-zero without that change, I realized that applying the bias adjustment to those years with no information about recruitment results in really low recruitment for the retro years (as shown in figure below) such that the realized catches can't be fully removed from the population. This is evident in the non-zero value for the "Catch" element in the table of likelihoods.

Changing the bias adjustment settings in future retrospectives should correct this although even without the downward adjustment to recent recruitments, there may still be cases where the catch can't be removed without positive recdevs.

![compare9_recruits](https://user-images.githubusercontent.com/4992918/75386789-24dd2480-5897-11ea-84dd-516d8aa7fbd1.png)

**Comment by aaronmberger-nwfsc** [comment]
Good to see that our test evaluations on the bias adjustment settings during retrospective runs also confirms this behavior.  We plan to move to mcmc for retros, but in the mean time need to remember to do this for MLE runs (see issue #728) where new lines of code will be added for retro runs.)

**Comment by kellijohnson-NOAA** [comment]
See #760 for an example of the squid plot and how this issue relates to MLE vs MCMC.
