### ISSUE TITLE
McAllister-Ianelli effective sample size calculation

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#696]
For what it's worth, the following equation is from Punt 2016 (Some insights into data weighting in integrated stock assessments):
"McAllister-Ianelli effective sample size for the conditional age-at-length data for year y and length-class L"
![image](https://user-images.githubusercontent.com/4992918/75377277-4da8ee00-5886-11ea-9dfe-d8b69d64b2b9.png)
where presumably the p-hat terms are the expected proportions at age and the p terms are the observed proportions.

**Comment by kellijohnson-NOAA** [comment]
Thank you @iantaylor-NOAA, this equation is what is used by SS to write the report file and goes in the effN column for each composition type. I let Dave know.
