### ISSUE TITLE
Day 2 request 1 - ratio of recruitments

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#697]
(Copy from Word file once John uploads it).

**Comment by andrew-edwards** [comment]
1.	Find the estimated absolute recruitment when the MLE model was done for age 2 (Xi) of each cohort and the estimated recruitment of that same cohort in the most recent assessment (Yi). Then create a histogram of Xi/Yi for the base model and Xi/Yi for the model including the age 1 index. If the age-1 helps, the ratios should be closer to 1 than for the base model.

**Comment by kellijohnson-NOAA** [comment]
44eb7ae70acb8d0b7666f21f9156dcf7d8b5f26c
