### ISSUE TITLE
Remaining document tasks - due Monday 2/27

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#700]
Feel free to add to this list or sign up for these tasks:
 - [x] Add contextual paragraph at the beginning of the age-1 survey appendix (Andy working on)
 - [x] Ensure document builds with fix applied to SSplotComparisons figures (bridging, sensitivity, others) and double check no related absolute SSB numbers are hard-wired (or reported incorrectly) 
 - [x] Add JTC responses to SRG requests code created for the SRG meeting into Appendix B
 - [x] Double check that we have included all of Trevor's comments that we want to this year
 - [x] Remove draft and other related disclaimers (Andy)
 - [x] Update acknowledgements to include SRG contributions
 - [x] Final spell check (Andy)
- [x] Add squid plot and just the 2008 retro plot (with the distributions) to age-1 index appendix - Andy originally thought of adding more but chatting with Aaron we thought less is more, so I"ll just add those (Andy)
 - [x] Update Fig 13 and Fig 14 (heatmaps) captions if we're going with the new format.

**Comment by andrew-edwards** [comment]
What's the 'fix to SSplotComparisons` figures? The xlim option doesn't matter for the document so much. Basically - do I need to update r4ss?

**Comment by aaronmberger-nwfsc** [comment]
Just need to use this version of r4ss and everything else should be automatic - this point it to just check to make sure that 2x biomass issue is resolved in final doc build...

devtools::install_github("r4ss/r4ss@hake2020")

**Comment by andrew-edwards** [comment]
Thanks - yes. GitHub says Kelli updated it two days ago - it feels like it was much longer! I'll delete knitr-cache and then biomasses should be correct, like they were in the talks.

**Comment by andrew-edwards** [comment]
I ticked the second box. We all update r4ss on Tuesday so we should all be good. This only related to the plots, so numbers in text should be fine.

**Comment by andrew-edwards** [comment]
I just pushed the age-1 appendix update - someone please take a read-over.

**Comment by andrew-edwards** [comment]
I'm just doing the easy SRG responses in Appendix B.

**Comment by andrew-edwards** [comment]
I just pushed Appendix B - have done some but still needs work. We're done here soon. We can finish this fine on Monday.

**Comment by kellijohnson-NOAA** [comment]
50c046f provides responses to all but one of the remaining requests and the potential "additional" request that was made on the third day. I am not sure which plots we need for the diagnostics, so I am going to leave that one for Chris or Aaron.

**Comment by andrew-edwards** [comment]
Think we're nearly there. Need to confirm:
- [ ] check Figures in Appendix B match (Chris's and Andy's, Kelli and Aaron's also)
- [ ] read over anything if you want (tonight)
- [ ] skim through to check formatting is okay (Andy's version)
- [ ] final build by 9:15am tomorrow, then email to Sandy?
