### ISSUE TITLE
Consider reporting DM multiplier in some spots, not just theta

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#704]
Report multiplier for DM parameters in some spots (maybe just text) as theta itself is not very informative.  Theta is the parameter being estimated so it still seems worthy of keeping it in parameter reporting tables.

**Comment by andrew-edwards** [comment]
Value is now reported in r4ss so just need to reference that column.

**Comment by kellijohnson-NOAA** [comment]
if
```
replist <- SS_output()
```
then
```
replist[["Dirichelt_Multinomial_pars'']]
```
has the following column names: Value, Phase, Min, Max, Theta, and Theta/(1+Theta), where the last column is the multiplier.

**Comment by kellijohnson-NOAA** [comment]
Note that this existing table in the list output of SS_output() would be MLE DM, not the MCMC DM values. I don't see anywhere in the text that we report actual theta values. I think we should just leave things the way they are because the equation is in the document.

**Comment by andrew-edwards** [comment]
Agree with Kelli that we don't report values in text and equation is in there.
