### ISSUE TITLE
Code in SPR illustration may be wrong

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#707]
Search the code for TODO, in ```make.SPR.illustration()```

It looks like it is using the old fecundity assumptions and needs updating.

**Comment by aaronmberger-nwfsc** [comment]
so this only had an influence on the explanation of SPR in our glossary?

**Comment by cgrandin** [comment]
Yes, there was some old code in there from before we changed the fecundity/weight-at age. It made a small difference in the plot and values on the plot in the glossary only.
