### ISSUE TITLE
xaringan package - consider it over beamer (?)

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#709]
Related to another science question, I was introduced to an end product presentation built by xaringan.  During discussions Ian noted that upon first glance the xaringan package seems to be clearly far better than Beamer (at least in looks).  Maybe this is something we want to consider for our presentations - though admittedly Beamer works just fine for our hake process purposes.

See this presentation and the acknowledgments slide:
https://www.dicook.org/files/visec2020/slides#1

**Comment by cgrandin** [comment]
I have done several presentations using xaringen. It's cool but it is rendering webpages as slides. Try opening that with Internet Explorer... FireFox and Chrome render it similarly but IE Edge is in a different font. We would have to say "Must use Chrome" or something. 

Also, this means re-formatting all the slides on all the presentations. Many are easy but those ones with column percentages for plot vs text and such would have to be redone. Maybe we could do the shortest one as a testbed first?

**Comment by kellijohnson-NOAA** [comment]
I would vote for keeping status quo right now given that we have plenty of other work to do and the IT capabilities of many of our readers is "challenged".

**Comment by andrew-edwards** [comment]
Agree with Kelli - beamer and .pdf works just fine, and the slides are somewhat automated. Plus that's the few days we get between submitting and the meeting, so keeping it simple gets my vote! I've seen people try and give talks from web slides and it doesn't really work well.

**Comment by aaronmberger-nwfsc** [comment]
sounds good to me - closing this then
