### ISSUE TITLE
Fix sizing issues with some of the new png figures

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#710]
Only played with the map one so far (expect others will be easier as they are simpler). Tried this and the two maps come out the same size but fonts are different sizes, suggesting the chunk options are making a bit of a difference:

```
%%%%%%%%%%%%%%%%%%%%%%%
\begin{figure}[H]
\begin{center}    % Don't make any bigger as then previous page becomes blank
<<main-overview-map, fig.height=8.5>>=
g <- make.overview.map.plot(path = rootd.map.data)
g
@
\end{center}
\caption{Overview map of the area in the Northeast Pacific Ocean occupied by \fishname.
  Common areas referred to in this document are shown.}
\label{fig:main-overview-map}
\end{figure}
%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%
\begin{figure}[H]
\begin{center}
<<main-overview-map2, fig.height=10>>=
g
@
\end{center}
\caption{Overview map of the area in the Northeast Pacific Ocean occupied by \fishname.
  Common areas referred to in this document are shown.}
\label{fig:main-overview-map2}
\end{figure}
%%%%%%%%%%%%%%%%%%%%%%%
```

 I'll carry on at some point.

**Comment by cgrandin** [comment]
I discovered that we can't really resize PNGs but we can make the plots, with the chunk not showing it (`fig.show='hide'`), then immediately load it using `\includegraphics` so that we can use whatever latex commands we like:

```
%%%%%%%%%%%%%%%%%%%%%%%
\begin{figure}[H]
\begin{center}    % Don't make any bigger as then previous page becomes blank
<<main-overview-map, fig.show='hide'>>=
make.overview.map.plot(path = rootd.map.data)
@
\hspace*{-8.5cm}\includegraphics[width=2\linewidth]{knitr-figs/main-overview-map-1}
\end{center}
\caption{XXX--Overview map of the area in the Northeast Pacific Ocean occupied by \fishname.
  Common areas referred to in this document are shown.}
\label{fig:main-overview-map}
\end{figure}
%%%%%%%%%%%%%%%%%%%%%%%
```

This has the fonts all wrong though. So maybe a combo of fig size in the chunk with this method will work.

**Comment by kellijohnson-NOAA** [comment]
How come we can't "size pngs" using the fig.height and fig.width chunk options?

**Comment by kellijohnson-NOAA** [comment]
I am honestly not sure what aspect ratio means, but I believe if you only assign one, i.e., fig.height or fig.width and not both, then R will figure out the correct dimension for the other one.

**Comment by aaronmberger-nwfsc** [comment]
I'm glad you all are figuring this out.  I have always had trouble with the aspect ratio and have never been able to a priori understand what my 'adjustments' would result in - thanks!

**Comment by cgrandin** [comment]
We use aspect ratio in our CSAS docs and it seems to work well, but those are compiled with pandoc (Rmd). 
We use the golden ratio which always seems to look good (https://www.onepager.com/community/blog/1-0-618-the-gold-standard-in-aspect-ratios/, https://en.wikipedia.org/wiki/Golden_ratio)  where the height is 0.618 height. Anyway, it seems we can't guarantee that here unless we multiply it out by hand.

**Comment by cgrandin** [comment]
All figures appear nice in the doc: 790dbb39a33ede6072852673e14d933cf3b6d864
