### ISSUE TITLE
PNG figure 5 is low quality

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#711]
Figure 5 "Unstandardized (raw) catch-rates (t/hr) of Pacific Hake catches" is noticeably lower quality than the rest, it is a hard-coded figure **fishCatchRatesUS.png**

Note I have set the knitr figures to 600dpi after researching what DPI will show high quality on paper and screen

**Comment by andrew-edwards** [comment]
A new version will need to be made anyway, so whoever makes it (looks like Kelli is assigned!) can just make a .png. The current one is just converted from .eps to get the build working. 
Good to know about the 600 dpi, thanks Chris.
