### ISSUE TITLE
Alternative text for accessibility

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#712]
I have written a Wiki on how the other parts of the accessibility are done (PNGs, table tagging): https://github.com/pacific-hake/hake-assessment/wiki/How-to-make-the-document-web-accessible

I checked all the tables one-by-one and fixed issues which messed up table tagging, so that part is done, and so are the PNG figures. All this is still in the compliance branch.

What remains is the alternative text part. I will take a look at how to implement this next, but we have to figure out alernative text for each figure, and it cannot just be the caption because the reader already reads that out and it would be duplicated. I am thinking we could just have it say that the caption explains this adequately or something.

**Comment by andrew-edwards** [comment]
Here's the older stuff from our CSAS investigations:  https://github.com/andrew-edwards/csas-style  regarding alt text

**Comment by cgrandin** [comment]
Done in e6e83a3105256753ab06e10edebe53b4abdf364d
See the Wiki for information
