### ISSUE TITLE
JTC meeting this week to check in

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#713]
Let's try to meet later this week to check in on final data extractions, plans for modeling, and any other priority updates.

Kelli and I can meet on Thursday at 9AM, 10AM, 1PM, or 2PM.  Or we could do Friday at 9AM or 10AM.  Chris and Andy, do any of these times work for you?

**Comment by andrew-edwards** [comment]
Happy New Year all! 

I have a 10am Thursday meeting, so that afternoon or Friday work best for me.

**Comment by cgrandin** [comment]
Happy 2021! Thursday at 1 would be best for me!

**Comment by aaronmberger-nwfsc** [comment]
Done and done - Thursday at 1PM then.  I just sent a calendar invite.  Here is the hangout link as well: meet.google.com/ruh-gnct-fun

**Comment by aaronmberger-nwfsc** [comment]
This is scheduled so closing
