### ISSUE TITLE
recruitment indexing in custom-knitr-variables

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#715]
Should we be using something like 
```
names(base.model$mcmccalcs$rlower) %in% names(prev.assess.recruitment.lower)
```
to index which recruitment values to compare recruitments in this year's compared to last year's model? The above makes things work when we are testing things in the bridging stage and the models are from the same year. I think it would also allow things to work if we were ever to change how we forecast.

https://github.com/pacific-hake/hake-assessment/blob/0e1f1446d88245bb41890e81c24180e0965054eb/R/custom-knitr-variables.R#L203-L211

So, I propose the following
```
compareablenames <- names(base.model[["mcmccalcs"]][["rlower"]]) %in% 
  names(prev.assess.recruitment.lower)
recruitment.lower.to.compare <- base.model[["mcmccalcs"]][["rlower"]][compareablenames]
recruitment.med.to.compare <- base.model[["mcmccalcs"]][["rmed"]][compareablenames]
recruitment.upper.to.compare <- base.model[["mcmccalcs"]][["rhigh"]][compareablenames]
```

**Comment by cgrandin** [comment]
That makes sense to me. Some of these things were done quickly so anything that avoids future bugs is great 😊
