### ISSUE TITLE
updating catch-targets-biomass

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#716]
Shouldn't [this](https://github.com/pacific-hake/hake-assessment/blob/master/data/catch-targets-biomass.csv) file be updated? It appears that historical columns are out of date.

**Comment by cgrandin** [comment]
If you have correct info that is great, it should be fixed. I think I just copied the values from the 2015 assessment when I built this in 2016.

**Comment by kellijohnson-NOAA** [comment]
kk, i can update things, just wanted to double check.

**Comment by kellijohnson-NOAA** [comment]
updated realized catch column and added 2020 with 949b471
