### ISSUE TITLE
Change sensitivity plots/tables to use MCMC, and change text values to reflect MCMC values

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#723]
Currently they are still MLE plots.

The text in the sensitivity section and other sections needs to reference MCMC variables instead of MLE for the sensitivities. Some or all of these will have to be inserted into `custom-knitr-variables.R`

This is a fairly large job

**Comment by andrew-edwards** [comment]
We did such plots in 2019 though. But yes, the text will be a bit of a bind.

**Comment by cgrandin** [comment]
To make the index fit plot for sensitivities:

![image](https://user-images.githubusercontent.com/4551051/105138916-6af03780-5aaa-11eb-8071-d7960d99d188.png)

We will need to run extra-mcmc on those sensitivities:

```
build_rds(c("2021.00.23_age1Survey",
                   "2021.00.24_compWeight_HarmonicMean",
                   "2021.00.25_compWeight_Francis"),
          run_extra_mcmc = TRUE)
```

I'm working on the plot (r4ss doesn't have this because CPUE is not reported in the output) so I have to make the plot from scratch. In the mentime you can run this in the background so it's done.

**Comment by andrew-edwards** [comment]
That `build_rds(....)` is still going for me - taken at least 6 hours on my 7 cores (and I thought we had the same laptop?!).

**Comment by cgrandin** [comment]
We’re you working on your computer while they ran? If so it will be slower.
I wasn’t for most of it.

**Comment by cgrandin** [comment]
Happy to say this is done. c7b07472babc8c947e8c1d1ac13c80062b6f97a1 is the commit where the tables were modified. The figures and text were done in previous commits.
