### ISSUE TITLE
What constant catch levels to use for projections?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#729]
Option f in Table g should use 2020 TAC of 475,255 (from Table e), currently uses the 2019 TAC of 597,500. 

![image](https://user-images.githubusercontent.com/6977190/105090058-c8f13080-5a52-11eb-8f93-1ce6bc82ddb9.png)

Changing involves updating the line in `forecast-catch-levels.R`, but then we have to re-order (and edit captions etc.) because this catch option of 475,255 is now less than the option e of 500,000. But then 500,000 is close to 475,255, so should probably change the 500,000. To 600,000?

Also option d (previous year's catch) will change to 379,270 (let's use 380,000).

Summary (x1000 t):
```
2020 values                   2021 suggestions
0                                    0
180                                180
350                                350   (I think there's historical reason for sticking with 180 and 350)
410 (2019 catch)                   380 (2020 catch)
500                                475,255 (2020 TAC)
597,500 (2019 TAC)                 600?? (new constant value not so close to 475,255).
```
For reference, the remaining values are currently:
![image](https://user-images.githubusercontent.com/6977190/105090800-bdead000-5a53-11eb-8431-db447510d1fb.png)

[Not sure why 2021 g and h catches are identical, when I don't think they should be identical by definition - well, they weren't last year - I can look into it].

So the only question is really whether to stick with 500,000 as a constant (but a bit close to 475,255), or bump it to 600 (or something else)? I can make the changes in the code, we just need to decide what the values should be.
 
 The TAC in 2016 was 497,500, and for 2017 assessment we used that and then 600,000. So 600,000 has precedent.

**Comment by aaronmberger-nwfsc** [comment]
What about the following for 2021:
0
180 (reason: historical use)
350 (reason: historical use)
380 (2020 catch)
430 (constant, just because it fills the gap here)
475,255 (2020 TAC)
597,500 (2019 TAC)

So essentially the same as you suggest Andy, but just keeping the 2019 TAC in there rather than moving to 600.  That way there is some meaning to the number, such as "what if we went back to the 2019 TAC" - though I suspect nobody will wonder that so it will act as a higher number in our range.  And then filling that near 100k gap, which is potentially a zone of consideration (i.e., below the 2020 TAC) given the stock trajectory continual decline from last year.

**Comment by cgrandin** [comment]
That makes sense. I offer to be the one to change these and commit.

We will all have to run the forecasts and catch-levels again using `build_rds()` once I fix Issue #730

**Comment by cgrandin** [comment]
Hopefully adding that one row doesn't make fixing the table hellish

**Comment by aaronmberger-nwfsc** [comment]
If it does, let's re-evaluate...

**Comment by andrew-edwards** [comment]
Good idea @aaronmberger-nwfsc , though I have a feeling that in the past we had issues with adding an extra row in table (and figures), so went with replacing where we could. There's still the three non-constant catch values at the end. 

But your idea does fill that 100,000 t gap. Could actually remove 350,000 as it's so close to 380,000 anyway so doesn't really add anything (and would clutter up the figures). Think that may be simpler, and keep the number of policies constant.

**Comment by andrew-edwards** [comment]
@cgrandin - in the commit referenced above (Change forecast catch levels...) you changed the catch levels, but there's not much point us re-running everything until #730 is fixed. (My extra-mcmc's from the other runs are still running). I need to rebase everything, so I may revert your commit and then we can always put it back in later. Else we'll never catch up to you! 

Also, I think we should first agree on the catch values. Thoughts on removing 350,000 (see previous comment)?

**Comment by cgrandin** [comment]
All those suggested are in there now, it turns out that last year I made it really easy to add and remove rows. 350,000 is currently there.

**Comment by andrew-edwards** [comment]
Yes, and the captions seem to automatically upate. I'll re-run today. Keep this Issue open as I'll also update the associated text, which isn't automated and actually needs some thinking.

Also, Aaron and Kelli should give a thumbs up here once they've rerun stuff (today onwards, since #730 also).

**Comment by cgrandin** [comment]
I was happy to see the caption update correctly even with the addition of a new row :)

**Comment by andrew-edwards** [comment]
Great that the tables expand so well. Just looking at them, someone will probably ask why we don't have the non-constant catch values in increasing order:
![image](https://user-images.githubusercontent.com/6977190/105937315-287aad80-600a-11eb-9948-fbe274b94e74.png)

But I think on balance it makes sense to keep them in the same order each year (and it's easier for us). So the first 7 are all constant catch, then the final three are the weird ones. Just wanted to mention it here.

**Comment by cgrandin** [comment]
This all looks good. 350,000 is in there for historical reasons even though it's close to 380,000. I don't think there's anything more to think about here so I'll close it.

@andrew-edwards We should probably keep the order as it has been in other years, even though the catch is out of order: i.e: constant catch in the first 7 rows followed by the calculated rates.
