### ISSUE TITLE
FI=100% management action does not yield median FI of 100%. 

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#730]
Table h currently builds as shown below Row g should have three 100% values in the 50% column (by definition). But the values are 105, 104 and 102. Wondered if it was a NUTS thing but we didn't show this exact table for last year's NUTS run (only the spawning biomass one). Previous assessments have all three as 100%. 

![image](https://user-images.githubusercontent.com/6977190/105091772-34d49880-5a55-11eb-8b23-3019175273e6.png)

**Comment by cgrandin** [comment]
That is calculated by the catch-levels/spr-100 algorithm. I'll look into it. possibly the tolerance needs to be lowered

**Comment by andrew-edwards** [comment]
I just thought of the tolerance, as I remembered the numbers flashing up as it was working. Unfortunately I killed that R window just before thinking of it....

**Comment by cgrandin** [comment]
I can look at this when we decide what to change the catch levels to, and get that all working at once

**Comment by cgrandin** [comment]
I lowered the tolerance of the SPR to be within 0.01 of 1 and got 100, 99, and 99% which is close. If we want to show exactly 100% for all three we will have to lower it further but the SPR calculation routine is working right. It takes a long time to run. See e04c65dd4bafd393e09b7344d017851a29023e94

**Comment by andrew-edwards** [comment]
Did you spot whether it was stopping because of reaching `catch_levels_spr_tol` or reaching `catch_levels_catch_tol`? 

Given I have to re-run anyway, I could set the first (or both if necessary) even lower just to get to the nice 100%. (I know it's good enough, but it will only mean leaving it running for a bit longer). 

I could try:
```
catch_levels_spr_tol <- 0.002  # you had 0.01
catch_levels_catch_tol <- 30  # you had 50
```
Or can you check your actual numbers to see how close to 100% it was? Might help to ascertain what to set the tolerances to.

**Comment by cgrandin** [comment]
It was `catch_levels_spr_tol`. I tried it at 0.01 but that brought it to within 1% of SPR, so two of the value in the table were still 99%. I changed it to 0.001 and they are all 100% now (within 0.1%).

**Comment by cgrandin** [comment]
Last year, it was 0.3! By amazing coincidence the value calculated happened to be within 0.5% of SPR even though the tolerance was 30%.

**Comment by andrew-edwards** [comment]
Love it when (a) you agree with my idea, and (b) have already done it and run it to check!
