### ISSUE TITLE
Table 18 - Annual changes in modeling framework update

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#734]
Some proposed updates to this table include:
- for 2020, change column should say "Add Normal prior for Dirichlet parameters; remove rec devs sum to zero restriction"
- Should the bias adjust column either say "Bias Adjust (MLE)", or should we just get rid of it completely as it doesn't matter given we are using MCMC for all these base models since 2011.
- Add row for 2021 and the Change column could say "change to No-U-Turn sampler for running MCMC" - or something similar

**Comment by andrew-edwards** [comment]
1. - yes
2. - Maybe for this year just put `n/a` and explain why in the caption, which will emphasise how it's the adjustment is not needed now. Then drop the column next year.
3. also MCMC runs for all sensitivity analyses.

**Comment by andrew-edwards** [comment]
Also mention (for 2020) the SS fix, mentioned on pp39-40 last year?

**Comment by aaronmberger-nwfsc** [comment]
Regarding #2, bias adjustment column, it is a bit weird because we have never used that with respect to our base model, which is what this table is referring to (i.e., changes in base model structure), because the base model we present is in mcmc so the bias adjustment setting never plays a role.  This all relates to the craziness of having an MLE and MCMC version of the model presented in the same document (thankfully we are about past that...).   Reporting the bias adjustment for our mcmc base model here is kind of like stating a prior distribution for tagging data - but we don't use tagging data so why even have it there. (bad analogy, I know...).

**Comment by andrew-edwards** [comment]
Good point - so just drop the column then (which I was originally going to suggest then changed my mind!).
