### ISSUE TITLE
Table 17 - Select parameters, derived quantities.... - DM parameters wrong 

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#735]
Looks like log theta_fish and log theta_surv   are now defined differently to last year? 

Base model values are 12,022 and 6,397, compared to -0.164 and -2.246 last year. 

Think it might get fixed automatically, but just noting for now.

**Comment by cgrandin** [comment]
They have different parameter names now, because someone thought it would be a good idea to change them in the SS output. They are `ln(DM_theta)_1` and `ln(DM_theta)_2`

**Comment by andrew-edwards** [comment]
Thanks - that's keeping you on your toes.

Also occurs in Tables 33-35, but they're changing anyway to MCMCs; just mentioning.
