### ISSUE TITLE
Figure 6 (fishing depths of US catch) is missing 2020 data, although those data are in Figures 5 and 7

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#737]
Figure 6 looks identical to last year's version.

Also probably worth including 0 on the y-axes of Figure 6.

**Comment by kellijohnson-NOAA** [comment]
1. [x] Added data for 2020 with df894e42085ac45034c1327bafe8be1b15c3afcc
2. [ ] Fixed axes to have 0
