### ISSUE TITLE
Keep extra details about age-1 survey sensitivity in appendix

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#739]
I'm thinking that we should keep the age-1 index appendix (just like was done last year) given that there is continued interest in that run and is often referred to when thinking about management advice and/or supplementary information about potential recent recruitments.  Others agree?

**Comment by cgrandin** [comment]
Yes I agree. It's also easier technically to keep it as-is

**Comment by andrew-edwards** [comment]
Yes, the SRG didn't explicitly ask for it, but wanted the NUTS results if only base model and this one could be run with NUTS, so on balance it sounds like they would want the appendix like last year. The first few figures may need a bit of updating/work, the rest should be fairly automatic.

**Comment by aaronmberger-nwfsc** [comment]
this is done, of course text edits or whatever welcome when reading through but I think this can be closed now...
