### ISSUE TITLE
Update from team conducting genetic analyses? 

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#741]
We had five paragraphs from them last year (p49), hoping to complete analyses in 2020 for submission of a manuscript. 

Any update? I think @aaronmberger-nwfsc contacted them before?

To go in Response to SRG Review section

**Comment by aaronmberger-nwfsc** [comment]
Email sent to check in with those researchers... I'll update once I hear back from them.

**Comment by kellijohnson-NOAA** [comment]
# 2022 assessment

SRG Request # 6

>The SRG strongly supports the ongoing genetic analyses to determine whether there are genetic differences between Pacific Hake from the area south of Point Conception and coastal regions to the north.

@iantaylor-NOAA sent a G-chat last week about the status, maybe he can update us once he has returned from Annual Leave?

**Comment by iantaylor-NOAA** [comment]
New genetic work by Gary Longo using samples from throughout the US west coast as well as BC, Straight of Georgia, and Puget Sound found the most likely number of clusters was 2 with a single coastal stock and SoG and PS grouped as a separate stock. 

The next most likely number of clusters was 5, but the patterns associated with that scenario were a bit puzzling, with no clear geographic pattern associated with the different groups. Brainstorming at the 19 Nov meeting generated some ideas for Gary to explore associations with different sizes, ages, data sources. While intriguing, this 5-cluster scenario is definitely less likely than the 2-cluster scenario with a single coastal stock scenario, so I don't see any impact of these findings on the 2022 assessment.

I believe that Gary will be actively working on this in the weeks ahead with a goal of publishing something from it, so I suggest you contact him slightly closer to your deadline for a brief write-up of his work in progress--he is expecting to hear from you.

**Comment by aaronmberger-nwfsc** [comment]
Added updated text provided by Ian above and Gary Longo and Melissa Head into the SRG request section.  Closing this for this year.
