### ISSUE TITLE
Completed summary of changes in sampling protocol of age comps as an Appendix?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#742]
See SRG request 5. We did say last year that "A more complete summary of the changes in the sampling protocol over time will be
completed in the upcoming months and included in the 2021 assessment as an appendix.".

**Comment by aaronmberger-nwfsc** [comment]
Kelli and I can have a stab at that one.  We can provide a bit more detail, but we don't have a "complete" summary.  This one we may chalk up to Covid or just say it didn't get done.

**Comment by aaronmberger-nwfsc** [comment]
Kelli, I can take a first stab at this and then I'll send what I compile to your for a look over, thumbs up here means you agree.

Andy/Chris: I forget where we were at with respect to Canada and biological sampling (mainly otoliths) protocols through time.  Can you give a brief update here for shoreside and FT.  I'm thinking like X/fish per haul or every Yth haul for FT and sample goals for shoreside at the docks.  Ideally we would report sampling protocol goals and actual # sampled through time by fleet (though I understand that is a lofty goal).  I seem to remember you saying Chris that the protocols have been pretty stable.

Related to this request is the SRG ask about the sampling differences for fleets that report by haul (US at-sea and FT) versus those that report by trip (shoreside at the dock).  For US side, we have a request out to database stewards to look at this as best as possible (from what I've gathered so far for US trip samples 3 to 5x more fish but also on average conduct 2x as many hauls, i.e., 2 hauls conducted per shoreside vessel trip)

So another question is if we want to get into all these details in a written appendix or just mainly verbally report on progress this year during the SRG (with a brief written reference in the Response to SRG section).  I'm more in favor of this approach given the complexities here and likely not being complete in 10 days.  Thoughts?

**Comment by andrew-edwards** [comment]
Agree to go with it in the Response to SRG section, no need for a full Appendix.

**Comment by aaronmberger-nwfsc** [comment]
Text has gone into the Response to SRG so closing this.  The broader plan (as indicated in the response to SRG) can be our reminder instead of leaving this open and adding a 2022 milestone. So closing...
