### ISSUE TITLE
Wed 27th - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#745]
Mainly to avoid duplicated efforts and conflicts.
And to give us an Issue to close at the end of each day (though given Chris is up so late, I'm not sure when the day 'ends'!).

**Comment by aaronmberger-nwfsc** [comment]
I'll be finishing my text edits to the executive summary section.  I'll put a thumbs up here when done.

**Comment by cgrandin** [comment]
I am going to do the tables that report Sensitivity values. They are still MLEs and need to be median posterior values. I realized overnight that we could also have an additional table for each reporting CIs but maybe that is overkill. Any thoughts on that?

**Comment by andrew-edwards** [comment]
A separate table may be overkill. I once did them as (in Latex notation):  $_{2.5% value} median _{97.5% value}$  which I saw recommended once. Puts the three values in a sensible order, but with the subscripts doesn't clutter things up. Just an idea.

I did try it once but the journal used their style in the main paper, so I had to use their style in my Supp Info (which is a bit more clutterred than the above suggestion): 
![image](https://user-images.githubusercontent.com/6977190/106056013-05e8a300-60a3-11eb-8eb5-022beeb2b80d.png)

**Comment by cgrandin** [comment]
Thanks for the info @andrew-edwards, but I think in this case the width added may just be too much for the one large table. Let's just see if @kellijohnson-NOAA or @aaronmberger-nwfsc have any comment. I have been working this one out all day, it's a beast to convert (`this is last year's table - don't look at the values`):

![image](https://user-images.githubusercontent.com/4551051/106061187-e608ad80-60a9-11eb-8c21-23a4e4e2b02b.png)

**Comment by aaronmberger-nwfsc** [comment]
I think credible intervals for sensitivity table is overkill.  The sensitivity table is for a quick comparison and only reviewer would likely be at all interested in digging into a sensitivity run or two and that's what the SRG week is for.  My vote is to leave those details to explanation (if even needed).

**Comment by cgrandin** [comment]
We can look those values up pretty quickly if asked anyway.

**Comment by kellijohnson-NOAA** [comment]
Less is more :)
