### ISSUE TITLE
Reference point table caption - need clarification

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#746]
The caption reads:
Summary of median and 95% credibility intervals of equilibrium reference points for the Pacific
Hake base assessment model. Equilibrium reference points were computed using 1975–2020 averages for
mean weight-at-age and 1966–2020 averages for selectivity-at-age.

However, when I look at the benchmark settings in the forecast file for selectivity I get -999 -999, which means the benchmark is based on selectivity from the first year (-999) to the first year (-999), or effectively our constant level of selectivity that is used over the period 1966 to 1990 (i.e., prior to t.v. selectivity implementation.  So the caption should read 1966-1990 for selectivity-at-age I think.  @kellijohnson-NOAA  or others, can you confirm that my understanding here matches yours.   I'll make the changes to main doc and executive summary captions once I get a second opinion.

**Comment by kellijohnson-NOAA** [comment]
I will look.

**Comment by kellijohnson-NOAA** [comment]
Yes, @aaronmberger-nwfsc you are correct. The benchmark calcs are based on 1966 for everything except recruitment and the stock-recruitment parameters, those are -999 to 0 (so, 1966 - 2020). I think this was just a mix up, thinking that it was the forecasting specifications.

**Comment by aaronmberger-nwfsc** [comment]
fixed, closed
