### ISSUE TITLE
Working on 1/28

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#748]
I finished my first pass at the executive summary, but see #747 as an outstanding item.  I'm going to go through the one page summary and the research and data needs sections next.

I'm also continuing to work on the discrepancy between the NUTs and MH mcmc runs.  So far it looks like it could be related to a sample size issue (effective sample size for ln(R0) was 1156 (out of 2000) for MH run last year and 3146 (out of 7850) for Nuts run last year.  After doing a randomization simulation experiment, it could be just by chance that median differences are due to the sample size here because of the broad lognormal distributions (needs lots of samples to characterize it); about 10% of simulations resulted in greater differences than what we see (akin to, but don't tell your frequentist/Bayesian brawlers, a p-value of 0.1).  I'm not fully convinced yet though.  It's only a 0.5% difference in the ln(R0) parameter itself but when exp'ed it makes a 7.5% difference in absolute R0.

**Comment by kellijohnson-NOAA** [comment]
I am working on #719, Figure 17 (removing MLE), and fixing text for mcmc sigma_R_info_table

**Comment by andrew-edwards** [comment]
Just getting it building, then I'll pick some main text to have a stab at, and have a think about #747.

**Comment by aaronmberger-nwfsc** [comment]
done with one-page summary and moving to research and data needs section

**Comment by aaronmberger-nwfsc** [comment]
done with research and data sections; I'll move to SRG responses next.  I think Andy your out of there for now, right?
