### ISSUE TITLE
Seems like we have 8250 MCMC samples instead of 8000 for the base model?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#749]
I noticed this while looking into #747. Can simply do:
```
> dim(base.model$mcmc)
[1] 8250  580
> 
```
to verify. Shouldn't the first 250 have been removed?

Checking some of the sensitivity analyses, they seem correct (8000 or 8001, presumably 8001 is just an artefact of parallel chains?):
```
> dim(sens.models.1[[1]]$mcmc)
[1] 8001  580
> dim(sens.models.1[[2]]$mcmc)
[1] 8000  579
> dim(sens.models.1[[3]]$mcmc)
[1] 8001  580
> dim(sens.models.1[[4]]$mcmc)
[1] 8001  580
> dim(sens.models.1[[5]]$mcmc)
[1] 8001  580
> dim(sens.models.1[[6]]$mcmc)
[1] 8001  580
```

**Comment by andrew-edwards** [comment]
If everyone's else's is correct then I think I need to rebuild the rds file.

Early next week we can do a comparison of everyone's .pdf files to look for any such differences.

**Comment by aaronmberger-nwfsc** [comment]
This is correct.  I did the base model run before we made our code changes to ensure ~8,000.  So I ran the base model as warmup=250 and iter = 1000 and I used 11 cores, so 11*750 = 8250.  For the future, this slight discrepancy won't happen b/c we will use our new code.  It doesn't matter for inference, but just so you know where it came from for this year.

**Comment by cgrandin** [comment]
```
> map(sens.models.1, ~{dim(.x$mcmc)})
[[1]]
[1] 8001  580

[[2]]
[1] 8000  579

[[3]]
[1] 8001  580

[[4]]
[1] 8001  580

[[5]]
[1] 8001  580

[[6]]
[1] 8001  580
```

**Comment by cgrandin** [comment]
```
> num.mcmc.samples
[1] 8250
```
