### ISSUE TITLE
Working on 1/29

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#750]
I'm diving into the Response to SRG section to start the day off and then will look into #742 more.

**Comment by cgrandin** [comment]
Table work - `main-tables/main-tables.rnw`

**Comment by andrew-edwards** [comment]
I'm just going to tighten up the one-page summary text a little (it's just over one page!) - thanks Aaron for updating it.

**Comment by andrew-edwards** [comment]
I tightened up the one page summary. Think I'm done for the night.
