### ISSUE TITLE
SRG request for sensitivity run

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#751]
I missed this and was reminded when going through the Response to SRG section:  
The SRG also recommends the following additional sensitivities (conducted if possible
using NUTS, but otherwise using MLE): 
1. steepness,
2. natural mortality,
3. σR,
4. alternative standard deviations for time-varying selectivity,
5. **increasing maximum age for constant selectivity** and
6. downweighting fishery age-composition data.

We didn't do that set of two to three sensitivity runs.  I suggest we don't worry about them in our document.  I'll run them just so we have them.  We can respond if someone actually brings it up.  I don't think we've done those runs since the 2018 assessment because the results never changed.  What we did was we changed age at max selectivity from the base model of age-6 to age-5, age-7, and age-10.

Thoughts?

**Comment by andrew-edwards** [comment]
If you're running them anyway then it's easy enough to add them. Though I'm fine with leaving them out, especially as they never changed results much in the past (and we haven't done them lately).

**Comment by cgrandin** [comment]
I would say add them in. They asked for them and it’s easy to add them. We would just need a couple of sentences in the sensitivity section on it and add them to the tables and plots which is easy

**Comment by aaronmberger-nwfsc** [comment]
models run so closing; new issue assigned to @aaronmberger-nwfsc regarding adding the models and related text

**Comment by kellijohnson-NOAA** [comment]
# 2022 Assessment

>The SRG also recommends continuing to conduct the following sensitivities: steepness, natural mortality, σR, alternative standard deviations for time-varying selectivity, and down-weighting fishery age-composition data. 

- [ ] steepness
- [ ] natural mortality,
- [ ] σR,
- [ ] alternative standard deviations for time-varying selectivity, and
- [ ] down-weighting fishery age-composition data

**Comment by kellijohnson-NOAA** [comment]
What is meant by "down-weighting fishery age-composition data"? And does this mean we can get rid of McAllister-Ianelli and Francis weighting sensitivities? Those are going to be a complete pain in the rear if we are doing them in Bayesian format because they currently each require four or five model runs.

**Comment by aaronmberger-nwfsc** [comment]
I think the down-weighting meant to just use MI or Francis method instead of DirchMult in sensitivity runs, because they both (in the past) resulted in a downweighting of fishery comp data relative to the DirchMult.  I wonder if we can 'tune' the MI and Francis in MLE (with the recruitment bias adjustment set to -1) and just stick with that in the MCMC environment.  I suspect it will not change (much).  But would need to be double checked.  I also think this should be something we discuss at the SRG meeting: do we really need to keep running these extra data weighting methods?

**Comment by cgrandin** [comment]
I thought we and the SRG had agreed a few years ago we don't need to do those those anymore !? Once we went through introducing the DM and subsequently using it standard.

**Comment by kellijohnson-NOAA** [comment]
At a minimum I would really like to take away Francis b/c it is **NOT** recommended when time-varying selectivity is present.

**Comment by andrew-edwards** [comment]
I think we can drop Francis given what Kelli said (which we mentioned last year). Also, we found last year:
![image](https://user-images.githubusercontent.com/6977190/149225982-92392c30-5a37-47d9-85f1-02aea91e81f5.png)

so this isn't what they are referring to (as Francis increased the weighting of the age comps, not decreased).

So in 2021 assessment we had this response (p49) to this 2020 SRG meeting request:

![image](https://user-images.githubusercontent.com/6977190/149226110-c8120876-2612-4373-adff-dec5ba59a7f9.png) 

etc.

So it's more complex than just tweaking a parameter. We can look into it more, but it sounds tricky.

So I think we can drop MI and Francis, given they weren't explicitly listed by SRG (and Kelli's point), and the downweighting thing looks to be something different (and more complicated).

**Comment by kellijohnson-NOAA** [comment]
- [ ] edit text regarding how MI is now run and removal of the Francis weighting to https://github.com/pacific-hake/hake-assessment/blob/62c93a9749cb2cf367511450def94261511d0881/doc/assessment-section/assessment-section.rnw#L1735-L1758

**Comment by aaronmberger-nwfsc** [comment]
I added a sensitivity run to our readme file related to the SRG request for a sensitivity that investigates the lack of age data in 2020 and 2021 in Canada (similar to analysis we did last year for 2020 only data). I'll also add a check box above.

**Comment by kellijohnson-NOAA** [comment]
@aaronmberger-nwfsc do you think we should look at just removing the freezer trawlers like we did before or I was also thinking it might be good to just run the model with only US ages to see the value of Canadian fishery ages in total.

**Comment by aaronmberger-nwfsc** [comment]
Good question - perhaps we 1) remove all Canadian fishery ages to get an idea of an overall value as you say, and 2) just Canadian age data from 2020 and 2021 b/c that is realistic of where we are at today (even though there were a few ages those years).  My guess is that this will show that a year or two isn't a big deal, but complete loss will have impacts.

However, this requires going back to the drawing board with respect to aggregating fishery comps.  Is that a time intensive process/burden?

Just FYI - this topic came up in MSC (Marine Stewardship Council), and related, meetings yesterday and this is on the fishery certification process boards minds.  They mentioned talking to Bruce T. about it when they met with Canadians.  I suspect the fishery is going to have a voice on bio sampling this coming year (if not already).

**Comment by kellijohnson-NOAA** [comment]
kk lets discuss this further in #849
