### ISSUE TITLE
Download the MCMC retrospectives and RDS file

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#754]
The NUTS `2021.00.04_base_v1` retrospectives finally finished. It was about 6 days runtime. Some of them took only 4 hours but a couple of them (-6yrs and -9yrs) took 24 hours each. The rest were somewhere in between. Here they are:
https://drive.google.com/file/d/1TvYLxh3sDpAwLi7VZY9IQ5CNoFxQhQzA/view?usp=sharing

You'll have to run this to refresh the RDS data for the base model (this took 96 minutes to run):
`source("R/all.R");build_rds()`

If you don't feel like running it right away, I put mine on the Google drive. This is getting ridiculous, this one file alone is over 1GB:
https://drive.google.com/file/d/18lpKqwe5HK9Ibb4DOYE1qZuRRY7crmxo/view?usp=sharing

It looks like this Hake JTC drive is on @iantaylor-NOAA's account. Ian, how is your space? Have you purchased extra and are you OK with hosting these files? Do we need to acquire funds for a generalized drive somewhere or to continue yours?

**Comment by aaronmberger-nwfsc** [comment]
Yep, my 500 GB laptop is overflowing in large part due to hake assessment.  Every year I have to do a major file cleanup after JMC meeting.  Size and run times are something we should think about and discuss with SRG.

**Comment by aaronmberger-nwfsc** [comment]
Just to keep track, check when you've done performed these downloads:

- [ ] Aaron
- [ ] Chris
- [ ] Kelli
- [ ] Andy

**Comment by andrew-edwards** [comment]
We need a qualifier somewhere in the doc to mention the extra 'efficiency' of NUTS!

**Comment by kellijohnson-NOAA** [comment]
I believe NOAA google drives are unlimited.

**Comment by aaronmberger-nwfsc** [comment]
everybody downloaded so we can close I think...
