### ISSUE TITLE
tonight and tomorrow - working on:

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#756]
I'm going to be going through section 3.4 text tonight and into tomorrow if need be...

**Comment by andrew-edwards** [comment]
I've done a couple of my minor assigned issues. Off home now. May work tonight but my eyes are shot....

**Comment by aaronmberger-nwfsc** [comment]
I'm also working on #758  and #759 tonight and tomorrow AM

**Comment by kellijohnson-NOAA** [comment]
Sorry for lack of commits the last two days, I have been trying to get the Laplace approximation to work for the hake model. Good news, it works now and the estimate is similar to other methods. Sorry for my absence and thanks for being patient. I will find something productive to do now.

**Comment by cgrandin** [comment]
I am working on #462 and #761 currently
