### ISSUE TITLE
Download 4 sensitivity model files from google drive

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#757]
You need to download four more sensitivity model files from the google drive and then run the below build_rds().  These are:
2021.00.40_MH_mcmc
2021.00.43_maxSel_Age5
2021.00.44_maxSel_Age7
2021.00.45_maxSel_Age8

 - [x] Aaron
 - [x] Chris
 - [x] Andy
 - [x] Kelli

I will make additional issues related to things to do with these.  This issue is just to ensure everyone downloads them.  I'm guessing we will have to also run:
build_rds(c("2021.00.40_MH_mcmc", "2021.00.43_maxSel_Age5", "2021.00.44_maxSel_Age7","2021.00.45_maxSel_Age8),         run_extra_mcmc = TRUE) - is this correct Chris?

**Comment by aaronmberger-nwfsc** [comment]
Or, actually, do we need the run_extra_mcmc=TRUE?  Or just do build_rds(c("2021.00.40_MH_mcmc", "2021.00.43_maxSel_Age5", "2021.00.44_maxSel_Age7","2021.00.45_maxSel_Age8))....?

**Comment by aaronmberger-nwfsc** [comment]
Ok, clarifying:  this is what I've done for building rds files on these:

build_rds(c("2021.00.43_maxSel_Age5", "2021.00.44_maxSel_Age7","2021.00.45_maxSel_Age8"))
build_rds(c("2021.00.40_MH_mcmc"), run_extra_mcmc=TRUE)

I did no extra mcmc on the first three b/c the sensitivity plots don't need it
I did do the extra mcmc on the MH run because we likely will need it.

**Comment by cgrandin** [comment]
We only need the extra MCMC if we need to plot the survey index fits
