### ISSUE TITLE
Add maxSel_Age sensitivity figure and brief text in sensitivity section

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#758]
Add the usual suite of 4 sensitivity plots that compare base model to the three maxSel_Age sensitiviity runs (i.e., comparing models 4, 43, 44, and 45).  This includes updating model setup files and adding some text related to these in the sensitivity section.

**Comment by aaronmberger-nwfsc** [comment]
Also we need to add these to our adnuts diagnsotics build - @andrew-edwards - do you want to do that?

**Comment by aaronmberger-nwfsc** [comment]
Done adding figures and text for this in 47bcb94c508895478bcae40363593e86dcdf698e; so leaving this open for Andy to add these runs to his adnuts diagnostics code

**Comment by andrew-edwards** [comment]
Ooh, I did this already!
