### ISSUE TITLE
Add MH mcmc run (40) as an appendix

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#759]
Add sensitivity run, 2021.00.40_MH_mcmc, as an appendix that compares to the base model.  Easiest would be to just use the adnuts appendix already built, comment out previous intro text and adapt to essentially be the reverse (Nuts the base and MH the sensitivity). I don't think we need much explanation, just show the figures with a few sentence summary (like the age-1 survey one).

**Comment by cgrandin** [comment]
**Important** - Make sure all chunks that produce figures have `is.fig = TRUE` in the chunk header or the doc will fail to build. Like this:

![image](https://user-images.githubusercontent.com/4551051/106591874-a3a8fb80-6503-11eb-8891-ca54daf3ca6b.png)

**Comment by aaronmberger-nwfsc** [comment]
Just an FYI - I reducing the random walk MH appendix to not follow the executive summary format (just commenting out), but rather keep it more like a set of sensitivity runs and diagnostic plots.  Last year it seemed appropriate for NUTS b/c we were planning on using it this year.  This year the rwMH is simply a sensitivity run and IMO has no chance of being actually used to base management decisions upon (i.e., thus no need for full executive summary).  The age-1 survey I think is still appropriate for a full executive summary like format.

**Comment by cgrandin** [comment]
That’s a good call, and makes it much simpler.
