### ISSUE TITLE
Wednesday 3rd - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#765]

**Comment by cgrandin** [comment]
I am finishing up the -as-age MCMC tables and running retros 9 and 10

**Comment by andrew-edwards** [comment]
Aaron - looks like you're partway through editing 3.4.2 (Assessment model results) and I presume you want to carry on with those.
I can do 3.5 (Model uncertainty), 3.6 (Reference points) and 3.7 (Model projections).

**Comment by kellijohnson-NOAA** [comment]
I am in 3.3

**Comment by aaronmberger-nwfsc** [comment]
Sounds good, I just pushed my final 3.4 edits.  I'll then jump ahead to 3.8 (see if I can add anything) and then do 3.9.

**Comment by kellijohnson-NOAA** [comment]
pushed 3.3, i am going outside for a bit. let me know if there is a specific section that anyone wants me to look at, otherwise i will just try and knock off issues (including documenting the squid plot thing).

**Comment by aaronmberger-nwfsc** [comment]
I have not looked at anything in section 1 (introduction - probably not much to change if any) or 2 (data - there will be changes needed in here but probably not any sweeping changes).

**Comment by aaronmberger-nwfsc** [comment]
I'm moving to the Introduction section...

**Comment by andrew-edwards** [comment]
I'm going to add some alt text to the main figures.

**Comment by andrew-edwards** [comment]
Done them but committing in the morning....
