### ISSUE TITLE
Notation in tables 26 & 27 is inconsistent (also 32-34).

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#768]
I think the notation should be changed back to what it was last year in the parameter estimation tables . I started doing it in table 26 (will push the commit) to make it consistent with 27, but see it's in the longer tables also. I'm guessing things got shortened because of the wide tables (@cgrandin ?). 

But it now introduces new notation that's confusing (B_F_40%) and not used elsewhere I think.

I think we spent a lot of time standardising it all one year, so best not to change it. Sorry, I should have checked first why it got changed this year. I can have a go at fixing it all.

**Comment by cgrandin** [comment]
These all look good to me, so I assigned you @andrew-edwards to finish up what you were doing or close it if you're happy with these. I just changed them to say they were now MCMC.
