### ISSUE TITLE
Alt text - the map Figures 2 and 3 don't have knitr hooks, which messes up the alternative_text.csv

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#770]
The two map figures are hardwired so don't have the knitr alt.text hooks.

I'll just easily add in a pdftooltip for each. The alternative_text.csv file will then need adjusting, probably by adapting the function to sneak them in. The Figure numbers are off because the function doesn't know about the map figures.

I'm not sure that Stacey does really need the .csv file, now that she knows the alt text approach works? So suggest not to worry about this too much for now.

**Comment by cgrandin** [comment]
That's what I had planned, and we can just start the figures at 3 in the function to correct for it if necessary

**Comment by andrew-edwards** [comment]
Closing. We just have to do Chris's suggestion if Stacey still wants the .csv file. I'll send her a quick email to ask.
