### ISSUE TITLE
Fixed the MCMC diagnostics test plot

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#771]
This was quite the task. I see now why I left it there all these years..

You will need to download the base model RDS file:
https://drive.google.com/file/d/1DCEofSPlqoQHRQpaEaH8LrWoOqKYtI-8/view?usp=sharing
and the 2021.00.40_MH_mcmc RDS file:
https://drive.google.com/file/d/1iXd32_c-abiXLAnDxM4g0UUgtmUplHR0/view?usp=sharing

These have a list called `post_names` which had to be added during the `build_rds()` process. This is a list of the names of the posteriors in the MCMC posteriors.sso file and is needed by the `plot_mcmc_param_stats()` function which is what makes these plots.

I didn't modify the `r4ss` version `mcmc.nuisance()` because it requires the directory of the MCMC and the filenames as arguments and changing that is too major a modification for people who may rely on the code. I just re-wrote the function which is located in a new file `R/figures-mcmc-param-stats.R`

I added a color option and made it blue with transparency. It's easy to change but it's nice to look at.
See commit 02e2f50ad8a41ebe8a4d254d3bc2a5e90a892b4e for details

**Comment by andrew-edwards** [comment]
Downloaded:
- [ ] Kelli
- [ ] Aaron
- [ ] Andy

**Comment by andrew-edwards** [comment]
This change also means that the adnuts-diagnostics pdf won't build, because the other runs don't have `post_names` defined. 

Not to worry for now (I don't need to rebuild it and it won't change), but just mentioning it in case anyone tries. [My rwMH one didn't build, but that's because I hadn't downloaded the new .rds, though my file is 4:10pm yesterday].

**Comment by cgrandin** [comment]
Right.. you could easily run build_rds() and all of them would then have it, but that takes time

**Comment by aaronmberger-nwfsc** [comment]
I spent quite a bit of time yesterday looking into alternative ways of showing "residuals" for Bayesian models.  There are lots of options that look super cool (tidybayes, for example) but none looked super easy to implement quickly for this year and/or would not easily fit into a age/year composition matrix like our current one does.  Something to think about for the future.  I also noticed that in the ShinySTAN call within our adnuts code -- launch_shinyadmb(nuts.updated) -- you can build sample Latex code that extracts all the main diagnostic summaries for all parameters and puts them in a table.  Maybe an appendix thing for next year?

**Comment by aaronmberger-nwfsc** [comment]
Bayesian purists would gawk at our frequentist-based residual plots though, so just be prepared...  :wink:
