### ISSUE TITLE
Thursday tasks

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#772]
I'm finishing looking over the Intro section to start

**Comment by andrew-edwards** [comment]
Morning. I'm going to finish all the alt-text, then finish section 3.7 Model Projections.

**Comment by andrew-edwards** [comment]
So I had two sets of conflicts, but the ones with Chris were only because we'd changed adjacent lines of code. 
I hadn't appreciated that git still forces you to check those manually, since functions can run over several lines and something might have got messed up (thanks for clarifying, Chris).

**Comment by aaronmberger-nwfsc** [comment]
I'm finished with my first pass through the introduction section, BUT there is still Canadian fishery relevant sections that are not completed/checked (1.3.2 and 1.4.1 Canada)

**Comment by andrew-edwards** [comment]
Doing #681 by making the bubble plot figure use MCMC.

**Comment by andrew-edwards** [comment]
Done the above. I'm here for about half an hour more. Going to fix some of the ** in the figure captions.

**Comment by andrew-edwards** [comment]
Am done for the night. Will do remaining three ** in fig captions tomorrow.
