### ISSUE TITLE
Clean up MCMC summary histogram plot

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#773]
When calling plot_mcmc_param_stats, we should omit the 'iter' and 'objective function' columns (defaults created from posteriors.sso and derived_posteriors.sso and carried through) when making the summary histogram plot because they are meaningless and create unintended oddities in the figure.  

Chris probably already has this fixed in the time it took to write this issue.

**Comment by cgrandin** [comment]
Download base model RDS again to have this change or run the following:

```
tmp <- readRDS(here::here("models/2021.00.04_base_v1/2021.00.04_base_v1.rds"))
tmp$post_names <- tmp$post_names[!tmp$post_names %in% c("Iter", "Objective_function")]
saveRDS(tmp, here::here("models/2021.00.04_base_v1/2021.00.04_base_v1.rds"))
```

**Comment by cgrandin** [comment]
And the same for the 40 model, you need to download again

**Comment by andrew-edwards** [comment]
@cgrandin - the 40 is the one that didn't work, yes? It says last updated 31 Dec 1969. Day 0 .
