### ISSUE TITLE
Suggest we change the Overview of fisheries heading levels

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#775]
It looks like this now:
![image](https://user-images.githubusercontent.com/4551051/106978603-66b25400-6711-11eb-9a37-83c489174abc.png)

I was thinking we could make the **Fisheries** section have two subheadings like the **Management** section does, one for each country. We could merge the **Fisheries** section and the **Overview of the fisheries in 2020** section into the main **Fisheries** section and make subheadings for the countries. As it is now there are bolded headings for the coutries but they do not appear in the TOC bar. 

The reason is that I click those all the time and then have to scroll to find Canada. Also it would make a more standardized document. I will do it if you all think it's a good idea.

**Comment by aaronmberger-nwfsc** [comment]
I'm fine with whatever you think works best.  I have noticed that U.S. and Canada bold but not linked subsections before and just thought oh well.  It would be nice to have headings/subheading all standard.  

Another thought I've had is having subsections in the Table and Figures as there are so many.  Figures could be separated by data, base model, sensitivity and retrospective sections, for example.  But that can wait until another time.

**Comment by cgrandin** [comment]
That’s a good idea with the tables and figures. Quite often there’s a lot of scrolling to find one. At least for me

**Comment by andrew-edwards** [comment]
I don't mind about the thing at the top of the issue as I never use it (I just use a simple Sumatra pdf reader and ctrl-f to search), so whatever looks good.

I'm also often scrolling through the figures, but I'm not sure if subsections would really help so much. (I guess if you have that panel thing open). I do like the main Table of Contents just being on one page though (followed by the Appendices TOC), so it'd be nice to keep that if possible.

**Comment by aaronmberger-nwfsc** [comment]
Are we still doing this or should this just move to either 1) final 2021 version or 2) 2020 milestone?

**Comment by cgrandin** [comment]
Maybe 2022...

**Comment by andrew-edwards** [comment]
Yes to 2022. Don't want to mess too much inbetween submission and final version.

**Comment by andrew-edwards** [comment]
Move to 2023? 'want' rather than a 'need', and may have unintended side effects at this late stage.

**Comment by kellijohnson-NOAA** [comment]
If I do  under 
```
\section{Figures}
\subsubsection{Data}
```

I get
```
8 Figures
8.0.1 Data
```
and the table of contents stays as is. Though I am getting an extra blank page between the tables and figures.
![image](https://user-images.githubusercontent.com/4108564/214619150-12ce4616-259e-4924-a517-f05c4b4bce3a.png)

**Comment by cgrandin** [comment]
Should be `\subsection{Data}` not `\subsubsection{Data}`

**Comment by kellijohnson-NOAA** [comment]
I don't want it in the table of contents though so maybe there is something that I can add to `subsection{Data}` that removes it from the table of contents?

**Comment by cgrandin** [comment]
Why not have it in the TOC? It would be nice to be able to click the figure section from the left panel

**Comment by cgrandin** [comment]
But the thing I would try next is this, I have no idea what it will do though
```
\section{Figures}
\subsection{}
\subsubsection{Data}

**Comment by kellijohnson-NOAA** [comment]
@cgrandin your suggest gives me
![image](https://user-images.githubusercontent.com/4108564/214652574-ccfc0439-f92e-4113-8667-6603846189fd.png)
I also tried it using
```
\section{Figures}
\subsection*{x}
\subsubsection{Data}
```
gave the same thing.

**Comment by kellijohnson-NOAA** [comment]
I think the best option is to use \subsection{Data} and have to table of contents be longer than one page. @andrew-edwards are you okay with this?

**Comment by andrew-edwards** [comment]
Yep, I never use what's in Chris's screenshot at the top. And with the Appendices TOC not on it's new page, we still have just two pages. All good (providing the new subheadings don't take up too much room and mess up figures and tables, but looks like you've done them small anyway).
