### ISSUE TITLE
All upload hake-assessment.pdf at some point to compare them

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#776]
To make sure we all have the right runs etc. 

Wait until retros are all finalised and the figures updated, and then pick a commit number. So maybe Friday afternoon or Saturday? I can compare them.

**Comment by aaronmberger-nwfsc** [comment]
And noting to cross check #641 regarding spacing issues if needed...

**Comment by andrew-edwards** [comment]
Worth doing a comparison this afternoon? Never resolved that spacing issue (which does mess up things when we hardwire stuff near completion, so would be worth a quick look). Else tomorrow is fine, I need to read rather than format!

**Comment by andrew-edwards** [comment]
Can we pick a time for today and I'll do the comparison. Maybe just before Superbowl starts (whenever that is)?

**Comment by andrew-edwards** [comment]
Aaron said upload at 2pm. Let's pick a commit just before then.

**Comment by cgrandin** [comment]
I’m going to the gym at 2 so that’s perfect

**Comment by andrew-edwards** [comment]
Was typing this then I went to the Google Drive to suggest where to put it, and say you've already done it!!! I didn't check Slack!

"Want to do this now as it's coming up to 2pm? Last commit that was pushed is `8c1a8ec2`. Maybe push anything you have now and we'll use those?

Save as `hake-NAME-HASH.pdf` where HASH is first four characters of the commit. e.g. `hake-andy-8c1a.pdf`. Then save on Google drive at ....."

**Comment by cgrandin** [comment]
Look at the commit code in ours, and use that one! I’m out the door for awhile!

**Comment by andrew-edwards** [comment]
Chris will presumably submit as he has to add the pdf Tagging in Adobe, so I compared everyone's to his. 

Good news is that other than the minor details below everyone's figures and tables and text are identical (amazes me every year, even though it shouldn't!).

Our Fig 1 maps are all slightly different, but Chris's is best so no worries. 

I still have that spacing difference after headings, but that's fine. Because of that I'd put in a `\clearpage` before Data section (on mine it was the end of the page and the footer needed fixing), which I'll take out.

Only thing maybe worth fixing on Chris's is Table F.1 has an extra page with nothing on. Can wait until after submission though, as it's a fiddly `longtable` thing I expect.

Compared to Chris's, Kelli's
 - has missing credible limits (shading) on Fig i (and identical 34) and G.9
 - R version (p47) is "Under development (unstable) (2021-01-05 r79797)"
 -  that one creates an extra line making it hard to compare the rest of the main text
 - Fig 1 map "Newport Beach" is moved up but the line goes over "Santa Barbara"
 - Fig 33 posterior is missing the dark shaded area
 - Fig G.5 missing grey shading (but Fig e is fine?!)

Compared to Chris's, Andy's
 - has slightly different spacing after heading again (the Issue that Aaron
 referenced), which shifts text making  it hard to compare text.
 - Fig 1 map "Newport Beach" fits in the same column as the others (presumably
 the different space available after the main section heading)
 - Table F.1 has one entry in its final page, whereas Chris's has an extra page
 with nothing on (I know that's to do with longtable, maybe don't worry about for now).
 - page numbers become slightly off after a while

Compared to Chris's, Aaron's
 - Table 3 caption has the text from the next commit already in there (don't worry)
 - Fig 1 map "Newport Beach" fits in the same column as the others (like
 Andy's), some other text moves around slightly

**Comment by cgrandin** [comment]
Look at the footer on the very last page of mine... weird

**Comment by andrew-edwards** [comment]
That is weird - I didn't go through all the control files (just the first few pages, figured they were good) so didn't see that. Ours are all correct though!

**Comment by andrew-edwards** [comment]
It can be a test to see if anyone reads to the end of the document.....

**Comment by cgrandin** [comment]
It’s the first thing I did,
See if they have the same number of pages

**Comment by kellijohnson-NOAA** [comment]
Regarding the footer, sometimes when I do pdflatex from the command line just once, instead of multiple times, some of the links to sections will automatically take you to the Figure section rather than to the section it should go to. So, maybe the footer issue will go away if you pdflatex it again?

**Comment by andrew-edwards** [comment]
Not sure why that would happen. I never clean everything up (don't tell Chris) because then you have to run it a few times to get all the references etc. correct. For a final version I just bibtex and then pdflatex multiple times to be sure... Chris fixed the footer anyway.

**Comment by andrew-edwards** [comment]
We can close this. Chris's fixed two minor things on his .pdf, and I'll deal with pesky #641 some time.
