### ISSUE TITLE
It's Friday...

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#778]
Morning. I'm going finish up the three figures with ** in the captions (make residual plot Fig 19 MCMC, and two minor ones).

**Comment by aaronmberger-nwfsc** [comment]
I love that anyone tracking this github see's "issues" that say "It's Friday...", which normally would imply "let's meet at the pub at 4PM!".

Sadly no, so I'll be going through the data section as I haven't looked at that at all really yet (at least in continuum).  And I really like your ** Andy as a way to specifically call attention to spots that might otherwise have been skimmed over and missed.

**Comment by cgrandin** [comment]
Good morning, home stretch...
Aaron we can still have a beer later 🍻 

I need to get the cohort table switched to MCMC, this will mean another download of the base model RDS at some point later. 
Also I will upload the last retrospective shortly and see where the output for age1 retrospectives is and get that finished up.

**Comment by andrew-edwards** [comment]
Residual plot Figure 19 - is it already MCMC? I'm going down a rabbit hole and I suspect some else will have an answer. Basically `make_age_comp_pearson_plot()` uses `model$agedbase`, but I can't find whether `...$agedbase` is MLE or MCMC median. 

From the README I see
```
model$extra.mcmc$agedbase$Exp         - median of posterior for expected value for age comps
model$extra.mcmc$agedbase$Pearson     - median of posterior for pearson residuals for age comps
```
and tried both of these in `make_age_comp_pearson_plot()` but no joy. Could make a separate issue but thought someone may know off the top of their head.

**Comment by aaronmberger-nwfsc** [comment]
That's where I got to the other day and gave up - maybe Kelli or Chris know?  If we have to add this to mcmc list then let's just forget about it for this year.  We still have all the diagnostics anybody would ever want through the shiny app if reviewers want to see more.  However, I do think people like to see the residual by cohort in Figure 19.

**Comment by aaronmberger-nwfsc** [comment]
Thinking more about this - if SS_output is called relative to an mcmc directory and then SS_plots is called to make the bubble residual plots then I'm guessing it is based on MCMC output, though I don't know for sure.

**Comment by andrew-edwards** [comment]
@aaronmberger-nwfsc - regarding the ** it's something I get on with while you're all doing some early SS runs, as I don't know the details of SS and can't really help much in that aspect!

**Comment by andrew-edwards** [comment]
Moving onto #768, fixing some notation.

**Comment by cgrandin** [comment]
model$agedbase$Exp is what you want I think. It's calculated in extra-mcmc.R using the all the 8100 comp report files.

![image](https://user-images.githubusercontent.com/4551051/107073046-b50c3500-679b-11eb-96ab-531161106a90.png)

**Comment by cgrandin** [comment]
I am working on this function now so let me know if you need to add anything and I can do that while in there

**Comment by andrew-edwards** [comment]
I tried `base.model$extra.mcmc$agedbase$Exp` above, but it failed because of the structure. I see it's values are different to `base.model$agedbase$Exp` but the structure looks the same:

```
> summary(base.model$agedbase$Exp)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.001164 0.009990 0.026845 0.066667 0.060927 0.745279 
> summary(base.model$extra.mcmc$agedbase$Exp)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.001098 0.010260 0.026843 0.066278 0.060670 0.748214 
> length(base.model$agedbase$Exp)
[1] 885
> length(base.model$extra.mcmc$agedbase$Exp)
[1] 885
```
Am thinking someone else can do this quicker than me.... [and, yes, I knew I should have made a new issue - thought it might be a quick one, as if....]

**Comment by andrew-edwards** [comment]
I'll now fix the final ** in the exec summary and main text....

**Comment by cgrandin** [comment]
All my cores are being used now, but I can look later

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards I just made the pearson figure using the extramcmc, what error were you getting?

**Comment by andrew-edwards** [comment]
I'm going to print out what we have and take a read through and then later make any edits. (My assigned issues #731 #732 require less brain power).

**Comment by andrew-edwards** [comment]
Just fixing the missing reference points table in exec summary....

**Comment by andrew-edwards** [comment]
@chris - I don't think we need the longtable option for these smaller tables? I think that's what's breaking it (also to do with maybe the usual forcing of the position). Is the usual form of
```
tabular.environment = "longtable"
```
just
```
tabular.environment = "tabular"
```
?

**Comment by cgrandin** [comment]
Yes go ahead and change. Also if there's no `latex_continue()` in the `addtorow` stuff, it should not be a longtable.

**Comment by andrew-edwards** [comment]
Can I just go back to the old version of it? We hadn't touched it for years! 
![image](https://user-images.githubusercontent.com/6977190/107089087-e0e6e500-67b2-11eb-85ad-98da44d60b6a.png)

**Comment by andrew-edwards** [comment]
I just grabbed the old version (and kept the new one). Pushing shortly, just going to fix some of the formatting of the main tables. Just need a few \clearpage 's to force tables to start on a new page (else some of the short ones get split over pages, but there's no need (and doesn't really save space).

**Comment by cgrandin** [comment]
I made lots of improvements to tables over the years, make sure the code is the new code!

**Comment by andrew-edwards** [comment]
I went to the version before you started changing it January (see screenshot above). Just checked and table looks the same as last year except for the updated numbers (and one notation addition).

**Comment by cgrandin** [comment]
Ok just checking that we aren’t moving any code backwards, thanks for checking!

**Comment by cgrandin** [comment]
I may have gotten “handsy” when adding the longtable stuff 😂

**Comment by andrew-edwards** [comment]
I checked out the old version, copied the function, checked out master, pasted old version in and called it ....old(). And wrote a comment to that effect ;)

**Comment by andrew-edwards** [comment]
Just going to fix the formatting on p15 (paragraph runs off because figure and table are fighting for space).

Then I think I'll finally print out and take a read.

**Comment by andrew-edwards** [comment]
Others have this on p15, yes?
![image](https://user-images.githubusercontent.com/6977190/107096591-f6164080-67bf-11eb-8865-e54c14da0635.png)

Think best thing is to put Figures f and g onto the same page (I think they were a few years ago), especially as Figure g gets referenced on p13 (two pages earlier than it appears).

**Comment by aaronmberger-nwfsc** [comment]
not in my current build, but I haven't built the doc since this AM

**Comment by andrew-edwards** [comment]
@cgrandin - the `tabular.environment = "tabular"` doesn't work, and `longtable` ignores placement options (`tbp` etc.) because doesn't let it float (and I think wants to put it at the top of the page; R is spitting out a warning). 

Anyway, I've fudged it to get Figure g and Table e on same page with space inbetween, like last year, so no worries at all.

**Comment by andrew-edwards** [comment]
Just had a careful read through the one-page and exec summaries. Looking good! 

I have some minor edits that I'll type up now.

**Comment by andrew-edwards** [comment]
Did my one-page edits. Done for the night, will do exec summary tomorrow then read the rest of the text.
