### ISSUE TITLE
Saturday fun....

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#783]
I'm doing edits on Exec Summary.
Chris is working on the updated .rds file.

**Comment by andrew-edwards** [comment]
Am done with Exec Summary for now. Going to sit and read the main text, figures and tables.

**Comment by aaronmberger-nwfsc** [comment]
I'll can work on #739 once those are retros are uploaded.

**Comment by andrew-edwards** [comment]
Doing some edits to Introduction and Data sections (1 and 2 in main text).
