### ISSUE TITLE
Need to rerun base model and age-1 survey rds files to make new forecasts

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#785]
We had to update the US TAC value (it was incorrect) and thus the coastwide TAC value for 2020.  This means we have to rerun the rds files for the base model and the age-1 survey (those models that make decision tables).  I suggest the following:

Chris re run the base model and upload rds file to the drive.

Aaron re run the age-1 survey and upload rds file to the drive.

Then we can download the updates. 

Aaron will check the document for related text changes (values should all be automatic).

**Comment by aaronmberger-nwfsc** [comment]
Chris, is there a shortcut to just rerun one of the forecasts (scenario f)?

**Comment by cgrandin** [comment]
The age1 model need the dynamic catch levels done as well:
`source(here::here("R/all.R")); build_rds("2021.00.23_age1Survey", run_catch_levels = TRUE, run_forecasts = TRUE)`

To re-run the base model forecasting with the new TAC which is in place (no need to re-calculate the dynamic catch levels):
`source(here::here("R/all.R")); build_rds("2021.00.04_base_v1", run_forecasts = TRUE)`

**Comment by andrew-edwards** [comment]
Regarding text, I put a bit in the Exec Summary about the 2022 probs of being below a ref point going down when catch goes up, but (thankfully) only referred to the 430,000 scenario, so that should be good.

**Comment by cgrandin** [comment]
The forecasting is fast and will just run them all concurrently so it doesn't matter.

**Comment by aaronmberger-nwfsc** [comment]
Ok, I've got the age-1 running now.

**Comment by aaronmberger-nwfsc** [comment]
I'm getting the following error:
> build_rds("2021.00.23_age1Survey", run_catch_levels = TRUE, run_forecasts = TRUE)
Error in str_split(tmp, "[:space:]") : 
  could not find function "str_split"
Called from: signalConditions(obj, exclude = getOption("future.relay.immediate", 
    "immediateCondition"), resignal = resignal, ...)

Unless somebody knows how to fix this right away, I may suggest that someone else just try to run the age-1 lines.

**Comment by andrew-edwards** [comment]
Looks like it's from the `stringr` package.

**Comment by andrew-edwards** [comment]
Give me a sec

**Comment by andrew-edwards** [comment]
After running `all.R` the function is there (`stringr` is not listed in `all.R` but is presumably a dependency).
I'm heading home but will start running it then.....

**Comment by cgrandin** [comment]
I fixed it locally and started running the age1 about an hour ago so if you don’t feel like doing it it’s on the way

**Comment by aaronmberger-nwfsc** [comment]
Great, I'll hang tight, thanks Chris.

**Comment by cgrandin** [comment]
With so much going on and the fact that it took 2 seconds to fix I forgot to tell you about that error, so my bad on that one

**Comment by cgrandin** [comment]
This is done, check box when download complete:

- [ ] Aaron
- [ ] Andy
- [ ] Kelli
