### ISSUE TITLE
Make it so that the RDS file can have parts re-loaded individually

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#786]
When we have to run only one forecast after the fact, or only the extra-mcmc changes a little, we should be able to just read in the RDS we previously built, modify it and write it back out.

This would save a load of time that it takes to construct the whole thing for only a small change.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin can we close this issue given that now you have the rds building so smoothly or should we assign it to 2024?

**Comment by cgrandin** [comment]
Thanks, I'll close it. We have a much faster build now so this is moot
