### ISSUE TITLE
Table e and Table 3 - Caption needs to define "-"

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#787]
The caption of Table e and Table 3 (same table) doesn't define what the dash means. Should be I put "A dash (--) indicates that the management target was not known."

**Comment by cgrandin** [comment]
That's what it means for Canada...

**Comment by aaronmberger-nwfsc** [comment]
I don't think Table e needs any further explanation b/c there are no dashes (all recent year), but Table 3 definitely does. I suspect it is a mix of "we just don't know" and "nit ever was specific explicitly".  If we don't know which is which how about we just say something like:
"The dashes (-) indicate where catch target information was either not specified or was unavailable at the time of this assessment."
