### ISSUE TITLE
Age 1 model has outlier recruitment for 2015

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#788]
![image](https://user-images.githubusercontent.com/4551051/107142852-71721200-68e6-11eb-8ace-a30e603bd204.png)

I checked and it is correct, the model estimated this

**Comment by cgrandin** [comment]
I suppose this is possible, it just stood out to me as unreasonably low.

**Comment by aaronmberger-nwfsc** [comment]
Good spot.  I saw this change on Figure 43 too and 2007 is even lower (just not shown in our table due to >10 years previous).  The big difference, as noted in the appendix, is the 2018 one.
