### ISSUE TITLE
Use of MLE in assessment document

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#789]
We really only rarely mention MLE anymore in the text - a couple places to describe how things such as priors were developed.  This is good!

One question though: we still say in the model uncertainty section (3.5) the following:
Note that we use the term MLE even though the priors are involved in the likelihood calculation and so the more accurate term would be the mode of the posterior density.

I think we can just delete this sentence now right?

**Comment by andrew-edwards** [comment]
Yes I think so. It was there in case we needed it, and not so important now if it's only to do with priors.
@kellijohnson-NOAA will be happy that MLE is fully banished!

**Comment by aaronmberger-nwfsc** [comment]
done in ca61db27bf356368cbc699142898085d1efff8ff, closing
