### ISSUE TITLE
Sunday Sunday Sunday....

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#790]
Who's doing what (hopefully Chris is sleeping)?

I'm:
- [x] creating tick boxes for myself to feel a sense of accomplishment as the day goes on
- [x] rebuilding doc
- [x] typing up edits for data section
- [x] reading through rest of text
- [x] edits for rest of text including appendices 
- [x] global spell check
- [x] my other fiddly issues

**Comment by aaronmberger-nwfsc** [comment]
I'm mostly just reading through and likely making very minor text edits here and there (if even needed);  I'll be pushing for every minor change today so as too hopefully not have conflicts.  Suggest we all do that.  How about we shoot for like a 2PM document compare?

**Comment by cgrandin** [comment]
I'm fixing minor issues and need to read it more closely!

**Comment by andrew-edwards** [comment]
Table 16 (medians for retro runs) isn't referenced is it? And it's in a strange place. I'll move it to later and reference it.

Last year it was for MLEs (but also wasn't referenced, but location maybe was a bit more sensible).

**Comment by cgrandin** [comment]
I thought it was in an odd place but I think it’s useful so worth keeping in. Good plan

**Comment by andrew-edwards** [comment]
It's getting bumped to the end. Where it belongs.

**Comment by andrew-edwards** [comment]
Wow - just run a spell check (ispell) on hake-assessment.tex. 

NO TYPOS! 

Good work team!

On that satisfying note I'm done for the day. Think we are in good shape for tomorrow.

**Comment by cgrandin** [comment]
No typos - amazing
