### ISSUE TITLE
Think we should note somewhere that the 'efficiency' of NUTS did lead to more work

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#794]
Just a sentence somewhere, without sounding like we're complaining. It still took 3-4 runs per sens run (compared to a few minutes for MLEs), but leads to 'better' results.

If I did it now it'd sound complain-y!

 I can do in the morning.

**Comment by cgrandin** [comment]
Note that the -10 retrospective run for the age 1 survey inclusive model took 74 hours which is twice as long as the original RWMH base model.

**Comment by aaronmberger-nwfsc** [comment]
good point - we are now doing way way more model run time then ever before...

**Comment by kellijohnson-NOAA** [comment]
One warning about this would be that in theory we should have been doing MCMC retros before, that had nothing to do with changing to NUTS.

**Comment by aaronmberger-nwfsc** [comment]
I think the best place for a sentence or two would be in the Response to SRG #10.  We could also mention the time length for retrospective runs here if we did that. 

OR

The research and Data needs section #13

There are probably other places too.

**Comment by andrew-edwards** [comment]
Thanks for the thoughts, I'll add something now (realised I said I would).

**Comment by andrew-edwards** [comment]
Are these roughly right? 
Base model NUTS - ~3.5 hours
Base model rwMH - ~35 hours
Sens NUTS runs - ~3.5 hours
Retro NUTS runs - one took 74 hours

**Comment by aaronmberger-nwfsc** [comment]
I was noting to Kelli and my supervisors that we would like to discuss with them (after assessment season) possible funding opportunities for computing/processing/storage/etc.  In that here is what I generically said for time stuff:

"NUTS drastically improves Bayesian model run times, so our 8,000 samples from the posterior takes about 2-3 hours total for the base model; 3-4 hours for each sensitivity run actually presented in the assessment document; 4-74 hours for each year in the retrospective run (recall that we had previously done retros back 20 years; we now do 10 years but that 4-74 hours for each year means that these times need to be summed across all 10 retro runs for one retrospective evaluation, and we do two of them (base model and age-survey sensitivity)).  Producing the retrospective figures (and people seem to really like the squid plot) for the base model alone took something like 150 hours."

Of course, this was just a quick general feeling - I didn't actually add up anything.  I do think the sensitivities tended to take a bit longer than the base model.

**Comment by cgrandin** [comment]
I edited your comment directly @andrew-edwards

**Comment by aaronmberger-nwfsc** [comment]
Maybe though in our assessment document we don't get into actual numbers and just say something more generic stating that NUTS efficiency allowed us to do the sensitivities and retros, but in total model run time was like 6-fold increase...

~ 2 retros * 150, something like 21 sensitivities *4, and base model of 3 =  ~240 hours; whereas previous years were maybe 40 hours total, so 6-fold increase

I see the edit comments, I'll just have a direct look.

**Comment by andrew-edwards** [comment]
![image](https://user-images.githubusercontent.com/6977190/107269026-d66c5b80-69fd-11eb-9fb8-a68a4fb1b23d.png)

I put it at the end of "Changes from 2020" where we mention in details.

**Comment by andrew-edwards** [comment]
Maybe last sentence is better as "The longest retrospective analysis using NUTS took 74 hours."

**Comment by cgrandin** [comment]
One thing @aaronmberger-nwfsc is that on your machine the base took 2-3 hours but on mine (and I think everyone who used 7 cores) it was 4.5 hours. Maybe we should report the higher number as that is the "basic" multi-core power laptops we usually qualify to purchase.

**Comment by andrew-edwards** [comment]
I think it's good (for the record, and Trevor might be interested anyway) to have a bit of detail for the numbers. Good point Chris - we buy the fastest laptops we're allowed!

**Comment by aaronmberger-nwfsc** [comment]
Yep, true @cgrandin!  Andy: ...retrospective analyses using NUTS took up to 74 hours per retrospective year.  (?) or just change "up to 150 hours"...  whatever you decide is fine

**Comment by andrew-edwards** [comment]
Kept it shorter, since I don't think we've gotten into details about years yet in the document.

**Comment by andrew-edwards** [comment]
Could add (bold) "The longest of the *20* retrospective analyses using NUTS took 74 hours."
