### ISSUE TITLE
Get rid of mountains plot for selectivity?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#795]
This is currently Figure 21, and shows the medians only for TV selectivity. Figure 22 shows the medians and the CI so the mountains plot is redundant. It also has much less explanation in the caption than Figure 22.

It's cool looking but do we need this?

If we remove, it is referenced by this tag:  `fig:main-tv-selex`

**Comment by aaronmberger-nwfsc** [comment]
That is personally one of my favorites for looking at how selectivity varies by year, especially for recent years and for young ages.  I'll put one vote in for keeping it.

**Comment by andrew-edwards** [comment]
I kind of think both figures can be tricky to see, but it helps to have them in two ways and I often use them both.

You know that if we take it out there'll be a (virtual) riot.

**Comment by andrew-edwards** [comment]
Could indeed add reference to each other in the captions, to clarify that they're showing similar things.

**Comment by cgrandin** [comment]
I’m ok with leaving it in, it’s just that we were on the “remove redundant stuff” train this year. So we leave it!
