### ISSUE TITLE
Should 'Additional variance for survey' in Table 15 say 1 parameter?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#797]
Not sure why it's a dash, but has a prior.

Also, related to 172d00 regarding captions for diagnostics plots (good spot, not sure how I missed that). I just checked the function those use, and using some of that code:
```
> parm_nm <- base.model$post_names
  parm_nm <- parm_nm[parm_nm != ""]
 parm_nm <- base.model$post_names
>   parm_nm <- parm_nm[parm_nm != ""]
> length(parm_nm)
[1] 243
> 
```
But Table 15 sums to 240.

`parm_nm` gives all the names, and includes 
```
 "ForeRecr_2021"                    "ForeRecr_2022"                   
 "ForeRecr_2023"                    "Q_extraSD_Acoustic_Survey(2)"   
```
Presumably the first three shouldn't really be in there (not going to make a huge difference to the plots). 

So that gives 240 but `parm_nm` seems to have the extra SD for survey but Table 15 doesn't (so we're still one off). I can't spot `q` in `parm_nm` anywhere.

The text on q is a bit confusing, because p47 says
![image](https://user-images.githubusercontent.com/6977190/107257932-0dd40b80-69f0-11eb-99f0-3c3897d2673a.png)

as though it's fixed, but we estimate it. Think something needs clarifying.....

**Comment by cgrandin** [comment]
You won’t need the parm_nm != 0 stuff anymore as I’ve incorporated it into the extra Mcmc calculations just to clean up the output

**Comment by cgrandin** [comment]
Should we get rid of the *ForeRecr parameters? If so it should be done in the extra Mcmc as well

**Comment by andrew-edwards** [comment]
It's only three parameters, so maybe fix after submission? (I think I have to fix something in my diagnostics .pdf also, so if we change it now they won't quite be comparable).

**Comment by cgrandin** [comment]
I guess I’m wondering if those are the few that fail the Heidlberger stat every time

**Comment by andrew-edwards** [comment]
Yes, maybe. Could be worth fixing if not too tricky. 

@aaronmberger-nwfsc aron mentioned something the other day, but I thought that was the recent recruitment deviates. Presumably the future ones are just randomly drawn from a distribution, so can be all over the place.

**Comment by cgrandin** [comment]
I'lll see if it makes a difference in the stat histograms and if so, change it

**Comment by kellijohnson-NOAA** [comment]
regarding Table 15, shouldn't the "1" on the catchability line just be swapped with the line below it b/c the extra survey sd is Q_extraSD_Acoustic_Survey(2) and it is estimated?

**Comment by aaronmberger-nwfsc** [comment]
Lot's going on here; I'll try a comment for each.

1. the table 15 survey additional variance should have a 1 by it (it is a single estimated parameter); and yes Kelli there shouldn't be a 1 by the catchability (q) line as it should be a dash there.
2. Q_extraSD_Acoustic_Survey(2) should be in the MCMC diagnostics as a parameter and it only has to do with adding an extra amount of standard deviation to the survey time series input standard deviation in the data file to account for this being an under-reported.  
3. the ForeRecr_2021 - ForeRecr_2023 are interesting cases as yes they are not really parameters in the estimation part of the model but implemented in the forecast part (and are drawn from a distribution with mean 0 and sigma R)
4. The text on q is a bit confusing: we estimate the extra SD associated with the survey (a single parameter that applies to all years), but do not directly estimate Q for the survey directly.  Instead the Q is an analytically derived quantity (think of it the same as 2021 SSB in that it is a derived quantity using mathematical population dynamic equations that are founded on other estimated parameters)

**Comment by aaronmberger-nwfsc** [comment]
My impression is that for 3 above that in a pure diagnostic sense you would not include those.  But I really doubt they make any difference in the visuals.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin who drew the short straw to fix the table, you or me?

**Comment by andrew-edwards** [comment]
Thanks all. Yes, realise this turned into a lot of different related ideas... 

Just saw this also:
``The objective function, as well as all estimated parameters and derived quantities, showed good mixing
during sampling, no evidence for lack of convergence, and low autocorrelation
(results for some key parameters are shown in Figures~\ref{fig:main-mcmc-diag-m-r0}--\ref{fig:main-mcmc-diag-dm}).```
Implies objective function is in the diagnostics plots? Should be clarified, yes?

**Comment by cgrandin** [comment]
Removal of ForeRecr* results in minor changes in the MCMC histograms for stats - nothing that will be noticed but note that if someone ever does forecast longer those will be included as well without their knowledge. Probably best to remove them,

**Comment by aaronmberger-nwfsc** [comment]
And Andy - I think that statement on page 47 should just say: "Survey catchability was calculated analytically as per...."

If you wanted to get more detailed, it could say: "Survey catchability was calculated analytically as per Ludwig and Walters (1982) for each set of posterior parameters resulting in a distribution of survey catchability" - or something like that

**Comment by kellijohnson-NOAA** [comment]
If we remove them though, then it might encourage people to do longer forecasts :( I think they should stay.

**Comment by cgrandin** [comment]
I can fix the table since I wrote that horrible code haha

**Comment by aaronmberger-nwfsc** [comment]
And funny enough that the objective function was in the diagnostics plot and we removed that as well as the "iter" (the mcmc iteration number) a few days back.  So Obj function is not (and should not) be in the diagnostics so word clarification as you say Andy seems reasonable.

**Comment by kellijohnson-NOAA** [comment]
The SS manual states "Q is adjusted in each model iteration to maintain a mean difference of 0.0 between the log observed and log expected index".

**Comment by aaronmberger-nwfsc** [comment]
Thanks for going to the source Kelli - yes, so Q is analytically derived but will have a posterior distribution and thus a median of the posterior distribution, but it is a derived quantity just like SSB, F, etc...

**Comment by aaronmberger-nwfsc** [comment]
I think all of us focusing on these details here means we are really close!!!

**Comment by cgrandin** [comment]
Isn't Q it's own parameter and Acoustic variance another one? So Catchability should kept in Table 15 and the dash on the Acoustic survey variance should become 1 right?

**Comment by aaronmberger-nwfsc** [comment]
As we specify Q it is (according to SS manual):

Floating: not estimated as an active parameter, set phase to negative, and not capable of being
time-varying. Can have a prior, or not. Future versions of SS may allow Q to be time-varying
and then rescaling that Q vector according to the float logic but this is not yet currently
implemented.

This option allowed Q to float and to compare the resulting Q value
to a prior, hence the information in that prior would pull the model solution in direction of a floated
Q that came close to the prior.

The use and development of float in Q has evolved over the life of SS. The original approach in earlier
versions of SS (version 3.24 and before) is that with Q "float" the units of the survey or fishery CPUE
were treated as dimensionless so the Q was adjusted within each model iteration to maintain a mean
difference of 0.0 between observed and expected (usually in natural log space).

Our base model report file reports 243 active parameters and our MCMC diagnostics do not include survey Q.

My take on all this is that it is somewhere in the middle of an estimated parameter (prior acts like a penalty) and a derived quantity.  So it sounds like you can make the argument to put it as a 1 or a dash in Table 15.  

Unless someone has strong preference, I suggest we just leave it as a 1.  The only caveat would be that it's not an "active" parameter per se.

**Comment by aaronmberger-nwfsc** [comment]
Having said that, I think technically it would not be considered a model parameter, in the same sense we don't count other derived quantities as "active" parameters.  This is all probably weedy details that probably don't need to be worried about unless we are explicitly cross checking and documenting the number of parameters in the model and they clearly don't add up in the document.

**Comment by cgrandin** [comment]
Great, thanks Aaron. That clears it up for sure. The median of the Q_vector (from extra mcmc) is what's reported in Table 25 but that table includes derived parameters so that's OK to keep there. Table 15 is estimated parameters only so it seems like it should be taken out.

**Comment by aaronmberger-nwfsc** [comment]
I'm on board with taking it out of Table 15.  We will just have to explain if anyone says "hey, why is q no longer there after its been in there for some many recent assessments" - we can just say its an SS thing  😉 

I think essentially what is happening is that SS assumes catch is known without error (well, usually now) and when Q is a float like we have it then (oversimplied here) using the Baranov catch equation C=F/Z(1-exp(Z)) and the standard survey equation relating survey catch to Biomass C=qsN     SS analytically solves for q here because C is known and N is input from survey and selectivity S is estimated.  That I think is the "Q was adjusted within each model iteration to maintain a mean
difference of 0.0 between observed and expected"

**Comment by cgrandin** [comment]
One last thing here - does the dash in the selectivity deviations bounds cell (near bottom) mean that there were no bounds?
We explained all dashes in tables this year so may as well do it here while I'm looking at it.

![image](https://user-images.githubusercontent.com/4551051/107270995-76c37f80-6a00-11eb-9c84-e9dfca847f12.png)

**Comment by andrew-edwards** [comment]
@aaronmberger-nwfsc agreed I should remove objective function from the sentence about diagnostics plots. Presumably also remove 'derived quantities' since we don't actually look at diagnostics for them (or did someone manually check them)? 

```
The objective function, as well as all estimated parameters and derived quantities, showed good mixing
during sampling, no evidence for lack of convergence, and low autocorrelation
(results for some key parameters are shown in Figures~\ref{fig:main-mcmc-diag-m-r0}--\ref{fig:main-mcmc-diag-dm}).
```
to just
```
All estimated parameters showed good mixing
during sampling, no evidence for lack of convergence, and low autocorrelation
(results for some key parameters are shown in Figures~\ref{fig:main-mcmc-diag-m-r0}--\ref{fig:main-mcmc-diag-dm}).
```
Thumbs up if okay (to avoid the multiple threads!).

**Comment by aaronmberger-nwfsc** [comment]
Hmm, the selectivity deviations are based on the fixed variance parameter which essentially acts like a penalty so they don't get too unwieldly.  Yet we can explictly set bounds for a similar set of parameters (rec devs).  I don't see anywhere in the control file where this is the case for selectivity deviations.  I'll look at the SS manual.  But as far as I can tell it just means there are no bounds per se, though in practice they are restricted by the fixed phi = 1.4.   

funny that we came to use 1.4 for rec devs and sel devs... coincidence!

**Comment by andrew-edwards** [comment]
@cgrandin - looking at the control file I think it should also be (-5, 9), but someone else should confirm.

**Comment by cgrandin** [comment]
It is (-5, 9) for them all. If only one ever gets changed and not all then we will have a problem. I'll set it to read the first one only and use that in the table.

**Comment by kellijohnson-NOAA** [comment]
10,10

**Comment by aaronmberger-nwfsc** [comment]
I'm not sure the -5,9 is for the deviations though, that is for the main estimates (in our case selectivity from 1966-1990); the deviations follow a different one.  Kelli where did you find 10,10  and do you mean -10,10?

**Comment by kellijohnson-NOAA** [comment]
yeah, sorry -10 to 10, it is in the Report file, they give the bounds for every parameter.

**Comment by andrew-edwards** [comment]
-10, 10 would make more sense for a normal prior with mean 0.

**Comment by cgrandin** [comment]
Thanks for help everyone! All done

**Comment by andrew-edwards** [comment]
To summarise (for future): table still has total of 240 parameters in it. `parm_nm` [see code at top of Issue] gives 243 parameters used in the diagnostic plots. The difference is
```
ForeRecr_2021, ForeRecr_2022, ForeRecr_2023
```
which shouldn't really be in there but is okay for now and isn't really going to make an obvious difference to the diagnostic plots.  

Think we clarified a few other things along the way, including q.

I'm not sure what 'SE' means in the parameter name though, but can live with it for now.

And the answer to the issue is "Yes"!

**Comment by andrew-edwards** [comment]
Thanks. Presumed it meant that, but seemed strange.
