### ISSUE TITLE
adnuts in glossary

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#799]
@andrew-edwards can you add adnuts to the glossary?

**Comment by andrew-edwards** [comment]
NUTS is in there which I think is fine. adnuts is just a package, and we don't really have those in the Glossary it seems.

**Comment by aaronmberger-nwfsc** [comment]
Related (kind of), I was thinking in the acknowledgements that we specifically call out SS and r4ss teams.  We say:

We thank the Stock Synthesis and the r4ss R package development teams for continually
improving stock assessment tools used in this assessment.

Should we add adnuts there as well given its importance in this document?  We do already acknowledge Cole in general and cite his work several times in the assessment.

**Comment by kellijohnson-NOAA** [comment]
I am fine with whatever you think is best Aaron.

**Comment by aaronmberger-nwfsc** [comment]
I just added in there with 68d7a45df6502531ae332336ebd68f47ae7e3d4e, but if you disagree feel free to remove it.  Plus, will I get the last commit???

**Comment by andrew-edwards** [comment]
I'll find a dodgy comma
