### ISSUE TITLE
Work out selectivity deviations likelihood explanation

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#800]
See discussion in ca3492bb547

**Comment by kellijohnson-NOAA** [comment]
7ed3b2205de4c9466f51686243a55878ad0b0700

**Comment by andrew-edwards** [comment]
So there's no mention of the survey selectivity there now. That's correct? 
If so can just replace A_min with 1, since don't need to mention both.

**Comment by kellijohnson-NOAA** [comment]
Correct, I took it out b/c survey selectivity is time-invariant and I thought it was muddying the waters to talk about both here. And sure, go ahead and replace A_min with 1 if you want.

**Comment by andrew-edwards** [comment]
And what would we call p_ay? It only appears once explicitly.

**Comment by andrew-edwards** [comment]
And does the new text all agree with this (p52)? 

![image](https://user-images.githubusercontent.com/6977190/151460306-1c630206-4a3c-4233-a54d-a39f70ccb13f.png)

**Comment by andrew-edwards** [comment]
- [ ] Also add something to the Figure 25 caption (based on above text snippet) that explains why it looks funny

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards what do you think of the following b/c as is p 52

```
The general parameterization of
selectivity was retained, although additional parameters were required to
estimate an additional year of deviations for each fishery selectivity parameter.
The selectivity of the acoustic survey is
assumed to be time invariant. Selectivity curves were modeled as
non-parametric functions with age-specific estimates for each age beginning
at age one for the fishery, age two for the index of age-2$+$ biomass,
and age one for the fishery. Ages beyond age six for the fishery and the index of
age-2$+$ biomass are assumed to have the same selectivity as age-6 fish.
Selectivity of the age-1 index was fixed at zero for all ages except age one,
which was fixed at the maximum value of one.
```

Not sure if `fishery selectivity parameter` in the second line can be improved 🤷‍♀️

**Comment by kellijohnson-NOAA** [comment]
$p_ay$ are the resulting changes year-specific values controlling the changing selectivity from age a-1 to a

**Comment by andrew-edwards** [comment]
Thanks - I'll figure out the text. 

So why does Fig 25 only go up to age-5 for biomass index selectivity, instead of age-6? (Want to add a note to the caption explaining that it continues, but need the numbers to agree). I'm digging into the function....

**Comment by andrew-edwards** [comment]
There's no age-6 selectivity in the `base.model$mcmc` output:  
```
names(base.model$mcmc)
...
[581] "OFLCatch_2025"                    "AgeSelex_std_2_Fem_A_2"          
[583] "AgeSelex_std_2_Fem_A_3"           "AgeSelex_std_2_Fem_A_4"          
[585] "AgeSelex_std_2_Fem_A_5"           "NatAge_std_1_Fem_A_20"           
...
```
Is it just constant from age-5 onwards then? (And just the text needs fixing).

**Comment by andrew-edwards** [comment]
I've done the text. To fix this last bit sounds like requires a new .rds build = time suck. Suggest for today just add to the caption that the age-6 values will be included for the SRG presentation. Okay @kellijohnson-NOAA @cgrandin ?

**Comment by cgrandin** [comment]
Yes the selectivity is 1 from 6 and up. So not sure what the issue was..

**Comment by andrew-edwards** [comment]
Scroll up (I know you're only on your phone). But fig worked fine last year. Doing for SRG is fine I think.

**Comment by kellijohnson-NOAA** [comment]
Rick changed this section of our control file for us. We have ages 1-6 selected but there are only 5 parameters that are estimated b/c everything is relative to either the terminal age or beginning age that is selected (cannot remember). SS3 has difficulty inverting the hessian when estimating sd for parameters that are fixed which is the reason for the change to the control file.

**Comment by andrew-edwards** [comment]
I'll close and reopen before SRG to get it out of the way now.

**Comment by aaronmberger-nwfsc** [comment]
Could we just manually add in the 0 selectivity at age 1 and 1 selectivity at age 6 and above for all posteriors here, or is there an additional rescaling we need to be careful about?

**Comment by kellijohnson-NOAA** [comment]
I added age 1 and age 6 to the reported values in a test run and it adds AgeSelex_std_Fem_A_1 and AgeSelex_std_2_Fem_A_6 to the Report.sso file in the derived quantities section. The values are 0.

**Comment by andrew-edwards** [comment]
And although age-6 and above are constant, they're not 1 (at least weren't for all MCMC samples last year, same for commercial).

**Comment by kellijohnson-NOAA** [comment]
They don't have to be one. Everything is rescaled and we don't specify selectivity to be asymptotic it can in theory be domed.

**Comment by andrew-edwards** [comment]
Try and fix figure if we can. (If not just update caption).

**Comment by andrew-edwards** [comment]
See comment in above commit. I think it should be 'constant' not '1'.
