### ISSUE TITLE
Send draft materials to Stacey for upload to SRG website and website

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#802]
We need to send to Stacey the following, correct?

 - [x] Draft assessment pdf
 - [x] alternative_text_submit.csv
 - [x] contents of hake-assessment\out-csv

Chris will send this to Stacey and then check these off.

**Comment by andrew-edwards** [comment]
Yep, and to get there we need:
- [ ] new .rds built by Chris
- [ ] Chris build fresh document with alt text
- [ ] Chris does autotagging
- [ ] Chris upload .rds and .pdf 
- [ ] We all take a quick look over the .pdf, then submit

**Comment by aaronmberger-nwfsc** [comment]
Also need to:

- [ ] tag repo for pre-SRG version (?)

**Comment by cgrandin** [comment]
Tagged and a release was made called 2021 Pre-SRG
