### ISSUE TITLE
Squid plot issue - revise text to say we went back ten years

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#803]
This is really not an issue just something I noticed that we should be aware of. On the squid plot, the 2010 cohort only goes back to age 1. This is more obvious on the age-1 sensitivity squid plot in the appendix. It's because we only went back 10 years and not 11.

**Comment by kellijohnson-NOAA** [comment]
Thanks Chris for bringing this up. I think it is important for all of us to have a response b/c we will be asked. Like Chris said it is just b/c our retro is only 10 years. Not a big deal, and not worth the computing time to try to predict a recruitment with no data to predict it. I think we can probably close this once Andy responds.

**Comment by andrew-edwards** [comment]
Can't see in the text that we explicitly say only went back ten years, so could maybe add in for revision.

**Comment by aaronmberger-nwfsc** [comment]
added a 10 year reference in the text cb21f6327ffe5326302ece8ff76c3b82b16de456, so closing...
