### ISSUE TITLE
Add NOAA disclaimer on our beamer presentations

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#804]
That same disclaimer that we put on the assessment document needs to go on our SRG presentations.  So when we get those building we can add something like that in the hake-assessment.rnw:

\thanks{\noindent Disclaimer: These materials do not constitute a formal
  publication and are for information only. They are in a pre-review,
  pre-decisional state and should not be formally cited. They are to
  be considered provisional and do not represent any determination or
  policy of NOAA or the Department of Commerce.}

**Comment by kellijohnson-NOAA** [comment]
@aaronmberger-nwfsc we should probably add that to the sty file as text rather than copying and pasting it everywhere. I can do it, or you can look how fishname and surveyname are set up.
- [ ] add disclaimer

**Comment by aaronmberger-nwfsc** [comment]
I'm fine with whatever workflow is optimal!  I just want us to check off that disclaimer thing and not think about it again, so sty file would be good.

**Comment by cgrandin** [comment]
Including the style file in the presentations breaks them. I get a hyperref collision right away and I don't really feel like debugging it all so I figured just add the text to each one

**Comment by kellijohnson-NOAA** [comment]
I didn't use the sty file because I got the same message that you did and for sure did not want to deal with it, I just made a ghetto .tex file and included it via `input`.

**Comment by cgrandin** [comment]
OK, Check my comment in code - tex file isn't in the repo yet

**Comment by kellijohnson-NOAA** [comment]
So sorry. I just did -A and did not realize it wasn't being included. I forced it. Should be there now. Hopefully I didn't break anything else.

**Comment by cgrandin** [comment]
No worries, I do that all the time:)
The sensitivity presentation compiles just fine. Nice idea to generalize it. We could put other things in there as well that are common across presentations.
