### ISSUE TITLE
Presentations - they are compiling now

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#806]
I spent several hours tonight making the SRG presentations compile. We made a lot of code changes and they needed some work to get them to a stage where they will at least compile, which I think is a much nicer place to start from.

I didn't look at any content at all in these yet, I just got them building. I did remove some things such as the Xu selectivity slides, but for the most part they are just copies of last year's presentations but working with this year's code. So we can go ahead and start editing them.

See Issue #805 for the one main thing I think needs fixing.

I have tinytex and got the error "beamer.cls not found" the first time I tried to compile. If you get that, do this:

```
tinytex::tlmgr_install("beamer")
```

**Comment by aaronmberger-nwfsc** [comment]
Thanks Chris!  

One thing we should keep in mind is that the length of the SRG meeting this year is shortened because the meeting is virtual.  I think in general we (and others) have a bit less time than we usually would.  Let's keep this in mind when making presentations and try to keep them as streamlined as possible.  There might be some slides that we can comment out (i.e., plan to include them perhaps next year but not this year given time restrictions).  Just something to think about when building presentations this year.

**Comment by aaronmberger-nwfsc** [comment]
Further, we might as well sign up for leading a particular presentation.  Anybody have a favorite or choice?  We have:

Data presentation
Base model presentation
Sensitivity/retrospective presentation
Management presentation

**Comment by cgrandin** [comment]
Assuming @kellijohnson-NOAA is doing the assessment one, that leaves three. I wouldn't mind doing the sensitivity one this year.  It's a long one so may have to come up with ways to trim that down.
I think we should rotate them year-to-year. I am open to other suggestions though!

**Comment by kellijohnson-NOAA** [comment]
Eww, the assessment one. I would much rather do the data one. I am a person of routine.

**Comment by cgrandin** [comment]
That's all good by me, that's the one I didn't want!

**Comment by aaronmberger-nwfsc** [comment]
I did management last year I think, so I can do the assessment one. (if Andy is then okay doing the management one)

**Comment by andrew-edwards** [comment]
Yes, I can do management. Anything but data for me.

**Comment by aaronmberger-nwfsc** [comment]
We don't need to worry about png file related build process for the presentations, correct?

So would the following code still work then?  It did for me until it errored on the ps2pdf beamer-hake-assessment

knit("beamer-hake-assessment.rnw")
#run these in terminal
#latex beamer-hake-assessment
#latex beamer-hake-assessment
#latex beamer-hake-assessment
#latex beamer-hake-assessment
#dvips beamer-hake-assessment
#ps2pdf beamer-hake-assessment

**Comment by andrew-edwards** [comment]
What was the error? It will fail if there's any .png files that are hardwired.  And yes, looks like Chris kept them as .eps for the talks, which is fine.

**Comment by andrew-edwards** [comment]
I'm trying it now.  And good idea that we should just comment out stuff that we can cut this year to keep it short, but may want back in in future years.

**Comment by aaronmberger-nwfsc** [comment]
C:\Users\Aaron.Berger\Documents\GitHub\hake-assessment\beamer\SRG\Assessment>ps2pdf beamer-hake-assessment
Error: /undefinedfilename in (beamer-hake-assessment)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:757/1123(ro)(G)--   --dict:0/20(G)--   --dict:77/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.53.3: Unrecoverable error, exit code 1

**Comment by aaronmberger-nwfsc** [comment]
I haven't spent time yet really digging into the error, but I was surprised it didn't arise until the final ps2pdf stage

**Comment by andrew-edwards** [comment]
Mine works. Just pushed a minor issue to do with the cache. Does your .ps view okay?

**Comment by cgrandin** [comment]
I used the batch files to build, you can just copy those commands into R and run them manually if you want, but it all builds fine with the batch files

**Comment by aaronmberger-nwfsc** [comment]
Okay all good now ...  I just forgot to add the '.ps' as I was just doing 'ps2pdf beamer-hake-assessment' from the command line instead of 'ps2pdf beamer-hake-assessment.ps'

It built for me now, thanks!
