### ISSUE TITLE
Figure 6 & 7 captions about depth

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#811]
Update the captions for Figure 6 and 7 to reflect the fact that the information is by haul and not by landings. Thanks to Dan W. for asking the question and providing US data to compare what is being plotted. 

It was suggested by Vanessa T. that it would be better to plot in fathoms rather than m. Does anyone have a preference here?

**Comment by cgrandin** [comment]
In all the years of work I've done at sea, depth has always been in meters and I feel that a scientific doc should only use metric. Why does she think it should be fathoms?

**Comment by kellijohnson-NOAA** [comment]
b/c it cannot be measured to the m accurrately, where fathom is a bigger measure. i am fine with leaving it as m b/c it matches metric units for other values.

**Comment by cgrandin** [comment]
OK, I figured it was just a conversion factor. I mean, we could use quintillionths of light years if we wanted 😂

**Comment by andrew-edwards** [comment]
Agree about using metric. I think someone said it was mixed between the figures, but they're not (think we fixed that a few years ago).

**Comment by kellijohnson-NOAA** [comment]
Dan W. thought that the US was wrongly labelled and that the numbers matched what he had for fathoms. I checked, they are in m. But the caption does need to be clarified.
- [ ] clarify caption
