### ISSUE TITLE
Management presentation - questions/comments

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#812]
1. Last year's management presentation ended with 7 slides for age-1 index and adnuts full MCMC results. Am thinking just a one-page summary of both (adnuts appendix = rwMH now) is fine now, summarising main conclusions. Sound okay?

**Comment by andrew-edwards** [comment]
2. Also thinking of leaving this slide out. Not sure what it adds, beyond higher recruitments (of big cohorts in particular) lead to higher default harvest rule TAC? 
![Uploading image.png…]()

**Comment by cgrandin** [comment]
This all sounds good.. I have retrospectives for the age 1 model in sensitivities and some slides on rwmh. Feel free to build that and take a look

**Comment by cgrandin** [comment]
I took all the MCMC diagnostics plots out of the sensitivity presentation as well (trace plots) because they are all fine and not adding anything.

**Comment by andrew-edwards** [comment]
Seeing Chris's sensitivity slides, don't think it's work me mentioning the age-1 and rwMH appendices, as he's nicely summarised the results.

**Comment by andrew-edwards** [comment]
I'll go through the new management slides 16-18 tomorrow to explain them (related to Shannon's point the other day). Rest is fairly standard from previous years.
