### ISSUE TITLE
About the difference in Effective sample size between base model and rwMH

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#814]
In the Sensitivity presentation we have these two slides (slides 31 and 32) which show the MCMC stats. They look similar except for the Effective Sample Size. The rwMH appears better, with many of its 2,000 posteriors having 212 effective parameters. The base model has only 110 effective parameters for 8,000 posteriors (I added option to show values above bars). What do we say about this difference?

![image](https://user-images.githubusercontent.com/4551051/108042362-8cced280-6ff4-11eb-9550-35334768f198.png)

![image](https://user-images.githubusercontent.com/4551051/108042411-97896780-6ff4-11eb-9942-0b5214bd045d.png)

**Comment by aaronmberger-nwfsc** [comment]
Let's talk about this when we meet on Thursday as I have some related things to discuss (regarding our mcmc runs - just things to consider for next year, not this year).  

Just quickly for now, some tests that I ran indicate that the effective sample sizes for our base model appear to be sufficient to capture the posterior distribution (i.e., >2000 for the least effN parameter; or in other words larger than the highest effN in our old rwMH approach).  We can make our effN figure look better (below is one of my test runs) but it all comes back to run time (this one was for 12,000 samples and ran in 5.5 hours on an 8 core machine). Ignore the near zero effN - this graph still has the "iter" and "obj fun" in there which is an error in creating the plot.

![image](https://user-images.githubusercontent.com/7946234/108080189-72145200-7024-11eb-8243-a7a1eec471fc.png)
