### ISSUE TITLE
Check box for draft presentation complete

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#815]
Just adding a check box here for when you have your presentation building and to a point where the draft is ready for others to build and have a look at ahead of our meeting on Thursday.  Mine for example is a draft and I might make further adjustments, but it is ready enough that others can have a look.

 - [x] Data
 - [x] Assessment
 - [x] Sensitivity and Retros
 - [x] Management

**Comment by andrew-edwards** [comment]
Mine is ready enough. I'm just working on something regarding Shannon's question about how well previous probabilities have panned out.

**Comment by kellijohnson-NOAA** [comment]
Sorry team, working on this now :(

**Comment by kellijohnson-NOAA** [comment]
I am wondering what the status of Canadian maturity samples being sent to the US is? We aren't very verbose about it in the main text.

**Comment by aaronmberger-nwfsc** [comment]
To my knowledge, although no explicit arrangements between Canada and US on who will process those samples and when (or any accompanying trainings) has been made, I've heard from Melissa Head that discussions have begun.  That's all I know.

**Comment by cgrandin** [comment]
I don't know either. I know there are no samples from the fisheries but there may be from the survey now. We need to ask Stephane about that

**Comment by andrew-edwards** [comment]
I just realised that my talk was taking a while to knit because we don't have the funky new switch that Chris put in `hake-assessment.rnw`, to only load the .rds files in once. I've put it in my talks, see the first thing in 4ed33fc6 . Didn't want to mess with others' talks, but you should probably just copy the same code into yours.

**Comment by andrew-edwards** [comment]
Just looking at the agenda - the descriptions of our talks aren't exactly how we have them, but we can just say that at the start; everything gets covered. (There seemed to be a lot in the 1:20-2:30pm slot, but some will get covered earlier). My management talk is about 20 mins, and the bonus historical one is about 12. Looks like there's ample time for all the talks (can't see the first two being an hour each). Prob going skiing tomorrow, hence the Sat night work!
