### ISSUE TITLE
Canadian research in Research Presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#816]
Chris/Andy:  is there anything that you want me to add about recently completed, ongoing, or new research at DFO that pertains to hake? I'm putting together a research presentation - very short like the one we did at the JTC meeting - which will just be a bullet of hake related research mostly as an FYI for the SRG.  I want to make sure to cover anything in Canada as well.  Also no worries if nothing pops out.

**Comment by andrew-edwards** [comment]
Can't think of anything specifically hake related. Maybe a bullet paraphrased from the SRG reply (to give something from DFO!) could be:

- Work on making fisheries advice robust to time-varying productivity is being conducted as part of DFO's initiative on an Ecosystem Approach to Fisheries Management, and will be monitored by the JTC.

**Comment by cgrandin** [comment]
The only thing that comes to mind strictly Canada-based is Stephane’s work on the upward looking sonar mounts but I think we should leave that for the survey team.

**Comment by aaronmberger-nwfsc** [comment]
Thanks, this is helpful, so closing now
