### ISSUE TITLE
Sensitivity presentation comments

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#817]
Well put together Chris, nice job!  Just a couple of minor comments to consider:

Selectivity section slide 11: true at the time but if you look at the current estimates (green line in the following slide) it continues to think that 2016 (and 2017) recruitment was really high (justifying our change). So the inflexibility in the phi really restricts the models ability to "tune" the size of the cohort with new information (b/c the age-1 proportion was soooo high, as seen in our Table 10).  And maybe this is your point and what you will get at already.

Just to note that slide 19 is kind of looking at a different thing than 18, b/c 19 has the age-1 survey in it and is thus the fit to data in the model, whereas 18 is model fits relative to an outside source of data.  I think its fine to show, just mentioning the difference.

I think it is fine to show projections and forecast probabilities relative to the age-1 survey, but just noting that you might get a bunch of questions about forecasting in general since the Management presentation will come after this one. 

Slide 28: first bullet - maybe delete in SS using ADMB because that's what the rwMH algorithm did; the NUTS is implemented in adnuts and while it calls SS (and thus does use ADMB) it really in effect is using utilities with STAN; so kind of confusing so suggest just delete the parenthetical

second bullet - advantages of NUTS is both slower and better explores the parameter space (I have citations that make that claim so can back it up).  Because there are differences (particularly in R0, but also other rec dev estimates) I think it will become important to state NUTS or Hamiltonian Monte Carlo more particularly as "improvements" over rwMH.  You don't need to say all this here or even change the text here, but just noting that I will be available to chime in on discussion or clarifications if/when it arises.

fourth bullet - the rwMH run that we used in our sensitivity analysis in the document followed the same protocols as our assessment last year so there was 24,000,000 million chain length that was thinned and burn in removed to get a final of 2,041 samples

fifth bullet - the run took ~38 hours.

Other notes on slide 28: I did do another sensitivity run (not shown in the assessment document, but available for discussion) where I ran a rwMH run that ended up being 110,320,000 chain length (not 74,000,000 as intended because I had to start and stop it several times) and after thins and burn ins resulted in 10,632 samples.  That took ~8days.  Inferences were very similar (identical essentially) as our typical 2,000 (or 2,041 this year) rwMH runs.  Happy to discuss further on Thursday.

Slide 37: fourth bullet - we need to be a little careful here as it does make a difference (but less so than other sensitivity runs but this isn't a structural or data change so it should result in no difference - but yet it does).  So if "significant" here is interpreted in so far as within the credible interval of the NUTS run then okay, but I think people might challenge that sentence especially given it shouldn't have mattered at all.  Let's talk more about this on Thursday.

**Comment by cgrandin** [comment]
Awesome, thanks for the feedback @aaronmberger-nwfsc 
I will clean those things up before Monday
