### ISSUE TITLE
Data presentation - few comments

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#819]
You all have seemed to slime down your presentations, nice!

Slide 2: I like the inclusion of info from fishing reports - nicely done

Slide 5: I don't know how exactly to continually handle language in terms of TAC/Allocations/etc...  I tend to think of "allocation" as your portion of the pie, but there was no pie this past year.  Even though it is a unilaterally summed TAC, it is a TAC nonetheless, just not a Treaty process agreed TAC.  Maybe we just don't use "allocation" here and just say 2020 TAC... in the header (?).

Chris: was there a Freezer Trawler vs Shoreside "allocation" within Canada?

The percentage shown for country-specific TACs are not correct this year b/c the Treaty process TAC (and thus allocation percentages) do no apply.  You could alter this to say the real percentage or just delete (comment out) this year. Same comment for slide 6.

Slide 11: Because there is not FT 2020 data the diagonals seem off, even though there are not, so hard to interpret.  Suggest adding a 2020 "blank" column in the FT plot or make sure to describe that difference during presentation.

Slide 17: I think one particular note to mention is the 2020 samples for age-1 (0) and age-2 (2) and how those compare to other years (i.e., fishery didn't catch squat from young fish in 2020 due to them not being there and/or fishery selectivity, though likely the former)

Slide 21: we can continue to say the stuff about winter surveys, but they are very likely to not happen again.  This is somewhat legacy text b/c it seemed more important when there was consideration of doing another winter survey, but maybe not relevant anymore so consider deleting (?).

**Comment by cgrandin** [comment]
There is no difference in allocations between the freezer trawlers and shoreside. They operate on the same quota.

**Comment by aaronmberger-nwfsc** [comment]
Thanks Chris - seems like something I should have known by now...!
