### ISSUE TITLE
canadian catches don't equal Can AP report

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#822]
Canadian AP report says 94262.62 mt (90.22% utilization) where we are using 91362 mt. Why is there a difference?

**Comment by cgrandin** [comment]
We would have to ask them how they arrive at that number. Ours comes from dockside monitoring (landings) and observer reports of discards (missing this year). Maybe they recorded some discards somewhere that we have no record of due to observers not being on board.

**Comment by kellijohnson-NOAA** [comment]
Thanks Chris for the response. It makes sense, just had a bit of a panic this morning. I will close the issue and we can re-open if they bring it up.

**Comment by andrew-edwards** [comment]
Could be a timing issue also, of when someone 'checked' what the total catch was.

**Comment by aaronmberger-nwfsc** [comment]
This is the same for our age data every year too; just not everything can be done by our data deadline.  So, good explanation Chris.  It is likely all catches in December would not make it into our data pull, luckily those are few and far between.
