### ISSUE TITLE
Add weight-at-age figure to the assessment

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#825]
`make.wt.at.age.plot(wt.at.age, ages = 2:10, lwd = 1)`
From data presentation

**Comment by aaronmberger-nwfsc** [comment]
Sounds like we can put this figure in the SRG response appendix this year (even though we maybe don't explicitly have it as a response...

**Comment by cgrandin** [comment]
Added, but nothing written about it. Placeholder code chunk

**Comment by cgrandin** [comment]
Add this plot to the 2022 assessment document, in main figures section

**Comment by andrew-edwards** [comment]
Done. Haven't added text to main text yet (flagged the caption to mention this).

**Comment by andrew-edwards** [comment]
Fixed caption, added bold line for age 5 for clarity, and mentioned in text. Sometime earlier today.
