### ISSUE TITLE
JTC request for feedback from SRG and others

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#827]
- [x] Age-1 index - need the full Appendix H every year? The retrospectives and projections take a long time to run in NUTS
- [x] Terminology - 0.4 B_0 and fishing intensity of 1.0 are misleading called 'targets'. Can we switch to calling them 'reference points' (next year). 
- [x] Feedback on format of decision tables 
- [x] Do another year of projection?

**Comment by andrew-edwards** [comment]
For next year:
Age-1 index - I think they wanted it kept, but not every year. John sent an email about it, but see what SRG say for next year.
Terminology - operational control points for B10 and B40, and I forget what John just said for fishing intensity....

For this year:
Decision tables plus extra year - going in SRG appendix this year. Explain 1% difference (I thought we has slightly less MCMC samples also). 
95% or 90% - confusing discussion currently going on.
Another year of projection - included in new table. Presumably next year we'd add them to the figures also.

**Comment by aaronmberger-nwfsc** [comment]
regarding terminology related to reference points - I made some text changes in commit d21bf14f5929f09fc9d6e7ea5bc698615e76840f, so have a look.  I think it may cover us with minimal changes elsewhere.

**Comment by andrew-edwards** [comment]
95% v 90% - people were happy to stick with 5% and 95% (i.e. 90% intervals). Makes sense, especially as the tails will get even huger with the three-year projections. 

Age-1 - Jim suggested doing it for non-survey years, given that survey years are generally more work anyway. Someone said do it every 3-4 years, people agreed, but then fell back to every two years. We can aim for every non-survey year. Though it's actually easier to do things every year - we can do that if we get a decent computer.

**Comment by andrew-edwards** [comment]
Age-1 index - SRG report ended up saying "The SRG encourages the JTC to include a complete reproduction of the executive summary incorporating the age-1 index in the next assessment and, if time permits, the retrospective analyses."
which isn't what I thought people were converging on (see above comment). But I think Jim said "encourages" gives us some flexibility.

**Comment by andrew-edwards** [comment]
Asking the JMC next week if 'reference level' rather than 'Target' works for F_SPR=40%.

Aaron's change above was fairly minor ( we didn't want to change lots of wording), but we think we ended up in the SRG meeting with 'operational control points' for B10 and B40, so can do that for 2022.

Could stick with 'reference points' in the bits where we refer to DFO and NOAA reference point values and policies.

**Comment by aaronmberger-nwfsc** [comment]
I specifically remember discussion saying that operation control points is a DFO term, so there was following discussion by the SRG to use the Treaty term "trigger" instead.  Maybe my memory is vague though...

**Comment by andrew-edwards** [comment]
And they didn't write anything in the report (didn't they keep notes?!?). We can make a \def{} next year so we can easily switch it if people. Ah yes, treaty does say "Triggered" -  okay, so "Trigger points" and "reference level" if JMC are okay. Thanks.

**Comment by cgrandin** [comment]
The good thing about "Trigger" is that on the Fishing Intensity plot if it is labelled as "Trigger" for the 1.0 line it is clear that is where the 40:10 adjustment kicks in. As long as we keep under it that rule will not trigger.

**Comment by andrew-edwards** [comment]
Closing for this year. Can revisit the wordsmithing early in 2023 process.

**Comment by andrew-edwards** [comment]
I had a note to reopen this one, but we didn't do anything on it last year so I think it probably doesn't need anything. Can't see anything major we should do, so expect we can just close it again easily (but I'd said I'd reopen it!).

**Comment by andrew-edwards** [comment]
This looks fine to be closed.
