### ISSUE TITLE
Add SRG request Day1 and Day2 to appendix B

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#828]
Follow the same structure as last year's assessment and add the SRG requests for Day 1 and Day 2 to appendix B.

**Comment by aaronmberger-nwfsc** [comment]
Has anyone started working on this appendix yet?  I don't want to cause conflicts if someone has already started.  It seems like it is largely a copy and paste code from the requests folders to the assessment doc SRG appendix folder task.  However, we will need to add a few sentences of explanatory text (though I think we can be very brief on this).  We should try to have this done today so that we can build and check tags (etc) for a final document by Tuesday morning.

**Comment by cgrandin** [comment]
I did - see 004f19b6e3277d6fb6daa05e92b3eab46304f1ce

**Comment by aaronmberger-nwfsc** [comment]
Seems like this is done now, other than just checking over for editorial stuff, so closing...
