### ISSUE TITLE
Table 31-33 (it looks like) don't build

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#829]
I get 
```
> sens.models.2.for.table
Error: object 'sens.models.2.for.table' not found
```

**Comment by andrew-edwards** [comment]
Could just be me. Don't worry.

**Comment by andrew-edwards** [comment]
Had to do `build_rds("2021.00.47_day2request_wtatage")` . Then restart it with the FALSE's in there ;) 

There was an .rds file in the directory but it had number 43 in it, so wasn't easy to spot the problem....

**Comment by cgrandin** [comment]
I just assumed everyone had downloaded the RDS files for those two models off Google drive.

**Comment by andrew-edwards** [comment]
Just keeping me on my toes.....
