### ISSUE TITLE
github action to compile the document

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#831]
I was able to successfully build an rmd file using `bookdown::render_book` and pandoc in another repository and we could probably do it here. Where upon commit it would build the pdf for us. We would have to think a bit more about file management and the size of the rds files, but we might be able to save them in a google drive and have the build access them. Not important right now, but would be a great way to have a single version to distribute.

**Comment by cgrandin** [comment]
I have wanted to transfer this into a proper package and over to Rmd files instead of Rnw for a few years but it is a huge undertaking and what we have works. I know exactly how to do it but all the text and code has to be rewritten, including every Sexpr statement and all code chunks. It’s not a small project!!

**Comment by cgrandin** [comment]
The benefit is as you say that we would have automated testing of every aspect of the code. It would be worth it to have that

**Comment by andrew-edwards** [comment]
I don't think transfer to a package or .Rmd is worthwhile, but I think Kelli was implying there's probably a way of setting up a GitHub Action to build the .pdf for each commit (using our normal knitr and pdflatex approach). Correct me if I'm wrong Kelli! 

I think I only had one time this year where I fetched and rebase and something had broken the build. So this idea might be worth looking into but I'm not sure if it's worth a ton of time. Plus, as Kelli mentioned, would add to the moving-about-of-files, which she hates!

**Comment by kellijohnson-NOAA** [comment]
Issues with having the pdf publicly available could lead to complications here. Also, GitHub doesn't provide storage for large files that we don't want version controlled. Closing b/c it doesn't really fit our workflow.

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards I use GitHub workflows in nwfsc-assess/sa4ss

**Comment by andrew-edwards** [comment]
Thanks. Do you have the actual rendered .pdf shown on GitHub? I can't see it (or a link from the README). Great project by the way - DFO should ideally have something similar, but it would us usual suspects having to create it. We have csasdown for the formatting, but not standardising the text.

**Comment by kellijohnson-NOAA** [comment]
It is in GitHub actions, bookdown, example. Here is a link <https://github.com/nwfsc-assess/sa4ss/suites/4156991435/artifacts/106722838>. I run the build to make sure LaTex can compile but it is just with a small trivial example.

**Comment by cgrandin** [comment]
I get a zip file download with that link with three files: md, tex, and pdf so I'm not sure what it's supposed to show.

**Comment by kellijohnson-NOAA** [comment]
Andy wanted an link to the rendered pdf, which as you say is in the zip file.

**Comment by andrew-edwards** [comment]
Thanks. So how you would link to just the .pdf file (so a user can read it without downloading anything or even knowing about GitHub)? I can't quite figure it out from the url.

**Comment by kellijohnson-NOAA** [comment]
You can easily just save the pdf rather than zipping multiple files.
