### ISSUE TITLE
A new type of way to convey recruitment uncertainty (for 2022 assessment)

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#836]
We rightly focus a lot on the recruitment Figure e that shows the uncertainties. But I've been thinking of additional ways to demonstrate the uncertainty, for the following reasons:
1. The y-axis is numbers of fish, which is good but not very intuitive.
2. The figure implies that the 2014 year class could be as large as the 2010 year class, but the probability of this from the model is 0% (more details below).

I've developed some ideas/figures that I'll paste here (probably in separate comments as there are a few figures)....

**Comment by andrew-edwards** [comment]
I like the trace plots we occasionally use to show a subsample of MCMC samples. Doing this for recruitment gives:
```
make.mcmc.recruitment.plot(base.model, start.yr = 2006, equil.yr = unfished.eq.yr, samples = 100)
```
![recs-trace](https://user-images.githubusercontent.com/6977190/110523764-64079d80-80c7-11eb-8960-a29ab9b4290f.png)

This shows that the traces (I think that's the right word?) are generally not overlapping, which I think is because a lot of the variability is driven by the differing estimates of R0 (one for each MCMC sample). Thus (could colour them in to highlight this) the top 2010 recruitment looks to correspond to the top 2014 recruitment. Note that from 2016 there are a few wayward ones that overlap , and from 2019 onwards they are all over the place because they are essentially random draws with little data.

**Comment by andrew-edwards** [comment]
Showing the same (for all MCMC samples) in the standard way (2.5-97.5% intervals):
```
make.mcmc.recruitment.plot(base.model, start.yr = 2006, equil.yr = unfished.eq.yr, samples = NULL, rescale = TRUE, traceplot = FALSE)
```
![recs-scaled-intervals](https://user-images.githubusercontent.com/6977190/110524878-cd3be080-80c8-11eb-9b22-bff54cc719d3.png)

Clearly shows 2014 is below 2010.

**Comment by andrew-edwards** [comment]
With respect to the points in my first comment:
1. People have an understanding (and intuition) that the 2010 year class was very large, so that's a good frame of reference. That last figure makes it more intuitive that the 2014 year class is more than likely to be <60% as large as 2010 (it's median is <0.6). Also shows that the projections are allowing occasional recruitments as large as 2010, but half of projected recruitments are still very low (this can be seen in Figure e but I do think the X's clutter it a bit).
2. The prob that 2014 recruitment is larger than 2010 is 0%:
```
> mean(base.model$mcmc$"Recr_2014" > base.model$mcmc$"Recr_2010")
[1] 0
> sum(base.model$mcmc$"Recr_2014" > base.model$mcmc$"Recr_2010")
[1] 0
```
None of the 8250 MCMC samples suggest otherwise. This is not intuitive from Figure e, which may give people 'false hope' that 2014 could still turn out to be very large?

The above figure suggests that there's only been three past recruitment events that might be as large as 2010 (i.e. 1980, 1984 and 1999). Whereas Figure e somewhat suggests that 1970 and 2014 could possibly be that large, and so may give an over-optimistic impression of how often the 2010-size cohorts occur (i.e. suggest there have been six years that may be on that scale, not just four)

**Comment by andrew-edwards** [comment]
I'll go back and add letters to those comments to make it easier to have a discussion.

**Comment by cgrandin** [comment]
I think that the issue here is that the recruitment estimates scale for both (probably all) recruitment years in the same way so that there is no overlap in the posterior traces, they are simply 'stacked'.

Your first figure with the traces sort of shows this but it's hard to tell with the middle ones what is going on. Maybe we could plot say 10 of them with colors showing that they scale the same way with each recruitment year? i.e. there is no overlap of the colored lines. Something like that to clarify that the 'overlapping' uncertainties for 2010 and 2014 in Figure e are not coming from the same posterior draws and are not related.

**Comment by andrew-edwards** [comment]
Exactly. I thought of the 10-colour idea last night. Just didn't have time. That would help as it's hard to tell when they all crash down together.

**Comment by kellijohnson-NOAA** [comment]
# 2022 Assessment

SRG Request # 9

>Based on the preliminary results shown, previous assessments have ‘correctly’ projected an increase or decrease in recruitment and spawning biomass in subsequent years, although the projections are usually less definitive than the current base model results. Given that this analysis provides some confidence in the current expectations of continued stock decline, the SRG recommends that the JTC continue to explore and refine this analysis for future assessments.

**Comment by andrew-edwards** [comment]
The SRG request is a different thing, so made it it's own issue #852

**Comment by kellijohnson-NOAA** [comment]
Thanks @andrew-edwards. Do you think that the topic in this issue is going to be worked on or should be frozen 🧊 and closed?

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards i came across [this paper on visualization](https://link.springer.com/article/10.1007/s10584-021-03109-w) and it made me think of hake.

**Comment by andrew-edwards** [comment]
Mostly incorporated into a new Appendix. (My postdoc read the paper Kelli mentioned and liked it - I'll listen to their talk tomorrow).

**Comment by andrew-edwards** [comment]
Note that we first talked about this kind of thing in #422 for 2018 assessment.
