### ISSUE TITLE
control file 2022 base model

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#838]
Change bias adjustment max to -1 so MLE output matches MCMC
- [x] make change
- [x] test that MLE matches MCMC output point estimates
- [x] number of sexes to divide SSB by 2

**Comment by aaronmberger-nwfsc** [comment]
Kelli - I'm running a test on the last check box now (was doing some runs anyway so will add this check)

**Comment by kellijohnson-NOAA** [comment]
Awesome, thank you.

**Comment by kellijohnson-NOAA** [comment]
As @aaronmberger-nwfsc found out, setting the bias adjustment to -1 as I suggested is a bad idea because the estimates of recruitment will be **VERY** different from how they are estimated in MCMC mode. The bias adjustment ramp is implemented to correct the differences between how the MLE mode uses a transformation normal--lognormal and the MCMC mode does not have to transform recruitment deviations. The ramp is doing its job in that estimates are more similar when the ramp is turned on than when it is not. 

### Conclusion

MCMC mode is preferred and we should move all assessments to MCMC mode and never have to code an adjustment 😄 🥇 but given we are not running anything in MLE it does not really matter and we should leave the bias adjustment ramp as is for the one-off analyses that we first explore in MLE. Each assessment cycle the terminal years will need to be incremented but that is pretty trivial. The adjustment value is consistent enough that there is no need to change it.
