### ISSUE TITLE
Some potential ideas for 2022

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#839]
Some ideas here, based on notes taken during the SRG and JMC meetings. Just pasting them all here to document them and can think about them more next year (and make individual issues if necessary). 

1. - [ ] add attainment by sector if we have the data (think it's in the presentations), then everyone has the numbers handy (and agreed upon)
2. - [ ] add TAC figures from management talk - people refer to them a lot
3. - [ ] maybe add other figures that are in talks but not in the document, so it's all consistent.
4. - [x] update historical calculations, and could make a movie using retrospectives 
5. - [x]  expand y-axis on SR curve plot to get all medians on it
6. - [ ]  explain how default harvest rate calculations are done - presumably done for each MCMC sample and then amalgamated together; should probably explain this and projections somewhere in document and in presentations
7. - [ ] Table e, 3 and elsewhere - "US catch target", "Canada catch target" etc. should say "US allowable catch" etc.
8. - [ ] - Related to Table i, we could somewhere give the median (and intervals) for the default harvest policy TAC in year assess.yr+1 for each catch alternative in year assess.yr. Those numbers must get already calculated to work out the final
probability column in Table i.
9. - [ ]  Bmsy/B0 might be useful (for comparisons to DFO reference points, especially as we might need a rebuilding plan at some point; could maybe add to Table 26).
10. - [ ] maybe call the probability tables i and j 'decision tables', and not use that term for g and h. 'Decision tables' is not in the captions, just in the text. This document is interesting (I was hoping it might explicitly give some definitions we could quote): http://www.fao.org/3/bf336e/bf336e.pdf
11. - [ ] change 'forecasts' to 'projections': "A forecast predicts what *will* happen. A projection describes what *would* happen, given certain hypotheses." Caswell (2001), Matrix Population Models (book). 
12. - [ ] Add figure/tables explaining the difference between median, and probability of being under a value. Maybe a density plot showing those lines all in one place.
13. - [ ] alt text - keep an eye on the knitr tools mentioned here https://www.r-bloggers.com/2021/04/new-in-knitr-improved-accessibility-with-image-alt-text/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+RBloggers+%28R+bloggers%29    but currently only works for html output.
14. - [ ] Maybe do a model run without the survey (or some years to ground it). To see how much impact it has - seemed to be a sense at the JMC that the survey will give lots of info that we don't have now. 

Happy to discuss. But no rush now.....

**Comment by andrew-edwards** [comment]
Think only plan on doing 7, 10 and 11, given time constraints. Also change target elsewhere I think.

**Comment by cgrandin** [comment]
I think the term 'forecasts' is fine. We have weather forecasts and we know they are always 100% accurate..
People think of forecast in those terms I think.

**Comment by andrew-edwards** [comment]
Yeah, it's a little semantic (more important in COVID modelling maybe). These are all low priority anyway, so may not get time to look into.

**Comment by andrew-edwards** [comment]
Not doing these as bit of a wish list (and text changes require lots of checking for consistency). May re-open again some time....
