### ISSUE TITLE
US SIS submittal

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#840]
Run Ian and Andi's R script to get SIS information for including the hake assessment in the US stock assessment database (i.e., SIS). I will take care of this, just needed somewhere to document a reminder.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, is this still something that you can do in the weeks ahead?
@andi-stephens-NOAA and I got pinged about it today so at this point I think we just need a plan of who will do the work when time allows.

**Comment by kellijohnson-NOAA** [comment]
Done, thanks to @andi-stephens-NOAA.
