### ISSUE TITLE
New name for natural mortality with updated SS version

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#841]
Just copying this over from (nwfsc-assess/nwfscDiag) as it likely pertains to our workflow once we update: 

SS version 3.30.17.01 changed the parameter label from "NatM_p_1_Fem_GP_1" to "NatM_uniform_Fem_GP_1"

**Comment by kellijohnson-NOAA** [comment]
@cgrandin I searched the repo for the old name and found it in the following two locations. Should we change those and then close this issue?

https://github.com/pacific-hake/hake-assessment/blob/9a9b9c64ad95bb036f85fead221145063aff6c69/R/tables-parameters.R#L351
https://github.com/pacific-hake/hake-assessment/blob/be6a0c53928dfc999fd42ed3d835d035eca964b9/beamer/SRG/Requests/requests-day1/beamer-hake-requests-day1.rnw#L210

**Comment by cgrandin** [comment]
Looks like Andy changed that first one so that it still works with last year's model, if the new name is found, use it otherwise use the old name. If that's not there then Table 25 will have last year's M missing.

```
 ifelse("NatM_uniform_Fem_GP_1" %in% names(.x$mcmc),
   f(median(.x$mcmc$`NatM_uniform_Fem_GP_1`), digits),
   f(median(.x$mcmc$`NatM_p_1_Fem_GP_1`), digits)),
```

I changed the second one. Thanks for checking!
