### ISSUE TITLE
Reference for 2022 assessment from Mexico

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#842]
[Catch rate, length, and sex ratio of Pacific hake in the Northern Gulf of California](https://spo.nmfs.noaa.gov/content/fishery-bulletin/catch-rate-length-and-sex-ratio-pacific-hake-merluccius-productus-northern) published in Fishery Bulletin.

**Comment by andrew-edwards** [comment]
Given the Issue title, I thought @aaronmberger-nwfsc was going to get it "from Mexico".
