### ISSUE TITLE
SRG Request recruitment deviations in decision table

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#844]
# 2022 Assessment

SRG Request # 3

>The SRG requests that the JTC consider developing a decision table in the next assessment with recruitment fixed at the median and mean levels to assess the resulting impact on stock depletion.

**Comment by cgrandin** [comment]
I'm guessing this isn't happening.. Seems like a big one that we didn't really talk about.

**Comment by andrew-edwards** [comment]
Yep. We can just say that there was not time to investigate this. It would actually get pretty complex I think. We could ask for exactly how they want it done, as I think there's several choices.

**Comment by andrew-edwards** [comment]
The current text is a bit confusing. Sounds like some analyses were done (I forget by who), but we don't show any results. @kellijohnson-NOAA - are you able to tidy up the answer? I'll assign you anyway ;)

**Comment by kellijohnson-NOAA** [comment]
@aaronmberger-nwfsc did some work on this. Can you point me to the lines of text you are talking about?

**Comment by kellijohnson-NOAA** [comment]
Edited the text in 706a89e1 but will need to 
- [ ] summarize the results in a presentation for the SRG (@aaronmberger-nwfsc)

Not sure @andrew-edwards if you want to close this and reopen, I will leave that up to you.

**Comment by andrew-edwards** [comment]
Text in assessment section is:
![image](https://user-images.githubusercontent.com/6977190/151871461-fd3f620f-d65e-4671-8cff-0e77f529e054.png)

**Comment by andrew-edwards** [comment]
Maybe just the penultimate sentence needs to say "Results will be presented at the 2022 SRG meeting."

**Comment by kellijohnson-NOAA** [comment]
Yep, already changed to
```
Results will be presented during the SRG in 2022 during the review.
```
in  706a89e.
