### ISSUE TITLE
SRG Request on dynamic reference points

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#845]
# 2022 Assessment

SRG Request # 4

>Pacific Hake dynamics are highly variable even without fishing mortality. The SRG encourages the JTC (and MSE technical team) to continue investigating the usefulness of dynamic reference points in the management of Pacific Hake.

**Comment by aaronmberger-nwfsc** [comment]
I will put together a response for this year.

**Comment by aaronmberger-nwfsc** [comment]
I've added a general paragraph in the SRG requests section.  Closing this...

**Comment by kellijohnson-NOAA** [comment]
2023 SRG Recommendation
1. Pacific Hake dynamics are highly variable even without fishing mortality. The SRG applauds the efforts of the JTC and the MSE Working Group to add capabilities for estimating dynamic reference points within the assessment and MSE, and __encourage those groups to jointly develop alternative reference points, including dynamic reference points, for future SRG consideration.__

**Comment by aaronmberger-nwfsc** [comment]
Closing this as we have responded to last year's SRG request on this.
