### ISSUE TITLE
SRG Request historical ages and weights

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#848]
# 2022 Assessment 

SRG Request # 11

>The SRG recommends that historical sources of data be investigated to determine whether they can be used to supplement the weight-at-age matrix, including unaged otolith samples (and associated data) from the 1970s that may be available in the Burke Museum in Seattle.

**Comment by kellijohnson-NOAA** [comment]
Do we want to take the stance that historical data are not super informative to the assessment or that covid-19 restrictions have limited the availability to access historical data let alone age them?

**Comment by aaronmberger-nwfsc** [comment]
Good question.  What about both stances. i.e. - we could look at historical, museum, data once Covid restrictions are lifted, but we don't expect it to make a difference relative to current management decisions via our previous analysis.

**Comment by aaronmberger-nwfsc** [comment]
I tried to include both ideas in a draft SRG response:

Restrictions related to the COVID-19 pandemic have limited the availability
  to access historical data. Even if historical \fishname age structures were found and where
  determined to be in a usable state, these new strictures would need to be integrated into existing
  ageing laboratory work plans.  The JTC has conducted analyses previously showing that small changes to
  historical data have little relevance to current management quantities of interest. So at this time,
  the JTC does not expect small amounts of historical weight-at-age data to significantly alter
  stock assessment results used for management decisions.
