### ISSUE TITLE
SRG Request analyses for lack of biological data collection in 2021

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#849]
# 2022 Assessment

SRG Request # 12

>If biological data cannot be collected by any fleet in 2021, the SRG encourages the JTC to explore model sensitivity to that absence. We commend the JTC for their foresight in investigating the impact of the lack of 2020 Canadian freezer-trawler age data in this year’s assessment.

@cgrandin I don't think was a problem for Canada was it? It was NOT a problem for the US.

- [x] Add response to the Assessment

**Comment by kellijohnson-NOAA** [comment]
@cgrandin can you give a summary of the data that was **NOT** available for 2021? Didn't you say that there were no observers? I am not sure exactly what fleet / samples that translates to though.

**Comment by kellijohnson-NOAA** [comment]
## Potential runs

1. remove all Canadian fishery ages to get an idea of an overall value
2. just Canadian age data from 2020 and 2021 b/c that is realistic of where we are at today (even though there were a few ages in 2021 and some from shoreside in 2020)
3. remove Canadian ages from Freezer Trawler sector (none to remove in 2021 or 2022)

In 2021 assessment we just did (3).

@cgrandin what are they proposing for the future, would shoreside ages be collected or nothing from either sector?

**Comment by cgrandin** [comment]
@kellijohnson-NOAA apologies for late response here -

I have not heard anything concrete about plans to sample the freezer trawler catch. The rumor I have heard is that there will be some sampling done on shore when the FT's come in from their week-long trips. But then I'm guessing the data would be aggregated to trip (nobody is going to separate them all into haul samples while at sea).

Shoreside should proceed as normal.
