### ISSUE TITLE
2022 Assessment document --- update SRG requests to 2021 requests

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#850]
Update the assessment document to state the 2021 SRG requests. [Official requests can be found here](https://media.fisheries.noaa.gov/2021-03/2021_SRG-Report_Draft_V5_20210303.pdf?VersionId=null).

2021 SRG Issues include the following issues in no particular order:

- [x] #849
- [x] #848
- [x] #847
- [x] #846
- [x] #845
- [x] #844 
- [x] #843
- [x] #837
- [x] #852
- [x] #751 
- [x] #468 
- [x] #465
- [x] #855  (wasn't actually in the full list of recommendations)

**Comment by cgrandin** [comment]
Thanks for doing all this @kellijohnson-NOAA , it's way easier to remember this way.

**Comment by andrew-edwards** [comment]
I've done the text with placeholders for our responses, just not merged into master branch yet.

**Comment by cgrandin** [comment]
@andrew-edwards I think you can rebase it in, I think we have to move forward now and forget last year's build. Unless anyone objects?

**Comment by andrew-edwards** [comment]
Yes, I'll rebase. But not yet as I'm editing/moving text and still want to be able to build (hence I didn't want anyone else to edit any text yet - think that's been fine so far). Once it's rebased then the build doesn't work until we have all the model runs done and assess.yr gets updated. 
I'm fine with the build breaking once I rebase, but just don't quite need to yet, if that's okay. Looks like not too many commits the last couple of days.
