### ISSUE TITLE
function to extract sigma r

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#853]
ensure that the sigma r extraction function makes it back to the greater community at the end of the year. See @cgrandin's code.

**Comment by cgrandin** [comment]
https://github.com/pacific-hake/hake-assessment/blob/8a5c1cda1bd3af6d1480e98ae66832526dd5c206/R/extract-sigma-r.R#L1

**Comment by andrew-edwards** [comment]
FYI I had to revert the commit "Switch to local extract_sigma_r()" to get the pdf building again. I'll un-revert it before merging my branch back in to master, just wanted to mention it. Didn't dig into details of why it didn't work.

**Comment by kellijohnson-NOAA** [comment]
This has been a while and no one has requested it within {r4ss} so I am closing.
