### ISSUE TITLE
Use the new format of decision tables shown in Table B.3 of 2021 assessment?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#855]
In 2021 several suggested changes were made to the format of the big decision tables, resulting in Table B.3. The SRG said:

" The SRG believes that the resulting decision tables are clearer and easier to understand and recommends that the JMC review these tables along with the standard decision tables, and provide feedback to the SRG and JTC as to its preference during the March 15-17, 2021 JMC Meeting. These alternative decision tables are presented in Appendix B of the JTC Stock Assessment document." [wasn't actually in the list of recommendations though]

At JMC we asked for feedback - I don't have my meeting notes handy and forget what they said. Kelli has followed up with Jim but not heard back.

Given the SRG prefers them, and if we don't recall anyone being against them, seems we should use them. We justified and explained the differences in 2021 Appendix B (so no need to again), including Trevor's 2019 one about the catch/biomass years being offset in  #553. Code is all written.

**Comment by andrew-edwards** [comment]
So in Exec Summary would update:
- [ ] Table g & h
- [ ] Figure i add the extra projection year
- [ ] Add extra Table i/j for the extra year, plus extra Figure j/k for the extra year

**Comment by andrew-edwards** [comment]
JTC internal meeting: agreed to do this. Decide upon exact catch streams later - maybe even non-equal from year to year if JMC get back to us. Easier to add further catch streams to big table than do a second table - okay if ends up as a long table over two pages.

**Comment by andrew-edwards** [comment]
Maybe on Friday we should just mention to the JMC that we're doing the new format as recommended by the SRG. If any objections we can stick with the usual.

**Comment by andrew-edwards** [comment]
Not sure that we actually showed an updated format for the relative fishing intensity table. Chris put a `type = "spr"` option into the `new_decision_table()` function, but it didn't work when I quickly tried it. So I haven't put that new format of table into main-tables yet (which I think would just be losing the % signs everywhere and losing the 25% and 75% columns). Have copied new format of biomass table into main-tables (but not Exec Summary yet - tweak it first as necessary in main-tables then copy over).

**Comment by cgrandin** [comment]
I didn’t write the code for that table yet

**Comment by andrew-edwards** [comment]
Thanks - that's what I thought. Got a bit confused because the SRG talked about showing alternative table**s** in App B, but we only had the biomass one.

**Comment by andrew-edwards** [comment]
All done except Chris to update the fishing intensity table if time (else I can do it - I can see what lines to tweak). No text updated yet.

**Comment by cgrandin** [comment]
@aaronmberger-nwfsc are you saying it should look exactly like this rel. biomass one then with the "start year" column? I thought there was some difference 

![image](https://user-images.githubusercontent.com/4551051/150869683-0252b3e8-a809-4bb6-8b52-097fc8ebc879.png)

**Comment by andrew-edwards** [comment]
I don't think we need the "Biomass year Start 2022" column. Will actually be confusing (and is the thing I figured might be a bit fiddly in the code).

**Comment by cgrandin** [comment]
@andrew-edwards I am talking about the Relative Fishing intensity table, are you also?

**Comment by cgrandin** [comment]
I thought we agreed to project 4 years, so we show 2025 relative fishing intensity for the catch stream because it is the 4th year. So we show the 2025 catch value.

**Comment by aaronmberger-nwfsc** [comment]
Yes, we still project 4 years, but don't show 2025 (fishing intensity table only).  Right, the whole point was that previously we showed fishing intensity for a year but did not show the result of that fishing (i.e., the biomass at the start of the next year).  Does that make sense?

**Comment by cgrandin** [comment]
So the sole reason to project 4 years is so we could show the 4th year start-of-year biomass after the last year's fishing. And not show the fishing intensity for that 4th year even though we have it.  I think I have it right now

**Comment by andrew-edwards** [comment]
Agree with Aaron. We're always going to kind of be off by one year. Three rows for this table.

**Comment by andrew-edwards** [comment]
And the table will have three rows like the snippet shown above. I said remove the "Biomass year Start 2022" for this table as we're not showing biomass at all and it might be confusing. (Unless it's too fiddly to take out).

**Comment by andrew-edwards** [comment]
Good job with the new fishing intensity table Chris. I noticed that the numbers are proportions now rather than percentages (like in the relative spawning biomass table), which is neater. Presume everyone is good with that.

I'll fix the caption (still says %ages), plus the main-tables equivalent, plus add it to the age-1 index appendix as I think it's not there. 



![image](https://user-images.githubusercontent.com/6977190/151084513-3f57ac93-f9f2-4f29-9fa6-66bf37ec19ea.png)

**Comment by cgrandin** [comment]
Thanks Andy. Note that I swapped the row that has the quantiles (5%, 50%, and 95%) and removed the "Model quantile" text.
