### ISSUE TITLE
Different output in new SS report file

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#856]
Comparing the report files generated using the new `sso` method in SS with the ones generated using the extra-mcmc method, there is a discrepancy:

Old extra-mcmc method (approx line 2476):
`sel*wt 1 2021 1 1 1 2021_1_sel*wt  ...`
.. 5 more lines

New `sso` method (approx line 2531):
`sel*wt 1 2020 1 1 1 2020_1_sel*wt ...`
.. 5 more lines

So 2020 is reported instead of 2021 for the final year for all of `sel*wt`, `sel*ret*wt`, `sel_nums`, `sel*ret_nums`, `dead_nums`, and `dead*wt`

All inputs were identical
@kellijohnson-NOAA

**Comment by kellijohnson-NOAA** [comment]
I will look at this tomorrow, but I was easily able to find what you are referring to. Thanks for making an issue.

**Comment by andrew-edwards** [comment]
I added the 'eyes' emojii to Chris's first comment - as in 'good eyes' in spotting that change, that will really have confused things....

**Comment by cgrandin** [comment]
I'm sure this is related to #859. As I said there, I bet there is one line of code that fixes all of these non-reporting of 2021 issues.

**Comment by kellijohnson-NOAA** [comment]
We might not be able to fix the sel*wt output because it is a timing issue in when things are written with SS3. Please let me know Chris if this will be a problem, please let me know, otherwise I think you can close this issue.

**Comment by andrew-edwards** [comment]
Pretty sure this is good to close.
