### ISSUE TITLE
No Dynamic_Bzero ref points in the new SS output

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#857]
The `sso` runs' Report files do not have `Dynamic_Bzero` output whereas the extra-mcmc ones did. We previously extracted it because we were going to do some SRG-requested work with this.

If we are abandoning that, we can ignore this and I will re-code the code that reads in this file. If we want to go ahead, we need SS to output those tables.

**Comment by aaronmberger-nwfsc** [comment]
Yes, we will want that the "no fishing" time series exported when using MCMC for future dynamic B0 analyses.  This wouldn't need to happen immediately or before this assessment cycle, but shortly thereafter would be great.  Might be just as easy to add this now.

**Comment by cgrandin** [comment]
OK, this will have to be requested to the SS team, @kellijohnson-NOAA

**Comment by kellijohnson-NOAA** [comment]
Solved with #863
