### ISSUE TITLE
Numbers-at-age in the new sso Report files

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#858]
In the old versions of the Report files, there were two headers for numbers-at-age:
`NUMBERS_AT_AGE_Annual_1 No_fishery_for_Z=M_and_dynamic_Bzero` and
`NUMBERS_AT_AGE_Annual_2 With_fishery`

The new Report file only has one called:
`NUMBERS_AT_AGE`

I am guessing that this represents the old `NUMBERS_AT_AGE_Annual_2 With_fishery` but just making sure.

**Comment by kellijohnson-NOAA** [comment]
We just needed to turn on this output. See #863 that turns on Dynamic Bzero and results in the output being included.
