### ISSUE TITLE
FORE years in numbers-at-age all zero in new sso Report files

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#859]
For last year's output, our `extra-mcmc` output had numbers-at-age values for 2021, 2022, and 2023 (the FORE years)

The new `sso` method has all zeroes for these

**Comment by kellijohnson-NOAA** [comment]
Is this because we calculated these values in the extra-mcmc step? I looked at a Report.sso file from previous years and the file has never had these numbers-at-age for the forecast period. I can try and project them and make them available or at least ask Rick why they are not calculated.

**Comment by cgrandin** [comment]
If you look at table 17 in the 2021 assessment you can see 2021 is reported. This is the median of all the extra-mcmc Report.sso files values. This is what one of those files looks like:
![image](https://user-images.githubusercontent.com/4551051/147055220-6e88b2a4-41d8-40d6-a3d4-e058feb816ab.png)

The files for the new method in the `sso` directory have all zeroes for this. We don't actually need all three years, just the current assessment year:
![image](https://user-images.githubusercontent.com/4551051/147054878-86729762-a7bc-474c-ba9d-85c9db4a52f6.png)

So it is SS not outputting them for the `sso` runs, not our R code.
Thanks :)

**Comment by kellijohnson-NOAA** [comment]
Got it, Rick fixed this yesterday for us. It was not a problem of the sso folder structure it was just a problem in general.
