### ISSUE TITLE
When we run the catch-levels code it generates all 2,000 extra-mcmc output files

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#860]
When we run the catch-levels code which determines our three dynamic catch levels (`default-hr`, `stable-catch`, and `spr-100`), it runs `ss -mceval` each iteration for them. Each of these times it generates all 2,000 files. This slows it down dramatically.

**Comment by cgrandin** [comment]
I'm still working on this, I have to verify it is not my code causing it before it gets sent to SS developers

**Comment by kellijohnson-NOAA** [comment]
You can turn off a lot of the output by using the switch in the starter file. It will also turn off that output in Report.sso though. So is there something in particular that we need from Report.sso that we can leave turned on for these runs?

**Comment by cgrandin** [comment]
I don't see any switch to turn off the generation of those Report.sso and CompReport.sso files. We don't need them at all for forecasting (but we should have the option if we want to in the future).

We are running 10 catch levels for 3 years, so 30 -mcevals, which adds up to 60,000 files we don't need. I can write code to erase them as they are run but it's a waste of runtime writing them all out.

It would be much better to have a command line switch in SS to turn on/off production of the extra MCMC files. If that were the case there would also be no requirement on us or other users of SS to pre-create an 'sso' directory to tell SS we want the extra MCMC files.
I cloned the SS repo and added one line of code to stop generation of those files with a command line switch so it seems like a fairly straightforward task to make the whole routine be based on that method.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin you can turn off the output by changing MCMC output detail - line 31 of starter.ss to 1 instead of 2. I just tested it and it works. Not sure if it turns off other output that we need though?

**Comment by cgrandin** [comment]
Thanks, I actually responded directly to Rick's issue on the SS GitHub repo not noticing that you had the same issue. I'm re-running it now so hopefully all the issues are solved.

Didn't he say change it to 2 though? Mine was set to 3.

**Comment by kellijohnson-NOAA** [comment]
I had mine set at three as well. If you use 2 all of the Report_mce_xx files are created. 1 suppresses the creation of these extra files. Rick was answering a different question of mine but referred to this section of the starter file when he said 2. I was wondering if we needed to include Dynamic Bzero as a section using the custom reporting.

**Comment by cgrandin** [comment]
Thanks, I will change to 1 and try again
