### ISSUE TITLE
complete bridging for 2022 assesment

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#866]
Complete the following steps to update the 2021 assessment to the 2022 assessment. All steps must be completed before the age-1 index can be added.

- [x] new Stock Synthesis executable
- [x] #838
- [x] #820
- [x] #863
- [x] Catch and ages from previous years but new values
- [x] Catches
- [x] Ageing error matrix
- [x] Age data from fisheries
- [x] Survey index of abundance
- [x] Age data from surveys
- [x] Weight-at-age data
- [x] turn on tail compression for the age 2+ survey

**Comment by kellijohnson-NOAA** [comment]
All starter files need
```
2 # MCMC output detail
```
rather than 3. This is documented in #860.

**Comment by cgrandin** [comment]
I wrote a function that changes this value, in `utilities.R` called `modify_starter_mcmc_type()`

**Comment by kellijohnson-NOAA** [comment]
For @aaronmberger-nwfsc 

### doc/data-section/data.rnw

#### https://github.com/pacific-hake/hake-assessment/blob/be6a0c53928dfc999fd42ed3d835d035eca964b9/doc/data-section/data.rnw#L140

Minor updates to catches used in previous assessments were made based on the best available information extracted from the aforementioned databases.
Slight changes of less than 10 mt were made to the time series of catches from Canadian waters since 2007 to reflect current information stored in the Canadian databases.
Updates to catches since 2019 were larger but all less than 1200 mt. Changes to the most recent values are typical as the data pulls for each assessment happen just days after the fishery closes and may not include all catches for the terminal year, and thus, typically get updated in the next assessment.
Tribal catches were key punched in a timely manner and available from the PacFIN database, facilitating the inclusion of these catches in all figures and tables.
The Makah Tribe is continuing to work on providing historical catches such that shore-based catches can be summarized separately from tribal catches since the onset of the fishery.
% Manual 2022 KFJ

**Comment by andrew-edwards** [comment]
Those commits should have referenced #820, sorry.
