### ISSUE TITLE
For age-1 sensitivity analysis definitely keep it as `sens.models.2[[1]]`

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#867]
So if we do include age-1 in base model, keep it in the same position in `model-setup.R` as that will avoid changing lots of code. 

Then variables such as 
```
retro.list.age1 <- list(sens.models.2[[1]])` 
```
will still refer to it. Just that 'age1' will now mean that we exclude the age1 index, rather than include it as for the 2021 assessment's sensitivity run. (And if we change our minds and do exclude it for the base model everything is still fine again).

I don't think this will be an issue, but wanted to mention it now for when we update `model-setup.R`. I added a note into that file.

**Comment by kellijohnson-NOAA** [comment]
Thanks @andrew-edwards for the great idea. When I coded the age-1 sensitivity I removed the index. I think we can close this issue or we might want to wait until we are sure the document builds.

**Comment by andrew-edwards** [comment]
I thought about automating the text using an `age_1_in_base -> TRUE` or `FALSE` setting, so that the text is something like
```
... the age-1 index sensitivity run that \Sexpr{paste0(ifelse(age_1_in_base, "excludes", "includes")} the age-1 index ....
```
We have to do change some text manually anyway, and this will make it easy to switch back to excluding age-1 in base if we have to (I'm not 100% sure we won't have to switch back to excluding the age-1 index in the base model - SRG didn't say to put it in). I can do it when we build.

**Comment by kellijohnson-NOAA** [comment]
I personally would like to just have more straightforward text without conditional statements like what you are proposing b/c it makes it easier to read and edit.

**Comment by andrew-edwards** [comment]
Great. Actually Chris thought it might be overkill also. Easy enough to search through the .pdf for age-1 index and just manually replace....

**Comment by andrew-edwards** [comment]
Closing, as Issue is done.
