### ISSUE TITLE
Parallelize forecast years - last thing to parallelize

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#870]
The last thing that can be parallelized is the individual years of forecasts. These folders are currently produced serially:
![image](https://user-images.githubusercontent.com/4551051/149087699-22f172ef-3fdc-48e1-b0e7-e7d749837007.png)

The catch levels inside each year are done in parallel though, i.e. all these are forecast in parallel:
![image](https://user-images.githubusercontent.com/4551051/149087828-4e2ffb2f-82f0-447a-b30f-19c6c9f9aeda.png)

This can wait until 2023 assessment since I'm writing this on the eve of running all the 2022 models, but it would take off approximately 90 minutes - 2 hours off  the current runtime with forecasting for the base model.

**Comment by cgrandin** [comment]
Notes.. Running this configuration on a 16 CPU machine with 30G RAM, we approach 29.8G RAM used for each forecast year so pushing the limits. Maybe use a 32 CPU machine

**Comment by andrew-edwards** [comment]
Hmm... but you can't do 2022 forecast and 2023 forecast in parallel as you need 2022 to do 2023. Yes, can do the different catch levels parallel. Am I missing something?

**Comment by cgrandin** [comment]
@andrew-edwards The forecast catch levels are already calculated and in the forecast files in each directory so no, the model for each year runs them out to the years listed at the end of the forecast file.

**Comment by cgrandin** [comment]
Done during the rewrite of 2023
