### ISSUE TITLE
Need to put a value in for catch for the fourth forecast year

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#871]
So we need to have a catch to run the forecasts for 2024. I'm sure it doesn't matter what it is because we are just extracting start-of-year biomass for that 4th year right?

What I've done:

- For the constant catch rules, the fourth year is the same constant value
- For the 10% reduced ones, I have continued with another 10% reduction
- For the three calculated ones, there's a bug in the catch-levels function and only the first year is calculated. I'll just set it up to run a fourth year in the calcs. **I'll fix this bug tomorrow**

**Comment by andrew-edwards** [comment]
Yes, I think it needs a catch for the fourth forecast year (will be 2025) for completeness, even though it doesn't get used as, yes, we only need the biomass at the start of 2025. What you did in a9595261 looks great. 

Sounds like you'll sort out your last point, great.

**Comment by cgrandin** [comment]
Ok, all this is working fine
