### ISSUE TITLE
To still update in model-setup.R

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#874]
- [x] ss.version (and maybe specify commit number in the document text?)
- [x] admb.version and commit number (we compiled it)
- [x] Add bridging run 6 back in when it's done in bridge.model.dir.names.1
   (replace with the commented):
          "2022.01.05_updatesurvey", # "2022.01.06_newsurvey",
- [x] When run 29 is done: change last element of sens.model.dir.names.4
   (replace with the commented):
    "2022.01.28_tvSelect_phi_low") # "2022.01.29_tvSelect_phi_high")
- [x] add in runs 48 onwards (if wanted - see notes in Google README); can put
   them into the next two:
- [x] sens.model.dir.names.5 is just a dummy one for now, placeholder for any
   new ones. If not needed then have to delete some later occurrences (in
  custom-knitr-varibales.R also), so easier to keep a dummy in for now.
- [x] sens.model.dir.names.7 - same as previous line.

**Comment by andrew-edwards** [comment]
- [ ] Then I'll re-run the diagnostics pdf.

**Comment by andrew-edwards** [comment]
- [ ] create an ss.version.commit also and then mention it in the text
- [ ] create an admb.commit also and then mention it in the text

**Comment by kellijohnson-NOAA** [comment]
I think that we should leave the commit numbers out of the text but keep them in the files for reference for us. Rick has stopped development of 3.30.19 (except a couple of commits related to hermaphrodites) so we can use the version number without needing to recompile the executable. I don't want to encourage others to be building SS3 off of random commits by mentioning a commit number. Second, we showed that the commit of ADMB did not matter within version 12.3.

**Comment by cgrandin** [comment]
I removed the commit stuff from the doc (d8490fe01e0f15a4e7e6cc71bd2e5fe6a9706035). Seems fine to me, as long as it is stored somewhere. It's in the model-setup.R file.

**Comment by andrew-edwards** [comment]
Looks like it can be closed....
