### ISSUE TITLE
Cannot get retrospective -7 for No-age1 model to run

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#879]
`run_retrospectives('models/2022.01.23_age1Survey', retrospective_yrs = 7, n_cores = 16)`

fails, with this error:

`Error in checkForRemoteErrors(val) :
16 nodes produced errors; first error: models/2022.01.23_age1Survey/retrospectives/retro-07/mcmc/chain_1/adaptation.csv exists = FALSE
models/2022.01.23_age1Survey/retrospectives/retro-07/mcmc/chain_1/unbounded.csv exists = FALSE
NUTS failed to run in chain 1. Check inputs.`

So the `adaptation.csv` file is not being created by ADMB as it is in every other retrospective run. I tried a few things like increasing the initial adnuts run to 500 iterations, see the link below. I also changed the seed but it made no difference. I think the algorithm starting at the MLE values is not correct somehow but I don't know what to look for.

See https://github.com/pacific-hake/hake-assessment/blob/27aeccb688149e0007b93dafa3740b85590c61f9/R/run-adnuts.R#L91

**Comment by kellijohnson-NOAA** [comment]
Does the number of parameters change because time-varying selectivity is removed?

**Comment by cgrandin** [comment]
Yes, there are 5 less going from -6 years to -7 years

**Comment by kellijohnson-NOAA** [comment]
I thought that maybe we had went far enough back in time that the whole block was gone. Bad guess on my part. I think this is going to take exploration on a local machine or logging into AWS to diagnose.

**Comment by cgrandin** [comment]
It's just this if you want to try it:

`run_retrospectives('models/2022.01.23_age1Survey', retrospective_yrs = 7, n_cores = 16)`

**Comment by cgrandin** [comment]
Change the n_cores though

**Comment by cgrandin** [comment]
If you want to try it on AWS go to:

`35.182.247.50:8783`
User: `kjohnson`
pass: `a`

**Comment by kellijohnson-NOAA** [comment]
Currently, I am running this locally and Chris is re-running on AWS and they both appear to be working.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin i think we can close this right?

**Comment by cgrandin** [comment]
Yes this has been done and incorporated into the results
