### ISSUE TITLE
Describe in assessment document how we ran this year's models

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#882]
The input files will be in the appendices as usual, so need to give the functions used to run the NUTS models, including the setting, such as `adapt_delta`. We had a lot of details the first year we did NUTS, then last year functionalised it but I don't think spelled out the final commands. 
Will be useful going forward.

**Comment by aaronmberger-nwfsc** [comment]
The very first paragraph of the Assessment model results section, Model fit subsection, might be a good place to add more details about settings used to get the 8,000 (or however many) MCMC samples.

**Comment by andrew-edwards** [comment]
Yep, and even just a few lines of code as it seems to be mostly functionalised. Or we go with 'Chris ran all the models from his phone'.
And mention the AWS and how many cores we used.

**Comment by kellijohnson-NOAA** [comment]
Current text
https://github.com/pacific-hake/hake-assessment/blob/4fc2f78b967a42f62278b69b130b18f5c838e9e9/doc/assessment-section/assessment-section.rnw#L668-L672

Proposed text
```
The {\tt adnuts} R package was used to apply the NUTS algorithm to produce \Sexpr{f(num.mcmc.samples)}
MCMC samples to describe posterior distributions for model parameters and derived
quantities.  This is nearly a ten-fold increase in samples from the
2020 assessment \citep{JTC2020} and earlier and a 33\% increase in samples from last
years assessment \citep{JTC2021}. Utilization of Amazon Web Services (AWS) and
high performance computers facilitated the increased number of samples
despite the short timeline between when the data were available and the assessment was due.
```

@crandin do you want to add a sentence about the workflow in `run_adnuts()`, i.e., (1) pilot, (2) mass matrix, (3) sample with burn in, convergence criteria, and anything else?

**Comment by cgrandin** [comment]
Yes, I'll have a go at it

**Comment by cgrandin** [comment]
I added quite a bit of detail. I'm not sure if it really belongs there but there also doesn't seem anywhere else to put it!

**Comment by aaronmberger-nwfsc** [comment]
What about in the appendix for base model diagnostics?  We have model fit there so it might work to have the specifics of the run that resulted in those diagnostics there to start.

**Comment by andrew-edwards** [comment]
I moved it earlier to more of a Methods-y section, which fitted well.

**Comment by andrew-edwards** [comment]
Any chance we can add some actual commands? I didn't actually run anything this year, and it would help for next year. Or maybe in the README at least.

**Comment by kellijohnson-NOAA** [comment]
I don't think the document is the place for commands but the readme or a wiki would be great.

**Comment by andrew-edwards** [comment]
Yes, README probably best (I never remember about Wikis). Can wait for now though....

**Comment by cgrandin** [comment]
I'll put it on a Wiki and make a link on the Readme.md
