### ISSUE TITLE
remove age 1 column in age 2+ survey age proportion table

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#886]
The age 1 column should be removed to not introduce confusion in Table 11 as this is an age-2+ survey.

**Comment by andrew-edwards** [comment]
They're all zeros though (and were last year). Maybe we can just tweak the caption to say age-2+.

**Comment by andrew-edwards** [comment]
Though I see that some refs to Table 11 should be Table 12. Will fix.
