### ISSUE TITLE
Rebuild the .rds files and then everyone download

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#887]
- [x] Chris to rebuild all the .rds files EXCEPT last.yr.base.model, as `calc.mcmc()` no longer dividing by 2 in 9bfca8e.
No rush since may be re-running base model, and age-1 index, and maybe the bridging models (#880).
 
Tick off when you've downloaded the new .rds files:
- [x] Chris
- [x] Kelli
- [x] Aaron
- [x] Andy

- [x] Andy will check that this fixes the Tables and Figures mentioned in #820.

**Comment by aaronmberger-nwfsc** [comment]
Just noting that I changed a forecast quantity, but this should be taken care of when we rebuild the rds file which hasn't been done yet.  The change was to update the 2021 TAC forecast run to the correct value, 473880, as it was still set at the 2020 TAC of 529290.

**Comment by cgrandin** [comment]
Everything is done except for the base model. I didn't bother because we may be changing it Mon Jan 24. If it changes it will just be for diagnostic purposes and should not affect the parameter estimates.

**Comment by andrew-edwards** [comment]
@chris Do you have time to rebuild the base model .rds? I know it will likely get redone anyway, but there's a bunch of results/figures that can't quite be checked until it's re-run (but are fixed in the build .rds code). Depends when the model's being re-run with new catch value.

**Comment by cgrandin** [comment]
I re-ran the forecasting last night and went to bed but the build RDS failed, so I am trying again now.

**Comment by cgrandin** [comment]
Base model with "good" diagnostics and corrected forecast value done. It is huge, 3.3 GB. Download like this:

`s3_quick_download("models/2022.01.10_base_v2/2022.01.10_base_v2.rds")`

If that fails try this:

`s3_download("models/2022.01.10_base_v2/2022.01.10_base_v2.rds")`

**Comment by andrew-edwards** [comment]
Presumably will also need
```
s3_quick_download(folders="models/2022.01.10_base_v2", ext = "ss")
```
for the appendices.

**Comment by cgrandin** [comment]
`s3_quick_download()` only works with a vector of exactly named files, not with ext because there is no index for it to compare to. Downloading the index (list of files) is why it takes so long. There are like 5,000,000 files!!

**Comment by andrew-edwards** [comment]
Thought so, it worked okay. Just building....

**Comment by kellijohnson-NOAA** [comment]
everyone checked off their name, so closing
