### ISSUE TITLE
Remaining csv files to update

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#888]
All major csv files are updated but a few remain:
- [x] assessment-changes.csv needs Dirichlet Mult values and number of mcmc iterations once we have our final base model confirmed
- [x] assessment-history.csv needs our SSB time series for this year once final base confirmed
- [x] ovary-samples.csv needs 2021 updates when sent by Melissa
- [x] depth-us-atsea-bottom.csv needs 2021 values
- [x] depth-us-atsea-fishing.csv needs 2021 values

**Comment by andrew-edwards** [comment]
`git revert 2172b73` should make the fishing depth Figure 6 work once last two boxes above are ticked. Or revert it manually in the code (see above commit).

**Comment by andrew-edwards** [comment]
Figure 6 works now.

**Comment by andrew-edwards** [comment]
Second checkbox above will fix Figure 56, which currently shows half the spawning biomass.

**Comment by aaronmberger-nwfsc** [comment]
closed with https://github.com/pacific-hake/hake-assessment/commit/6be9c9be806e931e48ab7658c80d89c54d339f9e
