### ISSUE TITLE
increase ADMB convergence

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#889]
## ADMB

1. Compiled ADMB using 
2. Compiled ADMB using [update_hess_step commit](https://github.com/Cole-Monnahan-NOAA/admb/commits/update_hess_step) commit [8d04fe2](https://github.com/Cole-Monnahan-NOAA/admb/commit/8d04fe283eb02394f7c579d5c7107c3df6f48b03)

## Comparison of ADMB in normal vanilla mode

* In MLE mode, ss_summary.sso were exactly the same.
* message to screen `  ic > imax  in fminim is answer attained ?` was only printed to the screen in (1) not (2).
* 297 iterations
* 1750 iterations for the hessian
* Final gradient: 3.80706e-05

## Comparison of ADMB with hess_step in MLE

* 2 Hessian steps to reduce maximum gradient
* small (5th and 6th decimal place) changes in estimates of recruitment, selectivity parameter deviations
* smaller gradient 3.80706e-05 to 0
* reduced NLL by 1.40972e-11
* strong evidence of convergence to a mode with quadratic log-likelihood surface
* took longer to run, 1.18 mins instead of 53.73 seconds

## Comparison of ADMB with hess_step in MCMC

More to come from @cgrandin

**Comment by cgrandin** [comment]
I didn't see much difference with this although it does bring the gradients down to 0 most of the time.
Our issue with diagnostics getting worse was due to not running the RWM "pilot" part of the adnuts routine prior to generating the mass matrix.
