### ISSUE TITLE
Create new MCMC trace plot for age-1 index

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#890]
I'm working on an equivalent of Figure 18 (MCMC trace plots for biomass survey index) for the age-1 survey. It then makes sense to:
- [x] replace Figure 11 with a plot of just the age-1 survey
- [x] have a Figure 11 equivalent in the age-1 excluded appendix, as the figure is showing the reasonable fit to the age-1 when the age-1 index is excluded. 
- [x] Update a bit of the new text regarding age-1 index.
- [x] Add an mcmc fit figure for the age1 index just after the similar figure (18) that we used for the 2+ survey.

**Comment by aaronmberger-nwfsc** [comment]
Agree, that makes sense. I edited it to add one more thing.

**Comment by andrew-edwards** [comment]
Ha ha. So here's the new trace plot (haven't tweaked axis and legend yet):

![image](https://user-images.githubusercontent.com/6977190/150603618-62370099-470c-420c-a111-c340683c564e.png)

Some years above, some below.

Figure 11 data were scaled to match the data (because the model didn't use the data). Which is why the numbers in that don't match the `age.1.index` values or those in the new plot (that threw me for a bit). 

The trace plot figure looks good - I don't need to scale by a q or use `base.model$mcmc$"Q_extraSD_Age1_Survey(3)"` do I? RT says they don't think the q on the age-1 is near 1 (so it's a relative index not an absolute). Think I'm just forgetting something here...

**Comment by aaronmberger-nwfsc** [comment]
Looks good and no you don't need to scale by a q here.  If you were comparing this index to some measure of absolute age-1 then you would, but we don't need that here. Yes, just a relative index with an analytical derived q (no q estimates)

**Comment by andrew-edwards** [comment]
Thanks. It is an absolute measure of age-1 though (numbers of fish, output from the model). (Maybe you meant relative).

**Comment by aaronmberger-nwfsc** [comment]
ha ha, semantics.  The survey is an absolute measure of age-1 from what they see, but effectively it is a relative index because q does not = 1.

**Comment by andrew-edwards** [comment]
- [ ] Something still to fix related to above commit, since numbers don't match Table 17 or the recruitment plots. Will come back to fresh.

**Comment by andrew-edwards** [comment]
- [ ] Also include the revised Figure 11 (age-1 survey without fits) in the Exec Summary? Would probably make sense. I think it best to have a more intuitive linear y-axis than the log axis.

**Comment by andrew-edwards** [comment]
Given these comments, I'm going with 'Relative age-1 index (billions of fish)' as the y-axis. Maybe caption can say that it's relative because catchability is not assumed to equal 1. Okay @aaronmberger-nwfsc ?

**Comment by aaronmberger-nwfsc** [comment]
Yes, that's fine.  I guess technically our acoustic survey is also a relative index because catchability is not = 1 (it's very close though).  I think we are fine calling it relative age-1 index b/c Q is so different than one, and it matches what we think - that the survey doesn't attempt to get all age-1s and the survey work up doesn't include kriging like the age-2+ survey does.

**Comment by andrew-edwards** [comment]
That's a better reason (when just showing data) than talking about catchability. I'll add that into caption, thanks.

**Comment by aaronmberger-nwfsc** [comment]
Andy: wrt to your remaining bullet at the top - please check over the new paragraph in the Model Results Section - Model Fit; paragraph starting "The base model fit to the index of age-1...";  I also added a couple sentence related to the age-1 index in the Model Uncertainty section.
