### ISSUE TITLE
Include new survey map figures

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#891]
I got them from Julia but they're 9Mb (and double the size of our .pdf), when last time were 300kb and 735kb and we shared them here. 

So not using new ones yet to see if we can get smaller ones.

Then `git revert 142ffede`

**Comment by cgrandin** [comment]
If you want I can open it in photoshop and save it as non-vector type

**Comment by andrew-edwards** [comment]
It's okay, all done with magick (that I'd put on our main README before, but now have it as a comment). Lots of back and forth by email with the figures, but finally got there.
