### ISSUE TITLE
Squid plots broken for MCMC

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#893]
The problem manifests inside the `r4ss` function `SSplotRetroRecruits ()` .

Setting browser at line 199 of the file, the data frame  `recvals` shows the years we are interested in as having labels "Multiple_labels_*" and all NA values for the years 2011 - 2020. 

I seem to recall something similar last year with "Multiple_labels" so I'll start there.

![image](https://user-images.githubusercontent.com/4551051/150755166-28dba55d-8c25-47bd-8c74-c9bdd78b5f55.png)

**Comment by cgrandin** [comment]
The hack works for now. But, everyone needs to use my fork of r4ss: https://www.github.com/cgrandin/r4ss to make the plot work.

@kellijohnson-NOAA If you want to fix this better in r4ss/r4ss that's fine but we could just continue using my working fork and work on other things if you want until the pressure is off!

**Comment by andrew-edwards** [comment]
FYI I wrote new code to show retro results on the past performance idea (new Figs 62-65). I wrote the code based on last year's .rds files and it worked fine, then it also worked fine with the new 2022 results. Just mentioning in case that helps diagnose.

**Comment by cgrandin** [comment]
You **MUST** use `cgrandin/r4ss`, that's where the fix is

**Comment by andrew-edwards** [comment]
Re-opening just so everyone updates and ticks a box, else this might get missed. I can't update yet since am downloading files and I'll need to wait until updating package. 
- [ ] Kelli
- [ ] Aaron
- [ ] Chris

**Comment by cgrandin** [comment]
Kelli isn't building the doc so I'll close this with hers unchecked
