### ISSUE TITLE
Monday/Tuesda - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#895]
Chris:
- [x] run some more tests
- [x] fix squid plot if time
- [x] create new table if time
- [x] Creating new .rds file

Andy:
- [x] fix non-building age-1 index figure, and tweak Exec Summary one
- [x] add new survey maps (just waiting for final version from Julia)
- [x] Check and finish text in 3.10 PERFORMANCE OF PAST PROJECTIONS section now we have the updated results.
- [ ] Read through Exec Summary once new .rds file is built.
- [x] commit 4d2dec11e tweaks (see comments)
- [ ] Finalise text for age-1 index Appendix.
- [x] Finalise text for new Appendix H (recruitment plots).
- [ ] Check Kelli's latest commit regarding #800.  
- [x] Fixing all new decision tables, #855.

Aaron:
- [x] Carry on with Exec Summary
- [x] Main text: model results section 3.4.1
- [x] Uploading base model results for Chris to make new .rds file.

Kelli:
- [x] Data Section
- [ ] Continue on sample size stuff (SRG response)
- [ ] WHAM! 

Remember to all re-load the .rds files #887.

**Comment by aaronmberger-nwfsc** [comment]
I think I added text in the data section referring to Figure 11, so need to double check that it still makes sense. It might be part of the justification for it and that's why I thought to keep it.

**Comment by andrew-edwards** [comment]
Thanks. This should refer to Figure 11 from a previous assessment though, else doesn't really make sense:
![image](https://user-images.githubusercontent.com/6977190/150859128-aec3ea2e-0379-4e2f-b536-6e9d9551fefa.png)

Also, this should say 'biomass estimate' just to clarify. I haven't read through this section at all, so won't make any further changes yet (except these two if that's okay).

**Comment by andrew-edwards** [comment]
Other references to Figure 11 are good - just talk about the data.

**Comment by andrew-edwards** [comment]
Thanks. This should refer to Figure 11 from a previous assessment though, else doesn't really make sense:

![image](https://user-images.githubusercontent.com/6977190/150859128-aec3ea2e-0379-4e2f-b536-6e9d9551fefa.png)

Also, this should say 'biomass estimate' just to clarify:
![image](https://user-images.githubusercontent.com/6977190/150859755-9c2c9835-1318-4084-950a-ece4a5779f0a.png)

 I haven't read through this section at all, so won't make any further changes yet (except these two if that's okay).

All other refs to Figure 11 are just about data, which is still correct.

**Comment by aaronmberger-nwfsc** [comment]
How about it just refers to the new Figure 11 location in that age-1 survey appendix?

And yes, changing 'data' to 'biomass estimate' is good.

**Comment by andrew-edwards** [comment]
I ref'ed the previous assessment for now, as not sure that sens model mentioned yet (and seems better to first reference previous results to justify the new base model). I'll read through all text at some point and see if it does make more sense to refer to the new Figure (Figure G.3).

**Comment by andrew-edwards** [comment]
Moved the incompleted ones to Wednesday.
