### ISSUE TITLE
links in table of contents are broken for tables and figures

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#896]
Tables takes you too references and figures takes you to tables.

**Comment by cgrandin** [comment]
This seems ok for me now

**Comment by andrew-edwards** [comment]
Works for me. Did you latex it a few times?

**Comment by kellijohnson-NOAA** [comment]
kk, probably the issue was just what @andrew-edwards mentioned. thanks for checking.
