### ISSUE TITLE
make.forecast.depletion.comparison.plot() broken in Executive Summary

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#900]
Since the new upload, this is broken.
Comment it out  while I try to fix it.

**Comment by cgrandin** [comment]
Problem is that all the derived quantities in the Report.sso file are zero for this new run. 

This lead me to wondering why those values were being used in the forecast plot and I think we have been showing MLE plot this whole time for this plot:

![image](https://user-images.githubusercontent.com/4551051/151214455-961ebf30-2319-4a44-8554-4cad7ee54ade.png)

**Comment by cgrandin** [comment]
It should look like this right?
![image](https://user-images.githubusercontent.com/4551051/151214861-6f04845a-e897-4682-b7ca-b71100192c53.png)

**Comment by andrew-edwards** [comment]
Wow. Yes you are correct. Figures in last year's assessment look like the two above - i.e. are also wrong.

**Comment by andrew-edwards** [comment]
No - the x-axes are different scales.

**Comment by andrew-edwards** [comment]
Last year's look okay.

**Comment by cgrandin** [comment]
Yes, but the values come from the Report.sso file, not the derived posteriors file. The red line is the Bratio values.

**Comment by kellijohnson-NOAA** [comment]
Chris, I think you are correct in that before we were probably using derived quantities from the Report.sso file which would have been MLE results. I just looked and Report_mce_0001.sso has values in the derived_quantities section but Report.sso does not. I think this agrees with what you are saying, right?

**Comment by andrew-edwards** [comment]
Note that:
- [ ] figures have different options (as to what they show), so standardise
- [ ] caption in main figures prob needs correcting as has a hardwired catch in it (though this won't be needed if we make it same as exec summary version).
Chris - I can do those when fig is fixed. Note you can just revert the above two commits to build again. Or I can, don't worry....

**Comment by cgrandin** [comment]
Done. Make sure to do this:

`devtools::install_github("cgrandin/r4ss")`

**Comment by andrew-edwards** [comment]
I have to fix those last two things (checkboxes).

**Comment by andrew-edwards** [comment]
The credible intervals aren't showing up for me - I updated the r4ss. Works okay for others (if so then don't worry)?

**Comment by cgrandin** [comment]
Yes it is for me

**Comment by aaronmberger-nwfsc** [comment]
Mine does not show 95% credibility intervals; I also updated r4ss

**Comment by cgrandin** [comment]
Did you delete the entry in the knitr-cache?
Here's mine
![image](https://user-images.githubusercontent.com/4551051/151265368-98ea6379-c573-45fa-8b3f-8514403d9830.png)

**Comment by aaronmberger-nwfsc** [comment]
Yes, I deleted the entry and then tried again starting fresh.  Both times no intervals.

**Comment by andrew-edwards** [comment]
I didn't update the 20 or so packages that r4ss depends on. Blatantly ignoring R's recommendation to update them all:
```
Downloading GitHub repo cgrandin/r4ss@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                   
 2: CRAN packages only                    
 3: None                                  
 4: systemfonts (1.0.2   -> 1.0.3 ) [CRAN]
 5: jsonlite    (1.7.2   -> 1.7.3 ) [CRAN]
 6: magrittr    (2.0.1   -> 2.0.2 ) [CRAN]
 7: rlang       (0.4.11  -> 1.0.0 ) [CRAN]
 8: digest      (0.6.27  -> 0.6.29) [CRAN]
 9: stringi     (1.6.2   -> 1.7.6 ) [CRAN]
10: glue        (1.4.2   -> 1.6.1 ) [CRAN]
11: htmltools   (0.5.1.1 -> 0.5.2 ) [CRAN]
12: yaml        (2.2.1   -> 2.2.2 ) [CRAN]
13: utf8        (1.2.1   -> 1.2.2 ) [CRAN]
14: cli         (3.1.0   -> 3.1.1 ) [CRAN]
15: pillar      (1.6.4   -> 1.6.5 ) [CRAN]
16: fansi       (0.5.0   -> 1.0.2 ) [CRAN]
17: curl        (4.3.1   -> 4.3.2 ) [CRAN]
18: xml2        (1.3.2   -> 1.3.3 ) [CRAN]
19: tibble      (3.1.2   -> 3.1.6 ) [CRAN]
20: colorspace  (2.0-1   -> 2.0-2 ) [CRAN]
21: dplyr       (1.0.6   -> 1.0.7 ) [CRAN]
```
Could take a chance and just try `colorspace`. Involves restarting R so not going to mess around with yet.

**Comment by kellijohnson-NOAA** [comment]
you can do
```
devtools::unload(package = "r4ss")
devtools::unload(package = "colorspace")
install.packages("colorspace")
library(r4ss)
```

**Comment by cgrandin** [comment]
I didn’t update anything when I got that screen

**Comment by andrew-edwards** [comment]
Thanks Kelli (added that to my R notes - useful). 
Didn't fix the problem though ;) But I was guessing it was one package. 
Chris - but it depends when we've each last updated each of a bazillion packages. Not going to worry about it for now..... (I may just try `glue` maybe).

**Comment by andrew-edwards** [comment]
`glue` didn't work. I get this warning:
```
> library(r4ss)
Attaching package: 'r4ss'
The following object is masked _by_ '.GlobalEnv':
    rich.colors.short
```
but can't tell if I had that before (it doesn't show up when I do a fresh `knitr`, so can't scroll back to old behaviour). Not going to worry about it for now. For real this time.

**Comment by andrew-edwards** [comment]
I updated all dependent packages and still no intervals. BUT it wouldn't let me update the following:
```
Doing all, but got Warning  messages and it couldn't unlock these files (so it
didn't update), I'll try Kelli's trick at some point:
magrittr.dll: Permission denied
rlang.dll: Permission denied
glue.dll
cli.dll
curl.dll
```
I'll do those using Kelli's trick (before I would go in and delete files, so thanks), just not yet.

**Comment by cgrandin** [comment]
You should do it in 'Rgui' with nothing loaded

**Comment by andrew-edwards** [comment]
You still have to close other R sessions though (but not with Kelli's method).

**Comment by aaronmberger-nwfsc** [comment]
I've started fresh with everything, R session, knitr cache, reload cgrandin/r4ss and still no intervals, I dunno

**Comment by andrew-edwards** [comment]
Credible intervals still not showing for me. I haven't tried updating those final packages yet - think have to go in and manually delete some locked files. Not urgent as we'll use Chris's build.

**Comment by andrew-edwards** [comment]
Not doing the final package installs today, as we'll use Chris' build. Will try them at some point.

**Comment by andrew-edwards** [comment]
So this figure builds fine for me in the management presentation. Slightly different workflow than the doc in that we make .eps files and then a .pdf (we switched to .png for the document for web accessibility, but didn't bother for the talks).
So, strangely:
- the .eps version comes out correct (with credible intervals)
- plotting straight to an R window loses the credible intervals
- plotting to a .png file also loses the credible intervals.

Not worrying about, just noting, since we'll still use Chris's final build for the document, and I'll be fine for my talk.

**Comment by cgrandin** [comment]
When is the last time you upgraded R?

**Comment by andrew-edwards** [comment]
Ooh, last May: R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
I did check our hake README file and it said 4.0.3+ was okay, but obviously it's hard for us to know exactly. So it's probably that and maybe the final few packages that I couldn't update. But can live with it for now.
@aaronmberger-nwfsc - what R version are you using?

**Comment by cgrandin** [comment]
That should be fine, it just sounds like there is an issue with your PNG renderer which is inside R. You might want to re-install R

**Comment by aaronmberger-nwfsc** [comment]
$version.string
[1] "R version 4.1.2 (2021-11-01)"

$nickname
[1] "Bird Hippie"

**Comment by cgrandin** [comment]
I have a much older version... Maybe they broke the PNG renderer in the new version..

```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out    
```

**Comment by cgrandin** [comment]
But your transparencies work in the other plots so... I dunno

**Comment by andrew-edwards** [comment]
Yeah, just that one. Not to worry, just good to keep track of it here.
