### ISSUE TITLE
KM to edit Research need for MSE

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#903]
https://github.com/pacific-hake/hake-assessment/blob/9d11bc9d2fbf61fc97cad76b053d5a9e0d66bb0b/doc/executive-summary/research-needs.rnw#L24-L39

@kristinmarshall-NOAA can you make sure that this text is appropriate for what we need for the MSE? I just want to make sure that it aligns with the funding we got and are asking for. Thanks. Feel free to put edits here or push directly to the repo.

**Comment by andrew-edwards** [comment]
@kristinmarshall-NOAA  - are you able to confirm that this is good? [We're submitting today, hopefully!]

**Comment by kristinmarshall-NOAA** [comment]
This looks good!  I added growth to the list of links and just pushed a change.
