### ISSUE TITLE
Table 25 additions wrt age-1 index

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#905]
Add under Parameters
Additional age-1 index SD
Catchability: age-1 index (q)

Change existing Catchability to:
Catchability: survey (q)

**Comment by andrew-edwards** [comment]
Related: Table 32 doesn't show the current q for some sens runs. Yet Table 33 does.

And there were two "DUMMY FOR NOW" sens placeholders still that we can presumably get rid of as presumably no more sens analyses to do.

**Comment by cgrandin** [comment]
We have to run those in extra-mcmc mode. Thought I was done running stuff

**Comment by andrew-edwards** [comment]
Re 'Confused' - I'll fix those placeholder ones (it might be a few spots).

**Comment by cgrandin** [comment]
Note that to get the age-1 parameters into Table 25 you need a new base model RDS. I will complete Table 32 which needs the output from the 6 sensitivities to fix and then get you to download them all.

**Comment by andrew-edwards** [comment]
I'm combining Tables 33 and 34 (Phi t.v. selectivity and max age selectivity sens) while removing the un-needed DUMMY FOR NOW columns.

**Comment by andrew-edwards** [comment]
Looking at Aaron's top post. For the last one we should go with:
Catchability: biomass index (q)

And have different symbols (not the same q). So maybe q_1 for age-1 and q_b for biomass survey?

**Comment by andrew-edwards** [comment]
And if so, then change elsewhere such as assessment-section.rnw:
```
\subsection{Model uncertainty}\label{sec:assessment-model-uncertainty}
 % Manual 2020 done
The base assessment model integrates over the substantial uncertainty associated
with several important model parameters including: acoustic survey and age-1 index catchability
($q$), the magnitude of the stock (via the $\log R_0$ parameter for equilibrium
```

**Comment by cgrandin** [comment]
I'll change them in the figure code

**Comment by cgrandin** [comment]
![image](https://user-images.githubusercontent.com/4551051/151461944-d3f8c327-7711-43a5-bf50-6512127f1e1c.png)

**Comment by cgrandin** [comment]
I'm changing the assessment section as well

**Comment by andrew-edwards** [comment]
I'm just on that Chris - I can do it.

**Comment by andrew-edwards** [comment]
Didn't we want 'acoustic survey 'and 'survey' to be 'biomass index'?

**Comment by cgrandin** [comment]
Oh yea, I justt added the new parameter names, go ahead I'm done

**Comment by andrew-edwards** [comment]
Okay, I'll do it.

**Comment by cgrandin** [comment]
My screenshot above is correct
