### ISSUE TITLE
Tease out why 2021 biomass is much higher than estimated in last year's assessment

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#906]
Median is 37% higher. [Was going to flesh out ideas here, but I think it's pretty much all done in the Bridging.....]
And B_2021/B0 was 59% in 2021 assessment, and 75% this year, so a fair difference (that's 27% higher). 

We mention this in Exec Summary, so need to succinctly tease out why:
![image](https://user-images.githubusercontent.com/6977190/151270484-70411c2a-051f-49fc-b9ae-5ea913b076f8.png)

Here's the bridging text:

![image](https://user-images.githubusercontent.com/6977190/151270752-a75310bc-3eb3-46a3-8f80-7500586fbf83.png)

I think we can just remove 'slight' from 'slight increase in recent recruitment' as the biomass does go up quite a bit. This figure doesn't look so dramatic though, but it is indeed driving the change from last year's values. 
![image](https://user-images.githubusercontent.com/6977190/151270956-ea78d760-eb9f-4e92-b92f-c9b8b070e7a7.png)

So maybe can just say in Exec Summary:
"due to the introduction of the age-1 index increasing the estimated 2016 and 2018 recruitments."

Need to check consistency with what's said elsewhere (just after). Seem okay?

**Comment by aaronmberger-nwfsc** [comment]
I think the recent recruitment shifts are mostly it, the other (smaller) part is higher R0 which looks like it increased SSB trajectory as well. Also I guess if you look at the bridging plots, the addition of the 2021 acoustic survey causes SSB to increase some too, especially in the last few years. But most of it is the age-1 index (second set of bridging plots)

**Comment by andrew-edwards** [comment]
Yep, thanks. Those wide bridging plots kind of mask some of the results (with the funny aspect ratio).

**Comment by andrew-edwards** [comment]
I added some text, completely forgetting to look at this. Tweaking again to:
```
The increase appears to be due to the addition of survey data, namely the 2021
biomass index and age compositions, plus the full age-1 index.
```
in Exec Summary, plus same with a link to bridging section in main text.
