### ISSUE TITLE
Decision Table - fishing intensity

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#910]
Last row of last scenario is all 0's.

**Comment by cgrandin** [comment]
I just looked at the forecast file and it has a catch of zero for 2025. This could take a while to figure out since it's the same code that's been used every year

**Comment by cgrandin** [comment]
I figured this out, have to re-run the catch levels and forecasting for the stable catch case

**Comment by andrew-edwards** [comment]
And also for n (default HR), to fix the NA in Table k:

![image](https://user-images.githubusercontent.com/6977190/151628293-32a1b152-c45b-46ea-b283-53e0009a5b57.png)

**Comment by cgrandin** [comment]
These are fixed once you get the new base mode with corrected forecasting

**Comment by andrew-edwards** [comment]
So we have to download the new .rds file anyway, yes?
