### ISSUE TITLE
Figure 57 retrospective

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#911]
Whoever added 2022, thanks.
The 2021 line is transparent though

![image](https://user-images.githubusercontent.com/4551051/151454880-0600c608-bd09-40e4-9dcc-4267f5138360.png)

**Comment by aaronmberger-nwfsc** [comment]
And the 2022 looks like SSB/2 again, even though it is correct in the csv

**Comment by andrew-edwards** [comment]
The transparent is easy. I took a quick look at the /2 the other day but saw it was correct as Aaron says.

**Comment by cgrandin** [comment]
I'll take a look

**Comment by cgrandin** [comment]
Fixed in 915dcec58507c1399e06ad94eebb22c3e4978c77
