### ISSUE TITLE
Weight-at-age heatmaps (Figures 13 and 14) are missing the projection years

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#912]
The current code still produces the correct figure using last year's base model:
```
weight.at.age.heatmap(last.yr.base.model,
                      proj.line.yr = last.yr.base.model$endyr,
                      extrap.mask = weight_age_extrapolation_mask,
                      longterm.mean.ages = NULL, colour = "both")
```

Kelli made some changes 11 months ago in https://github.com/pacific-hake/hake-assessment/blame/master/R/figures-size-at-age.R  but I don't think it's those, given the above code works. 

So presumably something to do with new format of output?

**Comment by kellijohnson-NOAA** [comment]
I am pretty sure this is just because the csv files are not updated, i.e., last row is 2021 not 2025. My fault. I will take care of it.

**Comment by aaronmberger-nwfsc** [comment]
Dang, I missed that csv too when going through them.

**Comment by kellijohnson-NOAA** [comment]
Okay, I actually had updated the csv files with fd7f6c8. Turns out that the figure won't build when the standard call to `r4ss::SS_output()` is used. Need to use `SS_output(wtfile = "wtatage.ss")` to read in the weight-at-age file. So @cgrandin this will be on you I think?

**Comment by cgrandin** [comment]
The reason for this is that the `wtatage.ss_new` created by the new SS version does not contain the projections wheareas the old one did. This is read in by `SS_output()` so that will need to be changed. I can attempt to do that or we can read in what's in the `wtatage.ss` file as it has up to 2024 in it.

**Comment by cgrandin** [comment]
After pulling the commit, rather than fetching a new base mode RDS etc, just modify yours to make it work:

```
base.model <- readRDS("models/2022.01.10_base_v2/2022.01.10_base_v2.rds")
k <- load_ss_files("models/2022.01.10_base_v2")
base.model$wtatage <- k$wtatage
RDS(base.model, "models/2022.01.10_base_v2/2022.01.10_base_v2.rds")
```

**Comment by aaronmberger-nwfsc** [comment]
Most of us only have the rds file, so we will need to get model input and report files, correct?

**Comment by andrew-edwards** [comment]
Seems safer to just fetch the new .rds file yes? May be out of sync with output files.

**Comment by andrew-edwards** [comment]
Re-opening just to track we all do this (easy to miss otherwise):
- [ ] Aaron
- [ ] Kelli
- [ ] Andy

**Comment by cgrandin** [comment]
I'll post an RDS file containing the wtatage in Slack..
I changed the above code

**Comment by kellijohnson-NOAA** [comment]
kk all boxes are checked, @cgrandin do you want to close this now?
