### ISSUE TITLE
NA in Table k

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#914]
![image](https://user-images.githubusercontent.com/4551051/151633337-19286023-ef04-495e-959d-21390d8afff5.png)

**Comment by andrew-edwards** [comment]
Sorry, definitely doesn't work for me. I thought the new .rds would fix it (as I mentioned in another issue), but doesn't seem to.
I'd grabbed the latest .rds file from AWS about 5pm; should be good yes?

**Comment by cgrandin** [comment]
It would be much quicker if I gave you the code to attach again as opposed to waiting for 2 hrs upload/download

**Comment by andrew-edwards** [comment]
Okay, just put the code here. 

Though see end of #800 - I wonder if that requires rebuilding the .rds anyway? 

Just re-opening this Issue (sorry!) until it's fully fixed, else it will get lost.

**Comment by cgrandin** [comment]
It's uploaded now, and has all the changes we've done the last couple days

**Comment by cgrandin** [comment]
Download the base model RDS file from S3.
Last person to check the box, close the issue:
- [ ] Kelli
- [ ] Andy
