### ISSUE TITLE
Last two tables have an error - Rerun models

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#915]
I have to re-run models 43, 44, and 45 to get the extra-mcmc. I REALLY have to remember to run them all the first time around next year!

**Comment by andrew-edwards** [comment]
Thanks. I think this was mentioned somewhere in Slack. But maybe two long days ago....

**Comment by cgrandin** [comment]
All done. Download from S3, last to check box close issue
```
s3_quick_download(c("models/2022.01.43_maxSel_Age5/2022.01.43_maxSel_Age5.rds",
                    "models/2022.01.44_maxSel_Age7/2022.01.44_maxSel_Age7.rds",
                    "models/2022.01.45_maxSel_Age8/2022.01.45_maxSel_Age8.rds"))
```
- [ ] Andy
- [ ] Kelli

**Comment by cgrandin** [comment]
This didn't fix the issue, so I will come back to this later and fix. Don't close

**Comment by cgrandin** [comment]
The commit above fixes them

**Comment by cgrandin** [comment]
@kellijohnson-NOAA are you downloading models?  If not let's close this
