### ISSUE TITLE
fore.catch.prop definition should have age-incremented values from last year, but doesn't.

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#920]
Just updating the end of Model Projections, paragraph that says `**[not incremented manual years yet`. 

So the numbers shown match (more or less) those in last year's assessment, but they shouldn't as the ages haven't been updated yet. So it's still estimating 12% of 2022 catch being age-11, but obviously these should be age-12 as from the 2010 cohort. So `forecatch.prop` is:
```
> fore.catch.prop
  Age0 Age1 Age2 Age3 Age4 Age5 Age6 Age7 Age8 Age9 Age10 Age11 Age12 Age13
1    0    4    4    3   15   27    0   25    1    2     0    12     1     1
  Age14 Age15 Age16 Age17 Age18 Age19 Age20
1     0     0     0     0     0     0     0
``` 
but the ages should all be one higher. 

It's defined as
```
# Estimated prop at age (numbers) of the catch in first forecast year ---------
fore.catch.prop <- as.data.frame( t(as.numeric(f(apply(base.model$extra.mcmc$natsel.prop, 2, median)* 100))))
names(fore.catch.prop) <- paste0("Age", 0:20)
```
which hasn't changed since last year (L449 of the blame: https://github.com/pacific-hake/hake-assessment/blame/master/R/custom-knitr-variables.R ). 

If I calculate the equivalent thing from last year's base model, the big cohorts show the same ages as above (but they shouldn't):
```
> fore.catch.prop.last.yr.base <- as.data.frame( t(as.numeric(f(apply(last.yr.base.model$extra.mcmc$natsel.prop, 2, median)* 100))))
> names(fore.catch.prop.last.yr.base) <- paste0("Age", 0:20)
> fore.catch.prop.last.yr.base
  Age0 Age1 Age2 Age3 Age4 Age5 Age6 Age7 Age8 Age9 Age10 Age11 Age12 Age13
1    0    1    6    1   16   20    0   27    1    2     0    12     1     1
  Age14 Age15 Age16 Age17 Age18 Age19 Age20
1     0     0     0     0     0     0     0
```

L1464 of the blame https://github.com/pacific-hake/hake-assessment/blame/master/doc/assessment-section/assessment-section.rnw shows that the values haven't been updated yet (the ages get incremented each year, after checking `fore.catch.prop` to add/remove any). 

So presumably it's one of those extra-mcmc changes that I'm not familiar with?

**Comment by andrew-edwards** [comment]
Just noticed Figure 40 (left) looks just like equivalent Figure 37 in last year's assessment. y-label incremented by a year but the fish didn't get any older 😮

**Comment by cgrandin** [comment]
Pretty sure I have figured this out. Due to changes in the output of `natsel` and `natsetwt` in the Report.sso file, the year reporting them is off by one compared to last year.

I just have to run the extra MCMC calculations again (not running the model, just the `fetch_extra_mcmc()` routine.

**Comment by cgrandin** [comment]
This is fixed . You need to download a new version of the base mode RDS from S3 and the plot will be correct.

**Comment by andrew-edwards** [comment]
Done, I'm just going to fix the text on p71.
