### ISSUE TITLE
Table G.9 has an NA, and Age-1 Appendix text needs a read through

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#922]
- [x] It just needs the same fix as Chris did for the base model. I'm fine to leave it for now to avoid more back and forth, and do it after submission (can mention in the caption). Unless it will keep Chris up at night ;)

- [x] Also I've done the text (the commit below) but it needs a read through - I can read again fresh tomorrow for sure. Gave some details about the retros, but, like last year, didn't go into details about decision tables etc. They're there for people to delve into.

**Comment by cgrandin** [comment]
I'm re-running the RDS generation code for non-age-1 model so it will fix this.

**Comment by andrew-edwards** [comment]
I knew you'd want to fix it ;)   Has to be done at some point anyway, so may as well.

**Comment by cgrandin** [comment]
Yes, and it only takes a minute to fire up a cloud machine to do it

**Comment by cgrandin** [comment]
Found out while doing this the forecasts are the old ones, so have to re-run those as well

**Comment by cgrandin** [comment]
The new age-1 RDS is on S3: Download:
```
s3_quick_download("models/2022.01.23_age1Survey/2022.01.23_age1Survey.rds")
```
- [ ] Andy
- [ ] Kelli

Whoever is last close issue

**Comment by kellijohnson-NOAA** [comment]
Edits to age-1 appendix are in c48b1117. Thanks for making that job easy 🥇

**Comment by cgrandin** [comment]
@andrew-edwards here it is
