### ISSUE TITLE
Make "Illustration of SPR" figure MCMC

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#923]
This needs Numbers-at-age from M and Numbers-at-age from Z, which are not extracted by the extra-mcmc code. We need to do this for 2023 or this plot won't work anymore.

It is currently MLE from 2021.

**Comment by andrew-edwards** [comment]
Fixed for 2022 in #834 with c5ef0886.

**Comment by aaronmberger-nwfsc** [comment]
I believe Chris has fixed this with 3c85451cd01bad074f6345881fd40e5bda73a3df
So closing now as I remove the ** in the caption.
