### ISSUE TITLE
Table 4 caption

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#924]
Pls Check this....

(**current protocols for the U.S. At-Sea sectors is three
fish every third haul).

**Comment by kellijohnson-NOAA** [comment]
Yes Sir. Just double-checked the [manual](https://media.fisheries.noaa.gov/2021-04/A-SHOP-Manual%202021-508-compliant-updated.pdf?null) and it still says 3 from every third haul.

![image](https://user-images.githubusercontent.com/4108564/151758143-a1eddcb8-f6e6-4dde-82fb-ece86e380f35.png)
