### ISSUE TITLE
Pre-1975 weigh-at-age heatmap projection values wrong?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#927]
- [x] The projection-period numbers match the historic ones, but they shouldn't. Looks quite different to this version from 25th Jan:

![image](https://user-images.githubusercontent.com/6977190/152395709-a765d97e-0fd9-4351-8522-1415affb85d2.png)

Comparing it to last year's version, it looks like:
1. pre-1975 values are wrong, and should be 0.01, 0.10, .... like they were in the screenshot above. 
2. the 0.02, 0.12, we currently have are correct for the projection years. 

- [x] Also we should show 2025 (as in the screenshot, though it was wrong), because we use that for the B_2025 calculations.  
- [x] And 1975 looks to have two sets of numbers over-written.

Think this happened near the end due to the projection years disappearing at one point.

**Comment by andrew-edwards** [comment]
That screenshot looks to match the `wtatage.ss` values that start at the bottom of p255 in the document ('wt at age for popn at beginning of the year, fleet = 0'. Looks like that's the relevant one. Also it doesn't have 2025, which I think would explain why 2025 got set to the pre-1975 values in the screenshot above (instead of same as other projection years).

So is the model assuming wt-at-age for 2025 the same as pre-1975 years rather than same as projection years? And so B_2025 values will be wrong?

**Comment by andrew-edwards** [comment]
The reason I was looking at this figure more carefully than had time to before, was to tease out why, with 0 catch, we certainly expect stock to increase from 2022 to 2023 (92% prob), and then (just) probably increase from 2023 to 2024 (53% prob). 

Tracing the diagonals in the heat map of the big cohorts (2017, 2016, 2014, 2010; age 5, 6, 8, 12 in 2022) they do all get heavier when a year older from 2022 to 2023 (and fecundity increases). [Interestingly their weight-at-ages all decreased from 2021 to 2022 as they crossed over the blue line in the heat map]. And the 2020 cohort is coming through, starting to contribute to spawning biomass in 2023. This presumably explains why the stock will increase from 2022 to 2023 without fishing (and even with heavy fishing it's 50-50). 

Then less of a jump in fecundity for the 2020 cohort from 2023 to 2024 (age 3 to 4 in Fig 12),  and incremental jumps for the other major cohorts. Hence, no definitive direction of stock from 2023 to 2024 (that's probably properly accounting for the large uncertainty in 2020 cohort - could still go either way). 

The cohort table (Table 22) shows a peak in cohort biomass around age-3 (or age-2), but that's total biomass and doesn't account for fecundity. So presumably combined with fecundity the spawning biomass contribution of the 2020 cohort (which is still highly uncertain) might be expected to decline from 2023 to 2024.

Just fleshing out ideas, please let me know if I'm wrong on anything. Maybe it is all just the 2020 cohort and I'm overthinking it. I expect someone will ask in the briefing meeting (I would), so wanted to have some thoughts worked out.

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards I think that you are right in that b/c 2025 was not specified, which is ENTIRELY my fault, that it is using values from a different year. Unfortunately, 
```
A negative value for year will fill the table from that year through the ending year of the forecast, overwriting anything that has already been read for those years.
```
and 1940 is negative thus being used for all years without information. 🤦

**Comment by andrew-edwards** [comment]
No worries, first time I looked carefully at the .ss files. I was hoping it wouldn't make a huge difference, but those big cohorts are age-8, 9, 11 and 15 in 2025, and comparing the top two rows for those ages in the screenshot above actually does show some substantial differences (we consistently used somewhat larger values than we should have). But, good news is that 2020 cohort would be age-5, for which we used 0.54 but should have used 0.55.

**Comment by kellijohnson-NOAA** [comment]
I didn't change any of the code from last year regarding the "data" and should have changed the number of forecast years. I think to stop this from happening in the future I will make the first year of the forecast negative such that it is used for all forecast years no matter how many there are.

**Comment by cgrandin** [comment]
I will carefully go through the table code again to see what is happening exactly. This is what happens when working at the 11th hour on code that creates more than one table..

**Comment by cgrandin** [comment]
The new version of SS only has output in wtatage.ss_new to 2021, last year it has output to 2023. So it no longer has output for forecast years (not sure if this is due to setting you mentioned @kellijohnson-NOAA )

**Comment by cgrandin** [comment]
What I changed 3 days ago: https://github.com/pacific-hake/hake-assessment/blame/master/R/figures-size-at-age.R

**Comment by andrew-edwards** [comment]
So.... I always thought that the 2021 weights-at-age, for example, were used for B_2021 (spawning biomass at start of 2021). But now, thanks to Kelli, realise that the 2020 weights would be used for B_2021. This makes sense because it's data from (throughout) 2020 that get used to assign weights to fish at the start of 2021. 

So B_2022 is based on the 2021 data (not the average of five years).

Looking at our text and slides I just think we were never explicit enough (so both approaches are consistent with what we wrote, hence my confusion).

Okay, so using the screenshot at the top if this Issue: the 2021 weights are:
age-2: 0.29
age-3: 0.52.

So these get used to calculate B_2021. BUT, for age-3 fish in 2022, which weight gets used? Is it:
a) the age-2 value from 2021 (because the 2022 age-3 fish were age-2 in 2021, so it's 'those fish'), or 
b) the age-3 value from 2021 because we're now talking about age-3 fish? 

I was originally trying to understand the projection results (as mentioned above somewhere), but they may all change anyway. But good to know for tracing cohorts through time. 
 
- [ ] Update text on p43 to clarify this. 
- [ ] Mention in mgt talk (verbally) when we mention the projection assumptions.

**Comment by cgrandin** [comment]
You need to re-make the figure now as I made changes to fix issues.. Don't look at the old one

**Comment by andrew-edwards** [comment]
I know the numbers aren't right. Just trying to understand how to interpret the figure (in general). Will wait for new one to try and understand results.

**Comment by andrew-edwards** [comment]
All good now - I'll just update the text in the document at some point.

**Comment by cgrandin** [comment]
The tables are both correct now.

I read through the weight-at-age section and searched the document for all instances of 'Figure 13' and 'Figures 13' and made sure everything was correct and it was. So closing this.
