### ISSUE TITLE
Check "Start of 2022" values in biomass decision table, they should match the value in table b

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#928]
They matched last year but the table format changed so this is probably the culprit

**Comment by cgrandin** [comment]
Fix #927 first and see if that corrects this. The two values are coming from:

`base.model$forecasts$`2022`$`01-0`$biomass`

`base.model$mcmccalcs$dmed[57]`

They should be the same but are not, possibly due to weight-at-age being different

**Comment by andrew-edwards** [comment]
The only modelling issue we thought wrong in #927 was that the 2025 wt-at-age used the historical values by mistake (because 2025 wasn't specified in the `wtatage.ss` file shown in the appendix).

Another problem seems to be that B_2022 (biomass at start of 2022) is calculated using two different wt-at-age assumptions. [I think because 2022 is kind of sometimes thought of as a forecast year?]. Aaron had said that some order of operations changed [presumably within SS] with wt-at-age this year.

**Comment by andrew-edwards** [comment]
Using what Chris had above, they are different with this year's base model, but not using last year's base model:
```
> base.model$forecasts[["2022"]][["01-0"]][["biomass"]]
            5%      25%      50%      75%      95%
2022 0.3542162 0.507432 0.646815 0.827445 1.194198
2023 0.4262010 0.628715 0.827604 1.091940 1.698354
2024 0.3258854 0.494339 0.671481 0.920383 1.603312
2025 0.2334712 0.367130 0.511052 0.729074 1.386230
> base.model$mcmccalcs$dmed[57]
     2022 
0.6910757 
```
69% is different to 50% in first row above.
For last year's base model:
```
> last.yr.base.model$forecasts[["2021"]][["01-0"]][["biomass"]]
            5%       25%       50%       75%      95%
2021 0.2844995 0.4467612 0.5922830 0.7966845 1.200041
2022 0.2832309 0.4411603 0.5844755 0.7991730 1.237446
2023 0.2157085 0.3331593 0.4500285 0.6317750 1.120434
> last.yr.base.model$mcmccalcs$dmed[56]
     2021 
0.5922814  
```
Both are 59%.
So it's a change in SS or in the saving of the SS output.

**Comment by andrew-edwards** [comment]
This year's base model for other 2022 catches gives the same 2022 biomass as the zero catch one shown above, correctly suggesting the catches are not impacting the 2022 biomass (but they're still different to the non-forecast runs):
```
base.model$forecasts[["2022"]][["02-180000"]][["biomass"]]
            5%      25%      50%      75%      95%
2022 0.3542162 0.507432 0.646815 0.827445 1.194198
2023 0.3853566 0.583178 0.780776 1.042680 1.643776
2024 0.3014752 0.467042 0.642816 0.889442 1.566230
2025 0.2196070 0.350473 0.493341 0.708848 1.361802
> base.model$forecasts[["2022"]][["03-225000"]][["biomass"]]
            5%      25%      50%      75%      95%
2022 0.3542162 0.507432 0.646815 0.827445 1.194198
2023 0.3747328 0.572164 0.768845 1.030990 1.630302
2024 0.2951864 0.460125 0.635612 0.880667 1.556268
2025 0.2165464 0.346158 0.488908 0.704427 1.356948
```

**Comment by andrew-edwards** [comment]
Possibilities are:
1. Issue with .rds file saving: Kelli ruled out by checking the above with .sso. 
2. Biomass isn't really the 'start of the year' - ruled out since same values above for different 2022 catches.
3. wtatage is used for B_2022 - seems unlikely since we haven't changed it lately. Should be used the same way.
4. ?

**Comment by andrew-edwards** [comment]
Looking at further catch runs:
```
> base.model$forecasts[["2022"]][["13-spr-100"]][["biomass"]]
            5%      25%      50%      75%      95%
2022 0.3542162 0.507432 0.646815 0.827445 1.194198
2023 0.2625596 0.452992 0.642685 0.899929 1.494322
2024 0.2322596 0.386660 0.556212 0.797684 1.461046
2025 0.1806048 0.301013 0.437275 0.650433 1.300366
> base.model$forecasts[["2022"]][["14-default-hr"]][["biomass"]]
            5%      25%      50%      75%      95%
2022 0.3542162 0.507432 0.646815 0.827445 1.194198
2023 0.2625596 0.452992 0.642685 0.899929 1.494322
2024 0.2322596 0.386660 0.556212 0.797684 1.461046
2025 0.1806048 0.301013 0.437275 0.650433 1.300366
```
This **is** different  to Kelli's .sso though.

**Comment by cgrandin** [comment]
This is all fixed with re-running of the mcevals.

**Comment by andrew-edwards** [comment]
And (just to keep track) the problem was numbers 3 and 4 in the above list, which Rick fixed in SS.
