### ISSUE TITLE
SRG presentations

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#929]
Maybe tick the box when you're ready for someone to take a look at yours.
- [x] Data (Kelli)
- [x] Assessment (Aaron)
- [x] Sensitivities (Chris)
- [x] Management (Andy)

We cut them down a bit for last year's meeting, so hopefully we can keep them somewhat the same.

**Comment by kellijohnson-NOAA** [comment]
Please make sure that all presentation have the following disclaimer so Aaron and I don't have to get approval for each presentation.
```
"These materials do not constitute a formal publication and are for information only.
They are in a pre-review, pre-decisional state and should not be formally cited.
They are to be considered provisional and do not represent any determination or policy of NOAA or the Department of Commerce."
```

**Comment by andrew-edwards** [comment]
Yep - they should still be automatically in each one. The DFO logo disappeared off the front page when I was running one of them, but that was because I did `pdflatex` instead of the old `latex dvips ps2pdf` sequence. Not sure how each person is building, but if that happens then just try a different build process.

**Comment by andrew-edwards** [comment]
For data presentation, I just made .eps files for the two acoustic survey maps (referenced in the next commit). You need to download them from our shared drive under Hake JTC 2022/data. Tick when done:

- [ ] Kelli
- [ ] Chris
- [ ] Aaron

**Comment by andrew-edwards** [comment]
I did a quick look through assessment talk. Looks great @aaronmberger-nwfsc . Couple of minor edits in the commit below.
