### ISSUE TITLE
Check over acknowledgments one more time

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#931]
Add Kiva and any others we can think of...!!!

**Comment by andrew-edwards** [comment]
I have the 'thanking the SRG folks' part commented out, so that can easily go back in (have to check the exact people). And realised after submission to add Kiva. I checked with RT and had already added in some extra survey people.

**Comment by aaronmberger-nwfsc** [comment]
done with 85f8a134a2851ee1dd50128b5461d1b22a62f28d
