### ISSUE TITLE
Figure 51 doesn't show the sens runs

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#933]
preSRG version. Figure 51 is missing the sens runs:
![image](https://user-images.githubusercontent.com/6977190/153508603-8772d606-7cab-4eff-bf96-17edfa3d53dd.png)

But Figure 46 is fine (same idea, with 'remove age-1 index' and 'downweight fishery comps'). I tried using the exact same code (subplots=14 like for Fig 46), but doesn't work for the Phi sens. Is this an mceval type thing?

Looks like it worked at some point as someone wrote:
![image](https://user-images.githubusercontent.com/6977190/153508938-874ef043-c9dc-476a-bf46-02467e23d138.png)

If a real pain to fix we can maybe just drop the figure (and in sens talk, which is where I noticed it) - we don't show it for all sensitivities anyway. But I think it might get fixed anyway with all the re-running.

**Comment by andrew-edwards** [comment]
If function call needs fixing, then do it also in sens talk (slide 12 currently).

**Comment by aaronmberger-nwfsc** [comment]
Another thing to mention when showing these survey fit figs as that they only show the survey input uncertainty (not the extra SD uncertainty).  For example, when you look at these without the extra SD added, it appears like the survey is not fitting points (badly); whereas with the extraSD there are within the error bars/bounds (i.e., compare to Figure 18).
