### ISSUE TITLE
Figures 16 and 17 (and right figure on p8 of assessment talk) - units should be same as Fig 19

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#935]
Since showing age-1 index, units should be "Relative age-1 index (billions of fish)". 

I took a quick look but not trivial to fix. So just be aware of (@aaronmberger-nwfsc ) for talk. We can just mention in caption if we can't easily fix it.

**Comment by aaronmberger-nwfsc** [comment]
good spot!  Thanks!

**Comment by cgrandin** [comment]
Fig. 16 is showing the acoustic survey age 2+ so it shouldn't but Fig 17 should and it is fixed now. Just remove object from knitr cache and remake it.

**Comment by cgrandin** [comment]
This also fixes the assessment presentation figure so it's worth a rebuild before showing
