### ISSUE TITLE
One-page summary: final bullet has a mix of two- and three-year projections.

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#936]
We need to decide if we want to talk about B_2025 here or not. It's kind of a mixture right now.

Either:
a) just talk about 2022 and 2023 catches, and resulting B_2023 and B_2024, or
b) add 2024 catches and talk about B_2025 (we do once already).

I'd lean slightly towards a) as b) makes it a bit unwieldly (though I can see how to simplify the text), and we were never too keen on three years anyway. Though b) has the full results, and can be added somewhat succinctly.

I can make the changes, just want to see what others thought.

**Comment by cgrandin** [comment]
I think only talking about the first couple of years (2022 and 2023 catches)  is fine for this one page summary
