### ISSUE TITLE
Add image files for eventual doc build

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#941]
There are two image files (with very poor names) that you need to download that are associated with the Requests presentation build that will also be used for the Response to SRG Appendix in the document build.  They are on the google drive [here](https://drive.google.com/drive/u/0/folders/1FssblREq26ngwyDjEfFK5bajIGjYRITn), and should go in beamer\images

Downloaded?

 - [x] Kelli
 - [x] Chris
 - [x] Andy
 - [x] Aaron

*Added 2/17/2022 - this isn't necessary unless you want to build the SRG requests beamer presentation.  For document build, see the check boxes below instead

**Comment by cgrandin** [comment]
Would put them in main-figures directory if going to be used in the doc

**Comment by aaronmberger-nwfsc** [comment]
Please ignore the above tasks and instead use these check boxes.  Add the three png files located on the drive [here ](https://drive.google.com/drive/u/0/folders/1FssblREq26ngwyDjEfFK5bajIGjYRITn) to hake-assessment\doc\main-figures in order to properly build Appendix B (response to SRG requests). 

 - [ ] Aaron
 - [ ] Kelli
 - [ ] Chris
 - [ ] Andy
