### ISSUE TITLE
Move SRG request slides to assessment document appendix B

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#942]
Put the suite of 2022 SRG requests into appendix B of the assessment document. Perhaps add a bit of explanation if needed.

**Comment by cgrandin** [comment]
See e754e9f12fc83a77b29c7fff7ab04cc7f2db8c9d

**Comment by aaronmberger-nwfsc** [comment]
Great, this is now done.  It certainly could use a second read through by someone, but good enough to close the issue.

**Comment by andrew-edwards** [comment]
I'll read through everything (hopefully!) on Monday. No holiday for us....
