### ISSUE TITLE
Complete JMC presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#944]
I got this presentation basically ready to go, but edits and suggestions of course always welcome.  I did move the "Historical Performance" section to the end (after the summary), thinking that we could reference those if people asked or wanted to hear about them.  I was thinking we focus on the basic output of the assessment so they can get right to discussions, but still have it handy if anyone wanted to see and/or discuss them (e.g., Shannon). In addition to edits, a couple things remain:

1. I added Kelli's SRG data presentation slide on our analysis of no Canadian age data since we were basically "warned" that there would be questions about this (also at the very end).  In addition to our analyses, the SRG makes comments about this in their report as well.  To build you will need to download the eps file and put it in the beamer\images folder.  I kept it there as it seems like one-off images for presentations could be housed there and not in our main-figures folder that would just continue to grow with files that are never used again.  Please download the 'nocanagesfigure-1.eps' file from [here](https://drive.google.com/drive/folders/1FssblREq26ngwyDjEfFK5bajIGjYRITn?usp=sharing)  and put in beamer\images to build the JMC presentation.
 - [x] Aaron
 - [x] Kelli
 - [x] Chris
 - [x] Andy

2.  I'd like to select the set of projection catch streams that are shown in the presentation decision tables.  We have a presentation specific decision table function (make.decision.table.pres) that uses 'models.inds' to identify a subset of runs to show, but that function doesn't include the new decision table format.  We have the new decision_table function that uses the new format, but only has a 'first.streams' flag which takes catch streams from 1 to N but doesn't allow (yet) for specifically defined subsets like 'models.inds' did. So, the presentation is all setup with the models.inds that I think would be useful (i.e., a diverse set), but we need to add that functionality to the new decision_table function.
 - [x] Check once decision_table function includes that capability (Chris can you easily adapt this?)

That's all for now I think.

**Comment by cgrandin** [comment]
I will fix the decision tables for the slides, yes.

**Comment by andrew-edwards** [comment]
Think I added the option to do the first N catch alternatives for the SRG talk, and realised it would be a time suck to select them (unless I was Chris), hence it's not as generalisable as it could be. Thanks Chris.
