### ISSUE TITLE
Footer is not present on rotated pages

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#947]
When the table is turned, i.e., on page 91 for Table 3, the footer just has the page number.

**Comment by cgrandin** [comment]
I knew this, spent what seems like forever on it last year. I don’t think it’s possible with fancyhdr package. I think we have to do a major document-wide overhaul to make it work

**Comment by kellijohnson-NOAA** [comment]
Could be easier to just remove the footer except for the page number. Also, removing it would be better for screen readers b/c it reads it out every page.

**Comment by andrew-edwards** [comment]
I find the footers super useful, as I often have older versions of the assessment open on my desk (and the footer has the year), so would definitely not want to lose the footers. Also it means we have 'draft' on each page also for the draft version.

**Comment by cgrandin** [comment]
Footers and header/footer lines now on every page, portrait and landscape. Integrated into master in 7e3d56f798390f51c5a914ff07a2225ce8e6c0ad
