### ISSUE TITLE
Figure and Table placement in Executive Summary splitting sentences

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#948]
Some figures and tables in the Executive Summary split sentences in the reading order given by adobe or probably any automated tagging. Figures and Tables should only come after completed paragraphs.

**Comment by andrew-edwards** [comment]
Hmmm..... that's going to be really hard to do, as Latex does such a good job of placing figures and tables on the same page as the text that talks about them (where possible, we have to force a few thing also though). Also preferable to reduce white space. Hmmm...... See how it looks next year. Might be some easy tweaks to the odd paragraph.

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards I am closing this because wherever you end up placing the figures will be just fine :)
