### ISSUE TITLE
Archiving of model RDS files and other files on Google Drive

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#954]
I took a closer look and there are only RDS files included for 2021 and 2022. I can't remember why we didn't save these for the previous years. We could checkout the repo at the correct yearly release and generate them though.

Any other notes on archiving historic models can be placed here...

**Comment by kellijohnson-NOAA** [comment]
Ian found .RData files for 2016 and 2017.

**Comment by cgrandin** [comment]
And I was wrong 2018 does have it for the base model (2018.40_base_model)

**Comment by andrew-edwards** [comment]
I have them all saved and backed up. Sounds like we're good though.
