### ISSUE TITLE
Naming of models for 2023 and beyond

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#955]
I'd like to start naming models with underscores (no periods) starting with a unique number and ending with the year like this:

001_newss_2023
002_newcatchage_2023
003_updatesurvey_2023
...

because when you tab complete in a command line you type only three digits to type instead of all this: `2022.01.10` for example.
It will be much less typing as we move to cloud or server-based modelling.
I would have saved about 10,000 keystrokes this year if it was like this.

The 'no periods' make future file code simpler. If there is one or more periods some functions think it is a filename with an extension which you have to write a special case for sometimes.

**Comment by kellijohnson-NOAA** [comment]
Seems like we should pick one or the other. I like having them all in one folder rather than a nested structure, but I am fine with going with whatever the majority wants.

**Comment by cgrandin** [comment]
We can also each have different structures. If you do this:
```
if(Sys.getenv("USERNAME") == "aedwards") # or whatever your username actually is
models_path <- "models/models-2022"
```
and paste it in the source code after this:

https://github.com/pacific-hake/hake-assessment/blob/947de55a5943aa6ca471e7e1077720c3c19682be/R/all.R#L55

PS: See all your environment variables like this:
```
Sys.getenv()
```

**Comment by cgrandin** [comment]
All settled !!
