### ISSUE TITLE
Further comments on 2022 assessment doc

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#957]
Note comments from Allan Hick's posted on the postSRG 'final' version of the 2022 stock assessment (below) for consideration in 2023.  
[hake-assessment-2022-preSRG_HicksComments.pdf](https://github.com/pacific-hake/hake-assessment/files/8466571/hake-assessment-2022-preSRG_HicksComments.pdf)

**Comment by andrew-edwards** [comment]
Just had a look through. It will be easier to address them once we have the new model results, since some will be redundant. Some are just 'thoughts' I think, or comments, but the odd typos etc. that we can fix.

**Comment by andrew-edwards** [comment]
Thanks for doing these Kelli. Good to close?

**Comment by kellijohnson-NOAA** [comment]
I am done but @aaronmberger-nwfsc had some he was going to complete for me. So, I will leave it for @aaronmberger-nwfsc to close.

**Comment by aaronmberger-nwfsc** [comment]
Mine are in there, so bam! closed
