### ISSUE TITLE
summarize M/G to recruitment of larval fish in California

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#959]
See talk by Iain Suthers, a Fulbright Future Fellow 2021 working with FRD at the SWFSC titled "The recruitment potential of larval fish from their size-spectra; can we reconsider the impossible?"

**Comment by kellijohnson-NOAA** [comment]
* Bailey's annual recruitment index? What is this?
* Why were the three recent strong year classes not sampled by CalCOFI?

**Comment by andrew-edwards** [comment]
That last point was definitely strange. I think he said it might have been timing (he hadn't got to April yet)? Could they already have moved out of the area (and that's something that happens in strong recruitment years)? Interesting stuff. 

Here's his paper on the general idea (applied to zooplankton not hake - hake work is in progress): https://onlinelibrary.wiley.com/doi/full/10.1111/faf.12633  
I can dig into it at some point.
