### ISSUE TITLE
reps is not passed as a variable

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#964]
https://github.com/pacific-hake/hake-assessment/blob/926cc7df44772187f168f236bedcf4956b0ad645/R/run-adnuts.R#L102

@cgrandin I am guessing that we can set this to some default?
It appears as though it might be a relic from https://github.com/pacific-hake/hake-assessment/blob/5ddcfb39016838597f29c02365185a9d748061c8/R/adnuts-run-base-model.R#L36

**Comment by cgrandin** [comment]
Yes, I made the adnuts running stuff into a function last year where you can set everything in arguments: https://github.com/pacific-hake/hake-assessment/blob/5ddcfb39016838597f29c02365185a9d748061c8/R/run-adnuts.R#L29

**Comment by kellijohnson-NOAA** [comment]
The function doesn't have an argument reps so it doesn't work for me. We either need to pass it as an argument or give it a default value.

**Comment by cgrandin** [comment]
Oops, can you just replace reps there with `parallel::detectCores() - 1 ` and push it?

**Comment by kellijohnson-NOAA** [comment]
Will do. Thanks!

**Comment by aaronmberger-nwfsc** [comment]
looks like maybe in the function it is 'chains' that needs to replace the 'reps'.  'reps' seems a relic from previous code that got in there

**Comment by cgrandin** [comment]
This is what is says in the adnuts docs for `sample_rwm()`

```
cores:
The number of cores to use for parallel execution. Default is number available in the system minus 1. If cores=1, serial execution occurs (even if chains>1), otherwise parallel execution via package snowfall is used. For slow analyses it is recommended to set chains<=cores so each core needs to run only a single chain.
```

So I think we could actually just delete it from that call because the default is what we are setting it to.

**Comment by kellijohnson-NOAA** [comment]
I think that there is a lot in the call to `sample_rwm()` that is just relic info. So how about
```
  pilot <- sample_rwm(model = exe,
                      iter = 100 * 10,
                      thin = 10,
                      seeds = seeds,
                      init = NULL,
                      chains = chains, # 100 * thin
                      warmup = chains / 4,
                      path = path)
```
I am trying it now within `run_adnuts()` and it appears to be working.

**Comment by cgrandin** [comment]
Sure, if you can get it working that's fine..

**Comment by kellijohnson-NOAA** [comment]
I am running last year's model files with 3.20.20, so a newer executable.

**Comment by cgrandin** [comment]
OK I will need to compile that version of SS as well. Does r4ss work for everything for it? I usually have to change things in r4ss to make it work

**Comment by kellijohnson-NOAA** [comment]
Changes are pushed in e424eb68. You don't actually have to compile it, you can just pull the executable for linux or windows from the [Stock Synthesis releases website](https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/tag/v3.30.20). In theory everything with {r4ss} works on this version.

Can we I delete (git rm ./R/adnuts-run-base-model.R)?

**Comment by cgrandin** [comment]
This has all been addressed in the updated adnuts: https://github.com/cgrandin/adnuts
