### ISSUE TITLE
Check why survey history test fails

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#967]
In `R/data-tables.R` I had to comment out one of the tests, see da596c59    (it was commented out last year, Chris had uncommented it but I had to comment it out again to avoid the error - didn't look into in detail; commit history is a little confusing because of a conflict).

It's this:
```
# Fails in 2022, but small differences, didn't yet look
# into exactly which columns to compare.
# testthat::expect_equal(round(survey.history$cv * 100, 1),
#                         round(survey.comparison$cv.with.extrap * 100, 1))
```

The test may be overkill, but would be worth tidying up.

**Comment by cgrandin** [comment]
Probably a rounding error. I uncommented it and it failed again so I commented it again. We should check I suppose
