### ISSUE TITLE
Need to manually install gfutilities package

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#968]
If you don't have gfutilities installed you need to do `devtools::install_github("pbs-assess/gfutilities")` 

The `pacman` command used below that won't automatically install a package from GitHub, only CRAN. See 7a2be856.

Just Kelli and Aaron would need to do this, then can close.

**Comment by aaronmberger-nwfsc** [comment]
Done, and I've made a note in my workflow to do this/check this after I reinstall R or move to other computer(s).
