### ISSUE TITLE
Should we reference weight-at-age data in the Introduction

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#971]
https://github.com/pacific-hake/hake-assessment/blob/d16776e45093f8ca380030b0d4806421f89af0e9/doc/introduction-section/introduction.rnw#L29

We list survey, catch, and age-comps but do not mention weight-at-age data. Should this be augmented?

**Comment by aaronmberger-nwfsc** [comment]
Yes, I think explicitly calling it out here is a good idea.  We probably should also add it to the executive summary (bullet 1) and the executive summary Data and Assessment section, paragraph 1.  For completeness, our "Overview of data used in this assessment...." figure (Figure 8 in last year's assessment) could also include a mention of the weight-at-age data in the caption.
