### ISSUE TITLE
Replace readLines() for control file output

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#973]
In `load_ss_files()`

`model$ctl <-  readLines()` should be replaced with `r4ss::SS_readctl()`

this may cause unforeseen bugs so care has to be taken

**Comment by kellijohnson-NOAA** [comment]
`readLines(ctl)` is here https://github.com/pacific-hake/hake-assessment/blob/266026b16ce6e21a711021750339f88ca8d71d07/R/run-retrospectives.R#L140
