### ISSUE TITLE
Sensitivity results Tables 33 and 34 not yet complete

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#974]
I've used the new naming structure to get them building, but wasn't sure how Chris was thinking of combining the list elements into groups. So Tables are just currently missing results from
```sens_models[[2]]```
```sens_models[[4]]```
See commit referenced below.

**Comment by andrew-edwards** [comment]
Will also apply to Figures 41-51. Presumably the same kind of tweak.

**Comment by aaronmberger-nwfsc** [comment]
Table 33 (or elsewhere) needs the Max. age selectivity 5, 7, and 8 models; Recdev sum to zero model, the Remove Age 1 Index model, and the Downweight Fishery Comps model added to it.  Some of these can be added to Table 33, but I suspect we will need a third sensitivity table.

**Comment by cgrandin** [comment]
How it looks now, needs the DM params and age-1 and age 2+ q param values

![image](https://user-images.githubusercontent.com/4551051/214453189-4c3cb534-69f7-4587-8b37-f982484ded4b.png)

**Comment by aaronmberger-nwfsc** [comment]
My earlier commit had the DM parameters all in there for Sensitivity and Retro Tables.

![image](https://user-images.githubusercontent.com/7946234/214455590-738d7e59-94bf-4718-aa98-233e7625b71d.png)

**Comment by cgrandin** [comment]
Those came back when i rebuilt it but need to run ALL sensitivities with extra mcmc for this table. So I have to run the first 7 of them now (sigh), the rest have them. After that it is a simple cut/paste to make tables for all of them

**Comment by cgrandin** [comment]
Done here: e05c88103b06b90ad1e27f64cac9ef0e8ec2e9ce

Also the new updated Hamel prior is in group 1
