### ISSUE TITLE
Decide which bridging models to show in Figure 16 (last year's Fig 17 presumably not needed).

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#975]
Doesn't build yet, but need to first decide which ones to show, and how to keep it flexible for years when we do add new survey data (based on Chris's new structure).

**Comment by aaronmberger-nwfsc** [comment]
I think there are few enough that we could get away with a single bridging model set (i.e., one figure this year).  The lines seem to separate enough that you can see what is going on pretty well.

**Comment by kellijohnson-NOAA** [comment]
I just kind of figured the path of least resistance would be to include them all and explain in the figures that some will not lead to any changes depending on the year or drop the two survey ones that are in the middle if it is a non-survey year.

**Comment by aaronmberger-nwfsc** [comment]
this can be closed, correct?
