### ISSUE TITLE
key_posteriors at bottom of all.R does not now have age-1 index extra SD parameter. 

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#976]
So Figure 22 only has six panels. Not sure if this is intentional so mentioning, and update caption if necessary.

**Comment by cgrandin** [comment]
I think this is a constant, @aaronmberger-nwfsc we had this conversation last year, is that why we didn't show this?

**Comment by aaronmberger-nwfsc** [comment]
The age-1 index does have an extra SD estimated.  The input CV associated with the index is a fixed constant.  Last year's assessment had it in there, so it would be nice to include it again if we can.

**Comment by aaronmberger-nwfsc** [comment]
Let's add back in the age-1 index extra SD as a key posterior so it can be plotted if there is time.  If not, we can add it back in next year.

**Comment by andrew-edwards** [comment]
Move to 2024 yes?

**Comment by cgrandin** [comment]
This has been done in the restructure
