### ISSUE TITLE
Last year's full Appendix H (the new recruitment plot idea) probably not needed

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#977]
It was based on that survey I sent out. Probably don't need the full explanation again (even though we didn't get to it last year with the shortened online meeting). Could just move Fig H.7  (recruitments scaled to 2010) to the main-figures as I think it's informative, and remove this appendix?

**Comment by aaronmberger-nwfsc** [comment]
I agree with your thoughts here Andy.  Keeping that central figure in the document is a good idea given it's attention the last few years.

**Comment by andrew-edwards** [comment]
I'm doing this now. I think Aaron was thinking about the historical prob plots, not the scaled recruitment one. Basically, moving the last figure of what's currently Appendix G into the main-figures, add a paragraph of text, and remove the Appendix.
