### ISSUE TITLE
Who's doing what (Tues/Wed/Thurs)?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#978]
Andy:
- [x] Fix current build issue (one-page summary I think); update - it's do with retros loading
- [x] Then will upload a build onto G Drive
- [x] Go back to 3e1bf400 regarding bold headings, figure it out (I think being bold didn't actually break it). Update: the switch to bold is what broke it (so turned bold off, see #980).
- [x] Sort out retro indexing - squid plot and historical prob retro plots
- [x] Check historical prob calcs, shorten text based on Kelli's suggestions last year (text is already in there, just commented)
- [x] Remove scaled-recruitment plot Appendix and just put the final figure into main-figures, add a bit of text, #977

**Comment by aaronmberger-nwfsc** [comment]
Aaron:
- [ ] executive summary text
- [ ] Section 3.1 to 3.4

**Comment by kellijohnson-NOAA** [comment]
- [ ] one-page summary
- [ ] executive summary

**Comment by cgrandin** [comment]
I've been fixing all the plots that were failing and correcting the sensitivity model plots. Also fixed the squid plot. If there are any legends that are off I will fix tomorrow.
