### ISSUE TITLE
Table 26 (comparing results with last year's base model) not working

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#980]
Yesterday it would just show an error but the .tex would still build. Now it's breaking as it won't put the 2023 and 2022 years on the first line. In console when just running the function, it says:
```
New names:
• `Base model` -> `Base model...2`
• `Base model` -> `Base model...3`
New names:
• `Base model...2` -> `Base model...3`
• `Base model...3` -> `Base model...4`
\begin{table}[H]
\centering
\caption{Select parameters, derived quantities, and reference point posterior median estimates for the (2023) base model compared to the previous assessment's (2022) base model.} 
\label{tab:main-parameter-estimates}
\begingroup\fontsize{10}{11}\selectfont
\begin{tabular}{lcc}
  \hline
 & \mlc{Base\\model} & \mlc{Base\\model} \\ 
  \hline
 &  &  \\ 
```
The bullet point errors are strange, and you can see the third line from the bottom doesn't have the years, when they got inserted last year. 

Chris - I put in `last_yr_base_model_name` in fa05a5b2, as it had disappeared from last year it seems. Later tables also breaking at the \mlc stage, but they were just letting me skip over them yesterday.  :puzzled.

**Comment by andrew-edwards** [comment]
Actually I think know what it is....

**Comment by andrew-edwards** [comment]
Above commit wasn't meant to close this (I thought I worded the message so it wouldn't automatically close). Builds for now.

**Comment by andrew-edwards** [comment]
Just missing the years being automatically included in the column headers.

**Comment by andrew-edwards** [comment]
Turns out that switching the bold headings on does break the table (I switched them back off in 3e1bf400). Not quite sure why, but not too important right now.

**Comment by andrew-edwards** [comment]
Also, the Dirichlet-multinomial parameters are missing from the first column (the 2023 model), to do with the names changing.

**Comment by andrew-edwards** [comment]
Above comment also relevant to the final three main tables (Tables 33-35).

**Comment by aaronmberger-nwfsc** [comment]
I also think (if we have time) that adding the 2020 recruitment (millions) after the 2016 row in the sensitivity tables will be useful.

**Comment by aaronmberger-nwfsc** [comment]
I think I got most of this working.  However, the DM parameters still don't show up for 2022 base model in the parameter estimate comparison table.  It looks like it was called the same thing last year.  Leaving this open for now.

**Comment by cgrandin** [comment]
All are correct, last year ones match with the table from last year, I added the fix to make DM params appear for both years.

I noticed that the 2023 relative biomass row is in the wrong subheading as it was added this year, I think it should be in derived quantities:

![image](https://user-images.githubusercontent.com/4551051/214445806-c4999d46-5004-4b79-b71c-7698b90b388b.png)

**Comment by andrew-edwards** [comment]
Agree it should be moved if possible. We're missing the '2023' in the first column heading, but it's kind of implied in the caption so probably fine.

**Comment by andrew-edwards** [comment]
The above screenshot correctly has two dashes in the 2022 base model column, but the latest version has some numbers (which is incorrect - they were correctly dashes in the submitted version):
![image](https://user-images.githubusercontent.com/6977190/218896447-bb18e4ff-dd10-4555-8084-85e011804151.png)

**Comment by andrew-edwards** [comment]
This fix also correctly put dashes in Table 36 for the retrospective calcs - nice.
