### ISSUE TITLE
Removing forecasted catch scenario m

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#981]
I think we can now remove the current catch scenario m (FI=100%) from our decision tables and forecast tables and figures.  I believe this was also noted in the comments by Allan.  I've adapted the text related to why we even did that in the first place in the executive summary Forecast Decision Tables section (and will do so in the main document too), so I think that explanation is good enough as to why relative fishing intensity for the default HCR doesn't equal 1.0.  Further, the forecasted quantities themselves do not really change so we gain nothing from having that row in there.  Plus, we need to make some space anyway.

Do others agree?

- [x] Andy
- [x] Chris
- [x] Kelli
- [x] Aaron 

Just noting that we can just eliminate this scenario from figures and tables, having it run already is just fine.

**Comment by andrew-edwards** [comment]
Maybe don't close this until both captions also updated (Table g and same one in main doc).

**Comment by cgrandin** [comment]
This is a bit of work because it means modifying the decision table code which isn't the most straightforward

**Comment by aaronmberger-nwfsc** [comment]
Yes, I think there is one spot where I changed a letter referencing a scenario.  I'll change that, so I'll just close this for now.
