### ISSUE TITLE
To fix squid plots

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#983]
I thought it was something in r4ss, but now realise it's the four (I think) lines in Chris's 

https://github.com/cgrandin/r4ss/blob/main/R/SSplotRetroRecruits.R 

that aren't in the r4ss version one. Can look further tomorrow. Figure built fine for me when I just copied Chris's code in and ran that function (then R hung)...

Chris - best practice for fixing this (as it happens every year).  They have updated the function in r4ss, but probably best just to copy yours in locally and maybe name it something different to avoid confusion?

Ideally get the r4ss version working for us, but that would take time.

**Comment by cgrandin** [comment]
Fixed in f93850372aecc34d16ad7b38cae08a426532d1ba
This is a permanent fix, I added the function `plot_retro_recruits()` directly to the hake-assessment codebase
