### ISSUE TITLE
Alignment in Table 3 of columns is off

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#985]
Numbers in columns of Table 3 (total catch per sector) should be right aligned.

**Comment by kellijohnson-NOAA** [comment]
@cgrandin i am guessing that center alignment was used because of the dash for missing numbers. We have three options
1. Get rid of the dash and change the caption to empty cells represent missing values
2. Leave the dash right aligned as I did here
![image](https://user-images.githubusercontent.com/4108564/214201350-7284f7b5-1303-4554-b3d0-66daa3d7afd0.png)
3. leave the columns center aligned so the dash is in the center but the numbers are not right aligned which imo makes them harder to compare.

**Comment by andrew-edwards** [comment]
That looks fine to me and an improvement. No-one's going to complain about the dashes not being in the centre. Hopefully...

**Comment by cgrandin** [comment]
I agree with what you're showing. I replicated it by changing this:
https://github.com/pacific-hake/hake-assessment/blob/7fd0ebaeff4e04d885a1dfdb485981bbb1fb31fa/R/catches.R#L255

to this:
`align = c("l", rep("r", ncol(tab)))),`

and had a quick look round to see if we could center the dashes but nothing easy as you already found out. So I will leave it to you
