### ISSUE TITLE
Executive summary CATCHES confusing average

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#986]
```
Across the time series, catch in U.S. waters averaged 185,086 t, (76.5% of the total catch) while catch from Canadian waters averaged 57,788 t.
```
I wasn't sure if the 76.5% was the average percentage of U.S. catch over the entire time series or the actual percentage of catch across the entire time series. It is the former. Where, the latter is 76.2%, i.e., sum(ct$us_catch)/sum(ct$tot_catch). Is that what other people expected? Which metric do we want and should the text be edited?

**Comment by cgrandin** [comment]
The way it's written, it's wrong. I think it should say what you calculated (with rounding of course):
```
Across the time series, catch in U.S. waters averaged 185,086 t, (\Sexpr{sum(ct$us_catch) / sum(ct$tot_catch)}% of the total catch) while catch from Canadian waters averaged 57,788 t.
```

**Comment by aaronmberger-nwfsc** [comment]
I think we also need to add in something like "....**annual** catch in U.S. waters averaged 185,086 t  ...."

**Comment by aaronmberger-nwfsc** [comment]
closed with [commit](https://github.com/pacific-hake/hake-assessment/commit/b1141be0a39e0e4cba75596757283ff18d9559a8)
