### ISSUE TITLE
Sensitivity figures - lines and colors and missing plots

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#993]
Many of the sensitivity plots are missing points/lines for certain models and/or have the legends not match the colors.  However, some plots seem correct.  Making this issue so that we carefully go over each to ensure they are plotted correctly.

**Comment by aaronmberger-nwfsc** [comment]
The Downweight Fishery Comps sensitivity appears to be a copy of the base model, this is why for some of the sensitivity figures it looks like it doesn't exist.

**Comment by aaronmberger-nwfsc** [comment]
Well, the above comment was for SSB, but for Recruitment it looks like the values are identical for the age-1 index and the downweight fishery comp sensitivities.  I am really confused.

**Comment by cgrandin** [comment]
They aren't actually missing, I had to copy some models around so you could build while the RDS was being made for those, and I haven't finished so haven't replaced the models yet. So what you're seeing is like four of the exact same model being plotted because they are all copies of one another, so the lines are and points are overwritten and hidden

**Comment by cgrandin** [comment]
Also I made a mistake and copied the wrong model RDS into model 02-h-fix-high so that will seem to be missing as well. It will all be fixed in one function call when I'm done

**Comment by cgrandin** [comment]
I made the changes and re-created all the sensitivity models RDS files, so this should be fine now. They are all the correct models that they should be.

There's a couple missing sensitivity plots which I'l fix next and bump the B0 points over a bit so they don't vanish off the left side
