### ISSUE TITLE
Probability SB decreasing in 2024 is above 72% for all catch levels but catch level of 0 increases

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#994]
https://github.com/pacific-hake/hake-assessment/blob/6d6a593f7349cc1a687dbe33fe572adc0c221623/doc/executive-summary/executive-summary.rnw#L897-L900

Do we include a catch level of 0 in the "catch levels"? If so, I think that this potentially needs to be re-written b/c the median SB in the start of 2024 for a catch level of zero leads to an increase in relative SB.

**Comment by kellijohnson-NOAA** [comment]
Sorry, I was thinking this was 2022 to 2023 not 2023 to 2024.

**Comment by kellijohnson-NOAA** [comment]
Umm I can tell it is late ... so I still think that there is an issue here though b/c we  give row 2, i.e., 71% rather than above 50% which would be all catch levels.

**Comment by andrew-edwards** [comment]
Think I just said 'non-zero catch levels' in the assessment section. Could do same here. Will look out for it when reading ES.

**Comment by aaronmberger-nwfsc** [comment]
addressed with 9f3a2d627e6545e6c67a2ad3c6ea6b9c341ad3b4
