### ISSUE TITLE
figures l and m have lines over the legend text

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#996]
![image](https://user-images.githubusercontent.com/4108564/213974797-06d8f607-6248-4a16-9dba-4a9194053170.png)

**Comment by andrew-edwards** [comment]
Probably best to just put a white background (instead of transparent) on the legend? Kind of obvious where the hidden points will be. Or just shrink the legend for this plot, but may have to shrink it too much.

**Comment by andrew-edwards** [comment]
Probably best to just put a white background (instead of transparent) on the legend? Kind of obvious where the hidden points will be. Or just shrink the legend for this plot, but may have to shrink it too much.

**Comment by aaronmberger-nwfsc** [comment]
We could also just adapt these manually when situations like this arise.  We could change the y-axis scale to max out at 1.1 such that 1.0 is still the last tick shown (cause can't go above a probability of 1 of course) but still leave a bit more room for legend.

**Comment by cgrandin** [comment]
I just tried it and we can adjust this to look like this... It's weird looking though

![image](https://user-images.githubusercontent.com/4551051/214217358-4f5d05ad-28f5-4826-90ce-23b64cfa1d24.png)

I'll leave it like this and we can change back if necessary, just change the legend.loc argument back to "topleft"

**Comment by kellijohnson-NOAA** [comment]
Can we just take up more space and place the legend outside of the figure?

**Comment by aaronmberger-nwfsc** [comment]
Great to have the option built in; my preference is the legend within the plot area but moved so it isn't in the way (even if not eye appealing), but that preference is ever so slight so I'm not fussed.

**Comment by cgrandin** [comment]
We don't have any other plots with the legend outside in the assessment

**Comment by andrew-edwards** [comment]
Also slightly prefer the legends inside (as elsewhere).

**Comment by andrew-edwards** [comment]
Also the x-labels get too bunched up with the shorter x-axis length (for the 2024 catch and 2025 catch versions of the figure).
