### ISSUE TITLE
Document assignments Deadline Wednesday EOD

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#998]
# One-page summary

  - [x] **Aaron**
  - [x] **Andy**
  - [x] **Chris**
  - [x] **Kelli**

# Executive summary

- [x] **Aaron**
- [x] Andy
- [x] Chris
- [x] **Kelli**

# Introduction

- [x] **Aaron**
- [x] Andy
- [x] Chris
- [x] **Kelli**
**Andy or Chris** need to add text updates to section 1.4.1 Canada and 1.3.2 (Canada specific text) 

# Data

- [x] Aaron
- [x] Andy
- [x] **Chris**  - there is Canadian specific text that I think needs updating still (e.g, 2.1.1 and 2.1.2)
- [x] **Kelli**

# Assessment

  - [x] **Aaron**
  - [x] **Andy** - Monday morning.
  - [x] Chris
  - [ ] Kelli

# Research and data needs

  - [x] **Aaron**
  - [x] Andy
  - [x] Chris
  - [x] **Kelli**

# Tables

  - [x] **Aaron**
  - [x] **Andy**
  - [x] Chris
  - [x] Kelli

# Figures

  - [x] **Aaron**
  - [x] **Andy** - AB: I did not update the performance of past projections figures (figured you could have first go)
  - [x] Chris
  - [x] Kelli

# Appendices

#923 is broken

  - [x] **Aaron** - focused on mcmc diagnostics
  - [x] **Andy**
  - [x] Chris
  - [x] **Kelli**

**Comment by cgrandin** [comment]
We can probably close this, good coverage..

**Comment by andrew-edwards** [comment]
Maybe leave it open as I'm still using it. But have read earlier versions of everything once, so don't feel I have to get to it all.
